redhat-appstudio/infra-deployments

- README.md
Added a couple of details that are needed to get this running in a clean CRC install.
Tested with:
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5
> added CRC tips

- components/build/README.md
- components/build/build-templates/nodejs-builder.yaml
- components/build/experimental-pipelines/app-studio-build-pipeline.yaml
- components/build/experimental-pipelines/kustomization.yaml
- components/build/experimental-pipelines/pvc.yaml
- components/build/hack/build.sh
- components/build/hack/default-build.yaml
- components/build/hack/install-pipelines.sh
- components/build/hack/test-known-build.sh
- components/build/kustomization.yaml
This PR adds a docker container build pipeline and sample scripts to install and run pipelines installed by the scripts.
To test, bootstrap the cluster.
As a non-admin user (admin works too) 
1. create a project `oc new-project demo`
2. install pipelines `./components/build/hack/install-pipelines.sh`
3. run test build `./components/build/hack/test-known-build.sh`
4. check the running pipelines via `tkn pipelines list` or `oc get pipelines` or via the OpenShift Console.
> Pipelines scripts

- components/authentication/user-ci-maintainer.yaml
> Support listing of secrets

- components/authentication/view-has.yaml
> Add sbose78 to has namespace

- hack/util-update-app-of-apps.sh
In util-update-app-of-apps.sh add missing `$` sign in one of the information strings.
> Fixed variable exposure

- README.md
- components/build/build-templates/docker-build.yaml
- components/build/build-templates/java-builder.yaml
- components/build/build-templates/kustomization.yaml
- components/build/build-templates/nodejs-builder.yaml
- components/build/build-templates/noop.yaml
- hack/build/build.sh
- hack/build/check-repo.sh
- hack/build/cleanup-pvc.sh
- hack/build/default-build.yaml
- hack/build/install-pipelines.sh
- hack/build/install-secrets.sh
- hack/build/install-single-pipeline.sh
- hack/build/ls-all-my-repos.sh
- hack/build/prune-pipelines
- hack/build/quick-noop-build.sh
- hack/build/repo-to-pipeline.sh
- hack/build/test-known-build.sh
This PR includes a set of build pipeline updates
- working nodejs builds, java may also build some repos
- more test scripts to run builds, determine buildable repos
- a new simple noop pipeline for quick test runs 
- utils for prune and cleanup of pipelines and pvc
- util to determine build type for a repo (temporary)
- doc README updates
> Build updates

- components/gitops/.tekton/kustomization.yaml
- components/gitops/.tekton/serviceaccount.yaml
> Patch the pipeline sa to use the appropriate secret

- README.md
- hack/build/ls-build.sh
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
> Add small fixes for README.md file.

- components/build/build-templates/bundle-config.yaml
- components/build/clustertasks/analyze-devfile.yaml
- components/build/clustertasks/appstudio-configure-build.yaml
- components/build/clustertasks/appstudio-init.yaml
- components/build/clustertasks/appstudio-summary.yaml
- components/build/clustertasks/appstudio-utils.yaml
- components/build/clustertasks/cleanup-build-directories.yaml
- components/build/clustertasks/image-exists.yaml
- components/build/clustertasks/kustomization.yaml
- hack/build/build-quay.sh
- hack/build/prune-builds.sh
- hack/build/templates/default-build-bundle.yaml
- hack/build/utils/install-sa.sh
- hack/build/utils/install-secrets.sh
- hack/build/utils/show-pvc.sh
This PR contains the following updates. 
- update to using pipelines  bundle v0.1.2 
- pipelines enable build for quay.io for docker and devfile builds
- adds new base cluster tasks for build phases 
- utility tasks for showing pvc contents
- updates to pruning configured (WIP)
> Pipelines Update

- .ci/oci-e2e-deployment.sh
Add a fake token to enable e2e tests to deploy HAS component.
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> Add a token for e2e tests to enable the has deployment

- components/authentication/view-spi.yaml
For monitoring SPI deployment this PR adds skabashn to spi-system namespace
> Add skabashn to spi-system namespace

- components/build/clustertasks/0-permissions.yaml
- components/build/clustertasks/kustomization.yaml
I will be removing supreme powers from Argo CD : https://github.com/redhat-appstudio/infra-deployments/tree/main/openshift-gitops/cluster-rbac ( Principle of minimum privilege ) .
> Add specific permissions to Argo CD for ClusterTasks

- components/has/kustomization.yaml
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
Refresh HAS Staging to pick up the following changes from the application service:
- Implementation of the Component Detection Query CR https://github.com/redhat-appstudio/application-service/commit/33da2433c6b0afaab8ca03e5b6a4654e09dc6f94
- Implementation of the Gitops resource generation https://github.com/redhat-appstudio/application-service/commit/951c552ba164b59b32bd182aca5aa626ca332e4e
- Adding build.ContainerImage to Component spec https://github.com/redhat-appstudio/application-service/commit/98d082511fd2242e49f98065d7d1e604a4fafd33
- Application controller finalizer bug fix https://github.com/redhat-appstudio/application-service/commit/e210b0ef6261ae11213e323138e4a8a5a8aac4a1
> Refresh HAS Staging to pick up gitops generation & comp det query CR

- components/has/kustomization.yaml
Refreshes HAS to pick up the following changes:
- https://github.com/redhat-appstudio/application-service/pull/37
- https://github.com/redhat-appstudio/application-service/pull/38
> Refresh HAS in AppStudio to pick up changes

- components/authentication/gitops-ci.yaml
- components/authentication/has-ci.yaml
.. to 🪓 the PipelineRuns lying around
> Make john the CI maintainer

- components/has/kustomization.yaml
Deploying https://github.com/redhat-appstudio/application-service/commit/037a3ec7e7e89b56afe7681ae86710e25d9d6c18
> HAS: Deploy integration with Builds

- components/spi/kustomization.yaml
update SPI Operator to `0.2.3` and SPI OAuth to `0.2.2`
operator changes: https://github.com/redhat-appstudio/service-provider-integration-operator/compare/v0.2.2...v0.2.3
oauth changes: https://github.com/redhat-appstudio/service-provider-integration-oauth/compare/v0.2.1...v0.2.2
> update spi images

- components/authentication/view-has.yaml
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
Added myself `maysunfaisal` for HAS, so that I can monitor the controller and other resources being generated by the HAS operators.
> Add HAS User for View

- components/has/kustomization.yaml
- components/has/manager_resources_patch.yaml
Increases resource limits for HAS in staging.
> Increase memory and CPU limits for HAS

- components/authentication/kustomization.yaml
Forgot to add in https://github.com/redhat-appstudio/infra-deployments/pull/91
> Add HAS Pruner role to kustomization.yaml

- components/authentication/prune-has.yaml
Needed to remove the finalizer on some stuck resources.
> Add patch verb to HAS Pruner role

- README.md
In this PR
* Added the config update for CRC required for sandbox setup to enable member cluster.
* Added a note to the SPI config default value in CRC setup.
Signed-off-by: Bamacharan Kundu <bamachrn@gmail.com>
> Added cluster monitoring config for crc setup and updated SPI config

- argo-cd-apps/overlays/development/delete-auth.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
Associated https://github.com/redhat-appstudio/infra-deployments/pull/86
> Authentication is very cluster specific, remove from devmode

- components/build/openshift-pipelines/kustomization.yaml
- components/build/openshift-pipelines/patch-tekton-config-rb.yaml
- components/build/openshift-pipelines/patch-tekton-config-role.yaml
- components/build/openshift-pipelines/patch-tekton-config-sa.yaml
- components/build/openshift-pipelines/pruner-configuration-job.yaml
Use job to configure pruner in TektonConfig.
> Configure tekton PipelineRuns pruner

- README.md
> Fix typo in preview.env readme instructions

- components/has/kustomization.yaml
Picks up the following changes
- https://github.com/redhat-appstudio/application-service/pull/25
- https://github.com/redhat-appstudio/application-service/pull/49
- https://github.com/redhat-appstudio/application-service/pull/46
- https://github.com/redhat-appstudio/application-service/pull/43
- https://github.com/redhat-appstudio/application-service/pull/41
> Refresh HAS in staging

- components/has/kustomization.yaml
Shouldn't have been removed in https://github.com/redhat-appstudio/infra-deployments/pull/110 🤦
> Add back argocd-permissions.yaml for HAS

- README.md
- argo-cd-apps/overlays/development/delete-applications.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- hack/bootstrap-cluster.sh
- hack/destroy-cluster.sh
- hack/preview-template.env
- hack/util-set-development-repos.sh
- Allow to pick Applications in development modes via DEPLOY_ONLY env
- Allow to select mode during bootstrap -> avoiding to deploying upstream mode first. Upstream mode is still default.
> Allow to select mode during bootstrap, allow to select application for deployment

- components/authentication/build-ci.yaml
- components/authentication/view-build-service.yaml
Create build-templates-maintainers role binding to be able to configure build-templates namespace
> Add build service view and pipeline-maintainer role

- components/gitops/staging/dbschema-config-map.yaml
This PR:
- Updates the ConfigMap which contains the latest database schema (related: I need to automate the process of keeping this up-to-date :stuck_out_tongue: )
> GitOps Service: Update database schema ConfigMap

- components/authentication/spi-ci.yaml
Giving me access to unblock #130
> Access to add SPI secrets

- components/has/kustomization.yaml
[DEVHAS-70] Add K8s labels to gitops resources (https://github.com/redhat-appstudio/application-service/pull/53)
https://github.com/redhat-appstudio/application-service/commit/648b04951243425302fcdbcfffb680ad40f908b8
https://github.com/redhat-appstudio/application-service/commit/18fee7fbaa0e7494d7db5efa7f32d7cd2d184ec1
> HAS: App labels, build pv subpath, build resources in gitops repo

- README.md
> Update directory in README

- components/has/kustomization.yaml
Pulls in https://github.com/redhat-appstudio/application-service/pull/66
> Refresh HAS in staging to pull in GitOps repo visibility changes

- .ci/oci-e2e-deployment.sh
- README.md
- components/authentication/build-ci.yaml
- components/authentication/user-ci-maintainer.yaml
- components/build/kustomization.yaml
- components/build/tekton-results/allow-http2.yaml
- components/build/tekton-results/db-execution-configmap.yaml
- components/build/tekton-results/ingress-annotation-job.yaml
- components/build/tekton-results/ingress-annotation-rb.yaml
- components/build/tekton-results/ingress-annotation-role.yaml
- components/build/tekton-results/ingress-annotation-sa.yaml
- components/build/tekton-results/kustomization.yaml
- components/build/tekton-results/patch-postgres-redhat-statefulset.yaml
- components/build/tekton-results/route.yaml
- hack/bootstrap-cluster.sh
- hack/build/set-tkn-results.sh
- Install tekton results
- Add permission to pipeline-maintainers to list and search in results
- Create helper script for setting `tkn results` command
TODO:
> Install tekton results

- components/authentication/tenants/shbose.yaml
.. this is temporary as part of demo prep.
> Bump privileges in namespace

- hack/bootstrap-cluster.sh
The config is in a different location on a mac
> dynamic support for openssl.cnf location

- components/has/kustomization.yaml
Switching to newest application-service image which contains the new annotation for PipelineRuns and a new field (releaseStrategies) in the Component CRD.
> Switch to 5864c77a3d1701618d358fd8fd0b53f38226bd49

- README.md
- components/authentication/e2e-tests-ci.yaml
- components/authentication/kustomization.yaml
- components/e2e-tests/.tekton/event-listener.yaml
- components/e2e-tests/.tekton/kustomization.yaml
- components/e2e-tests/.tekton/pvc.yaml
- components/e2e-tests/.tekton/serviceaccount.yaml
- components/e2e-tests/.tekton/trigger-template.yaml
- components/e2e-tests/.tekton/webhook-route.yaml
- components/e2e-tests/kustomization.yaml
> Build e2e-tests image in appstudio.

- argo-cd-apps/base/e2e-tests.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
> Fix: Add e2e-tests to app-of-apps.

- components/e2e-tests/.tekton/kustomization.yaml
- components/e2e-tests/.tekton/webhook-route.yaml
> Fix: Add missing route for e2e-tests event listener.

- components/has/kustomization.yaml
Pulls in https://github.com/redhat-appstudio/application-service/pull/63
> Update HAS to f9bd765925c2cc968701f236ab13892ef17a7e58

- components/has/kustomization.yaml
https://github.com/redhat-appstudio/application-service/commit/2976522a9052887a66a537c5e502cb7ac3fb8848
> Support builds for private git repos

- hack/preview-template.env
- hack/preview.sh
Avoid pull limit issue with docker.io by allow to set global image pull
secret.
> Preview mode: set docker.io globally

- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/base/release.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/release/allow-argocd-to-manage.yaml
- components/release/argocd-permissions.yaml
- components/release/kustomization.yaml
- components/release/manager_resources_patch.yaml
This change is adding a new component to deploy the release-service operator.
> Add release component

- components/has/kustomization.yaml
This PR updates HAS to include CDQ CR Alizer integration - https://github.com/redhat-appstudio/application-service/pull/64
> Update HAS to include CDQ w/Alizer

- components/gitops/staging/dbschema-config-map.yaml
- components/gitops/staging/kustomization.yaml
- components/gitops/staging/managed-gitops-appstudio-controller-deployment.yaml
- components/gitops/staging/managed-gitops-backend-deployment.yaml
- components/gitops/staging/managed-gitops-clusteragent-deployment.yaml
- components/gitops/staging/managed-gitops.redhat.com_gitopsdeployments.yaml
- components/gitops/staging/postgresql-staging.yaml
This PR:
- Update image/manifests to latest GitOps Service 'managed-gitops' commit 8c72ce9bc207c389e260a2808514083accbe42cf
> GitOps Service: Update to managed-gitops 8c72ce9bc207c389e260a2808514083accbe42cf

- components/build/.tekton/trigger-template.yaml
Clone infra-deployments, update the code, push and create MR.
Testing MR produced by the pipeline: #149 
Secret is set on the stage instance.
> Create MR when new build-definitions pipelines are created

- components/has/kustomization.yaml
Pulls in:
- https://github.com/redhat-appstudio/application-service/pull/77
- https://github.com/redhat-appstudio/application-service/pull/76
- https://github.com/redhat-appstudio/application-service/pull/75
> Update HAS to ebf7fed9ab85eae3ce2736f089886594d5765a39

- components/has/kustomization.yaml
https://github.com/redhat-appstudio/application-service/pull/79
> Pull in changes associated with bundle fixes

- components/authentication/tenants/shbose.yaml
follow-up from https://github.com/redhat-appstudio/infra-deployments/pull/185
> Make sbose78 an admin in the org/namespace redhat

- hack/chains/check-taskrun.sh
For in-toto the data being signed is in the DSSE protocol format[1], so
when verifying using `cosign verify-blob` we need to present the data in
that format.
[1] https://github.com/secure-systems-lab/dsse/blob/master/protocol.md
> Signature verification for in-toto via verify-blob

- hack/chains/README.md
- hack/chains/config.sh
- hack/chains/create-signing-secret.sh
- hack/chains/default-pipelines-demo.sh
- hack/chains/kaniko-cosign-verify.sh
- hack/chains/kaniko-demo.sh
- hack/chains/nice-logs.sh
- hack/chains/rekor-image-lookup.sh
- hack/chains/rekor-verify-taskrun.sh
A handful of miscellaneous fixes and cleanups related to chains. It's mostly tweaks to the demo scripts, but there's one configuration change intended to allow argocd admin permissions in the tekton-chains namespace.
See commits for explanations.
> Misc small chains improvements

- hack/chains/README.md
- hack/chains/config.sh
- hack/chains/deploy-local-rekor.sh
- hack/chains/deploy-local-rekor.tpl
This adds support for deploying rekor server in a local cluster.
Signed-off-by: Rob Nester <rnester@redhat.com>
> HACBS-60 - Add support for local cluster rekor

- hack/chains/rekor-image-lookup.sh
- hack/chains/rekor-verify-taskrun.sh
> Support custom rekor-server in image lookup

- components/authentication/view-build-service.yaml
- Removing Guillaume
- Adding myself (Michkov) to investigate why pruning is not working
> Adding access to Michkov to see openshift-pipelines

- hack/bootstrap-cluster.sh
Signed-off-by: Chris Ahl <cahl@redhat.com>
For issue #202
> Fix script to work on Mac without realpath tool

- components/authentication/kustomization.yaml
- components/authentication/view-e2e-tests.yaml
> Add view ClusterRole for QE team to e2e-tests namespace.

- components/build/kustomization.yaml
- components/build/pvc-cleaner/gitops/kustomization.yaml
- components/build/pvc-cleaner/has/kustomization.yaml
- components/build/pvc-cleaner/pipeline-applications/kustomization.yaml
- hack/build/utils/show-pvc.sh
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
> Add pvc-cleaner commonent.

- README.md
- hack/build/build-via-appstudio.sh
- hack/build/templates/application.yaml
- hack/build/templates/component.yaml
Script for secret creation and building via application and components
by AppStudio.
Replacement of m2-builds.sh after merge of https://github.com/redhat-appstudio/application-service/pull/74
> Add script for testing building via AppStudio

- components/authentication/view-build-service.yaml
Allow to see tekton configuration
> Allow to read operator.tekton.dev

- hack/chains/README.md
Adds the tested platforms for cluster-bot.
> Update chains readme

- components/authentication/view-gitops-service.yaml
Add users for read access to gitops service: CathalOConnorRH, Michkov
> Add users for read access to gitops service

- components/authentication/kustomization.yaml
- components/authentication/view-cluster-registration.yaml
Signed-off-by: Chris Ahl <cahl@redhat.com>
Part of issue https://issues.redhat.com/browse/CMCS-50
> Add ability to view cluster-registration pods

- .ci/oci-e2e-deployment.sh
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> RHDP-426 Send Webhook after the tests finished in OpenShift CI

- components/authentication/kustomization.yaml
- components/authentication/patch-argocd.yaml
- components/build/openshift-pipelines/patch-tekton-config-rb.yaml
* Investigate issue on stage why patching of tekton config returns '(no
change)' but the pruner is not set.
* Give permission to apply script from #155
> Set permission to investigation and apply one time changes

- components/has/kustomization.yaml
Signed-off-by: John Collier <jcollier@redhat.com>
> Update HAS to bd09eb52ee6b87f0543ebca701dbc795eb017929

- components/has/kustomization.yaml
- components/has/manager_resources_patch.yaml
Pulls in: 
- https://github.com/redhat-appstudio/application-service/pull/86
Also bumps up the memory limit to 2Gi
> Update HAS to 75a4c79e49ab5c1a4c15d844256d1e4419da63e3

- components/build/build-service/allow-argocd-to-manage.yaml
- components/build/build-service/kustomization.yaml
- components/build/kustomization.yaml
Adding Build-service deployment configuration to infra-deployments.
> Add build-service deployment configuration

- components/authentication/view-build-service.yaml
- components/authentication/view-e2e-tests.yaml
- components/authentication/view-gitops-service.yaml
- components/authentication/view-has.yaml
- components/authentication/view-spi.yaml
Using Groups which are mapped to teams in redhat-appstudio org, based on changes in #265
> Prefer using Groups for view roles

- components/has/kustomization.yaml
Updates HAS in stage to pull in:
- https://github.com/redhat-appstudio/application-service/pull/94
> Update HAS to 6ae1a3ff557d6d01fbc6a00db655b1babf3df786

- hack/chains/config.sh
Inspired by https://github.com/hacbs-contract/chains/pull/7
> Enable pipeline support for chains more easily

- hack/chains/release-pipeline-with-ec-demo.sh
> Add demo of enforcing EC in a pipeline

- components/has/kustomization.yaml
Pulls in the following changes:
- https://github.com/redhat-appstudio/application-service/pull/89
- https://github.com/redhat-appstudio/application-service/pull/92
- https://github.com/redhat-appstudio/application-service/pull/94
- https://github.com/redhat-appstudio/application-service/pull/95
- https://github.com/redhat-appstudio/application-service/pull/97
> Update HAS to 27318cfaa0c82c3e48a76c5d139fdacb8205a801

- components/build/build-service/kustomization.yaml
Override image for build-service.
> Define image for build-service

- components/spi/kustomization.yaml
SPI release 0.4.6 with the manual upload of Quay tokens
> SPI release 0.4.6

- hack/chains/copy-public-sig-key.sh
> Use cosign to copy the public key

- components/has/kustomization.yaml
Pulls in:
- https://github.com/redhat-appstudio/application-service/pull/98
- https://github.com/redhat-appstudio/application-service/pull/99
> Update HAS to 45c4a52d9b6c567983ec72c3a6b776a95b99ba26

- .ci/oci-e2e-deployment.sh
https://issues.redhat.com/browse/PLNSRVCE-149
> fix: update openshift-ci script

- components/authentication/view-build-service.yaml
- components/build/build-templates/e2e/kustomization.yaml
- components/build/build-templates/e2e/namespace.yaml
- components/build/build-templates/e2e/role.yaml
- components/build/build-templates/e2e/rolebinding.yaml
- components/build/build-templates/kustomization.yaml
Create build-templates-e2e namespace for running test of build templates
bundles.
> Add build-templates-e2e namespace for test execution

- hack/chains/nice-logs.sh
> Show non-json log lines from Chains

- hack/build/utils/show-pvc.sh
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
> Add namespace and pvc-claim arguments to show-pvc.sh

- components/build/pvc-cleaner/kustomization.yaml
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
> Update pvc-cleaner for AppStudio components

- components/authentication/view-build-service.yaml
- components/build/infra-deployments-ci/kustomization.yaml
- components/build/infra-deployments-ci/namespace.yaml
- components/build/infra-deployments-ci/pipelines-as-code.yaml
- components/build/infra-deployments-ci/pvc.yaml
- components/build/kustomization.yaml
Set PaC to be able to run checks on infra-deployments
> Set PaC repository on infra-deployments

- components/gitops/staging/kustomization.yaml
This PR:
- Updates the GitOps Service's container images and resource manifests, to the latest commit, as of this writing.
> Update to latest GitOps Service to latest commit: fed1a8c90f6c35247de21f1f0530ba4e99afacb3

- components/has/kustomization.yaml
Pulls in 
- https://github.com/redhat-appstudio/application-service/pull/107
> Update HAS to 6e9dda9f2676e9211d01afe54ccdf1c6c82a85f5

- components/build/build-service/kustomization.yaml
- components/has/kustomization.yaml
Contain:
- https://github.com/redhat-appstudio/application-service/pull/106
- https://github.com/redhat-appstudio/build-service/pull/14
- https://github.com/redhat-appstudio/build-service/pull/11
> Bundle selection enablement

- components/build/build-service/.tekton/kustomization.yaml
- components/build/build-service/.tekton/serviceaccount.yaml
build-service is using sharedSecret
> Build-service does not need modify SA

- hack/chains/release-pipeline-with-ec-demo.sh
> demo: Support local rekor instance

- components/authentication/tenants/kustomization.yaml
- components/authentication/tenants/mvalarh.yaml
Add Michal Vala admin rights on his namespace to be able to properly prepare for the SPI demo on staging.
> Add Michal Vala admin rights on his namespace

- components/authentication/view-has.yaml
Build team is working on build-service which is connected to application service.
> Allow build team members to view application-service

- hack/chains/release-pipeline-with-ec-demo.sh
Closes [HACBS-434](https://issues.redhat.com//browse/HACBS-434)
> Remove deprecated policy repo refs in ec demo

- .github/workflows/auto-update.yml
Based on the following conversation https://coreos.slack.com/archives/C02FANRBZQD/p1652911572021579
i have added an github action that will autoupdate the PR's that are approved by rebasing them whenever there are new changes in the repo .
JIRA: https://issues.redhat.com/browse/RHDP-474 
Signed off by @sawood14012 , [msawood@redhat.com](mailto:msawood@redhat.com)
> chore: Auto Rebase PR's that are approved

- components/spi/kustomization.yaml
Changed  allowed origins from https://prod.foo.redhat.com -> …https://prod.foo.redhat.com:1337
> SPI. Changed cors configuration.

- components/build/tekton-chains/chains-config.yaml
- components/build/tekton-chains/chains-controller-deployment.yaml
- hack/chains/config.sh
https://issues.redhat.com/browse/HACBS-461
> Use custom version of chains to attest pr

- .ci/oci-e2e-deployment.sh
Create openshift user which are necessary for has tests.
> Add openshift ci custom user

- .ci/oci-e2e-deployment.sh
* **Fix CI scripts**
* Follow-up on and https://github.com/redhat-appstudio/e2e-tests/pull/74 https://github.com/redhat-appstudio/e2e-tests/pull/92
> fix: add SPI setup to openshift-ci e2e

- components/has/kustomization.yaml
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
This PR includes
- https://github.com/redhat-appstudio/application-service/pull/118
- https://github.com/redhat-appstudio/application-service/pull/124
- https://github.com/redhat-appstudio/application-service/pull/112
- https://github.com/redhat-appstudio/application-service/pull/113
- https://github.com/redhat-appstudio/application-service/pull/116
- https://github.com/redhat-appstudio/application-service/pull/125
- https://github.com/redhat-appstudio/application-service/pull/121
creating on behalf of https://github.com/redhat-appstudio/infra-deployments/pull/384 since we cant rebase https://github.com/redhat-appstudio/infra-deployments/pull/384
> Update HAS May 27 2022

- hack/preview.sh
Force refresh of argoCD applications after changes are pushed.
> Preview mode: trigger refresh of argocd applications

- components/spi/kustomization.yaml
Context https://issues.redhat.com/browse/SVPI-133 
Changes https://github.com/redhat-appstudio/service-provider-integration-operator/commit/d3f466d20aa144fa9e61d95f0635fe00425bffaf
> SVPI-133 Print more information about failed Github's GraphQL request

- components/gitops/staging/kustomization.yaml
**Description**:
- Add the CustomResourceDefinitions for AppStudio Environment API to the cluster.
> Add Environment API CRDs to staging cluster

- components/build/openshift-pipelines/subscription.yaml
[PLNSRVCE-369](https://issues.redhat.com//browse/PLNSRVCE-369)
> Update openshift pipeline operator to v1.7.0

- hack/chains/gitops-sync.sh
> Allow toggle ArgoCD sync for enterprise-contract and rekor

- components/enterprise-contract/kustomization.yaml
> Create cluster roles for managing ECP resources

- argo-cd-apps/base/enterprise-contract.yaml
https://issues.redhat.com/browse/HACBS-380
> Update rekor to version 0.7.0

- argo-cd-apps/base/integration.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/integration/allow-argocd-to-manage.yaml
- components/integration/argocd-permissions.yaml
- components/integration/kustomization.yaml
- components/integration/manager_resources_patch.yaml
This change adds the integration component
> Add the integration component

- components/authentication/integration-ci.yaml
- components/authentication/kustomization.yaml
- components/authentication/view-build-service.yaml
- components/authentication/view-integration.yaml
Add the RBACs for the Test team and the integration service
> Setup HACBS test team's RBACs

- components/build/tekton-chains/chains-controller-deployment.yaml
Updating the chains controller with the latest chains build.
> Updating chains controller

- components/spi/kustomization.yaml
Fixes 
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/153  that fixes Spi operator is failing to start on staging https://issues.redhat.com/browse/SVPI-152
> SPI Update V0.6.1

- components/spi/kustomization.yaml
-  https://github.com/redhat-appstudio/service-provider-integration-operator/pull/150
> update spi-operator to v0.6.2

- components/has/OWNERS
Signed-off-by: John Collier <jcollier@redhat.com>
> Add OWNERS file for HAS

- OWNERS
- README.md
This PR adds an Root Owners file
> chore: Create Root Owners file

- components/integration/kustomization.yaml
> Update integration service

- hack/chains/release-pipeline-with-ec-demo.sh
> fix: Remove old task param from ec demo

- components/authentication/tenants/rbean.yaml
I think I did this incorrectly the last time.
> Give my github identity rights to my SSO-named user namespace

- components/spi/kustomization.yaml
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/171
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/170
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/141
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/161
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/163
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/173
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/167
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/181
- Used ubi8/ubi-minimal:8.6-854 image
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/1 …
> Spi update 0.6.8

- components/authentication/tenants/shebert.yaml
> Add admin role for shebert namespace

- components/authentication/tenants/kustomization.yaml
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>
> add sabhardw.yaml to kustomization

- components/build/jvm-build-service/kustomization.yaml
As part of the work around [PLNSRVCE-454](https://issues.redhat.com//browse/PLNSRVCE-454) these are no longer needed.
> Remove uneeded ClusterTasks

- components/build/tekton-chains/chains-controller-deployment.yaml
Updating chains deployment with most recent code in our chains fork: 
https://github.com/hacbs-contract/chains/commit/810cf430779da080e271a1d58b55e5058d29c424
> Updating chains deployment with rebased fork

- hack/destroy-cluster.sh
`hack/destroy-cluster.sh` can be now used for reseting the cluster. After
it's executed it is possible to run `hack/bootstrap-cluster.sh`
> Fix destruction of cluster

- components/gitops/staging/kustomization.yaml
Update GitOps Service images to commit `1b42854146c71359724dd402f72f0172f56c5443`
> GitOpsService update to 1b42854146c71359724dd402f72f0172f56c5443

- components/gitops/staging/argo-cd.yaml
- components/gitops/staging/kustomization.yaml
Selectively update memory limits on GitOps Service
> Update GitOps Service resources to latest from main branch

- components/build/build-service/kustomization.yaml
- components/gitops/staging/argo-cd.yaml
- hack/build/setup-pac-app.sh
- hack/build/templates/component.yaml
- hack/preview-template.env
- hack/preview.sh
Use pipelines-as-code instead of triggers.
> Appstudio Pipelines-as-code integration

- hack/preview.sh
Do not fail when state is 'Unknown Progressing'
> Print yaml of failed application when conditions are empty, do not fail on Progressing

- hack/destroy-cluster.sh
> PLNSRVCE-551: destroy-cluster.sh is too destructive

- components/spi/kustomization.yaml
- components/spi/vault/kustomization.yaml
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/212
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/214
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/213
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/210
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/216
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/219
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/220
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/127
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/126
> Spi update 0.7.2

- components/build/pipelines-as-code/kustomization.yaml
fix failure to report final PipelineRun status with GitHub App
https://github.com/openshift-pipelines/pipelines-as-code/releases/tag/v0.11.1
> Update PipelinesAsCode to v0.11.1

- components/quality-dashboard/frontend/deployment.yaml
- components/quality-dashboard/frontend/service.yaml
This PR fixes the current deployment failure of the quality dashboard frontend 
Signed off by msawood@redhat.com
> fix: Labels for frontend deployment

- components/quality-dashboard/frontend/deployment.yaml
> fix: Quality Dashboard frontend Labels  

- components/build/pipelines-as-code/kustomization.yaml
Avoiding issue [SRVKP-2377](https://issues.redhat.com//browse/SRVKP-2377)
> Downgrade PaC to v1.10.2

- components/build/tekton-results/.tekton/kustomization.yaml
- components/build/tekton-results/.tekton/pipelines-as-code.yaml
- components/build/tekton-results/.tekton/pvc.yaml
- components/build/tekton-results/kustomization.yaml
- PR to add pull request/push PipelineRun configs to tekton results: https://github.com/openshift-pipelines/tektoncd-results/pull/5
- Jira issue: [PLNSRVCE-548](https://issues.redhat.com//browse/PLNSRVCE-548)
Signed-off-by: Avinal Kumar <avinal@redhat.com>
> Add Tekton Result build configuration for HACBS 

- components/authentication/tenants/kustomization.yaml
- components/authentication/tenants/managed-rbean-namespace.yaml
- components/authentication/tenants/rbean.yaml
> Setting up managed workspace for rbean for demo

- components/spi/kustomization.yaml
- components/spi/vault/kustomization.yaml
- hack/monitoring/prometheus_servicemonitors.yaml
ServiceMonitor for spi-operator
Context
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/230
- https://issues.redhat.com/browse/SVPI-182
> Introduced SPI operator ServiceMonitor

- components/authentication/build-ci.yaml
- components/build/shared-resources/shared-resources-components.yaml
- components/build/tekton-results/.tekton/kustomization.yaml
- components/build/tekton-results/.tekton/serviceaccount.yaml
- allow to set custom registry secret
- allow Avinal to create secret in the namespace
> Allow access tekton-pipelines to shared secret

- components/authentication/tenants/shbose.yaml
- Refactor of Release Links to Release Plan and Release Plan Admission
> update rbac for refactor of release links

- components/authentication/tenants/rbean.yaml
I need rights to delete a validatingwebhookconfiguration to let argo
recreate it, to prove or disprove a theory in:
https://coreos.slack.com/archives/C031USXS2FJ/p1661870515286729
> Grant rbean tekton-triggers-admin

- components/authorization/cluster/kustomization.yaml
- components/authorization/kcp/kustomization.yaml
Fix of failing authentication on new kcp clusters
> auth: Fix link to files

- argo-cd-apps/base/authorization-in-cluster.yaml
- argo-cd-apps/overlays/development/delete-applications.yaml
> fix: authentication -> authorization

- components/authentication/tenants/rbean.yaml
This reverts commit f6f73906c893c3e485a7b124cbc26077020566e5.
> Revert "Grant rbean tekton-triggers-admin"

- hack/bootstrap.sh
> fir: drop missing usage of dev mode script

- hack/bootstrap.sh
- hack/util-set-development-repos.sh
- hack/util-update-app-of-apps.sh
when the dev mode is used, then it updates ArgoCD to use the right overlay
> fix: dev mode uses the right overlay

- components/quality-dashboard/frontend/deployment.yaml
- components/quality-dashboard/frontend/service-account.yaml
- Adds new Login screen to the Dashboard 
- promotes the logout feature in the dashboard
- Also enables authorization basis of an htpasswd file
> fix: Upgrade Dashboard to Latest

- README.md
- argo-cd-apps/app-of-apps/all-applications-staging.yaml
- argo-cd-apps/base/authentication.yaml
- argo-cd-apps/base/build.yaml
- argo-cd-apps/base/cluster-registration.yaml
- argo-cd-apps/base/e2e-tests.yaml
- argo-cd-apps/base/enterprise-contract.yaml
- argo-cd-apps/base/gitops.yaml
- argo-cd-apps/base/has.yaml
- argo-cd-apps/base/integration.yaml
- argo-cd-apps/base/quality-dashboard.yaml
- argo-cd-apps/base/release.yaml
- argo-cd-apps/base/spi.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/build/README.md
- hack/preview.sh
- hack/util-set-development-repos.sh
- hack/util-update-app-of-apps.sh
use `pre-kcp` branch as the target revision for all infra-deployments-related stuff in `pre-kcp` branch :-)
> use pre-kcp branch

- hack/setup/prepare-crc.sh
To make the branch switch easier, let's merge the `main` branch into `kcp` first, so it's up-to-date. Then I'll be able to easily create a PR from `kcp` into `main.
The next steps will be:
1. create a PR from `kcp` to `main`
2. change all `targetRevision` occurences to `main`
The only change that is kept from all the changes is this commit https://github.com/redhat-appstudio/infra-deployments/commit/fdfd38118e8e22238db546d9be0e8c5d2836e94c
> merge main into kcp

- components/build/jvm-build-service/.tekton/pipelines-as-code.yaml
jvm-build-service-builder-images has been taken from jvm-build-service
> CI: PaC cover jvm-build-service-builder-images

- hack/preview.sh
`preview.sh` is working with ArgoCD deployed on physical cluster. `oc` and `kubectl` commands should be forced to use CLUSTER_KUBECONFIG
> preview: force usage of CLUSTER_KUBECONFIG

- README.md
- hack/bootstrap.sh
> Show message when invalid bootstrap mode is used

- argo-cd-apps/overlays/development/repo-overlay.yaml
Finalizer is working only on Application level.
> resources-finalizer is not valid for ApplicationSets

- argo-cd-apps/base/application-api.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/application-api/base/kustomization.yaml
- components/application-service/base/kustomization.yaml
- components/application-service/base/manager_resources_patch.yaml
- components/application-service/overlays/dev/kustomization.yaml
- components/application-service/overlays/kcp-stable/kustomization.yaml
- components/application-service/overlays/kcp-unstable/kustomization.yaml
- components/ckcp/deployment.yaml
- hack/preview.sh
- hack/util-set-github-org
- Changed structure to include overlays
- added application-api
When APIBinding created in different workspace the application-service starts sucessfully and creates github repositories
> Integration of application-api

- README.md
- hack/install-pipeline-service.sh
Script for installing Pipeline Service for testing purposes.
> Add script for install Pipeline Service

- components/spi/base/kustomization.yaml
- hack/preview.sh
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/257
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/267
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/274
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/153
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/158
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/160
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/157
> Update spi components with latest changes

- README.md
Also includes what's in https://github.com/redhat-appstudio/infra-deployments/pull/718/
> Fixed some wording, grouped access info together

- apibindings/appstudio/build-service.yaml
- apibindings/appstudio/kustomization.yaml
- argo-cd-apps/base/build-service.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/build-service/OWNERS
- components/build-service/base/kustomization.yaml
- components/build-service/overlays/dev/apiexport.yaml
- components/build-service/overlays/dev/kustomization.yaml
- components/build-service/overlays/kcp-stable/apiexport.yaml
- components/build-service/overlays/kcp-stable/kustomization.yaml
- components/build-service/overlays/kcp-unstable/apiexport.yaml
- components/build-service/overlays/kcp-unstable/kustomization.yaml
- hack/build/build-via-appstudio.sh
Adding build-service supporting KCP
> Add build-service

- components/authorization/kcp/base/members-view-everything.yaml
Give Gal Ben Haim permissions to view resources.
Signed-off-by: gbenhaim <gbenhaim@redhat.com>
> Give Gal Ben Haim permissions to view resources

- components/authentication/tenants/kustomization.yaml
- components/authentication/tenants/sm43.yaml
to debug an issue where PAC is failing to report status, we need to debug the issue. we were unable to reproduce the issue on other cluster.
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
> Provides sm43 same access as PAC to debug an issue

- hack/preview.sh
> Fix variable quoting in preview.sh for APIExports

- hack/preview.sh
> preview - Update of identityhash code

- components/application-service/overlays/dev/apiexport.yaml
- components/application-service/overlays/dev/kustomization.yaml
- components/application-service/overlays/kcp-stable/apiexport.yaml
- components/application-service/overlays/kcp-stable/kustomization.yaml
- components/application-service/overlays/kcp-unstable/apiexport.yaml
- components/application-service/overlays/kcp-unstable/kustomization.yaml
Based on changes in https://github.com/redhat-appstudio/application-service/pull/192
> Update application-service to use apiexport from repo

- components/authorization/kcp/base/members-view-everything.yaml
This PR adds bkundu to have view access to kcp
Signed-off-by: Bamacharan Kundu <bamachrn@gmail.com>
> Add bkundu to everything viewer for kcp

- hack/configure-kcp.sh
> Bind syncer to kcp version

- hack/monitoring/configure_grafana.yaml
- hack/monitoring/configure_prometheus.yaml
- hack/monitoring/prometheus_servicemonitors.yaml
- hack/setup_observability.sh
APIVersion for the template resource needs update as it is moved from default group
> Template API Version update

- hack/build/build-via-appstudio.sh
Pipeline SA is created automatically by build-service
> build-via-appstudio.sh: do not create pipeline SA

- apibindings/hacbs/kustomization.yaml
- apibindings/hacbs/release-service.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/base/release-service.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/hacbs/release-service/OWNERS
- components/hacbs/release-service/base/kustomization.yaml
- components/hacbs/release-service/overlays/dev/apiexport.yaml
- components/hacbs/release-service/overlays/dev/kustomization.yaml
- components/hacbs/release-service/overlays/kcp-stable/apiexport.yaml
- components/hacbs/release-service/overlays/kcp-stable/kustomization.yaml
- components/hacbs/release-service/overlays/kcp-unstable/apiexport.yaml
- components/hacbs/release-service/overlays/kcp-unstable/kustomization.yaml
> add hacbs release-service apiexport

- components/application-service/overlays/kcp-unstable/apiexport.yaml
- components/build-service/overlays/kcp-unstable/apiexport.yaml
- components/hacbs/jvm-build-service/overlays/kcp-unstable/apiexport.yaml
- components/hacbs/release-service/overlays/dev/apiexport.yaml
- components/hacbs/release-service/overlays/kcp-stable/apiexport.yaml
- components/hacbs/release-service/overlays/kcp-unstable/apiexport.yaml
- hack/generate-apiexport-overlays.sh
Fix of variable in function which should be local.
> Fix: generate-apiexport-overlays.sh and regenerate

- apibindings/hacbs/integration-service.yaml
- apibindings/hacbs/kustomization.yaml
- argo-cd-apps/base/integration-service.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/hacbs/integration-service/OWNERS
- components/hacbs/integration-service/base/kustomization.yaml
- components/hacbs/integration-service/overlays/dev/apiexport.yaml
- components/hacbs/integration-service/overlays/dev/kustomization.yaml
- components/hacbs/integration-service/overlays/kcp-stable/apiexport.yaml
- components/hacbs/integration-service/overlays/kcp-stable/kustomization.yaml
- components/hacbs/integration-service/overlays/kcp-unstable/apiexport.yaml
- components/hacbs/integration-service/overlays/kcp-unstable/kustomization.yaml
Signed-off-by: Hongwei Liu hongliu@redhat.com
> Add hacbs integration-service apiexport to support kcp

- components/spi/base/kustomization.yaml
- components/spi/vault/kustomization.yaml
- hack/preview.sh
This PR includes:
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/283
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/283
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/299
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/298
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/284
Signed-off-by: Max Shaposhnyk <mshaposh@redhat.com>
> Update SPI to the latest version

- components/hacbs/release-service/base/kustomization.yaml
- components/hacbs/release-service/base/manager_resources_patch.yaml
> add hacbs release-service manager

- hack/preview-template.env
> Add description of WORKSPACE env vars

- argo-cd-apps/base/build-templates.yaml
- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/overlays/development/repo-overlay.yaml
- components/build-templates/kustomization.yaml
- components/build-templates/namespace.yaml
- components/build-templates/role.yaml
- components/build-templates/rolebinding.yaml
Build templates manages configmap in build-templates namespace used for selection of tekton bundles.
> Set build-templates component

- hack/bootstrap.sh
- hack/flags.sh
- hack/install-ckcp.sh
- hack/preview.sh
- hack/util-patch-spi-config.sh
- hack/util-set-development-repos.sh
- hack/util-set-github-org
- exit script when subcommand fails
- improve text output
> Improve scripts to end when subcommand fails

- hack/quicklab/templates/storageClass.yaml
- fix typo in param
- change destination dir to be only one dir otherwise it's not deleted with the PVC deletion
> Quicklab: fix directory removal

- hack/flags.sh
- hack/preview-template.env
- hack/preview.sh
- hack/util-validate-preview-env.sh
- Check required environments
- Put warning for record env in preview.env
- Print list of unused env variables
> Update util-validate-preview-env.sh to be more compact

- hack/preview.sh
In CI we need to wait few seconds until the routes are binding in redhat-appstudio workspace
> Add timeout for SPI OAUTH route creation

- argo-cd-apps/base/hac-pact-broker.yaml
Add target revision to fix pact broker deplyoment.
> Fix pact broker

- components/authentication/kustomization.yaml
- components/authentication/pact-broker.yaml
Add RoleBinding with view ClusterRole. Add a file with those permissions to kustomization.yaml.
> Fix permissions

- hack/install-pipeline-service.sh
fix according to the conversation https://coreos.slack.com/archives/C02FTKEMBU1/p1667218204211649  signed off by msawood@redhat.com
> fix: local versioned pipeline service

- components/has/.tekton/kustomization.yaml
- components/has/.tekton/pipelines-as-code-application-api.yaml
Add PaC repository for application-api to application-service namespace to make minimal changes in pre-kcp branch.
> Enable PaC for application-api

- components/integration/kustomization.yaml
- components/integration/manager_resources_patch.yaml
Signed-off-by: Jing Qi <jinqi@redhat.com>
> Update the integration image with some rbac issues fixed

- components/authorization/kcp/appstudio/build-service-secrets.yaml
- components/authorization/kcp/appstudio/kustomization.yaml
Allow to create secrets in build-service namespace.
> Build-service secrets creation roles

- components/monitoring/base/configure-prometheus.yaml
This PR is for fixing ArgoCD syncer from failing to deploy prometheus CR
> Removed interval from snitchHeartBeat

- apibindings/hacbs/enterprise-contract.yaml
- apibindings/hacbs/kustomization.yaml
> add enterprise contract APIBinding

- components/application-api/allow-argocd-to-manage.yaml
- components/application-api/argocd-permissions.yaml
> fix: add missing files in application-api application

- components/authentication/prune-has.yaml
https://github.com/redhat-appstudio/infra-deployments/pull/949 should have included environments
> Allow listing of environments in HAS pruner role

- components/has/kustomization.yaml
Updates HAS to a852feca3998db496d08ba012ba0cc588af5a6a3, which includes:
- https://github.com/redhat-appstudio/application-service/commit/a852feca3998db496d08ba012ba0cc588af5a6a3
> Bump HAS to a852feca3998db496d08ba012ba0cc588af5a6a3

- components/pipeline-service/openshift-pipelines/subscription.yaml
Testing PR for now to see which services are broken.
> Update Openshift pipelines to v1.8

- components/tekton-ci/repository.yaml
> chore: Add quality dashboard PaC Repository

- components/monitoring/base/configure-prometheus.yaml
- components/monitoring/base/grafana-app.yaml
This PR is to address errors while monitoring is getting deployed using ArgoCD
> Fix monitoring deployment with  ArgoCD 

- components/authentication/everyone-can-view.yaml
- allow to view repositories from pipelinesascode.tekton.dev
- jvmbuildservice.io - renamed userconfigs to jbsconfigs
> Auth-view: add PaC repositories, update jvm-build-service

- components/enterprise-contract/kustomization.yaml
https://issues.redhat.com/browse/HACBS-1410
> Add ConfigMap for latest EC task

- components/tekton-ci/repository.yaml
https://issues.redhat.com/browse/HACBS-1494
> Enable PaC for the ec-golden-image repository

- components/authentication/kustomization.yaml
- components/authentication/release-team.yaml
- Add GH group
- rename related files
> Update release team access

- argo-cd-apps/base/kustomization.yaml
- argo-cd-apps/base/monitoring-workload-grafana.yaml
- argo-cd-apps/base/monitoring-workload-logging.yaml
- argo-cd-apps/base/monitoring-workload-prometheus.yaml
- argo-cd-apps/overlays/development/delete-applications.yaml
This PR updates monitoring deployment
This deploys in 3 applications
* Prometheus
* grafana
* logging
> Updated GitOps deployments for monitoring with new file structure

- hack/build/build-via-appstudio.sh
I have been using this snippet for my testing for PLNSRVCE-693. Hopefully, it is useful for others as well.
> Allow testing with repo url that ends with .git

- components/enterprise-contract/kustomization.yaml
> Update verify ec-task reference

- components/has/kustomization.yaml
Copy of #1058 with pairing on e2e-test https://github.com/redhat-appstudio/e2e-tests/pull/275
> application-service update - with e2e-tests pairing

- components/build-service/build-pipeline-selector.yaml
- components/build-service/kustomization.yaml
- components/jvm-build-service/kustomization.yaml
> build-service: Pipeline selection

- components/build-service/build-pipeline-selector.yaml
- components/build-service/kustomization.yaml
- components/build-templates/kustomization.yaml
https://github.com/redhat-appstudio/e2e-tests/pull/280
> build-definitions - Skip checks pairing with e2e-tests

- components/build-service/build-pipeline-selector.yaml
> PLNSRVCE-934: remove hacbs param from pipeline selector config

- components/monitoring/README.md
This PR adds the documentation for on-boarding services to prometheus and grafana
Signed-off-by: Bama Charan Kundu [bamachrn@gmail.com](mailto:bamachrn@gmail.com)
> Add onboarding to monitoring

- components/build-service/build-pipeline-selector.yaml
Select fbc-builder pipeline when language in devfile is set to fbc.
> PLNSRVCE-885: build-selector - add FBC pipeline

- components/pipeline-service/tekton-chains/kustomization.yaml
https://issues.redhat.com/browse/HACBS-1529
> Update Tekton Chains to 0.14.0

- components/monitoring/prometheus/base/configure-prometheus.yaml
- components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
> Added metrics reader access to prometheus

- components/pipeline-service/public/README.md
- components/pipeline-service/public/tekton-chains-signing-secret.pub
Required by entreprise contrat
> Add tekton-chains public signing key

- components/monitoring/grafana/base/dashboards/controller-runtime-controllers-detail_rev1.json
- components/monitoring/grafana/base/kustomization.yaml
Generic controller-oriented grafana dashboard.
Grafana dashboard https://grafana.com/grafana/dashboards/15920-controller-runtime-controllers-detail/?tab=revisions after the import to this instance https://grafana-appstudio-workload-monitoring.apps.appstudio-stage.x99m.p1.openshiftapps.com/dashboards?query=
> Profiling performance-related metrics based on controller-runtime

- hack/build/build-via-appstudio.sh
> Allow to annotate a component with skip-initial-checks

- components/tekton-ci/repository.yaml
https://issues.redhat.com/browse/DEVHAS-217
Signed-off-by: Kim Tsao <ktsao@redhat.com>
> [DEVHAS-217] onboard gitops-repo-pruner repo

- components/monitoring/grafana/base/dashboards/go-processes_rev1.json
- components/monitoring/grafana/base/kustomization.yaml
Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details
> Grafana dashboard: Go Prometheus client library

- components/dev-sso/keycloak-realm.yaml
This reverts commit 811091410366a217960b0af75038e6152c92c206.
Revert change which was pushed by mistake.
> Revert "Update keycloak-realm.yaml"

- components/quality-dashboard/backend/kustomization.yaml
- components/quality-dashboard/frontend/kustomization.yaml
PR: https://github.com/redhat-appstudio/quality-dashboard/pull/26
> Update quality dashboard images with codecov v2 api

- components/monitoring/grafana/base/grafana-app.yaml
> Fixes issue: mount path should be unique

- components/build-service/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/build-service/pull/100
pairing with https://github.com/redhat-appstudio/e2e-tests/pull/302 to test the bug fix in build-service
> build-service update

- OWNERS
Signed-off-by: Romain Arnaud <rarnaud@redhat.com>
> Add Pipeline Service leads

- components/enterprise-contract/default-ecp.yaml
- components/enterprise-contract/kustomization.yaml
https://issues.redhat.com/browse/HACBS-1650
> Add default ECP resource

- components/enterprise-contract/README.md
- docs/_data/navigation.yml
JIRA: [HACBS-1591](https://issues.redhat.com//browse/HACBS-1591)
> Mention Enterprise Contract in the new docs

- components/monitoring/grafana/base/grafana-app.yaml
- components/monitoring/grafana/base/kustomization.yaml
- Incorporate 1st 5 basic metrics
- See release release service PR: https://github.com/redhat-appstudio/release-service/pull/155
> HACBS-1606 - Dashboard for Release Service

- components/enterprise-contract/OWNERS
> Add lcarva as EC owner and reviewer

- components/monitoring/grafana/README.md
This PR updates the token duration for grafana datasource authentications
> Added token expiration duration to readme

- components/quality-dashboard/backend/kustomization.yaml
- components/quality-dashboard/frontend/kustomization.yaml
PR: https://github.com/redhat-appstudio/quality-dashboard/pull/29
> updated quality-dashboard

- components/build-templates/kustomization.yaml
> PLNSRVCE-934: remove build-pipelines-defaults configmap

- argo-cd-apps/base/host/kustomization.yaml
- argo-cd-apps/base/host/sprayproxy/kustomization.yaml
- argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
- components/sprayproxy/OWNERS
- components/sprayproxy/allow-argocd-to-manage.yaml
- components/sprayproxy/kustomization.yaml
This PR adds [SprayProxy](https://github.com/redhat-appstudio/sprayproxy) as a component to the infra-deployments.
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>
> PLNSRVCE-1023 : feature:- add sprayproxy

- components/has/kustomization.yaml
Updates HAS to df9177f14a0e46f9e9da51ff2d0f6055b67f9abe to pull in just https://issues.redhat.com/browse/DEVHAS-228
> Update HAS to pull in fix for DEVHAS-228

- components/tekton-ci/repository.yaml
https://issues.redhat.com/browse/HACBS-1557
> Enable PaC on ec-cli repository

- hack/preview-template.env
- hack/preview.sh
- Add OAUTH image and tag support
> Improve support for overriding SPI images

- hack/build/build-via-appstudio.sh
- hack/build/templates/component.yaml
> Enable PaC with the new annotation

- components/authentication/tekton-ci.yaml
Signed-off-by: Jing Qi <jinqi@redhat.com>
> Add maintainer for integration service in tektion ci namespace

- components/authentication/pipeline-service-sre.yaml
- components/pipeline-service/kustomization.yaml
Pipeline-service component has been updated to be able to work on the necessary changes for the MVP staging environment.
> Update pipeline-service component to work on the new staging environment

- components/monitoring/grafana/base/grafana-app.yaml
- components/monitoring/grafana/base/has/kustomization.yaml
- components/monitoring/grafana/base/kustomization.yaml
Signed-off-by: Kim Tsao <ktsao@redhat.com>
https://issues.redhat.com/browse/DEVHAS-208
> add SLI dashboard for HAS

- argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
- components/sprayproxy/kustomization.yaml
- components/sprayproxy/servicemonitor-rbacproxy/servicemonitor.yaml
see https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1675946401182069
> remove redhat- prefix in sprayproxy etc obj names

- components/authentication/gitops-component-maintainer.yaml
- components/authentication/gitops.yaml
- components/authentication/kustomization.yaml
As discussed on stonesoup platform Slack:
- Add `jgwest` to GitOps Maintainers
- Add `gitops-component-maintainer` role
> Update gitops roles feb 2023

- components/monitoring/grafana/base/managed-gitops/kustomization.yaml
JIRA: https://issues.redhat.com/browse/GITOPSRVCE-341
> GitOps Service: Update to latest dashboard contents on managed-gitops repository

- components/monitoring/grafana/base/grafana-app.yaml
JIRA: [GITOPSRVCE-341](https://issues.redhat.com/browse/GITOPSRVCE-341)
> Add GitOps Service Dashboard references to Grafana Deployment/ConfigMap

- components/sprayproxy/OWNERS
per recent pr / stand up discussion
> add gabe to sprayproxy owners file

- components/has/kustomization.yaml
- components/monitoring/grafana/base/has/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/application-service/pull/246
- https://github.com/redhat-appstudio/application-service/pull/248
- https://github.com/redhat-appstudio/application-service/pull/230
- https://github.com/redhat-appstudio/application-service/pull/251
- https://github.com/redhat-appstudio/application-service/pull/252
- https://github.com/redhat-appstudio/application-service/pull/250
- https://github.com/redhat-appstudio/application-service/pull/255
- https://github.com/redhat-appstudio/application-service/pull/249
- https://github.com/redhat-appstudio/application-service/pull/260
- https://github.com/redhat-appstudio/application-service/pull/254
- https://github.com/redhat-appstudio/application-service/pull/252
- …
> Update Application service

- components/build-service/README.md
> Fix outdated link in README

- cluster-config/staging/member-base/namespaces/kustomization.yaml
- cluster-config/staging/member-base/namespaces/spi-system/kustomization.yaml
- cluster-config/staging/member-base/namespaces/spi-system/spi-shared-configuration-file.yaml
- cluster-config/staging/member-base/namespaces/spi-system/spi-vault-approle-spi-oauth.yaml
- cluster-config/staging/member-base/namespaces/spi-system/spi-vault-approle-spi-operator.yaml
- cluster-config/staging/stone-stg-m01/kustomization.yaml
- cluster-config/staging/stone-stg-m01/spi-shared-configuration-file-config-path.yaml
- cluster-config/staging/stone-stg-m01/spi-vault-approle-spi-oauth-config-path.yaml
- cluster-config/staging/stone-stg-m01/spi-vault-approle-spi-operator-config-path.yaml
- cluster-config/staging/stone-stg-rh01/kustomization.yaml
- cluster-config/staging/stone-stg-rh01/spi-shared-configuration-file-config-path.yaml
- cluster-config/staging/stone-stg-rh01/spi-vault-approle-spi-oauth-config-path.yaml
- cluster-config/staging/stone-stg-rh01/spi-vault-approle-spi-operator-config-path.yaml
This change adds spi's secrets managed by vault
https://issues.redhat.com/browse/SVPI-356
https://issues.redhat.com/browse/ASC-262
>  Add external secret for spi

- components/internal-services/kustomization.yaml
chore: updates CRD for InternalRequests
- updates CRD for InternalRequests
Signed-off-by: Leandro Mendes lmendes@redhat.com
> chore: updates CRD for InternalRequests

- components/quality-dashboard/backend/kustomization.yaml
- components/quality-dashboard/frontend/kustomization.yaml
- docs/deployment/stage.md
- docs/development/pre.md
- docs/introduction/about.md
PR: https://github.com/redhat-appstudio/quality-dashboard/pull/33
> update quality dashboard

- hack/bootstrap-cluster.sh
- hack/preview.sh
> STONE-445 - Fix handling of toolchain and keycloak parameters

- argo-cd-apps/base/host/sprayproxy/kustomization.yaml
- argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
- argo-cd-apps/k-components/inject-infra-deployments-repo-details/application-patch.yaml
- argo-cd-apps/k-components/inject-infra-deployments-repo-details/application-set-patch.yaml
Now that the multi-cluster branch was merged into main, we can switch our CI to deploy from main.
> feat(ASC-262): Deploy applications from main

- components/enterprise-contract/default-ecp.yaml
https://issues.redhat.com/browse/HACBS-1769
> Use shared public key in default ECP

- OWNERS
Add gbenhaim to the OWNERS file
> Add gbenhaim to the OWNERS file

- components/pipeline-service/development/kustomization.yaml
https://github.com/openshift-pipelines/pipeline-service/pull/495
> fix: pipeline-service ref update

- argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
Fix source path for quality-dashboard
> Fix source path for quality-dashboard

- argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
- argo-cd-apps/overlays/production/kustomization.yaml
No that we have overlays for the Prometheus component, we need to update the matching argo app to support them.
> Support overlays in the Prometheus app

- components/authentication/production/github-redhat-appstudio-secret-patch.yaml
- components/authentication/production/github-redhat-appstudio-sre-secret-patch.yaml
- components/authentication/production/kustomization.yaml
- Remove the sync of redhat-appstudio-sre, it's not needed.
- Update the secret patch in the production overlay.
> Update group-sync configurations

- components/spi/overlays/production/stone-prd-m01/config-patch.json
- components/spi/overlays/production/stone-prd-m01/oauth-service-config-patch.json
- components/spi/overlays/production/stone-prd-m01/spi-shared-configuration-file-config-path.yaml
- components/spi/overlays/production/stone-prd-m01/spi-vault-approle-spi-oauth-config-path.yaml
- components/spi/overlays/production/stone-prd-m01/spi-vault-approle-spi-operator-config-path.yaml
Context https://issues.redhat.com/browse/SVPI-379
> [prd-m01] Setup SPI configuration for prod

- components/spi/overlays/production/stone-prd-rh01/config-patch.json
- components/spi/overlays/production/stone-prd-rh01/oauth-service-config-patch.json
- components/spi/overlays/production/stone-prd-rh01/spi-shared-configuration-file-config-path.yaml
- components/spi/overlays/production/stone-prd-rh01/spi-vault-approle-spi-oauth-config-path.yaml
- components/spi/overlays/production/stone-prd-rh01/spi-vault-approle-spi-operator-config-path.yaml
Context https://issues.redhat.com/browse/SVPI-379
> Setup SPI configuration for prod/rh01

- components/image-controller/base/external-secrets/kustomization.yaml
- components/image-controller/base/external-secrets/quaytoken.yaml
- components/image-controller/production/kustomization.yaml
Adding external secrets for image-controller which were missing in previous commit.
> fix: image controller - add external-secrets

- components/tekton-ci/base/repository.yaml
Add CI for the o11y (observability) repo.
> STONEO11Y-27: Add CI for o11y

- components/pipeline-service/base/external-secrets/tekton-results/kustomization.yaml
- components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
- components/pipeline-service/production/stone-prd-m01/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/tekton-results-database-secret-path.yaml
- components/pipeline-service/production/stone-prd-m01/tekton-results-s3-secret-path.yaml
- components/pipeline-service/production/stone-prd-rh01/kustomization.yaml
- components/pipeline-service/production/stone-prd-rh01/tekton-results-database-secret-path.yaml
- components/pipeline-service/production/stone-prd-rh01/tekton-results-s3-secret-path.yaml
- components/pipeline-service/staging/stone-stg-m01/kustomization.yaml
- components/pipeline-service/staging/stone-stg-m01/tekton-results-s3-secret-path.yaml
- components/pipeline-service/staging/stone-stg-rh01/kustomization.yaml
- components/pipeline-service/staging/stone-stg-rh01/tekton-results-s3-secret-path.yaml
This updates RDS secrets path in prod and add S3 secret paths for both staging and prod
> pipeline-service: Update secrets path for RDS and S3

- components/authentication/base/has.yaml
Need access to HAS controller in staging & prod cluster.
> add yangcao to has yaml

- components/sprayproxy/staging/add-backends.yml
Add the endpoints of the pac instances on the member clusters.
> staging: Configure sprayproxy backends

- components/authentication/base/group-sync/external-secrets/github-redhat-appstudio-sre.yaml
- components/authentication/base/group-sync/external-secrets/github-redhat-appstudio.yaml
- components/build-service/base/external-secrets/pipelines-as-code-secret.yaml
- components/build-templates/base/external-secrets/redhat-appstudio-user-workload.yaml
- components/dora-metrics/base/external-secrets/exporters-secrets.yaml
- components/gitops/base/external-secrets/gitops-service-postgres-rds-config.yaml
- components/has/base/external-secrets/has-github-token.yaml
- components/image-controller/base/external-secrets/quaytoken.yaml
- components/monitoring/logging/base/external-secrets/monitoring-logging-cloudwatch-forwarder.yaml
- components/monitoring/prometheus/base/external-secrets/monitoring-prometheus-oauth-config.yaml
- components/pipeline-service/base/external-secrets/pipelines-as-code/pipelines-as-code-secret.yaml
- components/pipeline-service/base/external-secrets/tekton-results/tekton-results-database.yaml
- components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
- components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
- components/spi/base/external-secrets/spi-shared-configuration-file.yaml
- components/spi/base/external-secrets/spi-vault-approle-spi-oauth.yaml
- components/spi/base/external-secrets/spi-vault-approle-spi-operator.yaml
- components/tekton-ci/base/external-secrets/infra-deployments-pr-creator.yaml
- components/tekton-ci/base/external-secrets/tekton-ci-push-secret.yaml
Sync the external secrets before all the other resources, so they will get created before the resources that use them.
> Sync external secrets first

- components/monitoring/logging/production/kustomization.yaml
- components/monitoring/logging/production/monitoring-logging-cloudwatch-forwarder-path.yaml
This PR provides the authentication for fluentd to forward the logs to cloudwatch for prod stonesoup
> Add fluentd authentication for prod

- hack/preview.sh
This is to fix  updating resources properly  in pipeline-service development mode
> fix issue that update resources of plnsvc development layer

- components/authentication/base/kustomization.yaml
- components/authentication/sandbox-sre-admins.yaml
needed to be able to properly configure proxy
> let sandbox-sre admins impersonate groups and users

- components/authentication/base/kustomization.yaml
- components/authentication/base/sandbox-dev.yaml
Need ability to test and debug SpaceRequest CRs in my own namespace
> enable fmuntean to manage spacerequest in own namespace

- components/dev-sso/keycloak-realm.yaml
Add a whole keycloak realm setup to be able to properly set the client's default and optional scopes.
> Add whole keycloak realm setup.

- hack/preview.sh
This PR is to make sure Vault initialization is executed by checking if spi-in-cluster-local exists. 
**Issue Description:**
When Application `all-application-sets` is ["Healthy Synced"](https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh#L201-L204),  it doesn't mean all of Applications are created. So [`echo $APPS | grep -q spi`](https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh#L208) often return false. It will cause Vault initialization is skipped and spi applicatins cannot be installed succesffuly. This is the bug [SVPI-415](https://issues.redhat.com/browse/SVPI-415)
> Added one loop to make sure application spi-in-cluster-local is created 

- hack/build/setup-pac-integration.sh
It works with base64 encoded private key with or without -w0.
> Quote variable PAC_GITHUB_APP_PRIVATE_KEY

- components/quality-dashboard/staging/external-secrets/kustomization.yaml
- components/quality-dashboard/staging/external-secrets/quality-dashboard-auth.yaml
- hack/secret-creator/create-quality-dashboard-secrets.sh
- Creates the Secret while bootstrap 
- Fetches the Secret from vault via external secrets 
> fix: quality dashboard auth secret on stage

- components/quality-dashboard/base/frontend/kustomization.yaml
> fix: backendroute in the config map

- components/authentication/base/gitops.yaml
Adding `jannfis` as a maintainer for GitOps service.
> Add jannfis as maintainer for GitOps

- components/spi/overlays/development/config-patch.json
- components/spi/overlays/production/stone-prd-m01/config-patch.json
- components/spi/overlays/production/stone-prd-rh01/config-patch.json
- components/spi/overlays/staging/stone-stg-m01/config-patch.json
- components/spi/overlays/staging/stone-stg-rh01/config-patch.json
https://issues.redhat.com/browse/SVPI-367
> add spi instance id config

- components/image-controller/README.md
Describe secrets and rotation policy in README.md for image-controller
> STONEBLD-937: image-controller secrets description

- argo-cd-apps/overlays/development/delete-applications.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- components/o11y/development/kustomization.yaml
create dev overlay for o11y so that Prometheus rules will be deployed in dev and ci.
> chore(STONEO11Y-86): create dev overlay for o11y

- argo-cd-apps/overlays/staging/kustomization.yaml
The migration to the control plane was completed.
> chore(RHTAP-687): Enable autosync on staging

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
Update pipeline-service to include Tekton Results change enabling gRPC access logging.
> Bump pipeline-service version

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#1592
> Revert "Bump pipeline-service version"

- components/spi/overlays/production/base/kustomization.yaml
- components/spi/overlays/production/base/spi-aws-credentials-external-secret.yaml
- components/spi/overlays/production/stone-prd-m01/kustomization.yaml
- components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
- components/spi/overlays/production/stone-prd-rh01/kustomization.yaml
- components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml
https://issues.redhat.com/browse/SVPI-432
prepare external secrets
> prepare spi prod with aws secrets manager credentials secrets

- components/gitops/development/kustomization.yaml
- components/gitops/staging/base/kustomization.yaml
Pushing https://github.com/redhat-appstudio/infra-deployments/pull/1595 to staging and dev, first.
> managed-gitops update: staging and dev

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
* Deploy latest tekton-results
* Update some permissions for service accounts
* Use HSTS header for tekton-results api route
> Update pipeline-service component - dev & staging

- components/monitoring/grafana/README.md
- components/monitoring/grafana/base/grafana-app.yaml
- Configure Grafana with OpenShift login for all environments
- Add example dashboard example
> Configure Grafana with OpenShift login

- components/monitoring/grafana/base/grafana-app.yaml
- Inject the token for querying Thanos.
- Disable anonymous auth.
> Add missing Grafana configurations

- components/monitoring/grafana/base/grafana-app.yaml
Use an image reference with a sha.
> Pin Grafana oauth image

- components/gitops/staging/base/kustomization.yaml
Same as https://github.com/redhat-appstudio/infra-deployments/pull/1693, but applied only to staging.
> Managed-gitops: apply PR #1693 latest to staging, only

- components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
- components/sprayproxy/production/kustomization.yaml
- components/sprayproxy/production/pipelines-as-code-secret.yaml
- components/sprayproxy/staging/kustomization.yaml
- components/sprayproxy/staging/pipelines-as-code-secret.yaml
Sprayproxy will use the secret to validate the webhook request.
> Expose GH webhook secret to sprayproxy

- components/authentication/base/inspect-pods.yaml
- components/authentication/base/kustomization.yaml
https://issues.redhat.com/browse/ASC-359
> add inspect pods manifests

- components/gitops/staging/base/kustomization.yaml
Apply https://github.com/redhat-appstudio/infra-deployments/pull/1731 to staging, only
> GitOps Service: staging only, update components/gitops/staging/base/kustomization.yaml

- components/authentication/base/sandbox-sre-admins.yaml
needed to configure SAs with all necessary permission
> all permissions over secrets and SA tokens for sandbox-sre admins

- components/authentication/base/has.yaml
Adds user to HAS auth role binding
> add user to HAS auth role

- components/pipeline-service/production/base/kustomization.yaml
* OSP-1.10
* Allow for watcher logging level customization via gitops
* Using TLS for RDS connections
* Update tekton-results version, configuration and API route
Promotion of staging to production
> Promote pipeline-service

- components/monitoring/grafana/base/has/dashboard.yaml
Corresponding changes to pull in dashboard changes from HAS repo https://github.com/redhat-appstudio/application-service/pull/310
Which issue(s)/story(ies) does this PR fixes:
https://issues.redhat.com/browse/DEVHAS-272
> [DEVHAS-272] Add new HAS rate limiting dashboard

- components/quality-dashboard/base/backend/kustomization.yaml
Related PR: https://github.com/redhat-appstudio/quality-dashboard/pull/70
> AD-82 Update Quality Dashboard backend image

- components/dora-metrics/base/kustomization.yaml
- components/monitoring/prometheus/base/servicemonitors/dora-service.yaml
Update dora metrics Grafana dashboard and Prometheus service monitor resources.
> Update dora metrics dashboard and service monitor

- components/monitoring/logging/staging/configure-logforwarder-patch.yaml
- components/monitoring/logging/staging/kustomization.yaml
- components/monitoring/logging/staging/monitoring-logging-splunk-log-forwarder-external-secret.yaml
Add a new log-forwarder that will forward logs to the internal RH Splunk from the RHTAP Staging environment.
> STONEO11Y-153: Add a ClusterLogForwarder for Splunk for Staging env

- components/dora-metrics/base/kustomization.yaml
- components/monitoring/grafana/base/dora-metrics/kustomization.yaml
- hack/bootstrap-cluster-common.sh
Update to the Dashboard CR that will get reconciled by the Grafana operator.
> Update dora metrics dashboard name to be unique

- components/monitoring/logging/staging/configure-logging/cluster-log-forwarder-patch.yaml
- components/monitoring/logging/staging/configure-logging/kustomization.yaml
- components/monitoring/logging/staging/external-secrets/kustomization.yaml
- components/monitoring/logging/staging/external-secrets/monitoring-logging-splunk-log-forwarder.yaml
- components/monitoring/logging/staging/kustomization.yaml
* Minor fix for a missing ExternalSecret resource.
* Moved resources into folders.
> STONEO11Y-158: Add a ClusterLogForwarder for Splunk for Staging env

- components/gitops/staging/base/kustomization.yaml
Same PR as https://github.com/redhat-appstudio/infra-deployments/pull/1810, but targeted to staging only, for testing purposes.
> GitOps: Staging only version of PR #1810, update components/gitops/staging/base/kustomization.yaml

- components/gitops/staging/base/kustomization.yaml
Same PR as #1816 but only applied to staging.
> GitOps: apply #1816 to staging only,  update components/gitops/staging/base/kustomization.yaml

- components/monitoring/grafana/base/kustomization.yaml
- components/monitoring/grafana/base/o11y/kustomization.yaml
> chore(STONEO11Y-228): Add o11y dashboard

- components/monitoring/grafana/development/auto-assign-role-patch.yaml
- components/monitoring/grafana/development/kustomization.yaml
* Grant Grafana dashborad editor access for development environment
> chore(STONEO11Y-232): Dashborad editor access for development env

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
* Create `pipelines-scc` SecurityContextConstraint via ArgoCD.
* Disable the pipeline service account
* Turn off creation of RBAC resources
* Add job to create the service certificate authority for Chains, which was provided by the OpenShift Pipelines Operator RBAC feature (not documented!)
* Disable image signing test
> Update pipeline-service in development/staging

- components/pipeline-service/production/base/kustomization.yaml
* Disable the pipeline service account
> Update pipeline-service in production

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/development/scale-down-exporter.yaml
- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/base/scale-down-exporter.yaml
- components/pipeline-service/staging/base/kustomization.yaml
- components/pipeline-service/staging/base/scale-down-exporter.yaml
See https://redhat-internal.slack.com/archives/C02FTKEMBU1/p1684350155144749
/assign @adambkaplan 
/assign @Roming22
> PLNSRVCE-1318: scale down pipeline-metrics-exporter until we fix scaling/perf issues

- argo-cd-apps/base/tekton-ci/tekton-ci.yaml
> RHTAP-872: Update name of serviceaccount

- components/authentication/base/has-admin.yaml
> add yangcao77 as has-admin

- components/authentication/base/has-admin.yaml
- components/authentication/base/has.yaml
Requesting access for has-admin as member of the devfiles team.
> Add thepetk as has-admin

- components/authentication/base/has-admin.yaml
- components/authentication/base/has.yaml
Requesting access for has-admin as member of the devfiles team.
> add mike-hoang as has-admin

- components/monitoring/grafana/base/kustomization.yaml
- components/monitoring/grafana/base/release/kustomization.yaml
The release dashboard was not being imported correctly. This PR fixed that problem.
> feat: add release dashboard

- components/authentication/base/spi-vault-admin.yaml
- components/spi/OWNERS
- make SPI component owners up to date.
> Adjust codeowners

- components/monitoring/OWNERS
- components/o11y/OWNERS
Add o11y developers to monitoring and o11y sub-directories OWNERS files
> chore(RHTAPWATCH-275): Add o11y developers to monitoring and o11y OWNERS

- components/monitoring/grafana/base/integration/kustomization.yaml
- components/monitoring/grafana/base/kustomization.yaml
Adding integration service dashboard into appstudio grafana
> feat(STONEINTG-185): add integration service grafana dashboard

- hack/quickcluster/README.md
- hack/quickcluster/setup-nfs-quickcluster.sh
- hack/quickcluster/templates/deployment.yaml
- hack/quickcluster/templates/rbac.yaml
- hack/quickcluster/templates/storageClass.yaml
- hack/quickcluster/templates/test-pvc.yaml
The username for quickcluster provided by resource hub is different than the one we used for quicklabs.
> feat: support quickcluster as we do quicklab

- components/authentication/base/has-admin.yaml
- components/authentication/base/has.yaml
Requesting access for has-admin as a member of the devfiles team.
> Add michael-valdron as has-admin

- components/spi/overlays/production/base/kustomization.yaml
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/592
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/597
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/593
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/590
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/602
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/598
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/605
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/603
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/604
- …
> Promote SPI stage to prod

- components/monitoring/grafana/base/kustomization.yaml
- components/monitoring/grafana/base/pipeline-service/kustomization.yaml
Add a grafana dashboard for Pipeline Service
> Pipeline Service Dashboard

- components/gitops/staging/base/kustomization.yaml
This PR applies #1855 to staging only
> managed-gitops: staging only for #1855, update components/gitops/staging/base/kustomization.yaml

- components/spi/overlays/staging/base/config-patch.json
- components/spi/overlays/staging/base/kustomization.yaml
Enable remote-secret feature for staging
> Enable remote-secret feature for staging

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- components/monitoring/prometheus/development/monitoringstack/kustomization.yaml
- components/monitoring/prometheus/production/monitoringstack/kustomization.yaml
- components/monitoring/prometheus/staging/monitoringstack/kustomization.yaml
- Add ServiceMonitor to federate from UWM Prometheus
- Add patches to dev, staging and prod for adding the `source_environment` label
> chore(RHTAPWATCH-262): Federate from UWM Prometheus 

- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
* Bump metrics exporter through noncaching client change
* Update tekton results
* Increase log buffer size in tekton results
* Update pipeline service exporter image path
> Update Pipeline Service in Staging

- components/build-service/README.md
- hack/build/build-via-appstudio.sh
- hack/build/templates/component.yaml
build-via-appstudio.sh - use image controller registries by default
> Do not create image repository for component in build test script

- components/spi/overlays/production/base/kustomization.yaml
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/618
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/621
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/625
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/626
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/629
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/628
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/627
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/632
> Promote SPI staging to prod

- components/monitoring/grafana/base/pipeline-service/kustomization.yaml
- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
This version bump includes PaC Observational Grafana Dashboard to stage & dev.
> bump pipeline service version

- components/dev-sso/keycloak-realm.yaml
Add `profile_level.name_and_dev_terms` profile to Keycloak.
> Add new profile to Keycloak

- components/dora-metrics/staging/kustomization.yaml
- components/monitoring/grafana/base/dora-metrics/kustomization.yaml
- hack/secret-creator/create-dora-metrics-exporter-secrets.sh
Update DORA metrics image (on staging only) to add initial Pagerduty integration for failure metrics collection
> update dora metrics

- components/sprayproxy/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/sprayproxy/pull/46
- https://github.com/redhat-appstudio/sprayproxy/pull/42
- https://github.com/redhat-appstudio/sprayproxy/pull/47
- https://github.com/redhat-appstudio/sprayproxy/pull/48
- https://github.com/redhat-appstudio/sprayproxy/pull/49
- https://github.com/redhat-appstudio/sprayproxy/pull/30
> Update sprayproxy prod

- components/external-secrets-operator/staging/kustomization.yaml
- components/external-secrets-operator/staging/starting-csv-patch.yaml
Release notes: https://github.com/external-secrets/external-secrets/tags
> chore(RHTAPSRE-45): Upgrade ESO on stage

- components/external-secrets-operator/staging/starting-csv-patch.yaml
Release notes: https://github.com/external-secrets/external-secrets/tags
> chore(RHTAPSRE-45): Upgrade ESO on stage to 0.9.1

- components/gitops/staging/base/kustomization.yaml
Cherry pick https://github.com/redhat-appstudio/infra-deployments/pull/2080/commits to staging, only
> GitOps Service: deploy to staging only, update components/gitops/staging/base/kustomization.yaml

- components/image-controller/base/kustomization.yaml
Updates image controller operator to newer version
> Update image controller operator image

- components/application-api/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/application-api/pull/54
- https://github.com/redhat-appstudio/application-api/pull/57
- https://github.com/redhat-appstudio/application-api/pull/59
(follow-up on [this PR that got closed](https://github.com/redhat-appstudio/infra-deployments/pull/2004))
> application-api update

- components/monitoring/grafana/base/kustomization.yaml
- components/monitoring/grafana/base/o11y/kustomization.yaml
* Remove the reference to o11y directory
* remove o11y subdirectory
> chore(RHTAPWATCH-365): Remove o11y dashboard deployment from infra-deployments

- hack/preview-template.env
Setting Quay organization is required for successful build of component.
> Update instructions regarding setting Quay organization

- components/gitops/staging/base/kustomization.yaml
Cherry pick #2135  to staging only.
> gitops: cherry pick to staging #2135 to staging - update components/gitops/staging/base/kustomization.yaml

- components/gitops/openshift-gitops/overlays/staging/subscription-openshift-gitops.yaml
Jira Link -  https://issues.redhat.com/browse/GITOPSRVCE-660
> Update gitops version

- components/monitoring/grafana/base/grafana-operator.yaml
> replace grafan subscription

- components/monitoring/grafana/base/grafana-operator.yaml
> add syncwave to grafana

- components/gitops/production/base/kustomization.yaml
Bring production container image up-to-date with dev/staging from https://github.com/redhat-appstudio/infra-deployments/pull/2155
> managed-gitops update

- components/monitoring/grafana/base/dashboards/dora-metrics/kustomization.yaml
> Update dora metrics dashboard

- components/enterprise-contract/ecp.yaml
https://issues.redhat.com/browse/HACBS-2400
> Use new namespace for Tekton Chains public key

- components/authentication/base/kustomization.yaml
fixing ArgoCD deployment issue of authentication component.
> fix: gitops has been removed from authentication

- .github/workflows/kube-linter.yaml
- .kubelinter.yaml
https://issues.redhat.com/browse/RHTAPSRE-102
TODO:
> feat: add kube-linter CI check

- components/gitops/openshift-gitops/overlays/production-and-dev/subscription-openshift-gitops.yaml
https://issues.redhat.com/browse/GITOPSRVCE-660
> Update gitops version to 1.9 in prod and dev

- ci/teams/rhtap-servicerelease/release-build.yaml
- components/image-controller/base/kustomization.yaml
- fix sed expression
- correct kustomization.yaml for location
> Update image-controller component

- components/monitoring/grafana/base/dashboards/jvm-build-service/OWNERS
This will remove the need for multiple people to approve JVM Build Servie merge requests
> Add jvm-build-service monitoring owners

- argo-cd-apps/base/cluster-secret-store-rh/cluster-secret-store-rh.yaml
- argo-cd-apps/base/cluster-secret-store-rh/kustomization.yaml
- argo-cd-apps/overlays/production/kustomization.yaml
- components/cluster-secret-store-rh/base/appsre-stonesoup-vault-rh-secret-store.yaml
- components/cluster-secret-store-rh/base/kustomization.yaml
- components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
- components/cluster-secret-store-rh/production/approle-id-patch.yaml
- components/cluster-secret-store-rh/production/kustomization.yaml
The new stores will be used for fetching secrets to the RH clusters.
>  RHTAP-1201: Add RH cluster secrets stores

- components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
The enging that contains the S3 secrets is of type v1.
> FRHTAP-1201: RH - Fix secret store version

- hack/hac/installHac.sh
should fix issues with bonfire deploy and make the process a bit faster
> hac-e2e: update to bonfire 4.18

- hack/build/setup-pac-integration.sh
1. fixed an error that it should `exit 1` when fail
2.  increase the number of retries to wait until pac is ready
> fixed an issue in  setup pac script

- components/enterprise-contract/ecp.yaml
https://issues.redhat.com/browse/HACBS-2556
> Use new location for EC policy data references

- components/sprayproxy/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/sprayproxy/pull/57
- https://github.com/redhat-appstudio/sprayproxy/pull/58
> Update sprayproxy production

- components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Add tekton results roles for Pipeline Service group
> Add tekton-results roles

- components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
- components/spi-vault/kustomization.yaml
- components/spi/overlays/development/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/707
> service-provider-integration-operator update with e2e fix

- components/authentication/base/group-sync/group-sync.yaml
- components/build-service/OWNERS
- components/build-service/base/rbac/build-maintainer.yaml
- components/image-controller/base/OWNERS
- components/integration/integration.yaml
- components/internal-services/internal-services.yaml
- components/jvm-build-service/OWNERS
- components/jvm-build-service/base/rbac/jvm-build-maintainer.yaml
- components/release/release-team.yaml
- components/spi/base/rbac/spi.yaml
- components/sprayproxy/OWNERS
- components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
Removing myself from reviewers and RBAC
> Michkov - Bye, Bye

- components/dora-metrics/base/kustomization.yaml
- components/dora-metrics/staging/kustomization.yaml
> Update dora-metrics 

- components/tekton-ci/production/kustomization.yaml
- components/tekton-ci/production/plnsvc-codecov-secret.yaml
This secret is used to report code coverage on pipeline service repositories
> Add plnsvc-codecov secret

- components/build-service/base/rbac/build-maintainer.yaml
[STONEBLD-1611](https://issues.redhat.com//browse/STONEBLD-1611)
Build team members are added to allow list and view ServiceAccount and list secrets across namespaces.
> Allow build team to list and view SA and list secrets

- components/gitops/staging/base/kustomization.yaml
Cherry pick only the staging commit for https://github.com/redhat-appstudio/infra-deployments/pull/2401
> managed-gitops update: Cherry pick #2401 to staging only: update components/gitops/staging/base/kustomization.yaml

- components/authentication/base/rhtap-admins.yaml
See https://issues.redhat.com/browse/HACBS-2658 for motivation
> HACBS-2658: allow rhtap-admins to create rolebindings

- components/multi-arch-controller/OWNERS
- components/multi-arch-controller/base/host-config.yaml
The multi-arch-controller is being renamed to the
multi-platform-controller. This config update will work for both the pre and post change versions.
> Update multi platform config

- components/enterprise-contract/ecp.yaml
https://issues.redhat.com/browse/HACBS-2657
> Add new redhat-no-hermetic ECP

- components/authentication/base/everyone-can-view.yaml
This will allow developers to get the OpenShift version.
> Grant read access of clusterversions to all developers

- configs/enable-dvo-for-all-cluster/install-dvo.yaml
Restoring the namespace change to solve degraded state
> Fix subscription namaspace

- components/dora-metrics/base/kustomization.yaml
> Update dora-metrics image

- components/application-api/kustomization.yaml
For some reason the update PR did not get automatically created: https://github.com/redhat-appstudio/application-api/runs/17428616924
Manually updating
> Update application-api to 8b646f622222d641fe4b05e7d62845037a88cada

- components/pipeline-service/production/base/kustomization.yaml
Includes
- [add row/panel for scheduling alert](https://github.com/openshift-pipelines/pipeline-service/commit/09fc703d49b54fcceaa8995671e47e3b9e737dc9)
- [Update operator docs](https://github.com/openshift-pipelines/pipeline-service/commit/3f12d087b6a9b5f6a1cb6145a35dc10c8b999977)
- [Update binaries](https://github.com/openshift-pipelines/pipeline-service/commit/8d625b6c4509efab5c983d9393424578b8c7052a)
- [Remove update-pipeline-service image](https://github.com/openshift-pipelines/pipeline-service/commit/bd28b4d5c158117d8f53b9d4d975f6f0d144fe00)
- [Update dev docs](https://github.com/openshift-pipelines/pipeline-service/commit/441cdd83fa489322e4b4f1ad446cfb828b7ec285)
- [Fix issue with the grafana-dashboard task](https://github.com/openshift-pipelines/pipeline-service/commit/6cefd83c9a7c …
> bump pipeline-service prod to same level as stage

- components/gitops/staging/base/kustomization.yaml
Deploy #2529 to staging only, to verify functionality.
> managed-gitops: cherrypick #2529 to staging update components/gitops/staging/base/kustomization.yaml

- components/gitops/staging/base/kustomization.yaml
https://issues.redhat.com/browse/GITOPSRVCE-771
> managed-gitops update: Enable Environment webhook on staging only

- components/pipeline-service/production/base/kustomization.yaml
- https://github.com/openshift-pipelines/pipeline-service/pull/819
> [PROD] Update pipeline-service

- components/gitops/staging/base/kustomization.yaml
Cherry pick the staging commit from https://github.com/redhat-appstudio/infra-deployments/pull/2557 to staging only.
> managed-gitops update: cherry pick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml

- components/gitops/staging/base/kustomization.yaml
> managed-gitops: cherry pick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml

- components/gitops/staging/base/kustomization.yaml
This reverts commit e7fae4c8e832e70fbbba01cad185dbcabb03bfd8.
> Revert push to staging on #2574 "update components/gitops/staging/base/kustomization.yaml (#2574)"

- components/authentication/base/everyone-can-view.yaml
- components/authentication/base/rhtap-admins.yaml
- components/release/kustomization.yaml
- components/release/release-service-configurator-role.yaml
- components/release/release-team.yaml
- allow rhtap-admin to view/edit releaseserviceconfigs
- allow release team to view/edit releaseserviceconfigs
> chore(RHTAPREL-647): releaseserviceconfig rbac

- argo-cd-apps/overlays/production/kustomization.yaml
> chore(RHTAPREL-645): fix production overlay

- components/remote-secret-controller/overlays/production/base/kustomization.yaml
- components/spi/overlays/production/base/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/remote-secret/pull/180
- https://github.com/redhat-appstudio/remote-secret/pull/170
- https://github.com/redhat-appstudio/remote-secret/pull/174
- https://github.com/redhat-appstudio/remote-secret/pull/177
- https://github.com/redhat-appstudio/remote-secret/pull/175
- https://github.com/redhat-appstudio/remote-secret/pull/176
- https://github.com/redhat-appstudio/remote-secret/pull/172
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/737
- https://github.com/redhat-appstudio/service-provider-integration-operator/commit/180c529092af8715e417521b203ca98faf6168b0
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/736
- https://github.com/redhat-appstudio/service-provider-integratio …
> Promote SPI/RemoteSecret from staging to prod

- components/gitops/staging/base/kustomization.yaml
> managed-gitops: cherrypick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml

- components/release/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/release-service/pull/280
- https://github.com/redhat-appstudio/release-service/pull/276
- https://github.com/redhat-appstudio/release-service/pull/278
> Promote release-service from staging to production

- components/release/staging/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/release-service/pull/284
- https://github.com/redhat-appstudio/release-service/pull/281
> Promote release-service from development to staging

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
first panel monitoring latency of release creation second panel violations of 90% < 10s SLO
> feat(STONEINTG-533): Latency release creation slo panels

- components/sandbox/base/kustomization.yaml
- components/sandbox/base/monitoring/sandbox-registration-service-proxy.yaml
changes wrt https://issues.redhat.com/browse/ASC-248
> add serviceMonitor for proxy metrics

- components/gitops/staging/base/kustomization.yaml
Cherry pick #2620 to deploy to staging, only
> managed-gitops: Cherry pick #2620 to staging, update components/gitops/staging/base/kustomization.yaml

- argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
- argo-cd-apps/base/member/infra-deployments/toolchain-member-operator/toolchain-member-operator.yaml
so the obsolete manifests are removed
> sandbox: enable prune during sync

- argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/86160
> add support for stg-rh01 cluster

- argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
Reverts redhat-appstudio/infra-deployments#2656
> Revert "add support for stg-rh01 cluster"

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
SEB created to ready time series
SEB created to ready violations 90% in 120 seconds
> feat(STONEINTG-536): add 2 panels for SLO 6

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
SEB Ephemeral Deployments Total panel
> feat(STONEINTG-535): adding one SLI panel

- components/gitops/staging/base/kustomization.yaml
> managed-gitops: Cherry pick #2653 to staging, update components/gitops/staging/base/kustomization.yaml

- components/release/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/release-service/pull/285
- https://github.com/redhat-appstudio/release-service/pull/294
- https://github.com/redhat-appstudio/release-service/pull/291
> Promote release-service from development to production

- components/monitoring/grafana/base/dashboards/spi/dashboard.yaml
- components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Add Grafana dashboard for important remote secret metrics for RHTAP
> Add Grafana dashboard for remote secret metrics

- components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Fix RemoteSecret Grafana dashboard datasources variable
> Fix RemoteSecret Grafana dashboard datasources variable

- components/release/production/kustomization.yaml
- components/release/staging/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/release-service/pull/295
- https://github.com/redhat-appstudio/release-service/pull/297
> Promote release-service from development to production and staging

- components/gitops/staging/base/kustomization.yaml
Cherry pick the staging commit of https://github.com/redhat-appstudio/infra-deployments/pull/2686
> managed-gitops: cherry pick #2686 to staging, update components/gitops/staging/base/kustomization.yaml

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Update to the latest grafana dahsboard
> chore(integration-svc): update grafana dashboard

- components/integration/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/integration-service/pull/426
- https://github.com/redhat-appstudio/integration-service/pull/435
> Promote integration-service from staging to production

- components/build-service/base/rbac/build-admin.yaml
- components/build-service/base/rbac/build-maintainer.yaml
- components/image-controller/base/kustomization.yaml
- components/image-controller/base/rbac/image-controller-admin.yaml
- components/image-controller/base/rbac/image-controller-maintainer.yaml
- components/image-controller/base/rbac/kustomization.yaml
Requested permissions allow Build Team better troubleshoot issues with maintained services.
> Update Build team permissions

- components/authentication/base/everyone-can-view.yaml
Grant view access to RHTAP developers.
> Add internalrequests to view-appstudio

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Update to the latests integration-service grafana dashboard
> chore(integration): update to the latest grafana dashboard

- components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
- components/integration/base/external-secrets/pipelines-as-code-secret.yaml
> feat(STONEINTG-608): add integration ns to vault

- components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Improved and added graphs to RHTAP performance dashboard
> feat: More graphs

- hack/hac/installHac.sh
fixing https://issues.redhat.com/browse/RHTAPBUGS-1030
> update hac-proxy for hac-e2e

- components/tekton-ci/base/repository.yaml
Remove integration-service from tekton-ci
> feat(STONEINTG-696): remove integration from tekton-ci

- components/backup/staging/stone-stg-host/dpa-bucket-patch.yaml
- components/backup/staging/stone-stg-host/dpa-kmskeyid-patch.yaml
- components/backup/staging/stone-stg-host/kustomization.yaml
This change install oadp operator only, a follow up change will be done to create a backup schedule once backup has been manually tested.
> Install OADP operator on stone-stg-host cluster

- components/backup/production/stone-prd-m01/dpa-bucket-patch.yaml
- components/backup/production/stone-prd-m01/dpa-kmskeyid-patch.yaml
- components/backup/production/stone-prd-m01/kustomization.yaml
- components/backup/production/stone-prd-rh01/dpa-bucket-patch.yaml
- components/backup/production/stone-prd-rh01/dpa-kmskeyid-patch.yaml
- components/backup/production/stone-prd-rh01/kustomization.yaml
This change will install oadp and configure it to backup appstudio resources in tenant's namespaces.
> Deploy backup component on prd member clusters

- components/backup/base/host/backup-toolchain-host-schedule.yaml
- components/backup/base/host/kustomization.yaml
- components/backup/base/member/backup-toolchain-member-schedule.yaml
- components/backup/base/member/kustomization.yaml
Add a backup schedule for the toolchain operators, both host and member.
[RHTAPSRE-285](https://issues.redhat.com//browse/RHTAPSRE-285)
> Backup user registration information

- components/backup/production/stone-prd-host1/dpa-bucket-patch.yaml
- components/backup/production/stone-prd-host1/dpa-kmskeyid-patch.yaml
- components/backup/production/stone-prd-host1/kustomization.yaml
> Deploy oadp to production host cluster

- argo-cd-apps/app-of-app-sets/staging-downstream/change-source-path.yaml
- argo-cd-apps/app-of-app-sets/staging-downstream/change-target-namespace.yaml
- argo-cd-apps/app-of-app-sets/staging-downstream/kustomization.yaml
- argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
- argo-cd-apps/base/member/infra-deployments/gitops/gitops.yaml
- argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
- argo-cd-apps/base/member/infra-deployments/remote-secret-controller/remote-secret-controller.yaml
- argo-cd-apps/base/member/infra-deployments/spi/spi.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/kustomization.yaml
- components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
- components/gitops/staging/stone-stage-p01/kustomization.yaml
- components/monitoring/prometheus/staging/stone-stage-p01/cluster-id-label.yaml
- components/monitoring/prometheus/staging/stone-stage-p01/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stage-p01/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
- components/remote-secret-controller/overlays/staging/stone-stg-p01/aws-credentials-path-patch.yaml
- components/remote-secret-controller/overlays/staging/stone-stg-p01/config-patch.json
- components/remote-secret-controller/overlays/staging/stone-stg-p01/kustomization.yaml
- components/spi/overlays/staging/stone-stage-p01/config-patch.json
- components/spi/overlays/staging/stone-stage-p01/kustomization.yaml
- components/spi/overlays/staging/stone-stage-p01/oauth-service-config-patch.json
- components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
- components/spi/overlays/staging/stone-stage-p01/spi-shared-configuration-file-config-path.yaml
Add the required manifests for deploying a downstream version of appstudio.
> RHTAPSRE-279: Manifests for downstream deployment

- .tekton/pipeline/rhtap-staging-e2e.yaml
- .tekton/rhtap-staging-e2e-ci.yaml
- .tekton/tasks/check-pr-label.yaml
- .tekton/tasks/check-pr-rebase-label.yaml
- .tekton/tasks/component-app-name.yaml
- .tekton/tasks/get-git-token.yaml
- .tekton/tasks/get-pr-modified-files.yaml
- .tekton/tasks/merge-pr.yaml
- .tekton/tasks/rebase-pr.yaml
- .tekton/tasks/remove-pr-label.yaml
- .tekton/tasks/replace-revision.yaml
- .tekton/tasks/revert-replace-revision.yaml
- .tekton/tasks/verify-smoke-e2e.yaml
RHTAP staging pipeline failed to get triggered due to mismatch namespace
> Fix mismatch namespace error

- argo-cd-apps/base/smee-client/kustomization.yaml
- argo-cd-apps/base/smee-client/smee-client.yaml
- argo-cd-apps/overlays/staging-downstream/kustomization.yaml
- components/smee-client/deployment.yaml
- components/smee-client/kustomization.yaml
Install Gosmee in client mode on the DS staging cluster.
> feat(RHTAPWATCH-760): Smee client on DS cluster

- components/backup/base/all-clusters/kustomization.yaml
- components/backup/base/host/kustomization.yaml
- components/backup/base/member/kustomization.yaml
- components/backup/staging/stone-stg-m01/dpa-bucket-patch.yaml
- components/backup/staging/stone-stg-m01/dpa-kmskeyid-patch.yaml
- components/backup/staging/stone-stg-m01/kustomization.yaml
This is the last cluster to deploy backup component to so now that they all have it, include oadp in all-clusters kustomize file.
> Deploy backup component to stone-stg-m01

- components/smee-client/OWNERS
- components/smee-client/README.md
Adding some files that were mistakenly omitted from #2958
> chore(RHTAPWATCH-670): smee-client: OWNERS&README

- components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
- components/remote-secret-controller/overlays/staging/stone-stg-p01/aws-credentials-path-patch.yaml
- components/remote-secret-controller/overlays/staging/stone-stg-p01/config-patch.json
- components/spi/overlays/staging/stone-stage-p01/config-patch.json
- components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
Update secrets paths and SPI ids fpr the downstream cluster.
> RHTAPSRE-279: Update secrets paths and SPI ids

- argo-cd-apps/base/member/infra-deployments/remote-secret-controller/remote-secret-controller.yaml
- argo-cd-apps/base/member/infra-deployments/spi/spi.yaml
> RHTAPSRE-279: Fix the downstream cluster name for spi

- argo-cd-apps/base/ui/kustomization.yaml
- argo-cd-apps/base/ui/ui.yaml
- argo-cd-apps/overlays/staging-downstream/kustomization.yaml
- components/ui/README.md
- components/ui/base/chrome/chrome-frontend.yaml
- components/ui/base/chrome/kustomization.yaml
- components/ui/base/hac/hac-core-frontend.yaml
- components/ui/base/hac/hac-dev.yaml
- components/ui/base/hac/kustomization.yaml
- components/ui/base/kustomization.yaml
- components/ui/base/ns.yaml
- components/ui/base/proxy/kustomization.yaml
- components/ui/base/proxy/nginx.conf
- components/ui/base/proxy/proxy.yaml
- components/ui/staging/fed-modules.json
- components/ui/staging/kustomization.yaml
- components/ui/staging/set-hostname.yaml
- docs/_data/navigation.yml
Add a deployment of the UI to the internal cluster.
> RHTAPSRE-281: UI Deployment

- components/sandbox/base/rbac/sandbox-sre-admins.yaml
https://issues.redhat.com/browse/ASC-445
> add mfrancisc as sandbox sre admin

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
> Update pipeline-service in prd

- components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
- Include changes from https://github.com/redhat-appstudio/remote-secret/pull/312
> Used latest RemoteSecret's grafana dashboard

- components/authentication/base/admin-checker/cronjob.yaml
> Reduce admin-checker cron frequency to once a week

- components/monitoring/grafana/base/kustomization.yaml
Updated commit sha in infra-deployments related
to o11y exporters monitoring.
> chore: Update commit sha based on o11y pr

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
> Upgrade pipeline-service

- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
Update the url of the UI for the internal cluster.
> RHTAPSRE-252: UI url for the internal cluster

- OWNERS
[RHTAPSRE-303](https://issues.redhat.com//browse/RHTAPSRE-303)
> Remove gorkem from OWNERS file

- components/sandbox/base/rbac/sandbox-sre-admins.yaml
- components/sandbox/toolchain-host-operator/base/kustomization.yaml
- components/sandbox/toolchain-host-operator/base/rbac/sandbox-sre-admins.yaml
- components/sandbox/toolchain-member-operator/base/rbac/sandbox-sre-admins.yaml
Trying to apply latest user roles from sandbox-sre, but I'm getting this error:
```
Ensuring  'clusterrole-edit-sandbox-sre-cd-host' in namespace toolchain-host-operator (*v1.RoleBinding)
Error: unable to create resource of kind: , version: : unable to update the resource '&RoleBinding{ObjectMeta:{clusterrole-edit-sandbox-sre-cd-host  toolchain-host-operator   137006639 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[operator:host provider:sandbox-sre] map[toolchain.dev.openshift.com/last-applied-configuration:{"metadata":{"name":"clusterrole-edit-sandbox-sre-cd-host","namespace":"toolchain-host-operator","creationTimestamp":null,"labels":{"operator":"host","provider":"sandbox-sre"}},"subjects":[{"kind":"ServiceAccount","name":"sandbox-sre-cd","namespace":"sandbox-sre-host"}],"roleRef":{"a …
```
> grant admin permissions in sandbox namespaces

- components/monitoring/grafana/base/dashboards/image-controller/OWNERS
- components/monitoring/grafana/base/dashboards/image-controller/dashboard.yaml
- components/monitoring/grafana/base/dashboards/image-controller/kustomization.yaml
[STONEBLD-1775](https://issues.redhat.com//browse/STONEBLD-1775)
> Add grafana dashboards for image-controller, image repository provision

- components/sprayproxy/production/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/sprayproxy/pull/62
- https://github.com/redhat-appstudio/sprayproxy/pull/64
> Bump sprayproxy version prod

- components/remote-secret-controller/OWNERS
- components/spi/OWNERS
> RemoteSecret && SPI CODEOWNERS refinement

- .tekton/rhtap-staging-e2e-ci.yaml
Fix git clone failure on promotion pipeline
```
--add safe.directory /workspace/output
+ /ko-app/git-init '-url=https://github.com/redhat-appstudio/infra-deployments' '-revision=27c63b9930a5b3652813d181e750526157d5c2b2' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=3' '-sparseCheckoutDirectories='
{"level":"error","ts":1705300404.054263,"caller":"git/git.go:53","msg":"Error running git [init /workspace/output/]: exit status 1\n/workspace/output/.git: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:88\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\trun …
```
> Fix the git clone failure

- components/image-controller/production/kustomization.yaml
image-controller production update
> Promoting component image-controller from stage to prod

- OWNERS
- components/authentication/base/group-sync/group-sync.yaml
- components/has/base/rbac/has.yaml
- components/image-controller/base/OWNERS
- components/multi-platform-controller/OWNERS
- components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
> Offboarding of Shoubhik Bose

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Pulls in the staging changes from https://github.com/redhat-appstudio/infra-deployments/pull/3050 which included
- https://github.com/openshift-pipelines/pipeline-service/pull/903
- https://github.com/openshift-pipelines/pipeline-service/pull/907
> bump prod to staging level

- components/monitoring/grafana/base/dashboards/core/dashboard.yaml
- components/monitoring/grafana/base/dashboards/core/kustomization.yaml
- components/monitoring/grafana/base/dashboards/core/sandbox-proxy-metrics.json
- components/monitoring/grafana/base/dashboards/kustomization.yaml
https://issues.redhat.com/browse/ASC-269
> add sandbox proxy metrics grafana dashboard

- components/pipeline-service/staging/base/update-tekton-config-pac.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> Update PaC name in staging with Konflux

- .tekton/build-service-prod-overlay-update.yaml
- .tekton/image-controller-prod-overlay-update.yaml
Pipelines were not getting triggered with below error
`{"level":"info","ts":"2024-01-22T14:37:21.106Z","logger":"pipelinesascode","caller":"resolve/resolve.go:126","msg":"Skipping document not looking like a kubernetes resources: yaml: line 9: did not find expected key","provider":"github","event-id":"be317ca2-b933-11ee-91ea-acd77389233c","event-sha":"0f8038a5a49956caba85d6d5623d8faef882c3c3","event-type":"push","namespace":"rhtap-promotion-staging"}`
Will address: https://issues.redhat.com/browse/STONEBLD-2104
> fix: Fix the indentation in pipelineruns

- components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
This PR addresses story: https://issues.redhat.com/browse/STONEBLD-2010
> STONEBLD-2010: Added build-team as maintainer tekton-ci component

- components/enterprise-contract/ecp.yaml
Ref: https://issues.redhat.com/browse/EC-358
> Add ECP for verifying Tasks

- components/pipeline-service/production/base/update-tekton-config-pac.yaml
> Rename PaC in prd

- components/monitoring/README.md
- components/monitoring/grafana/base/dashboards/core/sandbox-proxy-metrics.json
Fix proxy metrics dashboard datasource
> fix: remove datasource to fallback on default one, fix example link

- components/sandbox/toolchain-host-operator/staging/toolchainconfig.yaml
as part of https://issues.redhat.com/browse/ASC-456
> move toolchainconfig from sandbox-sre

- components/pipeline-service/production/base/kustomization.yaml
Included PRs:
- https://github.com/openshift-pipelines/pipeline-service/pull/912
- https://github.com/openshift-pipelines/pipeline-service/pull/908
- https://github.com/openshift-pipelines/pipeline-service/pull/914
- https://github.com/openshift-pipelines/pipeline-service/pull/918
- https://github.com/openshift-pipelines/pipeline-service/pull/913
- https://github.com/openshift-pipelines/pipeline-service/pull/919
- https://github.com/openshift-pipelines/pipeline-service/pull/920
> Bump pipeline-service prod to version in staging

- components/sandbox/toolchain-host-operator/staging/kustomization.yaml
- components/sandbox/toolchain-host-operator/staging/space-provisioner-configs.yaml
Move new Space Provisioner config from https://github.com/codeready-toolchain/sandbox-sre/pull/1510/files#diff-9d80754556a41fb647b3e77160270174e174c563cbc17333330ddf299e33f5ac
> sandbox(stage): add stage space provisioner configs

- components/sandbox/OWNERS
Jira: https://issues.redhat.com/browse/ASC-463
> add rhtap core owners for sandbox component

- components/pipeline-service/development/update-tekton-config-performance.yaml
- components/pipeline-service/staging/base/update-tekton-config-performance.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> PLNSRVCE-1526: bump tekton operator proxy webhook to 2 replicas

- components/pipeline-service/development/bump-results-watcher-replicas.yaml
- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
- components/pipeline-service/staging/base/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> PLNSRVCE-1526: bump results watcher to 2 replicas in dev/staging

- hack/preview.sh
Original code has been replacing everything into defult, but we have more configs paths than just default
> fix(hack): integration service has multiple config refs

- hack/generate-deploy-config.sh
> Add utility to generate deploy.yaml

- components/sprayproxy/production/kustomization.yaml
fixes https://issues.redhat.com/browse/PLNSRVCE-1602
Promote https://github.com/redhat-appstudio/infra-deployments/pull/3224 to production
> promote update of spraproxy repo form staging to production

- OWNERS
This allows lcarva to approve execution of EC updates.
> Add lcarva to root OWNERS

- components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Change targeting a single cluster (stone-stg-rh01). Included PRs:
- https://github.com/openshift-pipelines/pipeline-service/pull/954
> pipeline-service update manual

- components/release/base/kustomization.yaml
- components/release/base/release-service-config-rbac.yaml
Update the release-pipeline-resource-role to also grant permissions for reading ReleaseServiceConfigs.
> feat(RHTAPREL-815): add ReleaseServiceConfig RBAC

- components/integration/production/base/kustomization.yaml
Promote snapshots garbage collection to production
> chore(RHTAPWATCH-838): promote snapshot gc to prod

- components/remote-secret-controller/OWNERS
- components/spi/OWNERS
> mmulholla offboarding

- components/integration/development/kustomization.yaml
- components/integration/staging/base/kustomization.yaml
This is a manual bump of integration service due broken automation.
> Update integration-service version

- components/pipeline-service/staging/base/update-results-watcher-performance.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> remove duplicate results watcher threadiness in stage

- components/ui/staging/kustomization.yaml
For https://issues.redhat.com/browse/HAC-5493
> Bump UI in the internal cluster

- components/tekton-ci/base/external-secrets/kustomization.yaml
- components/tekton-ci/base/external-secrets/registry-redhat-io-pull-secret.yaml
- components/tekton-ci/base/serviceaccount.yaml
[STONEBLD-1832](https://issues.redhat.com//browse/STONEBLD-1832)
> Link registry.redhat.io pullsecret to SA under tekton-ci

- components/integration/production/stone-prod-p01/kustomization.yaml
- components/integration/production/stone-prod-p01/pipelines-as-code-secret-path.yaml
- components/integration/staging/stone-stage-p01/kustomization.yaml
- components/integration/staging/stone-stage-p01/pipelines-as-code-secret-path.yaml
Add external secret of GH app for  stage and production deployments
for more information [STONEINTG-818](https://issues.redhat.com/browse/STONEINTG-818)
> fix(stoneinteg-818): Add external secrets of GH app for stage/prod

- components/tekton-ci/base/repository.yaml
https://issues.redhat.com/browse/KONFLUX-2244
> chore: re-add quality-dashboard Repository CR

- components/sprayproxy/staging/kustomization.yaml
- Migrate the sprayproxy images to quay.io/konflux-ci/sprayproxy on  stagging
> PLNSRVCE-1674: Migrate SprayProxy images to quay.io/konflux-ci on stagging

- components/build-service/base/build-pipeline-selectors/OWNERS
- components/integration/OWNERS
Update owners and reviewwers of the integration-service accordingly to current state
> fix: update integration owners

- argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
- argo-cd-apps/overlays/konflux-public-staging/migration.patch.yaml
This pull request will enable auto sync option for the Konflux Public Staging ArgoCD Instance running on `appsres05ue1`
> RHTAPSRE-429: enable auto sync for Konflux Public Staging ArgoCD

- components/enterprise-contract/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#3419
> Revert "enterprise contract update"

- components/sandbox/user-management/production/README.adoc
- components/sandbox/user-management/production/kubesaw-admins.yaml
- components/sandbox/user-management/staging/README.adoc
- components/sandbox/user-management/staging/kubesaw-admins.yaml
based on the latest changes, rename `sandbox-cli` to `ksctl`, `sandbox-config.yaml` to `kubesaw-admins.yaml`, and update the readmes.
> rename sandbox-cli to ksctl

- components/tekton-ci/base/serviceaccount.yaml
This reverts commit 91e79f1a6a41684d86eac9c376a23a510a92e43d.
> Revert "add quay-push-secret-konflux-ci to ci serviceaccount"

- components/image-controller/production/kustomization.yaml
Promote image-controller component from stage to production (last update was 17 Jan, so it's time :)
> Promote image-controller component from stage to prod

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
Important updates:
- Switch to OSP nightly builds
Included PRs:
- https://github.com/openshift-pipelines/pipeline-service/pull/956
- https://github.com/openshift-pipelines/pipeline-service/pull/972
- https://github.com/openshift-pipelines/pipeline-service/pull/962
- https://github.com/openshift-pipelines/pipeline-service/pull/978
- https://github.com/openshift-pipelines/pipeline-service/pull/980
> pipeline-service update prod

- argo-cd-apps/base/member/infra-deployments/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/project-controller/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/project-controller/project-controller.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- components/project-controller/OWNERS
- components/project-controller/README.md
- components/project-controller/base/allow-argocd-to-manage.yaml
- components/project-controller/base/argocd-permissions.yaml
- components/project-controller/base/kustomization.yaml
- components/project-controller/base/project-controller.yaml
- components/project-controller/development/kustomization.yaml
- components/project-controller/production/kustomization.yaml
- components/project-controller/staging/kustomization.yaml
Initial setup for project controller in
infra-deployments
> chore(RHTAPWATCH-819): Add project controller

- components/tekton-ci/base/repository.yaml
This is the first step towards building in Konflux proper.
> Remove JVM Build Service Builder Images Repo

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
Update the production files to include project-controller deployment in production.
> chore: project-controller deployment in production

- components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Will help to reduce the load from the migration team to approve users.
> Enable auto-approval for internal production

- components/sandbox/user-management/production/README.adoc
- components/sandbox/user-management/staging/README.adoc
based on changes in https://github.com/kubesaw/ksctl/pull/29
> update kubesaw READMEs with changes in ksctl

- components/monitoring/grafana/base/dashboards/release/kustomization.yaml
- components/release/development/kustomization.yaml
- components/release/production/kustomization.yaml
Urgent fix to try to resolve crashlooping container.
> release-service update
