redhat-appstudio/infra-deployments

- argo-cd-apps/base/member/infra-deployments/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/spacerequest-cleaner/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/spacerequest-cleaner/spacerequest-cleaner.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- components/spacerequest-cleaner/OWNERS
- components/spacerequest-cleaner/base/cronjob.yaml
- components/spacerequest-cleaner/base/kustomization.yaml
- components/spacerequest-cleaner/base/namespace.yaml
- components/spacerequest-cleaner/base/rbac.yaml
- components/spacerequest-cleaner/development/kustomization.yaml
- components/spacerequest-cleaner/production/kustomization.yaml
- components/spacerequest-cleaner/staging/kustomization.yaml
Add app to contain a cronjob that will periodically run process for cleaning spacerequests
> chore(RHTAPWATCH-766): add spacerequest cleaner app

- hack/preview.sh
https://issues.redhat.com/browse/KFLUXBUGS-19
> fix: setup pac integration after the tekton crds are ready

- components/monitoring/grafana/development/kustomization.yaml
- components/monitoring/grafana/staging/kustomization.yaml
Updated o11y grafana commit sha in development and staging
> chore(RHTAPWATCH-891): Update o11y commit sha

- components/monitoring/grafana/production/kustomization.yaml
Updated commit sha for o11y grafana production
> chore(RHTAPWATCH-891): Update o11y prod commit sha

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Check label is missing when writing to RHOBS so
adding it in the LabelKeep
> chore(RHTAPWATCH-891): Add check label to grafana

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
> feat(STONEINTG-872): update ref for integration service health dashboard

- components/release/base/cronjobs/remove-expired-releases.yaml
fix: adding line break to enable proper release removal
> fix: adding line break to enable proper release removal

- components/ui/production/kustomization.yaml
- components/ui/staging/kustomization.yaml
- based on method prescribed in [KONFLUX-2176](https://issues.redhat.com//browse/KONFLUX-2176)
> chore(KFLUXBUGS-1200): update UI images

- components/ui/production/kustomization.yaml
- based on method prescribed in [KONFLUX-2176](https://issues.redhat.com//browse/KONFLUX-2176)
- tested on stage via #3599
> chore(KFLUXBUGS-1200): update UI images for production

- components/integration/production/stone-prod-p01/console-url-config-patch.json
- prod p01 had a mis-configured URL
> fix(KFLUXBUGS-1200): update console url for integration service

- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
- prod p01 had a mis-configured URL
> fix(KFLUXBUGS-1200): update console url for PaC config

- components/ui/production/kustomization.yaml
Update UI images for internal production cluster
> Bump prod images for UI

- components/build-service/development/kustomization.yaml
- components/build-service/staging/base/kustomization.yaml
Included PRs:
- https://github.com/redhat-appstudio/build-service/pull/278
> Build service update

- components/konflux-ci/base/repository.yaml
- components/tekton-ci/base/repository.yaml
[KONFLUX-2245](https://issues.redhat.com//browse/KONFLUX-2245)
> chore: move ci-helper-app Repo CR to konflux-ci

- components/tekton-ci/base/repository.yaml
Reverts redhat-appstudio/infra-deployments#3640
> Revert "fix: set concurrency limit to 1 for build-definitions repo"

- components/dev-sso/keycloak-realm.yaml
Change user password due to secret leak.
> Rotate Keycloak secret

- components/multi-platform-controller/production/external-secrets.yaml
- components/multi-platform-controller/production/host-config.yaml
Configuring New AWS Account for Multi-Platform Build Public Production Overlay
> KFLUXINFRA-579: Configuring New AWS Account for Multi Platform Build

- components/multi-platform-controller/staging-downstream/external-secrets.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
Configuring New AWS Account for Multi-Platform Build Private Staging Overlay
> KFLUXINFRA-580: Configuring New AWS Account for Multi Platform Build

- components/multi-platform-controller/production-downstream/external-secrets.yaml
- components/multi-platform-controller/production-downstream/host-config.yaml
Configuring New AWS Account for Multi-Platform Build Private Production Overlay
> KFLUXINFRA-581: Configuring New AWS Account for Multi Platform Build

- components/integration/development/kustomization.yaml
- components/integration/development/manager_resources_patch.yaml
- components/integration/production/base/kustomization.yaml
- components/integration/production/base/manager_resources_patch.yaml
- components/integration/production/stone-prod-p01/console-url-config-patch.json
- components/integration/production/stone-prod-p01/kustomization.yaml
- components/integration/staging/base/kustomization.yaml
- components/integration/staging/base/manager_resources_patch.yaml
- components/integration/staging/stone-stage-p01/console-url-config-patch.json
- components/integration/staging/stone-stage-p01/kustomization.yaml
* Add CONSOLE_NAME for integration service to make it aligned with pipeline service
> feat(STONEINTG-861): add CONSOLE_NAME for integration

- components/multi-platform-controller/staging-downstream/external-secrets.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
Building IBM Power and Z builds through mulit-platform-controller in internal-staging
https://issues.redhat.com/browse/KFLUXINFRA-533
> KFLUXINFRA-533: Added IBM Z and Power machines to internal-stage hostconfig

- components/gitops/production/stone-prod-p02/gitops-service-postgres-rds-config-path.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/resources/tekton-results-database-secret-path.yaml
- components/pipeline-service/production/stone-prod-p02/resources/tekton-results-s3-secret-path.yaml
- components/remote-secret-controller/overlays/production/stone-prod-p02/aws-credentials-path-patch.yaml
- components/spi/overlays/production/stone-prod-p02/spi-aws-credentials-path-patch.yaml
Updating Secret Path for stone-prod-p02
> Updating Secret Path for stone-prod-p02

- components/remote-secret-controller/overlays/production/stone-prod-p02/config-patch.json
- components/spi/overlays/production/stone-prod-p02/config-patch.json
updating secrets prefix for spi and remote secret controller
> updating secrets prefix for spi and remote secret controller

- components/multi-platform-controller/staging-downstream/host-config.yaml
* Base image for IBMZ machines 
* RHEL 9.4
* updated on 05-29-2024
* podman installed
> Update base image for ibmz machines

- components/tekton-ci/production/cleanup-cronjob.yaml
- components/tekton-ci/production/kustomization.yaml
Story: https://issues.redhat.com/browse/STONEBLD-2323
> chore: add cronjob to cleanup stale applications in build-templates-e2e ns

- components/tekton-ci/base/repository.yaml
- docs/testing/e2e-tests.md
https://issues.redhat.com/browse/KONFLUX-2239
> chore: reflect moving e2e-tests to konflux-ci org

- components/image-controller/production/stone-prd-rh01/resources/konflux-ci-pull-request-builds-pruner-cronjob.yaml
- components/image-controller/production/stone-prd-rh01/resources/konflux-ci-pull-request-builds-pruner-token.yaml
- components/image-controller/production/stone-prd-rh01/resources/kustomization.yaml
- components/konflux-ci/base/repository.yaml
- components/konflux-ci/production/kustomization.yaml
- components/konflux-ci/production/redhat-appstudio-tekton-catalog-build-definitions-pull-secret.yaml
- components/tekton-ci/base/repository.yaml
[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
See individual commits for details
> Support pushing build-definitions images to quay.io/konflux-ci

- components/gitops/development/gitops-service-argocd.yaml
https://issues.redhat.com/browse/KFLUXBUGS-1171
related slack thread: https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1716309955368609
> fix: increase ARGOCD_EXEC_TIMEOUT

- components/integration/development/kustomization.yaml
- components/integration/development/manager_resources_patch.yaml
- components/integration/production/base/kustomization.yaml
- components/integration/production/base/manager_resources_patch.yaml
- components/integration/production/stone-prod-p01/kustomization.yaml
- components/integration/production/stone-prod-p02/kustomization.yaml
- components/integration/staging/base/kustomization.yaml
- components/integration/staging/base/manager_resources_patch.yaml
- components/integration/staging/stone-stage-p01/kustomization.yaml
* rename integration configMap console-url to integration-config
> fix: rename integration configMap console-url to integration-config

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Also some minor YAML formatting fixes
> Removing otel-collector from public staging (for now)

- components/release/production/kustomization.yaml
This commit includes:
- https://github.com/konflux-ci/release-service/pull/473
- https://github.com/konflux-ci/release-service/pull/472
- https://github.com/konflux-ci/release-service/pull/451
> release-service update on production

- components/release/staging/kustomization.yaml
This commit includes:
- https://github.com/konflux-ci/release-service/pull/473
- https://github.com/konflux-ci/release-service/pull/472
- https://github.com/konflux-ci/release-service/pull/451
> release-service update on staging

- components/mintmaker/base/renovate-config.yaml
ref: [CWFHEALTH-2950](https://issues.redhat.com//browse/CWFHEALTH-2950)
> Update renovate's configuration

- components/ui/production/stone-prod-p02/kustomization.yaml
- components/ui/staging/kustomization.yaml
> update hac-dev ui to latest

- components/dev-sso/keycloak-realm.yaml
Add a keycloak user to be used in a PR check for HAC e2e tests in the infra-deployments repo.
> test: add new keycloak user

- components/tracing/otel-collector/development/otel-collector-helm-values.yaml
- components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Configs being pushed prior to code changes due to chicken & egg issue with recursive git usage & helm chart values.
> PVCORE-4214 - Otel tracing configs for different environments

- components/mintmaker/production/base/kustomization.yaml
- components/mintmaker/production/base/manager_resources_patch.yaml
This is same to 0de62426 which was for staging.
> Increase memory allocation for mintmaker controller in production

- components/multi-platform-controller/production/host-config.yaml
Also lower the IOPS demand for the fast ones
> Fix extra fast instances

- components/mintmaker/base/renovate-config.yaml
It is useful to use the recommended preset.
> Add Renovate preset to Renovate's configuration

- components/mintmaker/production/base/kustomization.yaml
Included PR:
https://github.com/konflux-ci/mintmaker/pull/20
> Promote mintmaker from staging to production

- components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Add the missing otlphttp exporter to the traces pipeline
> Add otlphttp to the traces pipeline

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- components/tracing/otel-collector/production/honeycomb-api-key-secret-path.yaml
- components/tracing/otel-collector/production/kustomization.yaml
PVCORE-4216, [PVCORE-4217](https://issues.redhat.com//browse/PVCORE-4217)
> Enable Otel tracing in production environment

- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
- components/tracing/otel-collector/production/otel-collector-helm-values.yaml
This will patch the otel collector and tracing ApplicationSets to transform the environment from staging to prod.
> Patch the tracing ApplicationSets to transform stage to prod

- components/mintmaker/base/renovate-config.yaml
Clone of https://github.com/redhat-appstudio/infra-deployments/pull/3965 to fix the CI
> Add gitSignOff preset

- components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
- components/spi-vault/kustomization.yaml
- components/spi/overlays/development/kustomization.yaml
- components/spi/overlays/development/oauth-service-config-patch.json
- components/spi/overlays/staging/base/kustomization.yaml
- components/spi/overlays/staging/stone-stage-p01/kustomization.yaml
- components/spi/overlays/staging/stone-stage-p01/oauth-service-config-patch.json
- components/spi/overlays/staging/stone-stg-m01/kustomization.yaml
- components/spi/overlays/staging/stone-stg-m01/oauth-service-config-patch.json
- components/spi/overlays/staging/stone-stg-rh01/kustomization.yaml
- components/spi/overlays/staging/stone-stg-rh01/oauth-service-config-patch.json
- hack/preview.sh
Remove OAuth service deployment from SPI for development and STG
> Remove OAuth service deployment from SPI for development and STG

- components/multi-platform-controller/production-downstream/host-config.yaml
- components/multi-platform-controller/production/host-config.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
Followup PR for https://github.com/redhat-appstudio/infra-deployments/pull/3997
> KFLUXINFRA-651: Adding Instance Types for Multi-Platform Builds

- components/mintmaker/OWNERS
> Add lgallovi to the MintMaker project

- components/image-controller/development/kustomization.yaml
- components/image-controller/staging/base/kustomization.yaml
changes of https://github.com/redhat-appstudio/infra-deployments/pull/4036 needs to be paired with [e2e-tests change](https://github.com/konflux-ci/e2e-tests/pull/1253)
> fix: promote image-controller component to dev/stage

- components/workspaces/staging/kustomization.yaml
This PR sets REST API Server log level to Debug in Staging
> workspaces: set log level to debug in staging

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
* removed the snapshot concurrent attempts metric within integration-service.
* adjusted panel positions and fixed inconsistent height and x/y positioning.
> fix(STONEINTG-863): removed bugged snapshot concurrent requests metric

- components/workspaces/base/server/config/server/deployment.yaml
- components/workspaces/base/server/config/server/kustomization.yaml
linked to: https://github.com/konflux-workspaces/workspaces/pull/235
> workspaces: fix server image and security context

- components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
- components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Fixes [KFLUXBUGS-1461](https://issues.redhat.com//browse/KFLUXBUGS-1461)
> Fix broken urls when user signups in public instances

- components/mintmaker/base/renovate-config.yaml
Adds git-submodules manager for Renovate
> MintMaker: enable git-submodules manager

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
Bump OSP version to 5.0.5-369.
> Update pipeline-service prod

- components/jvm-build-service/OWNERS
> rm gabemontero from jvm-buld-svc owners

- components/monitoring/grafana/base/dashboards/jvm-build-service/OWNERS
> rm gabemontero jvm-build-svc

- .gitignore
This entry was added by mistake in af7cb2b315621c3bb5ea421dc76cd422a713936c
> Remove entry in .gitignore file

- components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
Staging looks good, enabling konflux tiers through infra-deployment for prod now
> Adding tier enablement in production

- components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
This reverts commit 49fa11d91f14edb478f88dd5f24960cc339a7d40.
> Revert "Set prd-m01 as default cluster (#4127)"

- components/mintmaker/development/kustomization.yaml
- components/mintmaker/staging/base/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/mintmaker/pull/30
- https://github.com/konflux-ci/mintmaker/pull/32
> mintmaker update

- components/pipeline-service/production/base/update-tekton-config-performance.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
We see spikes in production that reaches the 4Gi limit.
> Increase tekton-pipelines-remote-resolvers mem limit

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
> SRVKP-4523: make tekton controller k8s throttle metrics available to app-sre grafana

- components/pipeline-service/production/base/update-tekton-config-performance.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
@enarha @gbenhaim @ralphbean PTAL
> tune remote-resolvers again for memory issues seen on prod-rh01

- components/pipeline-service/production/base/update-tekton-config-performance.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
@enarha @gbenhaim @ralphbean PTAL
> enable OSP pruner again for resolver memory issues and results prune performance issues  seen on prod-rh01

- components/multi-platform-controller/staging/host-config.yaml
Check if we can support this many of concurrent multi-arch builds.
> feat(KONFLUX-3796): Test arm64 multi-arch builds with lots of VMs

- components/repository-validator/production/kustomization.yaml
- components/repository-validator/staging/kustomization.yaml
Update the repo-validator to the recent one with rhoai enabled.
> [KFLUXINFRA-717] Allow rhoai onboard to internal cluster

- components/project-controller/production/kustomization.yaml
See #4166 for list of changes.
> chore(RHTAPWATCH-1174): Prod: Bump project-controller

- components/multi-platform-controller/staging-downstream/host-config.yaml
This PR is for trying out the dynamic pool configuration for IBM Power Machines
> Add IBMP dynamic pool for internal stage

- components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
RHTAP and Konflux QE store secrets in vault to run in multiple tenants e2e tests.
> Allow ExternalSecrets in namespaces konflux-qe-team-tenant and rhtap-shared-tenant

- components/pipeline-service/base/rbac/openshift-pipelines/pipeline-service-sre.yaml
- components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
@zanssa FYI ... I will reference this in the SOP updates I'm making as part of responding to your comments over in the gitlab MR
@enarha @savitaashture @divyansh42 FYI
> SRVKP-4524: give tekton perms to konflux-sre

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/staging/base/kustomization.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> SRVKP-4532: bump metrics exporter only dev/stage

- components/cluster-as-a-service/staging/external-secrets.yaml
> fixing hcp secret foe eaas

- components/cluster-as-a-service/staging/external-secrets.yaml
- components/cluster-secret-store/base/appsre-vault-secret-store.yml
adding hcp namespace for appsre-vault cluster secret store
> adding hcp namespace for appsre-vault cluster secret store

- components/cluster-as-a-service/staging/external-secrets.yaml
- components/cluster-secret-store/base/appsre-vault-secret-store.yml
Changing Paths for EaaS External Secrets
> Changing Paths for EaaS External Secrets

- components/pipeline-service/production/base/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
> SRVKP-4532: bump metrics exporter on prod

- components/project-controller/production/kustomization.yaml
Upgrade the project-controller. This update  includes patches made to solve [RHTAPWATCH-1192](https://issues.redhat.com//browse/RHTAPWATCH-1192) and [RHTAPWATCH-1193](https://issues.redhat.com//browse/RHTAPWATCH-1193)
> feat(RHTAPWATCH-1192): Bump prod. project-controller

- components/notification-controller/base/deployment.yaml
update notification-controller container
> update notification-controller container

- components/multi-platform-controller/production/external-secrets.yaml
- components/multi-platform-controller/production/host-config.yaml
Using s390x machines with dynamic hosts
> KFLUXINFRA-786: Added s390x as dynamic hosts for public prod

- argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
- argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/kustomization.yaml
- argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/power-monitoring.yaml
- components/power-monitoring/OWNERS
- components/power-monitoring/kepler.yaml
- components/power-monitoring/kustomization.yaml
- components/power-monitoring/power-monitoring-operator.yaml
Add kepler and power-monitoring component
Add the power-monitoring application set to all cluster
> PVCORE-4433 - Add Power Monitoring Operator

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
> SRVKP-4524: add metrics/labels for results alerts/panels

- components/ui/development/kustomization.yaml
- components/ui/production/stone-prod-p01/kustomization.yaml
- components/ui/production/stone-prod-p02/kustomization.yaml
- components/ui/staging/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#4381
UI is not loading anymore
> Revert "Update UI images to the latest"

- components/multi-platform-controller/production-downstream/host-config.yaml
* Created a group of nodes with higher capacity
> KFLUXBUGS-1557: Add Large nodes for s390x and ppc64le to internal prod

- components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml
Fix from the previous PR https://github.com/redhat-appstudio/infra-deployments/pull/4338
> Change unit from percent to none

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
The CronJob was used as workaround for
https://issues.redhat.com/browse/RHTAPBUGS-256 now fixed.
> Remove PaC secret reaper CronJob

- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-m01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Needed to run the scripts one more time in https://github.com/redhat-appstudio/infra-deployments/pull/4409 
rh-pre-commit.version: 2.3.1
> forgot to re-run generate-deploy-config

- hack/preview.sh
- Make sure all development cluster will have proper nodes labels
> chore: label correspondingly development nodes

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
this commit adds new metrics to enable a new SLO and Dashboard for the Release Service
> feat: add new metrics required by release dashboard and SLO

- components/notification-controller/development/topic_region_add.yaml
- components/notification-controller/staging/topic_region_add.yaml
update environment variable patch
> update environment variable patch

- components/authentication/base/konflux-admins.yaml
* Should be in lowercase.
* Should be in plural form.
> Fix customresourcedefinitions name

- components/multi-platform-controller/staging-downstream/host-config.yaml
> test IBMP dynamic pool

- components/multi-platform-controller/staging-downstream/host-config.yaml
> Added route details as userdata for ppc64le

- components/notification-controller/base/external-secrets/aws-sns-secret.yaml
- components/notification-controller/staging/external-secret-path.yaml
- components/notification-controller/staging/kustomization.yaml
Update external secret location in staging environment
> chore(RHTAPWATCH-1266): update external secret location - staging

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
add slo availability panels, one to measure
and one to track violations
> chore(stoneintg-1023): add IS SLO availability panels

- components/notification-controller/production/external-secret-path.yaml
- components/notification-controller/production/kustomization.yaml
- components/notification-controller/production/topic_region_add.yaml
Promote the notification-controlller to production
> chore(RHTAPWATCH-1202): promote notification-controlller to production

- components/multi-platform-controller/base/kustomization.yaml
test fix for https://issues.redhat.com/browse/KFLUXBUGS-1532 in https://github.com/konflux-ci/multi-platform-controller/pull/290
> Test fix for provision script (temporary)

- components/multi-platform-controller/base/kustomization.yaml
Testing https://github.com/konflux-ci/multi-platform-controller/pull/290
> Update MPC provision script

- components/multi-platform-controller/production-downstream/kustomization.yaml
- components/multi-platform-controller/production/kustomization.yaml
use latest tag of MPC with memory limit fix (to prevent OOM kills on prod)
> use latest tag of MPC with memory limit fix

- components/notification-controller/development/kustomization.yaml
- components/notification-controller/production/kustomization.yaml
- components/notification-controller/staging/kustomization.yaml
update resources for notification controller
> update resources for notification controller

- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
Add notification controller to production
> add notification controller to production

- components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
slo is 99% over 24 hours
panels updated to reflect this
> chore(stoneintg-2013): update availability panels to 24h

- components/multi-platform-controller/production-downstream/host-config.yaml
- components/multi-platform-controller/production/host-config.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
- components/multi-platform-controller/staging/host-config.yaml
Adding AWS GPU Node support MPC under dynamic provisioning.
Instance Type -- `g4ad.xlarge`
This provides 4 vCPU and 16 GB Memory.
GPU -- Radeon Pro V520/V54
> KFLUXINFRA-837: Adding AWS GPU Nodes for Dynamic Provisioning

- components/multi-platform-controller/staging-downstream/host-config.yaml
Testing ppc dynamic provisioning with snat
> Updated ppc64le network config

- components/multi-platform-controller/staging-downstream/host-config.yaml
> updated cloud config

- components/multi-platform-controller/staging-downstream/host-config.yaml
> Fix route commands

- argo-cd-apps/base/member/infra-deployments/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/nvme-storage-configurator.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- configs/nvme-storage-configurator/base/clusterrolebinding.yaml
- configs/nvme-storage-configurator/base/daemonset.yaml
- configs/nvme-storage-configurator/base/install.sh
- configs/nvme-storage-configurator/base/kustomization.yaml
- configs/nvme-storage-configurator/base/mount.sh
- configs/nvme-storage-configurator/base/namespace.yaml
- configs/nvme-storage-configurator/base/nvme-storage.service
- configs/nvme-storage-configurator/base/serviceaccount.yaml
- configs/nvme-storage-configurator/production/kustomization.yaml
- configs/nvme-storage-configurator/staging/kustomization.yaml
This Pull Request will do the following -
1. Create Namespace
2. ServiceAccount
3. ClusterRoleBinding
4. ConfigMap
5. DaemonSet
This DaemonSet will make use of shell scripts coming from the ConfigMap to configure NVMe Disks.
> KFLUXINFRA-777: Config to Configure Worker Nodes with NVMe Disks

- components/tracing/otel-collector/production/otel-collector-helm-values.yaml
... simple enough, fixing a name mismatch.
> Fixing env name from stage to prod in prod config

- components/multi-platform-controller/production-downstream/host-config.yaml
- components/multi-platform-controller/production/common/host-config.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
- components/multi-platform-controller/staging/host-config.yaml
Changing GPU Instance Type from `g4dn.xlarge` to `g6.xlarge` due to performance reasons.
> Changing GPU Instance Type from g4dn.xlarge to g6.xlarge

- argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/kustomization.yaml
Fixing ApplicationSet for the DaemonSet
> Fixing ApplicationSet for the DaemonSet

- argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
- argo-cd-apps/base/member/infra-deployments/kubearchive/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/kustomization.yaml
- argo-cd-apps/overlays/development/kustomization.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
- components/kubearchive/OWNERS
- components/kubearchive/base/kustomization.yaml
- components/kubearchive/base/rbac.yaml
- components/kubearchive/development/kustomization.yaml
- components/kubearchive/development/postgresql.yaml
- components/kubearchive/staging/database-secret.yaml
- components/kubearchive/staging/kustomization.yaml
Hi! We aim to introduce KubeArchive to Konflux with this PR.
> Add KubeArchive to development cluster

- components/multi-platform-controller/production/common/host-config.yaml
increasing the number nodes in the cluster
> Increase maximum number of aarch64 nodes can spin up for public prod

- components/multi-platform-controller/production/kustomization.yaml
- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
prd-m01 was updadated few days ago and the update verified.
> Update OSP prod

- components/multi-platform-controller/production-downstream/kustomization.yaml
OSP was upgraded and we missing upgrading MPC version in internal clusters.
> Upgrade MPC version in internal clusters

- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
This was deployed in Stage by c9f164e835f22ce89bed625a97f23097a0572668
> feat(KONFLUX-4508): Run more Pipelines Controller replicas across more zones in Prod

- components/project-controller/production/kustomization.yaml
project-controller quay repository should be
updated to use konflux-ci
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-69
> chore(KFLUXVNGD-69): Update prod configuration for project-controller

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
This Pull Request will deploy daemonset and configurations to configure local nvme disks attached to the ROSA nodes.
Related Pull Request for staging -
- https://github.com/redhat-appstudio/infra-deployments/pull/4361
> KFLUXINFRA-777: Unblocking NVME Disk Configuration for Production

- components/konflux-ci/base/repository.yaml
- components/tekton-ci/base/repository.yaml
Related PR: https://github.com/containerbuildsystem/cachi2/pull/665
> Move cachi2 pipelines from tekton-ci to konflux-ci

- components/repository-validator/production/kustomization.yaml
* Allow red-hat-data-services org repositories to the internal instances
[KFLUXINFRA-877](https://issues.redhat.com//browse/KFLUXINFRA-877)
> Update repo validator config to latest revision

- components/release/base/release-pipeline-resources-clusterrole.yaml
- release pipeline can create pipelineruns to trigger additional workloads
> feat(RELEASE-1192): release sa needs plr rbac

- components/multi-platform-controller/production-downstream/host-config.yaml
Enabling dynamic ppc in internal prod
> KFLUXINFRA-640: Enable dynamic nodes for ppc64le internal production

- components/multi-platform-controller/production-downstream/host-config.yaml
Cleaning up the static nodes and adding large node for ppc in internal prod
> KFLUXINFRA-640: Removed static ppc-nodes and added ppc-large nodes for internal prod

- components/multi-platform-controller/production-downstream/host-config.yaml
- components/multi-platform-controller/production/common/host-config.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
- components/multi-platform-controller/staging/host-config.yaml
Supplements PR https://github.com/konflux-ci/multi-platform-controller/pull/306
Adds configuration for VM custom tags
> Add custom tags to apply on MPC VM's

- components/multi-platform-controller/staging/host-config.yaml
This is for testing dynamic s390x in stage
> KFLUXINFRA-812: Dynamic host for s390x in external stage

- components/cluster-secret-store/base/insights-secret-store.yaml
- components/cluster-secret-store/base/kustomization.yaml
- components/cluster-secret-store/production/insights-approle-id-patch.yaml
- components/cluster-secret-store/production/kustomization.yaml
- components/cluster-secret-store/staging/insights-approle-id-patch.yaml
- components/cluster-secret-store/staging/kustomization.yaml
Creating Cluster Secret Store for Insights to retreive secrets in konflux build pipelines.
> KFLUXINFRA-799: Creating Cluster Secret Store for Insights

- components/workspaces/base/server/config/server/proxy-config/dynamic/config.yaml
> workspaces: ensure validation of JWT's sub and exp

- components/multi-platform-controller/production/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Promotes the following fixes to production:
- https://github.com/konflux-ci/multi-platform-controller/pull/306
- https://github.com/konflux-ci/multi-platform-controller/pull/311
> Promote MPC fixes to production

- components/cluster-secret-store/base/insights-secret-store.yaml
This Pull Request will fix the API Version for Vault in Cluster Secret Store.
> fix: fixing the api version for vault

- argo-cd-apps/base/member/infra-deployments/workspaces/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
- components/workspaces/staging/stone-stg-rh01/kustomization.yaml
> fix: workspaces resources required on member clusters

- components/monitoring/grafana/base/dashboards/release/OWNERS
- components/release/OWNERS
> chore: update release-service owners

- components/multi-platform-controller/base/common/monitoring.yaml
- components/multi-platform-controller/base/kustomization.yaml
Testing changes to the secure metrics endpoint
> [temporary] Test MPC metrics refactoring to secure endpoint

- components/multi-platform-controller/production-downstream/replicas_patch.yaml
Testing to see if it helps to drain the currently provisioned VMs faster.
> increase MPC replica count

- components/multi-platform-controller/production-downstream/replicas_patch.yaml
Reducing to one. Instead, we will see if multiple reconciliations will be any more successful konflux-ci/multi-platform-controller/pull/318
> More replicas do not seem to improve the situation

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
- configs/proactive-scaler/base/deployments.yaml
This Pull Request will enable the proactive autoscaling for the production overlay and disable it for the stating overlay.
Related Pull Request that was implemented for the staging environment --
- https://github.com/redhat-appstudio/infra-deployments/pull/4670
> Enabling Proactive Autoscaling for the Production Clusters

- components/release/base/cronjobs/kustomization.yaml
this PR includes the new definition file for `cleanup-timed-out-pipelineruns-internal-requests` cronjob
in the kustomization file.
> fix: updating kustomization file

- components/build-service/production/base/kustomization.yaml
- components/build-service/production/stone-prod-p01/kustomization.yaml
- components/build-service/production/stone-prod-p02/kustomization.yaml
- components/build-service/staging/base/kustomization.yaml
- components/build-service/staging/stone-stage-p01/kustomization.yaml
[KFLUXBUGS-1744](https://issues.redhat.com//browse/KFLUXBUGS-1744)
> create internal certs config map in all cluster for build-service

- components/authentication/production/kflux-ocp-p01/kustomization.yaml
[KFLUXINFRA-921](https://issues.redhat.com//browse/KFLUXINFRA-921)
> Fix authentication for new kflux-ocp-p01 cluster

- components/multi-platform-controller/production-downstream/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/321
> Promote latest MPC to the internal prod

- components/multi-platform-controller/staging-downstream/host-config.yaml
For testing purposes.
https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1730181905884509
> feat(KONFLUX-5124): Test with more VMs available

- components/notification-controller/development/kustomization.yaml
update staging notification controller
> fix(KFLUXBUGS-1764): update staging notification controller

- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
- components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
Dev and Stage already verified.
Bumping prod-m01 in preparation for bumping all prod
> Update OSP prod-m01

- components/notification-controller/production/kustomization.yaml
update notification-controller production
> fix(KFLUXBUGS-1764): update notification-controller production

- configs/nvme-storage-configurator/base/install.sh
- configs/nvme-storage-configurator/base/mount.sh
This Pull Request will make thew following changes -
1. Add error handling in mount.sh script
2. Change the lock file name
> fix(KFLUXINFRA-777): Adding Error Handling in mount.sh Script

- components/multi-platform-controller/production/kustomization.yaml
- components/multi-platform-controller/production/manager_resources_patch.yaml
Pod is in crashloop, a follow up change will be done to make this change across staging and prod environments.
> Increase memory of MPC on prd-rh01

- configs/nvme-storage-configurator/base/install.sh
Adding a readonly variable for a lock file
> fix(KFLUXINFRA-777): Adding a readonly variable in install.sh script

- components/multi-platform-controller/production-downstream/host-config.yaml
- components/multi-platform-controller/production-downstream/kustomization.yaml
- components/multi-platform-controller/production/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
... and update IBM limits to 50 for rhel release.
> Update mpc to the latest staging-tested version

- components/monitoring/logging/staging/stone-stage-p01/configure-logforwarder-compression-patch.yaml
> fix logs compression in staging p01

- components/multi-platform-controller/staging-downstream/host-config.yaml
Testing the new snat in the stagging
> KFLUXINFRA-903: Remove additional routing to support route from TGW

- components/ui/base/proxy/nginx.conf
> remove workspaces endpoint from proxy's UI

- components/multi-platform-controller/production-downstream/kustomization.yaml
- components/multi-platform-controller/production/kustomization.yaml
This PR includes important changes (confirmed to be working) on STG:
- https://github.com/konflux-ci/multi-platform-controller/pull/325
- https://github.com/konflux-ci/multi-platform-controller/pull/309
-  https://github.com/konflux-ci/multi-platform-controller/pull/335
> Promote MPC staging to production

- components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-database-secret-path.yaml
This Pull Request will fix the RDS Secret Path.
> fix(KFLUXINFRA-921): Fixing RDS Secret Path

- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
This Pull Request will fix the Vault Path for the RDS Secret.
Related Pull Request --
- https://github.com/redhat-appstudio/infra-deployments/pull/4934
> fix(KFLUXINFRA-921): Fixing Vault Secret Path for RDS

- components/has/base/kustomization.yaml
- components/has/production/kustomization.yaml
- components/has/staging/kustomization.yaml
- components/monitoring/grafana/base/dashboards/has/kustomization.yaml
Included PRs:
- [chore: update application-api version (#489)](https://github.com/redhat-appstudio/application-service/pull/489)
> application-service update

- components/release/production/kustomization.yaml
this commit updates the release-service on the prod cluster
Included PRs:
- https://github.com/konflux-ci/release-service/pull/614
- https://github.com/konflux-ci/release-service/pull/611
> release-service update in production

- components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
This also adds new retention-policy-agent component, currently not used by Konflux.
> Update Tekton Results to v0.13.0

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
based on the conversation in [this thread](https://redhat-internal.slack.com/archives/C02M210JZ7B/p1732802281598569?thread_ts=1732713198.999119&cid=C02M210JZ7B)
> Reduce the Results buffer time to 1m in Development

- components/internal-services/kustomization.yaml
this PR updates the internal-services controller to the latest version.
> chore: update internal-services controller

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
- hack/secret-creator/create-plnsvc-secrets.sh
This fixes the secret name used by Vector. It also unifies the names used in staging and development (CI).
> Fix Vector secret name

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
This enables the vector worker in infra nodes.
> Enable Tekton Log Forwarding in infra nodes

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Schedule Tekton Logging Forwarder to konflux-ci.dev/workload.
We don't require a forwarder in master.
> Schedule Tekton Logging Forwarder to konflux-ci.dev/workload

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
We are reverting NVMe Disk Configuration to troubelshoot an ongoing issue.
> Revert NVMe Disk Configs for Prod Overlays

- components/build-service/production/kflux-prd-rh02/kustomization.yaml
- components/build-service/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
- components/integration/production/kflux-prd-rh02/console-url-config-patch.json
- components/integration/production/kflux-prd-rh02/kustomization.yaml
- components/integration/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
- components/mintmaker/production/kflux-prd-rh02/kustomization.yaml
- components/mintmaker/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
- components/monitoring/logging/production/kflux-prd-rh02/kustomization.yaml
- components/monitoring/prometheus/production/kflux-prd-rh02/cluster-id-label.yaml
- components/monitoring/prometheus/production/kflux-prd-rh02/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/osp-perf-resolvers.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/pipelines-as-code-secret-path.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/tekton-chains-public-key-path.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/tekton-chains-signing-secret-path.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-database-secret-path.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-s3-secret-path.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
Create the overlays for:
- build-service
- mintmaker
- pipelines-service
- integration-service
- monitoring
console urls for the pipeline service and integration will be added after the cluster will be ready.
> KFLUXINFRA-1131: Overlays for kflux-prd-rh02

- argo-cd-apps/base/eaas/crossplane-config/crossplane-config.yaml
- argo-cd-apps/base/eaas/crossplane-config/kustomization.yaml
- argo-cd-apps/base/eaas/kustomization.yaml
- components/crossplane-config/OWNERS
- components/crossplane-config/base/kustomization.yaml
- components/crossplane-config/base/rbac.yaml
- components/crossplane-config/base/secret.yaml
- components/crossplane-config/development/kustomization.yaml
- components/crossplane-config/production/kustomization.yml
- components/crossplane-config/staging/kustomization.yaml
Add service account, cluster role, role binding and related ArgoCD configuration for deployment.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-89
> chore(KFLUXVNGD-89): Add service account and related config

- components/internal-services/kustomization.yaml
this PR updates the internal-service controller
to the latest version.
(required to restart the controller, so it gets the new config)
> chore: internal-services update

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
[KFLUXINFRA-1111](https://issues.redhat.com//browse/KFLUXINFRA-1111)
> Fix IBM s390 VPC name for kflux-ocp-p01

- hack/preview.sh
> fix: typo in preview script for integration-service

- components/multi-platform-controller/production/host-config.yaml
Taking the nodes out of config to investigate on the nodes before moving to dynamic
> Remove large nodes from config

- components/crossplane-control-plane/staging/kustomization.yaml
- components/crossplane-control-plane/staging/provider-config.yaml
Crossplane kubernetes provider config for staging environment is added in crossplane-config.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-89
> chore(KFLUXVNGD-89): Add stage kubernetes provider config

- components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
add the crossplane-system namespace secrets to access the vault.
> chore: add crossplane-system secrets

- components/crossplane-control-plane/production/kustomization.yaml
- components/crossplane-control-plane/production/provider-config.yaml
Add provider config and external secret for crossplane-control-plane production environment.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-89
> chore(KFLUXVNGD-89): Add crossplane provider config for prod

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
- components/multi-platform-controller/production/kustomization.yaml
From https://github.com/redhat-appstudio/infra-deployments/pull/5075
> Roll out MPC update to prod

- components/multi-platform-controller/production/host-config.yaml
Single 4x16G type looks liltte too heavy, let's make 2 grades as it is done for internal cluster.
> Add two grades of s390x VM

- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/ui/production/stone-prod-p01/kustomization.yaml
- components/ui/staging/kustomization.yaml
Add Vector for forwarding Pipelines log.
Update Tekton Results to version 0.13.2-2.
The base file for prod is updated and the deploy.yaml file updated for a single cluster stone-prod-p01 to allow gradual update.
> Add Vector and update Results stone-prod-p01

- components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
* Removes empty settings for the collector.  tolerations in particular wants either object or nil, null is not valid.
> KFLUXBUGS-1610 - Remove empty collector settings

- components/project-controller/production/kustomization.yaml
Promote project-controller to production to introduce enhancements: https://github.com/konflux-ci/project-controller/pull/143 https://github.com/konflux-ci/project-controller/pull/142
> feat(KFLUXVNGD-142, KONFLUX-5791): promote project-controller

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Similar to https://github.com/redhat-appstudio/infra-deployments/pull/5050
> [OCP] Create new flavors with larger disk

- components/multi-platform-controller/production/host-config.yaml
MPC is waiting to get the allocated VM  freed to create new VMs
> Updated amd64 concurrent builds to 50 prod-external

- components/monitoring/grafana/base/grafana-app.yaml
This pull request will revert the changes that were made in the following pull request -
- https://github.com/redhat-appstudio/infra-deployments/pull/5202
> Reverting Changes made in PR-5202

- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
- components/ui/production/kflux-ocp-p01/kustomization.yaml
- components/ui/production/stone-prod-p02/kustomization.yaml
Update Results prod internal.
Updates kflux-ocp-p01 and stone-prod-p02.
Update UI to match Results update.
> Update results prod internal

- components/multi-platform-controller/staging-downstream/host-config.yaml
test changes for  Support disk parameter for IBM arch ( https://issues.redhat.com/browse/KFLUXINFRA-1198)
> Test custom IBM volumes size feature

- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
This Pull Request will disable NVMe Disk Configuration for stone-stage-p01
> KONFLUX-5670: Disable NVMe Disk Configuration

- components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
- components/pipeline-service/development/kustomization.yaml
- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- hack/secret-creator/create-plnsvc-secrets.sh
The Minio testing service play.min.io is down for almost a day blocking the CI, so switching back to local deployment in development.
> Switch back to local Minio in development

- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
This Pull Request will enable NVMe Disk Configuration for stone-stage-p01
> KONFLUX-5670: Enable NVMe Disk Configuration

- components/enterprise-contract/ecp.yaml
- components/enterprise-contract/kustomization.yaml
Recreating #4984 with a different owner, i.e. myself, and with my personal fork.
> enterprise contract update

- components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Update the ssh-key name, security group and subnet.
> Fix AWS host config for rh02

- components/project-controller/production/kustomization.yaml
https://github.com/konflux-ci/project-controller/pull/149 tested in staging. This commit promotes it to production.
> chore(KFLUXVNGD-160): project-controller prod update

- components/integration/production/base/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#5258
> Revert "Promote integration-service from staging to production"

- components/multi-platform-controller/base/kustomization.yaml
- https://github.com/konflux-ci/multi-platform-controller/pull/388
- https://github.com/konflux-ci/multi-platform-controller/pull/389
> Multi platform controller

- argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
See [here](https://kyverno.io/docs/installation/platform-notes/#notes-for-openshift-users) for details.
> kyverno: delete security context from policy reports cleanup job

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Similar to https://github.com/redhat-appstudio/infra-deployments/pull/5050
> [OCP] Create new ppc64le flavor with larger disk

- components/mintmaker/production/base/kustomization.yaml
Make a prod release containing updated mintmaker image.
> Promote new mintmaker image to prod

- components/workspaces/staging/stone-stg-rh01/kustomization.yaml
- components/workspaces/staging/stone-stg-rh01/temp-dperaza-rbac.yaml
Testing user migration script in staging.
> Giving me temp access to test rolebinding migration

- components/mintmaker/staging/base/kustomization.yaml
This is a temporary release to stage, as we need to test some new refactoring in MintMaker.
> Push refactored version of MintMaker to stage

- OWNERS
- components/enterprise-contract/OWNERS
Removes zregvart from OWNERS files
> Remove zregvart as owner

- components/project-controller/production/kustomization.yaml
Upgrade project-controller config in production to include changes from https://github.com/konflux-ci/project-controller/pull/153
> chore(KFLUXVNGD-167): project-controller to prod

- components/external-secrets-operator/base/operator-config.yaml
- components/external-secrets-operator/staging/kustomization.yaml
- components/external-secrets-operator/staging/resource-requests.patch.yaml
This Pull request will add the resource requests and limits for the following resources that are created by external-secrets operator -
1. Cert Manager
2. Webhook
3. Controller Manager
4. External Secret Deployment
> KONFLUX-5674: Adding Resource Requests and Limits

- components/namespace-lister/base/deployment.yaml
- components/namespace-lister/base/kustomization.yaml
- **bump namespace-lister**
- **unset imagePullPolicy**
> bump namespace lister

- components/sandbox/toolchain-member-operator/production/patch_resources.yaml
- components/sandbox/toolchain-member-operator/staging/patch_resources.yaml
> fix memory request for sandbox's member-operator

- components/sandbox/toolchain-member-operator/production/patch_resources.yaml
- components/sandbox/toolchain-member-operator/staging/patch_resources.yaml
> set cpu request for sandbox's member-operator

- components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/patch_resources.yaml
- components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/stone-prd-host1/patch_resources.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p01/patch_resources.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
- components/sandbox/toolchain-host-operator/production/stone-prod-p02/patch_resources.yaml
- components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
- components/sandbox/toolchain-host-operator/staging/stone-stage-p01/patch_resources.yaml
- components/sandbox/toolchain-host-operator/staging/stone-stg-host/kustomization.yaml
- components/sandbox/toolchain-host-operator/staging/stone-stg-host/patch_resources.yaml
> increase memory request for sandbox's host-operator

- OWNERS
jduimovich has retired, remove him from OWNERS
> remove jduimovich from OWNERS

- components/namespace-lister/base/kustomization.yaml
We've cut a new release, so let's use it.
> deploy new version of namespace-lister

- components/namespace-lister/base/kustomization.yaml
- components/namespace-lister/base/metrics/kustomization.yaml
- components/namespace-lister/base/metrics/monitor.yaml
- components/namespace-lister/base/metrics/service-account.yaml
See https://github.com/konflux-ci/namespace-lister/pull/39 for details on the metrics added.
> expose metrics for namespace lister

- components/namespace-lister/base/network_policy.yaml
> namespace-lister: allow incoming traffic from openshift-monitoring

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Update development overlay to match staging by using statefulsets. Limit resources requirements in staging.
> Move pipelines remote resolvers to statefulset

- components/namespace-lister/base/metrics/kustomization.yaml
- components/namespace-lister/base/metrics/rbac.yaml
- components/namespace-lister/base/metrics/service-account.yaml
> improve namespace-lister monitoring manifests

- components/kyverno/staging/kyverno-values.yaml
> unset securityContext for kyverno's components

- components/kyverno/staging/kyverno-values.yaml
> kyverno: set fullnameOverride and namespaceOverride to konflux-kyverno

- components/namespace-lister/base/deployment.yaml
namespace-lister is getting OOMKilled. Let's give it a bit more resources.
> increase namespace-lister resources

- components/namespace-lister/base/metrics/kustomization.yaml
- components/namespace-lister/base/metrics/network_policy.yaml
> improve namespace-lister's network policies

- components/mintmaker/production/base/kustomization.yaml
This PR is the weekly release of MintMaker.
I have watched the runs in stage, and everything seems to be working as expected.
> Promote MintMaker changes from stage to prod

- components/sandbox/toolchain-member-operator/base/kustomization.yaml
- components/sandbox/toolchain-member-operator/base/monitoring/kustomization.yaml
- components/sandbox/toolchain-member-operator/base/monitoring/monitor.yaml
- components/sandbox/toolchain-member-operator/base/monitoring/prometheus-network-policy.yaml
- components/sandbox/toolchain-member-operator/base/monitoring/rbac.yaml
- components/sandbox/toolchain-member-operator/base/monitoring/serviceaccount.yaml
> update KubeSaw member-operator's ServiceMonitor

- components/konflux-ci/base/repository.yaml
Cachi2 has been migrated to new repo
> konflux-ci: Cachi2 repo change

- components/namespace-lister/base/deployment.yaml
- components/namespace-lister/base/kustomization.yaml
- components/namespace-lister/base/metrics/kustomization.yaml
- components/namespace-lister/base/metrics/monitor.yaml
- components/namespace-lister/base/metrics/network_policy.yaml
- components/namespace-lister/base/metrics/service.yaml
* https://github.com/konflux-ci/namespace-lister/pull/51
* https://github.com/konflux-ci/namespace-lister/pull/48
> release new version of namespace-lister

- components/integration/staging/stone-stage-rh01/kubearchive-config-patch.yaml
- components/integration/staging/stone-stage-rh01/kustomization.yaml
- components/kubearchive/base/kubearchive-config.yaml
- components/kubearchive/base/kustomization.yaml
- components/release/staging/kubearchive-config-patch.yaml
- components/release/staging/kustomization.yaml
Set up the global configuration for archiving snapshots with kubearchive.  This will automatically archive all snapshots upon deletion.
> feat(stoneintg-1111): begin archiving snapshots with kubearchive

- components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Asked by istio team in slack support channel
https://issues.redhat.com/browse/KFLUXSPRT-1713
> Add amd64 and arm64 options with larger disk on p02

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
- components/multi-platform-controller/production-downstream/base/role-temp.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/role-temp.yaml
- components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-rh01/role-temp.yaml
Final PR in series of kube-rbac removal https://issues.redhat.com/browse/KFLUXINFRA-1235
> Update prod with recent MPC changes

- components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Support ticket https://issues.redhat.com/browse/KFLUXSPRT-1713
> Add 200Gb IBM machines (requested by istio)

- components/kubearchive/base/kustomization.yaml
Remover operator memory limit.
> Remover operator memory limit.

- components/mintmaker/staging/base/kustomization.yaml
This commit is to send a custom image to stage, for testing purposes.
> deploy custom MintMaker image to stage

- argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
- argo-cd-apps/base/all-clusters/infra-deployments/cost-management/kustomization.yaml
- argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
- argo-cd-apps/overlays/development/delete-applications.yaml
- components/cost-management/base/costmanagement-metrics-config.yaml
- components/cost-management/base/costmanagement-metrics-operator.yaml
- components/cost-management/base/kustomization.yaml
- components/cost-management/staging/cost-management-config-source-patch.yaml
- components/cost-management/staging/kustomization.yaml
Installing Cost Management operator to the staging environment.
> Add Cost management operator to staging environment - PVO11Y-4610

- components/monitoring/grafana/base/grafana-operator.yaml
- components/monitoring/grafana/staging/kustomization.yaml
After having been deployed to staging successfully (#5605) I am applying this to the base.
> [KONFLUX-5918] Deploy Grafana operator resource limits

- argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
- components/konflux-ui/staging/stone-stg-p01/add-service-certs-patch.yaml
- components/konflux-ui/staging/stone-stg-p01/dex-config.yaml
- components/konflux-ui/staging/stone-stg-p01/kustomization.yaml
- components/konflux-ui/staging/stone-stg-p01/oauth2-proxy-args-patch.yaml
- components/konflux-ui/staging/stone-stg-p01/remove-run-as-user-proxy-patch.yaml
- components/konflux-ui/staging/stone-stg-p01/set-hostname.yaml
- components/konflux-ui/staging/stone-stg-p01/set-redirect-uri.yaml
- components/konflux-ui/staging/stone-stg-p01/set-replicas-patch.yaml
This deploys konflux-ui and any missing dependencies to stone-stage-p01.
> konflux-ui: deploy to internal staging

- argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
- components/cost-management/staging/kflux-stg-es01/cost-management-config-source-patch.yaml
- components/cost-management/staging/kflux-stg-es01/kustomization.yaml
- components/cost-management/staging/stone-stg-host/cost-management-config-source-patch.yaml
- components/cost-management/staging/stone-stg-host/kustomization.yaml
- components/cost-management/staging/stone-stg-p01/cost-management-config-source-patch.yaml
- components/cost-management/staging/stone-stg-p01/kustomization.yaml
- components/cost-management/staging/stone-stg-rh01/cost-management-config-source-patch.yaml
- components/cost-management/staging/stone-stg-rh01/kustomization.yaml
This update will ensure that source names are unique to each cluster.
> Update cost-management source patches to stage clusters

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Updates Tekton Results to v0.14.0-1 and enable PartialResponse.
> Update Tekton Results to v0.14.0-1 staging

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
- components/multi-platform-controller/staging/host-config.yaml
Realted Pull Request -
- https://github.com/redhat-appstudio/infra-deployments/pull/5613
> KONFLUX-6962: Adding a New ARM Build Instance for all the Overlays

- argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- components/namespace-lister/production/stone-prd-rh01/kustomization.yaml
This enables namespace-lister on stone-prd-rh01.
> deploy ns-lister to stone-prd-rh01

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Add in missing instance-tag params
> [OCP] add missing instance-tags

- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
This should fix issue with workspace applications in production looking at components in staging environment
> adding workspace member application set to prod overlay

- argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
- components/konflux-rbac/production/kflux-ocp-p01/kustomization.yaml
- components/konflux-rbac/production/stone-prd-rh01/kustomization.yaml
- components/konflux-rbac/production/stone-prod-p01/kustomization.yaml
- components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
- components/konflux-rbac/staging/stone-stage-p01/kustomization.yaml
This will allow to use the new namespace based
tenancy in all the clusters.
> Deploy tenants RBAC to all the clusters

- components/namespace-lister/base/kustomization.yaml
> bump namespace lister to latest version in staging

- components/repository-validator/staging/kustomization.yaml
This repo is private so it's been added to the allow list.
> Allow MPC sample multi-arch repo on staging

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Since @mshaposhnik had found out the cause was not related to this issue. 
https://issues.redhat.com/browse/KFLUXINFRA-1311
> Revert "[OCP] update IBM tags"

- components/namespace-lister/base/deployment.yaml
> temporarily increase log verbosity for namespace-lister in staging

- components/namespace-lister/base/deployment.yaml
This reverts commit e3bda37042b11c2e6ee765da4faa67bb1d035dec.
> Revert "temporarily increase log verbosity for namespace-lister in staging (#5689)"

- components/namespace-lister/base/kustomization.yaml
> bump namespace-lister in staging

- components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
These secrets are expected by oauth2-proxy, but they're not getting generated on stone-stage-p01.  Add these secrets in.
> konflux-ui: generate oauth2 secrets on stone-stage-p01

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
> Increase memory request and limit for appstudio-federate-ms

- argo-cd-apps/base/member/infra-deployments/etcd-defrag/etcd-defrag.yaml
- argo-cd-apps/base/member/infra-deployments/etcd-defrag/kustomization.yaml
- argo-cd-apps/base/member/infra-deployments/kustomization.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
- configs/etcd-defrag/base/cluster-role.yaml
- configs/etcd-defrag/base/cronjob.yaml
- configs/etcd-defrag/base/kustomization.yaml
- configs/etcd-defrag/base/namespace.yaml
- configs/etcd-defrag/base/role-binding.yaml
- configs/etcd-defrag/base/serviceaccount.yaml
- configs/etcd-defrag/production/kustomization.yaml
- configs/etcd-defrag/staging/kustomization.yaml
This Pull Request will create following resources -
- Namespace
- ClusterRole
- ClusterRoleBinding
- ServiceAccount
- CronJob that will run every 5 minutes
> KFLUXINFRA-1269: Adding Configuration to etcd defrag periodically

- components/konflux-ui/production/base/proxy/nginx.conf
> fix UI's proxy websocket support in prod

- components/konflux-ui/staging/stone-stage-p01/dex-config.yaml
> clean konflux-ui dex config in stage-p01

- components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Adding the `tekton-bundle-builder` pipeline to the build configmap
> chore(KFLUXVNGD-195): add tekton-bundle-builder to build configmap

- components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
> add AccessCache panels to namespace-lister's grafana dashboard

- components/namespace-lister/base/kustomization.yaml
> bump namespace lister in staging

- argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- components/kyverno/production/empty-base/kustomization.yaml
- components/kyverno/production/empty-base/namespace.yaml
- components/kyverno/production/kflux-prd-rh02/job_resources.yaml
- components/kyverno/production/kflux-prd-rh02/kustomization.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-generator.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
This PR deploys kyverno in production cluster rh02
Dependencies:
> kyverno: release in prod rh02

- argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
- components/konflux-ui/production/kflux-ocp-p01/add-service-certs-patch.yaml
- components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/production/kflux-ocp-p01/dex-config.yaml
- components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
- components/konflux-ui/production/kflux-ocp-p01/oauth2-proxy-args-patch.yaml
- components/konflux-ui/production/kflux-ocp-p01/remove-run-as-user-proxy-patch.yaml
- components/konflux-ui/production/kflux-ocp-p01/set-hostname.yaml
- components/konflux-ui/production/kflux-ocp-p01/set-redirect-uri.yaml
- components/konflux-ui/production/kflux-ocp-p01/set-replicas-patch.yaml
Adds konflux-ui to the internal production cluster `kflux-ocp-p01`.
> add konflux-ui to kflux-ocp-p01

- components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
> konflux-ui: add dex secret genetor job to stg-rh01

- components/konflux-ui/staging/stone-stg-rh01/base/dex/dex.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/dex/kustomization.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/kustomization.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/proxy/kustomization.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/proxy/nginx.conf
- components/konflux-ui/staging/stone-stg-rh01/base/proxy/proxy.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/route-and-oauth.yaml
- components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
This PR updates the stage p01 to use updated manifests from production.
Stage rh01 is not updated by this PR, to test if anything breaks in p01 first.
> konflux-ui: update stage p01 manifests to prod ones

- components/kyverno/development/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
> kyverno: unset `runAsUser` and `runAsGroup` fields in Jobs

- components/konflux-ui/production/base/kustomization.yaml
- components/konflux-ui/production/base/proxy/proxy.yaml
- components/konflux-ui/staging/base/kustomization.yaml
- components/konflux-ui/staging/base/proxy/proxy.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/kustomization.yaml
- components/konflux-ui/staging/stone-stg-rh01/base/proxy/proxy.yaml
I'm trying to pull in https://github.com/konflux-ci/workspace-manager/pull/123
> Update workspace manager to latest

- components/kyverno/production/stone-prd-rh01/job_resources.yaml
- components/kyverno/production/stone-prd-rh01/kustomization.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Configuration is a copy of kflux-prd-rh02, since there's nothing specific to that cluster in its configuration.
> add kyverno to stone-prd-rh01

- components/kyverno/production/stone-prod-p01/job_resources.yaml
- components/kyverno/production/stone-prod-p01/kustomization.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
Configuration is a copy of stone-prd-rh01.
> add kyverno to stone-prod-p01

- components/kyverno/production/stone-prod-p02/job_resources.yaml
- components/kyverno/production/stone-prod-p02/kustomization.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
> rollout kyverno to prod p02

- components/vector-tekton-logs-collector/production/vector-helm-generator.yaml
- components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Upgrade Vector version and configuration to match staging.
> Upgrade and optimize Vector Results

- components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
> fix konflux-ui stg rh01

- components/konflux-ui/staging/base/proxy/nginx.conf
> konfluxui: deprecate workspaces endpoints

- components/konflux-ui/staging/base/proxy/nginx.conf
> konflux-ui: fix tekton enpoint in stage

- components/ui/development/kustomization.yaml
- components/ui/production/kflux-ocp-p01/kustomization.yaml
- components/ui/production/stone-prod-p01/kustomization.yaml
- components/ui/production/stone-prod-p02/kustomization.yaml
- components/ui/staging/kustomization.yaml
Repository: openshift/hac-dev
Changes between c77c78a and 61fc5b4
- openshift/hac-dev#1039 feat([KFLUXUI-326](https://issues.redhat.com//browse/KFLUXUI-326)): get partial data for tekton records by @testcara [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1039))
- openshift/hac-dev#1038 fix: remove absolute position style from hac dev wrapper by @sahil143 [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1038))
- openshift/hac-dev#1040 chore([KFLUXVNGD-222](https://issues.redhat.com//browse/KFLUXVNGD-222)): add tekton-bundle-builder pipeline to ui by @avi-biton [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1040))
> fix: deploy partial data fetch for pipeline runs

- components/vector-tekton-logs-collector/development/vector-helm-values.yaml
- components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
This sets the dev/stage values to the values of prod.
> Bump Vector S3 batch max bytes

- components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
> konfluxui: restart deployments on secret update

- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Kyverno Background Controller gets OOMKilled, let's give it more resources.
> kyverno: increase resources in staging

- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
> fix kyverno config in staging

- components/integration/development/kustomization.yaml
- components/integration/development/manager_resources_patch.yaml
- components/integration/production/base/kustomization.yaml
- components/integration/production/base/manager_resources_patch.yaml
- components/integration/staging/base/kustomization.yaml
- components/integration/staging/base/manager_resources_patch.yaml
* add github application config to integration-config
> feat(STONEINTG-569): add github application config to integration-config

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
This Pull Request will enable etcd defrag config for public production clusters and internal staging clusters.
Related Pull Requests -
- https://github.com/redhat-appstudio/infra-deployments/pull/5670
- https://github.com/redhat-appstudio/infra-deployments/pull/5732
- https://github.com/redhat-appstudio/infra-deployments/pull/5781
> KFLUXINFRA-1269: Enable ETCD Defrag Config

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
This commit updates the production MPC components with part 1 of the MPC code cleanup.
> Update prod MPC w/ code cleanup changes

- components/multi-platform-controller/base/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/420
- https://github.com/konflux-ci/multi-platform-controller/pull/419
- https://github.com/konflux-ci/multi-platform-controller/pull/418
> Test MPC code cleanup part 2 changes

- components/namespace-lister/production/base/kustomization.yaml
> nslister: promote label policy to production

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#5835
> Revert "Update prod MPC w/ code cleanup changes"

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Kyverno's background controller is getting OOMKilled. This change gives it more resources
> kyverno: more resources to background controller in prod

- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
> ensure kyverno has Guaranteed QoS in staging

- components/release/development/kustomization.yaml
- components/release/production/kustomization.yaml
- components/release/staging/kustomization.yaml
Included PRs:
**production**
- https://github.com/konflux-ci/release-service/pull/684
- https://github.com/konflux-ci/release-service/pull/693
- https://github.com/konflux-ci/release-service/pull/696
- https://github.com/konflux-ci/release-service/pull/697
- https://github.com/konflux-ci/release-service/pull/694
- https://github.com/konflux-ci/release-service/pull/691
- https://github.com/konflux-ci/release-service/pull/689
- https://github.com/konflux-ci/release-service/pull/686
- https://github.com/konflux-ci/release-service/pull/671
- https://github.com/konflux-ci/release-service/pull/680
- https://github.com/konflux-ci/release-service/pull/679
- https://github.com/konflux-ci/release-service/pull/678
- https://github.com/konflux-ci/release-service/pull/675
- …
> feat: release-service update

- components/konflux-ui/staging/base/proxy/proxy.yaml
- components/namespace-lister/base/kustomization.yaml
- components/namespace-lister/base/patches/with_header_auth_groups.yaml
- **bump namespace-lister version**
- **configure the proxy to set the impersonate-group header**
> nslister-ui: add group support in staging

- components/konflux-ui/staging/base/proxy/proxy.yaml
> konfluxui: fix proxy permissions on staging clusters

- components/multi-platform-controller/base/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/430
- https://github.com/konflux-ci/multi-platform-controller/pull/429
- https://github.com/konflux-ci/multi-platform-controller/pull/428
- https://github.com/konflux-ci/multi-platform-controller/pull/412
> MPC Staging clusters update

- components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
- components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
- components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
> konfluxui: restart dex on secret change in prod

- components/konflux-ui/production/base/proxy/proxy.yaml
- components/namespace-lister/production/base/kustomization.yaml
- components/namespace-lister/production/base/patches/with_header_auth_groups.yaml
This releases groups support in namespace-lister and in UI's proxy.
> bump namespace-lister in production

- components/konflux-ui/production/base/proxy/nginx.conf
- components/namespace-lister/production/base/patches/with-header-auth-email.yaml
- components/namespace-lister/production/base/patches/with_header_auth_groups.yaml
> namespace-lister: fix prod configuration

- components/konflux-ui/production/base/proxy/nginx.conf
> konfluxui: rollback x-user header value in prod

- components/repository-validator/production/kustomization.yaml
See https://github.com/redhat-appstudio/internal-infra-deployments/pull/11
> Update repository validator w/ new allow list

- components/authentication/base/everyone-can-view.yaml
> remove rights on workspaces CRs from everyone-can-view

- components/integration/staging/stone-stage-rh01/kustomization.yaml
Fix the integration /stage kustomization path and namespace patch
> fix(STONEINTG-1137): fix kubearchiveconfig kustomization

- components/konflux-ui/production/base/proxy/proxy.yaml
- components/konflux-ui/staging/base/proxy/proxy.yaml
> konfluxui: allow proxy to only impersonate the system:authenticated group

- components/repository-validator/production/kustomization.yaml
See https://github.com/redhat-appstudio/internal-infra-deployments/pull/11
> Update prod repository validator w/ new allow list

- components/multi-platform-controller/production-downstream/stone-prod-p01/external-secrets.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p01/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/430
- https://github.com/konflux-ci/multi-platform-controller/pull/429
- https://github.com/konflux-ci/multi-platform-controller/pull/428
- https://github.com/konflux-ci/multi-platform-controller/pull/420
- https://github.com/konflux-ci/multi-platform-controller/pull/419
- https://github.com/konflux-ci/multi-platform-controller/pull/418
- https://github.com/konflux-ci/multi-platform-controller/pull/417
- https://github.com/konflux-ci/multi-platform-controller/pull/416
- https://github.com/konflux-ci/multi-platform-controller/pull/415
- https://github.com/konflux-ci/multi-platform-controller/pull/412
> Update prod MPC w/ part 2 code cleanup

- components/multi-platform-controller/staging-downstream/host-config.yaml
Add new VMs size to dynamic-platforms and add 2 more flavors.
> Add new PPC VMs to dynamic-platforms

- argo-cd-apps/overlays/development/delete-applications.yaml
- configs/etcd-defrag/base/role-binding.yaml
This Pull Request will create a role bidning for `openshift-etcd` namespace, which requires to create a debug pod.
> Fix Role Binding

- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/stone-prd-m01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
> Update Konflux Openshift Pipelines nightly release

- components/konflux-ui/staging/base/proxy/nginx.conf
remove deprecated endpoints and unused headers
requires 
> konfluxui: clean proxy's configuration

- components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/430
- https://github.com/konflux-ci/multi-platform-controller/pull/429
- https://github.com/konflux-ci/multi-platform-controller/pull/428
- https://github.com/konflux-ci/multi-platform-controller/pull/420
- https://github.com/konflux-ci/multi-platform-controller/pull/419
- https://github.com/konflux-ci/multi-platform-controller/pull/418
- https://github.com/konflux-ci/multi-platform-controller/pull/417
- https://github.com/konflux-ci/multi-platform-controller/pull/416
- https://github.com/konflux-ci/multi-platform-controller/pull/415
- https://github.com/konflux-ci/multi-platform-controller/pull/412
> Update prod-p02 MPC w/ code cleanup

- components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
- components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
This PR aligns the new konflux users Roles with the already existing ones.
> align konflux users permissions in staging

- components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/multi-platform-controller/pull/430
- https://github.com/konflux-ci/multi-platform-controller/pull/429
- https://github.com/konflux-ci/multi-platform-controller/pull/428
- https://github.com/konflux-ci/multi-platform-controller/pull/420
- https://github.com/konflux-ci/multi-platform-controller/pull/419
- https://github.com/konflux-ci/multi-platform-controller/pull/418
- https://github.com/konflux-ci/multi-platform-controller/pull/417
- https://github.com/konflux-ci/multi-platform-controller/pull/416
- https://github.com/konflux-ci/multi-platform-controller/pull/415
- https://github.com/konflux-ci/multi-platform-controller/pull/412
> Update prd-rh02 MPC w/ code cleanup (#5968)

- components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
- components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
- components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
> align konflux users permissions in production

- components/multi-platform-controller/staging-downstream/host-config.yaml
With this one, we have the 200Gb flavors of all the VMs.
> Add one more ppc flavor in staging

- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
This Pull Request will deploy thye etcd custom solution to the internal production clusters
- prd-p01
- prd-p02
- ocp-p01
> ETCD Changes for Konflux Internal Environment

- components/konflux-ui/production/base/proxy/nginx.conf
> update endpoint for tekton-results in production

- components/kubearchive/base/kubearchive-config.yaml
We want to start archiving Pipelines to have some usage and discover issues.
> KubeArchive: archive PipelineRuns

- components/multi-platform-controller/staging-downstream/host-config.yaml
Create a various flavors of PPC machine, similar to what we have for amd, arm and ppc.
> Create new flavors of s390x in internal staging

- components/kubearchive/base/kubearchive-config.yaml
We want to store Releases as well as Snapshots.
cc @kasemAlem
> KubeArchive: store Releases

- components/release/development/release_service_config.yaml
- needed for [RELEASE-1479](https://issues.redhat.com//browse/RELEASE-1479)
> add emptyDir config to devel layer

- argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
- argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#5919
> Revert "Temporarily disable sync of kubearchive application"

- components/multi-platform-controller/base/kustomization.yaml
Included PRs:
* https://github.com/konflux-ci/multi-platform-controller/pull/409
* https://github.com/konflux-ci/multi-platform-controller/pull/413
* https://github.com/konflux-ci/multi-platform-controller/pull/426
* https://github.com/konflux-ci/multi-platform-controller/pull/431
* https://github.com/konflux-ci/multi-platform-controller/pull/433
* https://github.com/konflux-ci/multi-platform-controller/pull/434
* https://github.com/konflux-ci/multi-platform-controller/pull/436
> Update staging MPCs w/ more code cleanup

- components/namespace-lister/base/deployment.yaml
- components/namespace-lister/production/base/deployment.yaml
> ensure namespace-lister has Guaranteed QoS

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Expose node CPU seconds while non-idle.
> Export non-idle cpu seconds total

- components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
- components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
> disable dex/proxy's secrets generator job in staging

- components/smee-client/base/deployment.yaml
pod on crashloop state, removing livenessprobe
> removing livenessprobe

- components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Add tekton-bundle-builder-oci-ta pipeline to build configmap
> chore(KFLUXVNGD-240): add tekton-bundle-builder-oci-ta to config

- components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
- components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Reverts redhat-appstudio/infra-deployments#6053
> Revert "Allow 70ppc VMs with default profile"

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
> Export total running pipelinerun count

- components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Included PRs:
* https://github.com/konflux-ci/multi-platform-controller/pull/426
* https://github.com/konflux-ci/multi-platform-controller/pull/431
* https://github.com/konflux-ci/multi-platform-controller/pull/434
* https://github.com/konflux-ci/multi-platform-controller/pull/413
* https://github.com/konflux-ci/multi-platform-controller/pull/433
* https://github.com/konflux-ci/multi-platform-controller/pull/409
* https://github.com/konflux-ci/multi-platform-controller/pull/436
* https://github.com/konflux-ci/multi-platform-controller/pull/437
* https://github.com/konflux-ci/multi-platform-controller/pull/435
* https://github.com/konflux-ci/multi-platform-controller/pull/425
* https://github.com/konflux-ci/multi-platform-controller/pull/410
* …
> Update stone-prod-p02's MPC w/ capacity checking

- components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-appstudio-pipeline-clusterrole.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-rolebinding.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-rolebinding.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-rolebinding-appstudio-runner.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
> fix clusterrole in bootstrap tenant policy

- components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
> promote pipeline-runner sa policy to prod-p02

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
> bump kyverno resources in production

- components/smee/base/deployment.yaml
Adding livenessProbe for smee server, based on jira request https://issues.redhat.com/browse/SPRE-1255 
Solution has been tested locally and it works correctly.
> Adding liveness Probe for sme server

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-generator.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-generator.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-generator.yaml
> bump kyverno to 3.3.7 in production

- components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
- components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
- components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
- components/konflux-ui/production/stone-prod-p01/kustomization.yaml
- components/konflux-ui/production/stone-prod-p02/kustomization.yaml
> disable dex/proxy's secrets generator job in production

- components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
> use new UI in PaC custom console urls in staging

- components/konflux-rbac/production/base/kustomization.yaml
- components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
- components/konflux-rbac/staging/base/kustomization.yaml
- components/konflux-rbac/staging/stone-stage-p01/kustomization.yaml
- components/konflux-rbac/staging/stone-stg-rh01/kustomization.yaml
> rollout pipeline sa rolebinding policy to all clusters

- components/konflux-ui/production/base/kustomization.yaml
Repository: konflux-ci/konflux-ui
Changes between d0c7c50 and ae827c9
- konflux-ci/konflux-ui#197 [KFLUXUI-375](https://issues.redhat.com//browse/KFLUXUI-375) - [Snapshots Details Page] Fix: handle nullable 'labels' field by @rrosatti [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/197))
- konflux-ci/konflux-ui#158 fix(release): update cve modal by @abhinandan13jan [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/158))
- konflux-ci/konflux-ui#194 fix([KONFLUX-5814](https://issues.redhat.com//browse/KONFLUX-5814)): fixed strings overflow to other tab by @janaki29 [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/194))
- konflux-ci/konflux-ui#190 fix([KONFLUX-5796](https://issues.redhat.com//browse/KONFLUX-5796)): the nudging should be enabled for app has a single …
> Promote konflux-ui to prod

- components/mintmaker/base/kustomization.yaml
- components/mintmaker/development/kustomization.yaml
- components/mintmaker/staging/base/kustomization.yaml
Stage deployment was sucessful
> Deploy Redis for MintMaker to production

- components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Included Changes:
* https://github.com/konflux-ci/multi-platform-controller/pull/449
* https://github.com/konflux-ci/multi-platform-controller/pull/450
* https://github.com/konflux-ci/multi-platform-controller/pull/451
* https://github.com/konflux-ci/multi-platform-controller/pull/438
* https://github.com/konflux-ci/multi-platform-controller/pull/453
> Update prod-p02 MPC

- components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Need to get to commit 8cbcdd4a49ec9dba5d738b46b84d0c2a5d438f91
Included Changes:
* https://github.com/konflux-ci/multi-platform-controller/pull/449
* https://github.com/konflux-ci/multi-platform-controller/pull/450
* https://github.com/konflux-ci/multi-platform-controller/pull/451
* https://github.com/konflux-ci/multi-platform-controller/pull/438
* https://github.com/konflux-ci/multi-platform-controller/pull/453
> Update MPC on prod-p02

- components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Missing host-config file
Included Changes:
* https://github.com/konflux-ci/multi-platform-controller/pull/449
* https://github.com/konflux-ci/multi-platform-controller/pull/450
* https://github.com/konflux-ci/multi-platform-controller/pull/451
* https://github.com/konflux-ci/multi-platform-controller/pull/438
* https://github.com/konflux-ci/multi-platform-controller/pull/453
> Fix MPC on prod-p02

- components/integration/production/base/kustomization.yaml
- components/integration/production/kflux-ocp-p01/console-url-config-patch.json
- components/integration/production/stone-prod-p01/console-url-config-patch.json
- components/integration/production/stone-prod-p02/console-url-config-patch.json
- components/integration/staging/base/kustomization.yaml
- components/integration/staging/stone-stage-p01/console-url-config-patch.json
> update console urls in integration component

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
exported metric has typo - fix pluralizes pipelineruns
> fix-up(PVO11Y-4681): Fix typo - pipelinerun -> pipelineruns

- components/konflux-ui/production/base/kustomization.yaml
Repository: konflux-ci/konflux-ui
Changes between 43848ce6 and 9d564af9
- konflux-ci/konflux-ui#209  feat([KFLUXUI-416](https://issues.redhat.com//browse/KFLUXUI-416)): add secret link option and component selector by @testcara [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/209))
- konflux-ci/konflux-ui#208 fix: add filter for no beta taskrun by @JoaoPedroPP [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/208))
- konflux-ci/konflux-ui#218 fix: uploading test results to Sealights by @psturc [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/218))
- konflux-ci/konflux-ui#196 test: onboard Sealights for PR and periodic testing by @psturc [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/196))
> chore: promote konflux-ui

- components/multi-platform-controller/production/kflux-prd-rh02/external-secrets.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
We have a networking issue with the static ones from br-sao so try one from jp-tok to see if we have same issue there.
> Add one s390x static machine to rh02 from Tokyo DC

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
This exposes the ETCD MVCC DB defragmentation in progress.
> Expose etcd_disk_defrag_inflight for cluster capacity monitoring

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Update Tekton Results to the v0.14.0-3 downstream version.
> Update Results v0.14.0-3 staging

- components/multi-platform-controller/production/kflux-prd-rh03/external-secrets.yaml
- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
This is first VM in ca-tor region to test build performance in Toronto, a follow up change will add all other VMs if first one works.
[KFLUXINFRA-1541](https://issues.redhat.com//browse/KFLUXINFRA-1541)
> Add first static s390x VM to rh03

- components/konflux-rbac/policies/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
- components/konflux-rbac/policies/validate-rolebindings/invalid-subjects.yaml
> optimize kyverno policies

- components/konflux-rbac/production/base/kustomization.yaml
> promote restrict-binding-system-authenticated Policy to prod

- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
[KFLUXINFRA-1506](https://issues.redhat.com/browse/KFLUXINFRA-1506): Updated AWS security group and subnet fields to match those in the RH03 AWS account and configured 2 static IBM VMs for testing the IBM multi-arch builds.
> Update rh03 host config

- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
[KFLUXINFRA-1506](https://issues.redhat.com/browse/KFLUXINFRA-1506)
> Fix security group on rh03

- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
[KFLUXINFRA-1506](https://issues.redhat.com//browse/KFLUXINFRA-1506)
> Add s390x static VMs to rh03

- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
[KFLUXINFRA-1506](https://issues.redhat.com/browse/KFLUXINFRA-1506)
> Fix AWS key name for all AWS architectures

- components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
[KFLUXINFRA-1542](https://issues.redhat.com//browse/KFLUXINFRA-1542)
> Add all remaining rh01 ppc VMs

- components/mintmaker/staging/base/kustomization.yaml
The automated PR wasn't created
> Bump mintmaker on stage

- components/etcd-shield/base/etcd_shield_alerts.yaml
- components/etcd-shield/production/base/etcd_shield_alerts.yaml
Lower trigger thresholds from 95% to 85% and release thresholds from 85% to 75%.
> etcd-shield: lower trigger thresholds

- components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
> disable KubeSaw's autoapproval for prod rh01

- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-resources.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-resources.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-configmap_trusted-ca.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-console-namespaces.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-olm-namespaces.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-openshift-ingress.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-openshift-monitoring.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-same-namespace.yml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
> promote bootstrap-tenant-namespace policy to prod

- components/kubearchive/base/kubearchive-config.yaml
- components/kubearchive/base/kubearchive-maintainer.yaml
- components/kubearchive/base/kustomization.yaml
* Update to fix an error that made KubeArchive not work at all.
* Changed global KubeArchiveConfig to ClusterKubeArchiveConfig
* Removed unnecessary patches
> Update KubeArchive to fix an error

- components/monitoring/grafana/staging/kustomization.yaml
This is to test out the [changes made to the building of o11y/exporters](https://github.com/redhat-appstudio/o11y/pull/576)
> update o11y dsexporter in stage

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- Include new cpu label to improve cluster cpu usage overview.
> fix(PVO11Y-4776): Include new cpu label

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
The VM needed to be recreated, former one was not booting anymore. Also delete commented out configurations.
> Replace static-1 ppc machine on ocp-p01 cluster

- components/multi-platform-controller/staging-downstream/external-secrets.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
[KFLUXINFRA-1581](https://issues.redhat.com/browse/KFLUXINFRA-1581)
> Update stage-p01 to use IBM stage account s390x VM

- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Kyverno is requiring more resources on rh01.
> bump resources for kyverno

- components/multi-platform-controller/staging-downstream/external-secrets.yaml
- components/multi-platform-controller/staging-downstream/host-config.yaml
[KFLUXINFRA-1581](https://issues.redhat.com/browse/KFLUXINFRA-1581)
> Update stage-p01 to use IBM stage account PPC VM

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- Include etcd-shield metric
- Include metrics to measure impact with API server rejection webhook metrics
- Include kube node to identify cluster master and infra nodes.
> feat(PVO11Y-4784): Include new etcd-shield related metrics

- hack/new-cluster/tasks/components.yaml
This should fix an error reported by Manish.
> Ensure directory is present in new-cluster playbook

- components/cost-management/base/kustomization.yaml
To reduce pressure on rh01, we want to remove this non-core policy
> disable cost-management policies

- components/kyverno/development/kyverno-helm-values.yaml
> kyverno cleanup configuration for dev

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- Include new API server metrics and labels.
> feat(SPRE-1489): API server metrics

- components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-networkpolicies-clusterpolicy.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
- components/konflux-rbac/policies/bootstrap-tenant-namespace/kustomization.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-networkpolicies-clusterpolicy.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
- components/konflux-rbac/production/policies/bootstrap-tenant-namespace/kustomization.yaml
at our scale it reaches the etcd's maximum size on UpdateRequests
Requires:
> split bootstrap-tenant-namespace in two in prod

- components/pulp-access-controller/base/kustomization.yaml
Refreshing the cluster role of pulp access controller
> refresh pulp access controller

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
At our scale Kyverno Reports is putting too much pressure on the APIServer.
Requires:
> disable kyverno reports in prod

- components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml
changes:
- new service and deployment names
> chore: update kanary exporter

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
- components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
removes cpu limits as they are not needed
> kyverno remove cpu limits in prod

- components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml
- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Spun up from [this conversation](https://github.com/redhat-appstudio/o11y/pull/587#discussion_r2135254213)
Issue: [PVO11Y-4802](https://issues.redhat.com/browse/PVO11Y-4802)
> PVO11Y-4802: Kanary label change and appending label to prometheus whitelist

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
- Update api server metrics and reduce apiserver_request_total labels.
> fix(SPRE-1489): Update API Server metrics

- components/kubearchive/base/kustomization.yaml
- components/kubearchive/base/migration-job.yaml
Automate the SQL migrations of KubeArchive using a job and a PreSync hook. Related thread: https://redhat-internal.slack.com/archives/C04F4NE15U1/p1748869924759329
> KubeArchive: Job to automate SQL migrations

- components/kyverno/development/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
> fix kyverno admission leader election retry period in dev and stg

- components/kyverno/production/kflux-ocp-p01/kustomization.yaml
- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kustomization.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh03/kustomization.yaml
- components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
- components/kyverno/production/kflux-rhel-p01/kustomization.yaml
- components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kustomization.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kustomization.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kustomization.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
follow-up to https://github.com/redhat-appstudio/infra-deployments/pull/6402
> disable remove-configmap job in prod

- argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
- components/cert-manager/staging/base/kustomization.yaml
- components/cert-manager/staging/base/operator.yaml
- components/cert-manager/staging/stone-stg-rh01/kustomization.yaml
- components/kueue/staging/base/kueue-external-admission/kustomization.yaml
- components/kueue/staging/base/kueue-external-admission/monitoring.yaml
- components/kueue/staging/base/kueue/kueue.yaml
- components/kueue/staging/base/kueue/kustomization.yaml
- components/kueue/staging/base/kueue/operator.yaml
- components/kueue/staging/base/kustomization.yaml
- components/kueue/staging/base/queue-config/cluster-policy.yaml
- components/kueue/staging/base/queue-config/cluster-queue.yaml
- components/kueue/staging/base/queue-config/kustomization.yaml
- components/kueue/staging/base/queue-config/kyverno-rbac.yaml
- components/kueue/staging/base/tekton-kueue-monitoring/kustomization.yaml
- components/kueue/staging/base/tekton-kueue-monitoring/monitoring.yaml
- components/kueue/staging/base/tekton-kueue/controller-patch.yaml
- components/kueue/staging/base/tekton-kueue/kustomization.yaml
- components/kueue/staging/base/tekton-kueue/webhook-patch.yaml
- components/kueue/staging/stone-stg-rh01/kustomization.yaml
All of the content was copied from the development overlays.
I added patches the configure multi replica deployment for the tekton-kueue controller and webhook.
> KFLUXINFRA-1768: Deploy Kueue and CertManager to stone-stg-rh01

- components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
In https://github.com/konflux-ci/konflux-ui/pull/114, support was added for displaying pipeline descriptions but we never added them to the ConfigMap. Adding those descriptions so that we can start to display them.
Additionally, adding another property with slightly more detail about the pipelines. While the UI doesn't currently support displaying this, the imformation is still helpful. We might be able to add support for displaying this information in the future.
> Add pipeline descriptions and details

- components/authentication/base/konflux-admins.yaml
> give konflux admins permission over Kueue's CRs

- components/pulp-access-controller/production/kustomization.yaml
- components/pulp-access-controller/staging/kustomization.yaml
Refresh the pulp access controller to newer version.
> refresh the pulp access controller

- argo-cd-apps/base/member/infra-deployments/policies/policies.yaml
> enable policies component

- components/policies/OWNERS
> add OWNERS file for policies component

- components/kubearchive/README.md
- components/kubearchive/development/kustomization.yaml
* Upgrade development, which upgrades staging as well.
> KubeArchive: upgrade to v1.1.0

- components/kubearchive/base/migration-job.yaml
* The Job is failing to be updated, this will probably helps.
> KubeArchive: migration Job force replacement

- components/knative-eventing/production/base/kustomization.yaml
* Update Knative Eventing to a newer version.
* Increase memory for IMC Controller.
> Knative Eventing: update production version

- components/release/development/release_service_config.yaml
- for push-artifacts-to-cdn pipeline
> feat(RELEASE-1596): enable emptyDir for push-artifacts-to-cdn

- components/pipeline-service/production/base/update-tekton-config-pac.yaml
- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
- components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
- components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
- components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
Tested in staging here: https://github.com/redhat-appstudio/infra-deployments/pull/6812
> Enable multi-repo Github App token scoping in pipelines production 

- components/smee-client/staging/deployment.yaml
- components/smee/staging/deployment.yaml
The image needs to be updated for server and client at the same time.
> chore: update gosmee image in staging

- components/policies/development/kustomization.yaml
> disable cost-management policy in development

- components/repository-validator/production/kustomization.yaml
[KFLUXSPRT-3933](https://issues.redhat.com//browse/KFLUXSPRT-3933)
> Allow ansible-automation-platform-azure-billing-operator

- components/smee-client/staging/deployment.yaml
- components/smee-client/staging/kustomization.yaml
- components/smee/staging/deployment.yaml
- components/smee/staging/kustomization.yaml
This is to later allow the image to be updated during release scripts
> chore: reference smee sidecar by tag

- components/kubearchive/production/stone-prod-p02/kustomization.yaml
Promote the kubearchive version already deployed
in staging.
Also, enable impersonation to fix
the access of the UI through nginx.
> Upgrade to KubeArchive v1.2.0

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
- components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Expands Kyverno metrics scraping to Production environments.
This PR follows up on #6792. Following its approval and successful verification of Kyverno metrics scraping in non-production environments (Grafana and OpenShift), we are now extending this configuration to our production systems.
> scrape kyverno metrics in prod

- components/authentication/base/konflux-admins.yaml
> Konflux admin update

- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Increase to 2000 to unblock things and allow us to investigate why we reached the max, which was 1000.
> Increase kyverno UpdateRequests in p02

- components/authentication/base/konflux-admins.yaml
- Fix API  group of flow control.
> fix(SPRE-1522): Fix API group access to APF

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
This update includes a feature to disable storing of incomplete PipelineRuns and TaskRuns aiming to reduce the calls on the k8s API server, decrease the workqueue size and improve the overal performance.
> Update Tekton Results v0.15.2-1 staging

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
Reverts redhat-appstudio/infra-deployments#7042
> Revert "update downstream prod with a recent MPC bugfix"

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Set the values as the chains controller.
> Set the qps and burst for Results watcher

- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/kflux-osp-p01/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
- components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
We are hitting the ceiling, so bumping this up.
> Increase Tekton Results Watcher CPU resources

- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
we want every kyverno's pod to be assigned with Guaranteed QoS.
> ensure kyverno has Guaranteed QoS in stg

- components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
- components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
we want every kyverno's pod to be assigned with Guaranteed QoS.
> ensure kyverno admission controller has Guaranteed QoS in stg

- components/integration/development/kustomization.yaml
- components/integration/staging/base/kustomization.yaml
Promote integration-service in stage in order to fix bug blocking ITS creation
> chore: integration-service update

- components/policies/development/integration/OWNERS
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-konflux-integration-runner-clusterrole.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/expected-integration-rolebinding.yaml
- components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/expected-integration-serviceaccount.yaml
- components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
- components/policies/development/integration/bootstrap-namespace/kustomization.yaml
- components/policies/development/integration/bootstrap-namespace/kyverno-rbac.yaml
- components/policies/development/integration/kustomization.yaml
- components/policies/development/kustomization.yaml
- components/policies/staging/base/integration/kustomization.yaml
Deploying to all dev and staging clusters.
Assisted-by: cursor(claude-3.5-sonnet)
> ClusterPolicy to deploy integration resources to tenants

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Adding some labels so we can pass enough information so the histograms are well constructed.
> KubeArchive: add labels for histograms

- components/pipeline-service/development/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Changes:
```
_        __  __
_| |_   _ / _|/ _|  between before.json
/ _' | | | | |_| |_       and after.json
| (_| | |_| |  _|  _|
\__,_|\__, |_| |_|   returned 59 differences
|___/
images.pipelines-cache-rhel9.downstream_commit
± value change
- 5b9a93bf7e2d0cbd4819e1505dcc9af8cdee022e
+ 5c48a03161ee212643190281a9c1d96c3fc926e2
images.pipelines-cache-rhel9.image
± value change
- quay.io/openshift-pipeline/pipelines-cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
+ quay.io/openshift-pipeline/pipelines-cache-rhel9@sha256:64fc67b97b5dccf057a2581293803e813f5396d582f5f59bb53c404f967a37f7
images.pipelines-console-plugin-rhel9.downstream_commit
± value change
- 53c5dece9a6b040b3593914d6314e7692ff4fbeb
+ 4d6a55726ff0c94929d3847646261d5f22f6a7c1 …
```
> Update pipelines version in dev and staging

- components/integration/OWNERS
> chore: add Nigel to the integration owners

- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
We've been asked to set the same resources in staging as in prod.
> Use same resources in stage as prod

- components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-osp-p01/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
- components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
- components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
- components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
> ensure kyverno controllers has Guaranteed Qos in prod

- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
> fix kyverno config for prd-rh01

- components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
> reduce cpu for kyverno on prod rh01

- components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/kflux-osp-p01/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
- components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
Promotes https://github.com/redhat-appstudio/infra-deployments/pull/7200 to production
Details:
```
_        __  __
_| |_   _ / _|/ _|  between before.json
/ _' | | | | |_| |_       and after.json
| (_| | |_| |  _|  _|
\__,_|\__, |_| |_|   returned 59 differences
|___/
images.pipelines-cache-rhel9.downstream_commit
± value change
- 5b9a93bf7e2d0cbd4819e1505dcc9af8cdee022e
+ 5c48a03161ee212643190281a9c1d96c3fc926e2
images.pipelines-cache-rhel9.image
± value change
- quay.io/openshift-pipeline/pipelines-cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
+ quay.io/openshift-pipeline/pipelines-cache-rhel9@sha256:64fc67b97b5dccf057a2581293803e813f5396d582f5f59bb53c404f967a37f7
images.pipelines-console-plugin-rhel9.downstream_commit
± value change
- …
```
> update pipelines version in production

- components/konflux-kite/base/rbac.yaml
Needed to view external secrets.
I added some additional comments for clarity as well.
> Update Konflux-Kite RBAC

- components/kueue/staging/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
- components/kueue/staging/base/tekton-kueue-monitoring/kustomization.yaml
- components/kueue/staging/base/tekton-kueue/kustomization.yaml
- Update image and git ref to the manifests
- Deploy alerting rules
> Promote tekton-kueue to stage

- components/konflux-ui/staging/base/proxy/proxy.yaml
This is typo fix should make the nginx proxy work
> Fix typo on the init-container logic

- argo-cd-apps/base/member/infra-deployments/cert-manager/cert-manager.yaml
- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/kustomization.yaml
- components/cert-manager/production/base/kustomization.yaml
- components/cert-manager/production/base/operator.yaml
- components/cert-manager/production/kflux-ocp-p01/kustomization.yaml
- components/cert-manager/production/kflux-osp-p01/kustomization.yaml
- components/cert-manager/production/kflux-prd-rh02/kustomization.yaml
- components/cert-manager/production/kflux-prd-rh03/kustomization.yaml
- components/cert-manager/production/stone-prod-p01/kustomization.yaml
- Deploy on all production cluster except for p02 and rh01.
- Required for deploying Kueue.
> KFLUXINFRA-2013: Deploy cert-manager partially on production

- components/kubearchive/base/migration-job.yaml
- components/kubearchive/production/kflux-prd-rh03/kustomization.yaml
We had a problem regarding passwords containing invalid URL characters on rh03, we are consolidating the fix to all the clusters.
> KubeArchive: consolidate password encoding

- components/knative-eventing/production/base/kustomization.yaml
> Eventing: increase memory for IMC

- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
We debug an issue with status check reporting
when using Kueue with PAC. The included image will provide additional logs that can help with the investigation.
> stage: Patch PAC controller image

- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
We need those images for debugging an integration issue of Kueue and PAC.
> staging: Patch PAC images

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
New metric to monitor namespace pod information
> feat(SPRE-1697) New metric

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Supplements #7414
cc @Kousalya1998
> chore(KFLUXSPRT-3661): Forward kube_deployment_spec_replicas for konflux_user_support

- components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
- components/monitoring/prometheus/staging/stone-stg-rh01/prometheus_rule_test.yaml
> feat(SPRE-1702): Test Recording Rules

- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Continue to debug the reporting to SCM issue when using Kueue and PAC.
> SRVKP-8255: Patch PAC images on stage

- components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
There was a change to the host-config, thus
the cluster queue should get updated as well.
> Update cluster queue resource for rh03

- components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
- components/pipeline-service/staging/stone-stage-p01/deploy.yaml
- components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Try to understand if the race conditions with reporting happen because of multiple replicas.
> SRVKP-8255: Run one PAC watcher replica

- components/konflux-info/README.md
- components/konflux-info/banner-schema.json
As the subject.
It is for  https://issues.redhat.com/browse/KFLUXUI-587
> improve the banner readme

- components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
jira: [CWFHEALTH-4347](https://issues.redhat.com//browse/CWFHEALTH-4347)
> Mintmaker redis memory usage added

- components/internal-services/OWNERS
Updates OWNER file to add new members
> chore(): update internal-service OWNERS for new members

- components/konflux-kite/OWNERS
Adding more devs to the OWNERS file so they're kept in the loop.
> Add more owners to Kite service

- components/monitoring/grafana/base/dashboards/kueue/kueue.json
- Add for tekton-kueue webhook request success rate
- Fix font and widgets size.
> KFLUXINFRA-1986: Update Kueue dashboard

- components/kueue/production/base/queue-config/mintmaker-local-queue.yaml
- components/policies/production/kflux-prd-rh02/kustomization.yaml
- components/policies/production/kflux-prd-rh03/kustomization.yaml
- components/policies/production/kflux-rhel-p01/kustomization.yaml
- components/policies/production/policies/kueue/kustomization.yaml
- components/policies/production/policies/kueue/queue-config/cluster-policy.yaml
- components/policies/production/policies/kueue/queue-config/kustomization.yaml
- components/policies/production/policies/kueue/queue-config/kyverno-rbac.yaml
- components/policies/production/policies/kustomization.yaml
- components/policies/production/stone-prd-rh01/kustomization.yaml
- components/policies/production/stone-prod-p01/kustomization.yaml
- components/policies/production/stone-prod-p02/kustomization.yaml
The Kueue policy will create the local queues in the mintmaker namespace and the tenant namespaces.
> KFLUXINFRA-2027: Deploy Kueue policy to production

- components/kueue/production/kflux-prd-rh02/kustomization.yaml
- components/kueue/production/kflux-prd-rh03/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh02/resources/override-pac-images.yaml
- components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh03/resources/kustomization.yaml
- components/pipeline-service/production/kflux-prd-rh03/resources/override-pac-images.yaml
- Enable queuing for all pipelineruns on rh02 and rh03
- update PAC image on rh02 and rh03. The images contain a fix required for enabling Kueue on all pipelineruns.
> Update PAC image on rh02 and rh03 & Enable queuing for all pipelineruns on rh02 and rh03

- components/kubearchive/development/kustomization.yaml
- components/kubearchive/development/release-vacuum.yaml
- components/kubearchive/development/vacuum.yaml
This version includes improvements in the message handling and improvements in tracing.
> KubeArchive: upgrade staging to v1.6.0

- components/monitoring/grafana/base/dashboards/kueue/kueue.json
Fixes [KFLUXINFRA-2069](https://issues.redhat.com//browse/KFLUXINFRA-2069) and followup to
http://github.com/redhat-appstudio/o11y/pull/740
> Update Kueue dashboard

- components/konflux-kite/base/kustomization.yaml
This release should include the latest changes from https://github.com/konflux-ci/kite/pull/101 .
> feat(update): Update kite SHA tag

- components/mintmaker/OWNERS
removed lucie and added Hozifa
> Modified owners

- components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
- components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/kyverno_rbac.yaml
- components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/validate-restrict-binding-system-authenticated-releng-clusterpolicy.yaml
> fix name of ClusterPolicy in stg

- components/monitoring/prometheus/production/base/monitoringstack/kustomization.yaml
- components/monitoring/prometheus/production/base/monitoringstack/prometheusrule-uwm.yaml
-  Promote uwm recording rules to prod
> feat(SPRE-1818): Include uwm recording rules in prod

- components/multi-platform-controller/OWNERS
> Align MPC approvers/reviewers to reflect actual state

- components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Since we are uploading a lot of metrics lately, this might be tricky to idenfity sometimes which are there and not. I have reorganisez all metrics based on pod, containers, etc...for a better management and visualization.
Doing stage first to ensure nothing changes (shouldnt be).
> Organising Stage Metrics

- components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
- Move metrics change to production
> feat(SPRE-1675): Include apiserver etcd cpu and memory metrics prod

- components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
- components/pipeline-service/production/kflux-osp-p01/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
- components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
- components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
- components/pipeline-service/production/stone-prd-rh01/deploy.yaml
- components/pipeline-service/production/stone-prod-p01/deploy.yaml
- components/pipeline-service/production/stone-prod-p02/deploy.yaml
Looks like the deploy.yaml files were modified manually, re-generate them using the script.
> Regenerate pipeline deploy files

- components/monitoring/kanary/production/stone-prod-p02/kustomization.yaml
Stage deployment successful and has been online for a while now.
This PR is to deploy it to prod.
> Deploy updated kanary supported clusters to prod

- components/tracing/otel-collector/development/otel-collector-helm-values.yaml
- components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Otel image version bump; includes prometheus exporter.  Fixes breakage.
> bump otel collector version

- components/kubearchive/production/kflux-prd-rh03/kubearchive.yaml
- components/kubearchive/production/kflux-prd-rh03/kustomization.yaml
Promoting staging changes to kflux-prd-rh03 to see how it goes. This cluster has been failing to archieve some stuff, so let's test it out.
> KubeArchive: install watchers solution on prd-rh03

- components/release/production/kustomization.yaml
Included PRs:
- https://github.com/konflux-ci/release-service/pull/822
- https://github.com/konflux-ci/release-service/pull/816
> release-service prod update

- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/rbac.yaml
> fix ingester credentials error

- components/konflux-info/production/stone-prod-p02/banner-content.yaml
Add an IBM Cloud PPC re-provisioning banner to stone-prod-p02 for August 29th 7:30AM - 10AM ET.
> Add stone-prod-p02 PPC maintenance to banner

- components/kueue/production/base/tekton-kueue/config.yaml
- components/kueue/production/base/tekton-kueue/kustomization.yaml
- components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
- components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
- components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
- components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
- components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
- components/kueue/production/pentest-p01/queue-config/cluster-queue.yaml
- components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
- components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
- components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
Includes:
https://github.com/konflux-ci/tekton-kueue/pull/93
https://github.com/konflux-ci/tekton-kueue/pull/91
[KFLUXINFRA-2161](https://issues.redhat.com//browse/KFLUXINFRA-2161)
> Promote tekton-kueue to production

- components/konflux-info/production/kflux-ocp-p01/banner-content.yaml
- components/konflux-info/production/kflux-osp-p01/banner-content.yaml
- components/konflux-info/production/kflux-prd-rh02/banner-content.yaml
- components/konflux-info/production/kflux-prd-rh03/banner-content.yaml
- components/konflux-info/production/kflux-rhel-p01/banner-content.yaml
- components/konflux-info/production/stone-prd-rh01/banner-content.yaml
- components/konflux-info/production/stone-prod-p01/banner-content.yaml
- components/konflux-info/production/stone-prod-p02/banner-content.yaml
- components/konflux-info/staging/stone-stage-p01/banner-content.yaml
- components/konflux-info/staging/stone-stg-rh01/banner-content.yaml
> Remove the whole new build banner

- components/multi-platform-controller/production-downstream/base/kustomization.yaml
Updating the commit reference to the latest after testing the new changes in Staging clusters.
> updating commit reference

- components/knative-eventing/production/kflux-prd-rh03/kustomization.yaml
Pushing a new change to see if it helps.
> Eventing: apply a fix on kflux-prd-rh03

- argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
- argo-cd-apps/overlays/production-downstream/delete-applications.yaml
This reverts commit 37f146494ed8342c66a0be899e7284b9ebca7ea8.
Requires:
> ensure self-provisioning is turned off by default in prod

- components/kubearchive/production/stone-prod-p02/kustomization.yaml
- components/kubearchive/staging/base/kustomization.yaml
- components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
- components/vector-kubearchive-log-collector/development/loki-helm-minio-values.yaml
- components/vector-kubearchive-log-collector/development/vector-helm-values.yaml
- components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
- components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-stg-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/vector-helm-values.yaml
> reduce number of streams for product-kubearchive-logging

- components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
- components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-stg-values.yaml
> increase loki stream rate

- components/konflux-ui/production/base/kustomization.yaml
Repository: konflux-ci/konflux-ui
Changes between e16d3ec760ad648f5fa43570bc9d5cb1c14202b0 and 4dca539d8f2812031d77822b417629e79518afb2
- konflux-ci/konflux-ui#295 feat: public view option for namespace by @brianwcook [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/295))
- konflux-ci/konflux-ui#356 feat([KFLUXUI-656](https://issues.redhat.com//browse/KFLUXUI-656)): [Logs] replace custom log viewer with PatternFly LogViewer by @rrosatti [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/356))
- konflux-ci/konflux-ui#369 feat([KFLUXUI-657](https://issues.redhat.com//browse/KFLUXUI-657)): use Kubearchive to fetch logs by @marcin-michal [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/369))
- konflux-ci/konflux-ui#371 feat(PVO11Y-4872): add card for linking to status …
> chore: bump konflux-ui (production) e16d3ec760ad...4dca539d8f28

- components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
- components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
> optimize chunk flushing to s3 to avoid slowdown error

- components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
- components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
> remove retry configuration

- components/authentication/base/everyone-can-view-patch.yaml
- components/has/base/rbac/has-admin.yaml
- components/has/base/rbac/has.yaml
- components/has/staging/rbac/has-exec.yaml
Remove the team that are not in Konflux anymore.
> Clean up old teams from everyone can view

- components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
We want to do some load tests on Konflux with KubeArchive disabled.
> KubeArchive: downscale to 0 on stage-stg-rh01 for tests

- components/squid/development/squid-helm-generator.yaml
- components/squid/staging/squid-helm-generator.yaml
> chore: update the squid image tag

- argo-cd-apps/base/member/infra-deployments/vector-kubearchive-log-collector/vector-kubearchive-log-collector.yaml
- components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/.gitignore
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/grafana-helm-generator.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/grafana-helm-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/kustomization.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-generator.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-stg-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-generator.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-stg-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-values.yaml
> KAR-615: setup log collector stone-stage-p01 config

- components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
- components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
- components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Update internal production with recent MPC version.
Contains fixes:
- https://github.com/konflux-ci/multi-platform-controller/pull/556
-  https://github.com/konflux-ci/multi-platform-controller/pull/538
- https://github.com/konflux-ci/multi-platform-controller/pull/539
and minor updates
> Update external production with recent MPC version

- argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
> product-kubearchive-logging: remove staging deletion patch

- components/monitoring/prometheus/staging/base/monitoringstack/monitoringstack-log-level.yaml
Update prometheus monitoringstack loglevel back to info
> feat(SPRE-1609): Update monitorinstack log level 

- components/cost-management/OWNERS
- components/cost-management/base/costmanagement-metrics-operator.yaml
- Upgrades the cost-management operator to the latest release.
- Adds support for capturing VM metrics collection.
> feat: update cost-management operator to latest version

- components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
> Fix operational_config in loki

- components/crossplane-control-plane/base/kustomization.yaml
Bump the Crossplane to get this new feature https://github.com/konflux-ci/crossplane-control-plane/pull/44
> Upgrade the  Crossplane Component

- components/vector-kubearchive-log-collector/production/kflux-ocp-p01/loki-helm-prod-values.yaml
- components/vector-kubearchive-log-collector/production/kflux-prd-rh03/loki-helm-prod-values.yaml
> kflux-ocp-p01, kflux-prd-rh03: increase loki grpc log chunks

- components/kubearchive/production/base/kustomization.yaml
- components/kubearchive/production/base/release-vacuum.yaml
> KubeArchive: add release vacuum to prod

- components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-stg-values.yaml
- components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-stg-values.yaml
> optimize grpc logs chunking for staging

- components/crossplane-control-plane/base/kustomization.yaml
- components/crossplane-control-plane/production/kustomization.yaml
- components/crossplane-control-plane/production/testplatform-provider-config.yaml
Production counterpart for https://github.com/redhat-appstudio/infra-deployments/pull/6449
/cc @amisstea
> Add testplatform ProviderConfig in Production

- components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
> KubeArchive: increase memory for operator on staging

- components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-values.yaml
- components/multi-platform-controller/production-downstream/kflux-osp-p01/host-values.yaml
- components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-values.yaml
- components/multi-platform-controller/production-downstream/pentest-p01/host-values.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p01/host-values.yaml
- components/multi-platform-controller/production-downstream/stone-prod-p02/host-values.yaml
- components/multi-platform-controller/production/kflux-prd-rh02/host-values.yaml
- components/multi-platform-controller/production/kflux-prd-rh03/host-values.yaml
- components/multi-platform-controller/production/stone-prd-rh01/host-values.yaml
- components/multi-platform-controller/staging-downstream/host-values.yaml
- components/multi-platform-controller/staging/host-values.yaml
User scripts cleanup as was suggested by @oswcab  in previous PRs my moving configuration
---
> MPC VM user scripts cleanup

- components/repository-validator/base/kustomization.yaml
- components/repository-validator/base/namespace.yaml
Add namespace object for repository-validator configmap
> Add namespace object for repository-validator configmap

- components/repository-validator/base/validating-admission-policy.yaml
Fixup VADP validation message to avoid compilation error
> Fixup  VADP validation message

- components/multi-platform-controller/production/kflux-prd-rh03/host-values.yaml
Partial revert of some cleanups to try to debug things
> Fixup user script of RH03 for test
