redhat-appstudio/infra-deployments

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Forgot a couple with https://github.com/redhat-appstudio/infra-deployments/pull/4159

SRVKP-4523: need both old and new tekton k8s throttle metrics available to app-sre

---

components/backup/staging/stone-stage-p01/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-host/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-m01/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-rh01/backup-s3-credentials-patch.yaml
components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
components/remote-secret-controller/overlays/staging/stone-stage-p01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/staging/stone-stg-m01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/staging/stone-stg-rh01/aws-credentials-path-patch.yaml
components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/staging/stone-stg-rh01/spi-aws-credentials-path-patch.yaml

AppSRE Team is decommissioning the `appsres05ue1` cluster and replacing it with `appsres09ue1`.
Konflux has ArgoCD Instances running on the `appsres05ue1` cluster, they have been moved over to `appsres09ue1`.
We now need to update the vault paths containing `appsres05ue1` in infra-deployments with `appsres09ue1`

KFLUXINFRA-744: Migrating Konflux Resources from appsres05ue1 to 09ue1

---

argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
argo-cd-apps/base/tenants-config/tenants-config.yaml

- as part of the migration of tenants-config from GH to Gitlab, we need to eventually delete the ApplicationSets that point to GitHub while ensuring that resources are not deleted since they are being monitored by the ArgoCD instance that is looking at Gitlab.
- this is Part 1 of 2 in the process. Simply preventing cascading deletion.
- Part 2 will be the actual deletion of the ApplicationSet

chore(RHTAPWATCH-1188): prevent cascade deletion

---

components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml

SpaceRequests cannot be provisioned unless this is enabled. The default targetClusterRole for user signup is tenant so the placementRoles on the SpaceProvisionerConfig should prevent it from being undesireably used for that flow.

Enable kflux-stg-es01 SpaceProvisionerConfig

---

argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml

- remove old tenants-config and rh-managed-workspaces-config ApplicationSets from production overlays.
- Thanks to #4243 (part 1), a cascade deletion of resources will be prevented.
- Part 3 will be the deletion of the tenants-config and rh-managed-workspaces-config resources from this repo.

chore(RHTAPWATCH-1188): part 2: rm tenants-config

---

components/pipeline-service/base/rbac/openshift-pipelines/kustomization.yaml
components/pipeline-service/base/rbac/openshift-pipelines/resolution-req-perms-exporter.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Needed for https://github.com/redhat-appstudio/infra-deployments/pull/4246 and subsequent prod bump for metrics exporter while pipeline service bump is paused for 4.15 OCP upgrade
@enarha @savitaashture @divyansh42 FYI

SRVKP-4532: add resolver crd to exporter permissions

---

components/cluster-as-a-service/base/clustertemplates.yaml

The updated chart includes a configurable timeout value.

Bump version for hypershift-aws-cluster template

---

components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml

These changes enable support for public-viewer in public staging even if the feature is not completely merged in KubeSaw. This will avoid the loop in which KubeSaw host-operator deletes the SpaceBinding for the Public-Viewer user and the Konflux-Workspaces operator is creating it back.
RegistrationService is not going to be impacted by this change until https://github.com/codeready-toolchain/registration-service/pull/453 merges.

workspaces: enable public-viewer support in public staging

---

components/multi-platform-controller/staging/host-config.yaml

Added linux-g4xlarge/amd64 dynamic platform, backed by g6.4xlarge AWS instance type.

KONFLUX-2256: multi-platform controller can spawn GPU accelerated nodes

---

components/workspaces/base/operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml
components/workspaces/base/operator/config/crd/kustomization.yaml
components/workspaces/base/operator/config/manager/kustomization.yaml
components/workspaces/base/operator/config/rbac/internalworkspace_editor_role.yaml
components/workspaces/base/operator/config/rbac/internalworkspace_viewer_role.yaml
components/workspaces/base/operator/config/rbac/role.yaml
components/workspaces/base/server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml
components/workspaces/base/server/config/crd/kustomization.yaml
components/workspaces/base/server/config/default/kustomization.yaml
components/workspaces/base/server/config/rbac/role_workspace_server_editor.yaml
components/workspaces/base/server/config/server/kustomization.yaml
components/workspaces/base/server/config/server/proxy-config/dynamic/config.yaml
components/workspaces/staging/stone-stage-p01/kustomization.yaml
components/workspaces/staging/stone-stg-host/kustomization.yaml

This release changes the group name of the resources from `konflux.io` to `konflux-ci.dev`.  A full list of release notes can be found [here].
[here]: https://github.com/konflux-workspaces/workspaces/releases/tag/v0.1.0-alpha5

update workspaces to v0.1.0-alpha5

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

This change had already been made on the UI with
https://github.com/openshift/hac-dev/pull/966, making the change in infra-deployments as well.
References: https://issues.redhat.com/browse/EC-739

Add the docker-build-oci-ta pipeline to the configmap

---

components/multi-platform-controller/production-downstream/host-config.yaml

* This PR is for managing loads in the production system where we have multiple buildpipeline running and requesting nodes.
* Also increasing the node capacity from 1CPU, 4GiB RAM ro 2CPU 8GiB ram

Increase s390x capacity for supporting more production load

---

components/pipeline-service/README.md

I could not find any doc for running `generate-deploy-config.sh` so adding it here.
This also serves as the announcement for moving off of pipeline service repo, how teams should go about getting changes to tekton config.
@enarha PTAL
@divyansh42 more fyi / education
rh-pre-commit.version: 2.3.1

SRVKP-5855: add README for update openshift pipeline related configuration

---

components/multi-platform-controller/OWNERS
components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

"linux/amd64" now runs in the cluster (If the pipeline task supports this). A few other names were given the the "local" configuration as well.
While I'm at it, refactored the string syntax for the `dynamic-platforms` config-map entry to make it more readable. Also added Hugo and Max to the OWNERS file so they can review and approve.

chore(KFLUXINFRA-743): Add "local" platform hosts

---

hack/sandbox-development-mode.sh

With [PR #1030] landing in toolchain-e2e, tests now will try to pair an open PR against toolchain-e2e with an open PR against [ksctl].  We're always going to run tests with the latest version of ksctl, so we should install it before deploying member-operator.
[PR #1030]: https://github.com/codeready-toolchain/toolchain-e2e/pull/1030
[ksctl]: https://github.com/kubesaw/ksctl/

install ksctl during kubesaw deployment

---

components/multi-platform-controller/production/host-config.yaml

This PR adds PPC64LE nodes reducing their concurrecy. This is to handle the issue of pods not getting assigned to the nodes.

KFLUXINFRA-786: Add resource pool for ppc64le in public prod

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

When deploying OSP, the operator generates a default TektonConfig is one does not already exist. This creates a race condition with the TektonConfig managed in this repo and deployed on the cluster by ArgoCD. Setting the AUTOINSTALL_COMPONENTS=false variable in the OSP Subscription, prevents the generation of the TektonConfig, so always the one from this repo is used.

Disable autogeneration of TektonConfig

---

components/multi-platform-controller/production-downstream/kustomization.yaml
components/multi-platform-controller/production/kustomization.yaml

Bump the **production** version version of multi-platform-controller.
The major change included in this version is the support for "local" platforms.
To actually use the new feature, an additional change for configuring "local" platforms would be needed.

feat(KFLUXINFRA-741): PROD: MPC w/ "local" support

---

components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

Adding the `linux-mlarge/amd64` platform as a migration path from what was previously called `linux/amd64` as that is being changed to run locally in the cluster.
For completeness sake, also adding `linux-mlarge/arm64` which is identical to the current `linux/arm64` but lets users be explicit about running in a VM.
**This change is only done in STAGE for now**

chore(KLUXINFRA-743): STAGE: Add "mlarge" platform

---

components/multi-platform-controller/production-downstream/host-config.yaml
components/multi-platform-controller/production/host-config.yaml

Adding a set of MPC platforms that use the "local" definitions.
Also adding "mlarge" platforms as a migration path away from using MPC with generic platform names as a way to run on a VM.
This change would require #4328 to work.

chore(KFLUXINFRA-743) Prod local platforms

---

argo-cd-apps/base/host/workspaces/workspaces.yaml

Workspaces is deployed in the `workspaces-system` namespace, not the `konflux-workspaces` namespace.  Update argocd's reference so that it doesn't have to manage a namespace that will never be populated.

workspaces: fix outdated namespace reference

---

components/multi-platform-controller/production-downstream/host-config.yaml

This VM has both stage and prod ssh key but the stage one is not available as a secret in the prod cluster.
This is causing the multi-platform-controller update task to fail for this node.

Fix IBM a100 ssh key

---

argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
components/tracing/otel-collector/development/otel-collector-helm-values.yaml
components/tracing/otel-collector/production/otel-collector-helm-values.yaml
components/tracing/otel-collector/staging/otel-collector-helm-values.yaml

- Moves the image to quay.io and pins it to a specific tag.
- Pins the chart to a specific version to avoid mismatches in the future.

PVCORE-4435 - Move otel image to Quay.  Pin versions of image and chart

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This should allow better distribution of the load across nodes.
This is related to:
* https://github.com/redhat-appstudio/infra-deployments/pull/4249
* https://github.com/konflux-ci/build-definitions/pull/1247

feat(KONFLUX-3985): Bump up default `requests` for task containers in Stage

---

components/release/k-components/manager-resources-patch/manager_resources_patch.yaml

this commit fixes the OOMKill happening during controller start up by increase the memory resources for the pod.

fix: release controller oomkill on start up

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

With https://github.com/konflux-ci/build-definitions/pull/1236, we started building a multi-arch pipeline. This change adds it to the config map so that it can be used for configuring components.

Add the multi-arch pipeline to the pipeline config

---

components/tracing/otel-collector/production/otel-collector-helm-values.yaml
components/tracing/otel-collector/staging/otel-collector-helm-values.yaml

Send traces via the RH Honeycomb Refinery instance to enable sampling of traces.

Send traces via honeycomb refinery for sampling purposes

---

components/pipeline-service/base/external-secrets/openshift-pipelines/chains-public-key.yaml
components/pipeline-service/base/external-secrets/openshift-pipelines/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
components/pipeline-service/production/stone-prod-p02/resources/kustomization.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-m01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-chains-public-key-path.yaml

Instead of the Job used to read the secret and create a new secret including only the public key, we now use ExternalSecret pointing to the same vault entry, but creating a secret including only the public key. This eliminates the race condition issues we had with the Job. This is also a more conformant way of managing the secret using the same ExternalSecret mechanism.
This will also make it easier to rotate the secret, updating the value in the vault will update both secrets (the one including private+public keys and the other one including only the public key).
Changes in the production kustomizations are to suppress the new ExternalSecret creation until we are ready to do the same change in production. Then we only need to remove the "delete" patches.

Replace chains public key Job by ExternalSecret

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Increase the default timeout for pipelines from
1 hours (the default) to 2 hours.
The reason is that users complained about timeouts while their pipelines were waiting for resources.

KFLUXINFRA-808: Set default pipelines timeout to 2 hours - stage

---

argo-cd-apps/overlays/production-downstream/kustomization.yaml

This is required for tenants to be able to extract secrets from those clusterstore on internal clusters.

Add cluster-secret-store-rh to internal clusters

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

As part of the deadlock alert / SOP, this will allow SRE to gather goroutine dumps so we can isolate where the deadlock is.
Been running on stage for a bit and I confirmed I can get goroutine dumps from both result api and watcher pods.
https://github.com/redhat-appstudio/infra-deployments/blob/5e89946f746273a5cee58d0753fc4cfeecec47e6/components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml#L732
https://github.com/redhat-appstudio/infra-deployments/blob/5e89946f746273a5cee58d0753fc4cfeecec47e6/components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml#L825
pprof enablement per golang is safe in production:  https://go.dev/doc/diagnostics
FYI there is an issue unfortunately with minimally tekton-pipelines-controller that I've opened and issue …

SRVKP-5900: enable pprof for results thread dumps, prod

---

components/pipeline-service/staging/stone-stg-m01/deploy.yaml

NodeSelector and Tolerations in TektonConfig schedules OpenShift Pipeline workload coming from the Pipeline Operator not the PipelineRuns and their associated TaskRuns. 
Hence, reverting the changes made to TektonConfig in `stone-sig-m01 `cluster.

KFLUXINFRA-801: reverting tekton config changes

---

argo-cd-apps/base/host/workspaces/workspaces.yaml
components/workspaces/production/stone-prd-host1/kustomization.yaml
components/workspaces/production/stone-prd-host1/route.yaml
components/workspaces/production/stone-prod-p01/kustomization.yaml
components/workspaces/production/stone-prod-p02/kustomization.yaml

Let's try this again, only without the UI components.  Those will be added in a future PR once things settle.
The intention here is to make sure that workspaces gets its `ApplicationSet` rendered correctly and comes alive.

workspaces: add production configuration

---

components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-m01/resources/tekton-config-patch.yaml

This PR will help us schedule Konflux and Tenants Workload on dedicated Node Pools. This will make use of TektonConfig.
NodeSelector and Tolerations values are sample values only, we can change them if we want. We will need to create a new Node Pool in OCM (Manually or using Terraform) with the values of (NodeSelector and Tolerations ) we specifiy in the TektonConfig.

KFLUXINFRA-802: Segregate Konflux and Tenants Workload using TektonConfig

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
components/pipeline-service/production/stone-prd-rh01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
components/pipeline-service/production/stone-prod-p01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/production/stone-prod-p02/resources/kustomization.yaml
components/pipeline-service/production/stone-prod-p02/resources/tekton-chains-public-key-path.yaml

Instead of the Job used to read the secret and create a new secret including only the public key, we now use ExternalSecret pointing to the same vault entry, but creating a secret including only the public key. This eliminates the race condition issues we had with the Job. This is also a more conformant way of managing the secret using the same ExternalSecret mechanism.

Replace chains public key Job by ExternalSecret - prod

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml

Integration service need access to QE secrets in order to run e2e tests in Konflux CI

chore: Give access to integration service to access vault secrets for e2e tests

---

.github/workflows/kube-linter.yaml

We've been receiving warnings whenever we run our github actions pipelines for a little while now, such as on [this PR][1].  For more information, read the following posts from github:
- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
- https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
To silence these warnings, we need to bump the following actions:
- `actions/checkout@v3` to `v4`
- `github/codeql-action/upload-sarif@v2` to `v3`
[1]: https://github.com/redhat-appstudio/infra-deployments/actions/runs/10563058594?pr=4393

bump versions of github actions dependencies

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Increase the default timeout for pipelines from
1 hours (the default) to 2 hours.
The reason is that users complained about timeouts while their pipelines were waiting for resources.

KFLUXINFRA-808: Set default pipelines timeout to 2 hours - prod

---

components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
components/sandbox/toolchain-member-operator/base/rbac/kustomization.yaml

- currently this ClusterRole is managed and deployed by the Sandbox host operator.
- Since it is a Konflux specific role, it should be migrated and maintained in this repo and deployed by Argo
- This role should be installed on member clusters
Needed for [KONFLUX-4171](https://issues.redhat.com//browse/KONFLUX-4171)

Migrate ClusterRole appstudio-pipelines-runner

---

components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml

- This PR enables the appstudio-pipeline service account to get and list PipelineRuns
- The motivation for this is to allow Integration Test Scenarios PipelineRuns to query itself to inspect label and annotations added by the Integration Service such as:
```
appstudio.openshift.io/component: acb-service
test.appstudio.openshift.io/type: component
```
which tells you that the underlying Snapshot for this Test was created by a component that was recently built called `abc-service`
Addresses [KONFLUX-4171](https://issues.redhat.com//browse/KONFLUX-4171)

Enable pipeline SA to read and list plrs

---

argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml

This enables workspaces in production environments.  Resources were added in PR #4393.

workspaces: don't delete applicationset from prod

---

components/release/production/kustomization.yaml

this commit adds the release-service-monitor to production cluster.

feat(RELEASE-996): add release-service-monitor to production

---

components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

once we bump the nightly version on konflux, someone should update the `TektonConfig` to make the webhooks non-blocking, since [SRVKP-4442](https://issues.redhat.com//browse/SRVKP-4442) will be available
This change will allow you all the view the webhook config on the konflux clusters and confirm the `TektonConfig` changes have taken hold.
@enarha @savitaashture @jkhelil  FYI
rh-pre-commit.version: 2.3.1

allow pipeline service SREs to view openshift-pipelines webhook configuration

---

components/ui/base/proxy/nginx.conf

Workspaces is now live in production environments, but is currently inaccessible as it's not exposed.  In external environments, workspaces is configured to use a route, but on internal environments, it can piggy-back off of the nginx configuration already in place for UI components.

ui: pass relevant requests to workspaces

---

components/ui/base/proxy/nginx.conf

The workspaces service listens on port 8000, so we need to explicitly communicate on that port when passing requests to it.

set port when forwarding requests to workspaces

---

components/mintmaker/production/base/manager_patches.yaml

This commit updates MintMaker's prod image to a newer version.
This version is still pinned.

Update MintMaker image in prod

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Fix a typo in the match string for the service monitor used for federating  metric kube_pod_container_status_restarts_total

fix: kube_pod_container_status_restarts_total federate match

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Temporarily drop this metric from being remote-written to see if it affects the ability to remote-write other metrics.

chore: don't remote write taskrun duration metric

---

components/authentication/base/everyone-can-view-patch.yaml

There are people contributing to Konflux that do not belong to any official Konflux team that we want to grant view access to our clusters. A new rover group was created to put those people in so grant view role to that new group.
Also re-order alphabetically the groups.

Grant everyone can view role to konflux-contributors

---

components/authentication/base/everyone-can-view.yaml
components/authentication/base/kustomization.yaml

Until version 4.14 of OCP, all Konflux teams could access cluster monitoring, grant view cluster role was enough. Starting with 4.15, something changed and view clusterrole no longer allow to access monitoring and execute queries.
Granting cluster-monitoring-view cluster role to all teams resolve the issue.

Grant cluster-monitoring-view role to all Konflux teams

---

components/monitoring/README.md
components/monitoring/prometheus/README.md

This changes mainly includes minor updates for things changed since the documentation was written. Additionally, some of the content was removed as it's being moved to the SOP repository.

docs(RHTAPWATCH-1261): prepare o11y docs for handoff

---

components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml

Update the 'ClusterLogging' CR collection spec
according to the updated spec as documented here:
https://docs.openshift.com/container-platform/4.16/observability/logging/log_collection_forwarding/cluster-logging-collector.html#configuring-logging-collector_cluster-logging-collector

Update ClusterLogging CR collection spec

---

components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml

This is first step to be able to decommission m01.
[KFLUXINFRA-796](https://issues.redhat.com//browse/KFLUXINFRA-796)

Make stg-rh01 the default member cluster

---

components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
components/pipeline-service/development/kustomization.yaml
hack/secret-creator/create-plnsvc-secrets.sh

The operator no longer exists in OperatorHub and cannot be installed on OCP 4.16+ without an enterprise license from MinIO.
See https://github.com/minio/operator/issues/2226
Version 5.0.15 is selected over 6.0.3 as the latter requires a minimum k8s version of 1.28 (OCP 4.15+). With 5.0.15 the minimum supported k8s version is 1.21 (OCP 4.8+).

Install minio-operator from upstream

---

components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml

All spaces were move from m01 to rh01, remove the possibility to provision new spaces on that cluster.
[KFLUXINFRA-796](https://issues.redhat.com//browse/KFLUXINFRA-796)

Remove stg-m01 spaceProvisionerConfig

---

components/multi-platform-controller/production-downstream/host-config.yaml
components/multi-platform-controller/production/host-config.yaml
components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

Changing AWS GPU Instance Type to `g4dn.xlarge`

KFLUXINFRA-837: Changing AWS GPU Instance Type

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml

The tekton-pipelines-controller pod did not have request and limit set and this is causing the pods to be evicted from the nodes where they run in production. Not having request make those pods ideal candidates for eviction and when this happens, it cause a slight outage during restart of the controllers as they need to process the queue of pipeline runs.
Set cpu/memory request and memory limit in staging first, a follow up change will be done for production.
The cpu limit was not set intentionally as setting CPU limit in k8s is not a good idea and even an anti-pattern. Many articles are available out there explaining why but here is one of them[1].
The resources are different for stg-rh01 as we want them to be the same as production to be able to do load testing on that staging cluster. …

Set cpu/memory request and memory limit for tkn controllers in staging

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml

The tekton-pipelines-controller pod did not have request and limit set and this is causing the pods to be evicted from the nodes where they run in production. Not having request make those pods ideal candidates for eviction and when this happens, it cause a slight outage during restart of the controllers as they need to process the queue of pipeline runs.
The cpu limit was not set intentionally as setting CPU limit in k8s is not a good idea and even an anti-pattern. Many articles are available out there explaining why but here is one of them[1].
This commit is a follow up of this commit[2] where the same was changed but for staging.
[1] https://home.robusta.dev/blog/stop-using-cpu-limits
[2] 90ee9cb7a3ce13e58e53a695f48c53597649c350 …

Set cpu/memory request and memory limit for tkn controllers in prod

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

This is a dependency of https://github.com/redhat-appstudio/o11y/pull/388
Regarding how many labels combinations this mean, on `stone-stg-rh01` during last week I see 51. There are actually only 2 labels that change over time:
* `lease` - if we do not reconfigure Tekton Pipelines Controller to use different buckets count, there will be just 4 of these for every reconciler (so 12)
* `lease_holder` - this is a Pipelines Controller pod identification, so every time that pod restarts or so, new label value appears here (these pods are supposed to be stable, always running and restarts will be matter of upgrades or signs of cluster issues)

feat(KONFLUX-4508): Expose metrics for Pipelines leases distribution alerts

---

components/release/base/release-pipeline-resources-clusterrole.yaml

- some tasks may need config maps to obtain configuration data

release pipeline sa reading configmaps

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

In production, on rh01, the container got OOMKilled. Increase from 6 to 8 and also set staging to same values. We want staging to be a mirror of prod.

Increase tekton results memory

---

components/authentication/base/everyone-can-view.yaml

This PR adds `get`, `list`, and `watch` permissions for InternalWorkspaces to anyone having the `view-appstudio` role

add workspaces.konflux-ci.dev to view-appstudio ClusterRole

---

components/tracing/otel-collector/production/otel-collector-helm-values.yaml
components/tracing/otel-collector/staging/otel-collector-helm-values.yaml

A mismatch in variable names is causing a deployment failure of the Otel collector; this fixes that issue.

Fix SIGNALFX_API_KEY variable name mismatch

---

components/tracing/otel-collector/production/otel-collector-helm-values.yaml
components/tracing/otel-collector/staging/otel-collector-helm-values.yaml

This fixes a config issue preventing the start of the collector.

OTel - Remove logging from list of exporters in the pipeline

---

components/mintmaker/production/base/manager_patches.yaml

This commit updates MintMaker to use the latest image, which includes an update to the rpm-lockfile script.

Update MintMaker to use rpm-lockfile script v0.9.0

---

components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml

Update already verified on the staging clusters. We start with updating a single prod clusters to verify the process and MPC update after initially encountering some problems with the staging clusters.

Update OSP version on stone-prd-m01

---

configs/nvme-storage-configurator/base/nvme-storage.service

NVME Disk Configuration Service was pointing to incorrect script. We have fixed that by poiting it to `mount.sh`. We have also hard coded the nvme device name `/dev/nvme1n1`

Fix for nvme disk configuration service

---

components/sandbox/toolchain-host-operator/production/stone-prod-p02/network-policy.yaml
components/sandbox/toolchain-host-operator/staging/stone-stage-p01/network-policy.yaml

Host operator needs to talk to registration-service to check health endpoints to set the status of the toolchainstatus resource.  However, since there are network policies defined on registration service, host-operator is disallowed from making network connections to registration-service, causing the toolchainstatus resource to report that registration service was unavailable.
To fix this, we need a network that allows pods within toolchain-host-operator to talk with each other.  This policy was already defined on the external clusters and the p01 internal cluster, but not on the others.

kubesaw: add network policy for in-namespace communication

---

components/multi-platform-controller/production-downstream/host-config.yaml
components/multi-platform-controller/production/common/host-config.yaml
components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

This PR will take care of the followings --
- cloud-init config will take care of configuring nvme disk attached to the gpu instance type `g6.xlarge`
- this configures a new custom ami which is built from fedora 40.
- this will also generate nviDIa configuration to run gpu builds.

adding cloud-init configuration for gpu instances

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

The newer OSP version expects a value of type string.

Chains deep-inspection string value

---

components/release/production/kustomization.yaml

The latest release-service renamed Processing to ManagedProcessing and the UI wasn't updated.

revert release status change to fix ui

---

argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
components/authentication/base/everyone-can-view-patch.yaml
components/kubearchive/base/kustomization.yaml
components/kubearchive/development/kustomization.yaml
components/kubearchive/staging/kustomization.yaml

This PR aims to change the namespace of KubeArchive because ROSA does not support namespaces for applications that are `kube.*`, which matches `kubearchive`. I changed it to be `product-kubearchive` given that we don't have any other name and I didn't want to use our shorthand (`k9e`). I tested it on CRC with the `prepare-crc.sh` script and then the `bootstrap-cluster.sh preview`.

Change KubeArchive namespace because of ROSA

---

components/cluster-secret-store/base/appsre-vault-secret-store.yml

Kubearchive need this access to retrieve RDS instances secret.

Allow app-sre vault access from kubearchive namespace

---

components/kubearchive/staging/database-secret.yaml

ExternalSecret are using go templates when using template to create the target secret. If the key to access contains a dot (e.g. db.user), we must use an index function to access it otherwise is is looking for an object(db) containing another object (user).

Fix kubearchive database secret extraction

---

components/kubearchive/staging/database-secret.yaml

This PR changes the name of the Secret created by ExternalSecret to the correct one. It needs to be called `kubearchive-database-credentials` not `kubearchive-database-secret`.

Fix DB secret name for KubeArchive

---

components/release/staging/kustomization.yaml

The UI depends on the release.status.processing field and it was renamed to managedProcessing.

rollback release-service in staging

---

components/kubearchive/staging/database-secret.yaml

A key for the KubeArchive's DB secret was wrong, sorry about the multiple PRs.

Fix DB secret keys for KubeArchive

---

components/project-controller/development/kustomization.yaml
components/project-controller/staging/kustomization.yaml

Update project-controller quay repository to change to konflux-ci organization from redhat-appstudio.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1267

chore(RHTAPWATCH-1267): Update quay repository for project-controller

---

components/cluster-as-a-service/base/clustertemplates.yaml
components/cluster-as-a-service/development/add-hypershift-params.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml
components/cluster-as-a-service/staging/add-hypershift-params.yaml

The previously used image repo unexpectedly removed tags for OCP versions. The MCE operator provides its own HO image which should provide better guarantees of compatibility since the image tag corresponds to the version of MCE deployed.

Use MCE provided images for the hypershift CLI

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml

- this allows ExternalSecrets to work in the rhtap-releng-tenant

feat(RELEASE-1192): allow rhtap-releng to use es

---

components/backup/base/member/schedules/backup-toolchain-member-schedule.yaml

Backing up a list of resources can lead to incomplete backup, e.g. if a CRD is added without updating the back up list.
To be on the safe side, change the backup to include all resources in toolchain-member-operator and restore procedure will explicitly mention which resources to restore. Doing it that way will cost a bit more on the AWS storage but has the huge advantage of covering the case of CRD being added later. Backup will include it and restore procedure might not but can be adjusted when restore is performed.
[KFLUXINFRA-730](https://issues.redhat.com//browse/KFLUXINFRA-730)

Backup all resources in toolchain member namespace

---

components/release/k-components/manager-resources-patch/manager_resources_patch.yaml

Increasing memory limits for the release-service controller.

fix: increase release controller memory

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/workspaces/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/workspaces/staging/stone-stg-rh01/kustomization.yaml

To allow end users to retrieve the Custom Resource Definition for Workspaces  from the proxy, it needs to be deployed in the member clusters also.
A subsequent PR for production will follow

add Workspace CRD in staging's member cluster

---

components/cluster-secret-store/base/insights-secret-store.yaml

Fixing the wrong tenant name for a cluster secret defined in https://github.com/redhat-appstudio/infra-deployments/pull/4677

KFLUXINFRA-799: adjusted tenant name for insights

---

components/perf-team-prometheus-reader/base/serviceaccount.yaml

This PR updates cluster permission of service account `perf-team-prometheus-reader-cluster-sa` in order to access Thanos Querier API.
Fix is based on the solution: https://access.redhat.com/solutions/5151831

fix(KONFLUX-4955): Update cluster monitoring permission for Perf-Monitoring Service Account

---

components/cluster-secret-store/production/insights-approle-id-patch.yaml
components/cluster-secret-store/staging/insights-approle-id-patch.yaml

Changing Role ID for Insights Vault App Role to authenticate to external vault instance.

KFLUXINFRA-799: Fixing Role ID for Insights Vault App Role

---

components/multi-platform-controller/production-downstream/kustomization.yaml

It's a follow-up of https://github.com/redhat-appstudio/infra-deployments/pull/4711
Promotes the following fixes to production:  
- https://github.com/konflux-ci/multi-platform-controller/pull/306
- https://github.com/konflux-ci/multi-platform-controller/pull/311

Promote MPC fixes to internal production

---

components/integration/production/base/manager_resources_patch.yaml

* The service manager pod is getting OOMKilled because of increased amout of resources on the production cluster(s)
* Increase the limit to 4096Mi as agreed on architecture calls
* Increase the requests to 2048Mi as that's the new expected consumption

fix(KFLUXBUGS-1735): increase memory limits for integration service

---

components/ui/development/kustomization.yaml
components/ui/staging/kustomization.yaml

- openshift/hac-dev#970 from abhinandan13jan/fix-component-url (#f97289a9 972d55e4)
- openshift/hac-dev#986 from jrichter1/wait-for-mbop (#6b5f00eb 9bc1cd6e)
- openshift/hac-dev#984 from sahil143/it-params (#3a05ee41 f73e9847)
- openshift/hac-dev#982 from sahil143/rerun-pipeline-run (#aa03f816 b21fc0e8)
- openshift/hac-dev#1 from Katka92/fix_dropdown_locator (#50ff3af6 5d42a263)
- openshift/hac-dev#983 from sahil143/nudge-permission (#3ff2d0d2 07770925)
- openshift/hac-dev#987 from Katka92/fix_tests (#6f80bb7a a7ea8728)
- openshift/hac-dev#988 from caugello/KFLUXBUGS-1197 (#55270666 79065eec)
- openshift/hac-dev#995 from Katka92/fix_advanced_test (#8cddfe10 135923f2)
- openshift/hac-dev#991 from JoaoPedroPP/KFLUXBUGS-96 (#caa7cb1e a14a004e)
- openshift/hac-dev#990 from …

fix: promote latest hac-dev to staging

---

components/release/base/cronjobs/remove-internal-requests.yaml

this PR add a new CronJob to prune internalrequests that are left from timed out pipelineruns, 24 hours after their creation.

fix(KFLUXBUGS-1600): internalrequests for timed out pipelineruns are not removed

---

components/multi-platform-controller/production-downstream/kustomization.yaml
components/multi-platform-controller/production-downstream/replicas_patch.yaml

Issue with timed out TaskRuns still persist on `p02`, let's try to scale the MPC to 3 instances to see if that have any effect.
Discussion: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1728630785195409 (at the bottom)

Set MPC deployment replicas to 5 for internal clusters

---

components/multi-platform-controller/production-downstream/host-config.yaml

We have seen on p02 that MPC takes long to complete reconciliation due to IBM API calls being slow. We did increase the number of VMs but that made thing worse.

Reduce number of IBM VMs in internal prod

---

components/multi-platform-controller/development/logs-in-console-format-cmd-arg-patch.yaml

With adding the `rbac-proxy` container, the order is changed and patched one is now index `1`

Fixup MPC container patch

---

configs/proactive-scaler/base/deployments.yaml
configs/proactive-scaler/base/priority-class.yaml

This priority class is meant to be lower that priority class used by the tenant pods. The original change created a default class with priority value of 0 and scaler pods used a class with priority of -1.
The problem is all the tenants pods get assigned to sandbox-users-pods priority class which has a value of -3, causing the scaler pods to not be evicted from the node when resource are needed.
We are planning to remove sandbox so this sandbox-users-pods priority class will be deleted eventually but in the meantime, set scaler pods to -10.
Also rename the 2 priority classes so their name are more meaningful.
[KFLUXINFRA-889](https://issues.redhat.com//browse/KFLUXINFRA-889)

Fix priority class of the proactive scaler pods

---

components/multi-platform-controller/production-downstream/kustomization.yaml
components/multi-platform-controller/production/kustomization.yaml
components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml

This change include:
- Apply version with better concurrency on public cluster (showed good results on private);
- Apply `s390x` 100Gb VM disc size.

Update production to the latest MPC with all recent fixes

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Request is what is guaranteed so having such low requests vs limit is not good. There is a problem in production where resolving remote bundle is timing out. To rule out lack of resources, set the memory request same as limit to guarantee access to that amount of memory. Also increase CPU request for same reason and remove CPU limit.
If we see over time that we do not need such high memory request, a follow up change will be done to reduce it.

Increase tekton remote resolver resources

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

In 5e0efd89e2a35795ed277dc5c3005595ab6ce7fd, the resources requests/limits were changed to rule out potential lack of resources issue.
After the change was done, we could see the actual usage of the remote resolver controller. Reduce the resource requirements to number closer to actual usage. These numbers do include a buffer.

Reduce Tekton resolver resources

---

argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
argo-cd-apps/base/member/infra-deployments/knative-eventing/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/knative-eventing/OWNERS
components/knative-eventing/base/kustomization.yaml
components/knative-eventing/development/kustomization.yaml
components/knative-eventing/staging/kustomization.yaml

I'm adding Knative Eventing because its a dependency for KubeArchive. There was an [ADR](https://github.com/konflux-ci/architecture/pull/202) to install it for everyone use, but my intention here is that is used by KubeArchive.
cc @ralphbean @hugares

Add Knative Event, KubeArchive dependency, as infra component

---

argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml

#4764 Knative Eventing was introduced, but the deployment was in and out of sync constantly. This is because Knative Eventing uses aggregated roles. The following PR makes the Knative Eventing ArgoCD application ignore the roles that were being aggregated.
PD: I found no way to tell the `ignoreDifferences` option to ignore "all clusterroles that have `aggregateRules`". So I had to exclude them one by one.
cc @hugares

Ignore Aggregated Roles in Knative Eventing

---

argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
components/kubearchive/base/alternative-service.yaml
components/kubearchive/base/kustomization.yaml
components/kubearchive/development/kustomization.yaml
components/kubearchive/staging/database-secret.yaml

Updating KubeArchive from 0.1.0 to 0.3.0. Some stuff related to the database changed, and now namespace is present on all resources, so patching takes that into account. Also I detected some problems regarding certificates in webhooks, so this is correcting it.
I want to wait for #4764 to be merged, so I can make sure KubeArchive archives stuff (I didn't properly test this before, just that it installed).

Update KubeArchive to v0.3.0

---

configs/proactive-scaler/base/deployments.yaml

Looking at the tekton task throttled by node, we can see that one node in advance is helping but not enough to get rid of task pending due to lack of nodes.

Make sure we have 2 worker nodes in advance

---

components/monitoring/logging/staging/stone-stage-p01/configure-logforwarder-compression-patch.yaml
components/monitoring/logging/staging/stone-stage-p01/kustomization.yaml

This PR enables `gzip` compression on logs forwarded to SPLUNK from the stage p01 cluster. We expect this to just work and to see a reduction in generated traffic towards SPLUNK.
Official doc for [Configuring log forwarding in OpenShift](https://docs.openshift.com/container-platform/4.15/observability/logging/log_collection_forwarding/configuring-log-forwarding.html\#logging-delivery-tuning_configuring-log-forwarding)

enable compression in SPLUNK log forwarder for the staging cluster

---

components/cluster-as-a-service/base/clustertemplates.yaml

The imageContentSources chart value is made available as a result of this change.

Bump hypershift-aws-template chart version

---

components/pipeline-service/staging/stone-stage-p01/deploy.yaml

In 43682e0f1ef1fab7e684e51bb6efbf5bd5ad9307, the change was done but the deploy.yaml was not regenerated.

Generate stone-stage-p01 pipeline deploy.yaml

---

components/sandbox/toolchain-member-operator/base/olm/toolchain-member-operator.yaml

When nodes are overcommited pods that are over their requested memory can be evicted. Increasing the target memory will reduce this risk.

Update CatalogSource mem target to avoid eviction

---

components/tekton-ci/production/cleanup-cronjob.yaml

Even removing applications that are older than a day wasn't sufficient. Since deleting applications will trigger the deletion of a component and any imagerepositories, we need to ensure that deletion happens after the PLR timeout.
While the e2e tests have a 2 hour timeout for the pipelineruns, deleting the imagerespositories will also result in deleting the quay repos. Increasing timeout to the [e2e pipeline timeout](https://github.com/konflux-ci/build-definitions/blob/050297455791697a52c97fa50a1e2f5e4d914bcc/.tekton/pull-request.yaml#L270) + 30 minutes.

Further reduce maximum application age

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Increase the number of buckets so the 2 controllers can acquire leases.

Set number of buckets for OSP resolver controllers

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This change is an attempt to improve the resolutionRequest time, we see a lot of resolution timing out. We cannot configure the number of threads per controller yet so increase the number of controllers.
[KFLUXBUGS-1784](https://issues.redhat.com//browse/KFLUXBUGS-1784)

Increase OSP remote resolver replicas to 2

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This change is an attempt to improve the resolutionRequest time, we see a lot of resolution timing out. We cannot configure the number of threads per controller yet so increase the number of controllers.
[KFLUXBUGS-1784](https://issues.redhat.com//browse/KFLUXBUGS-1784)

Increase OSP remote resolver replicas to 4

---

components/multi-platform-controller/production/manager_resources_patch.yaml

Something is happening on prd-rh01 and controller is getting OOMKilled even with 8Gi Increase this further just to try to get things working before we investigate.

Increase MPC controller to 16Gi

---

components/project-controller/production/kustomization.yaml

This update introduces to production the support for templatizing resolverRef param values, as implemented here:
https://github.com/konflux-ci/project-controller/pull/109

chore: project-controller production update

---

components/kubearchive/development/postgresql.yaml

This is necessary due to what seems to be a bug in the bitnami/postgresql:16.4 container. See
https://github.com/bitnami/containers/issues/74788

fix kubearchive PostrgreSQL deployment

---

components/release/k-components/manager-resources-patch/manager_resources_patch.yaml

This PR increases the memory limit to 8Gb to decrease the Pod restarts over the week.

fix: increase memory limit

---

components/release/base/cronjobs/remove-expired-releases.yaml

this PR increase the request and limit for the release prune cronjob pod to avoid it being oomkilled.

fix: increases memory request/limit for release deletion pod

---

components/cluster-as-a-service/base/multicluster-engine.yaml
components/cluster-as-a-service/development/kustomization.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml
components/cluster-as-a-service/staging/kustomization.yaml

A 4.17.4 cluster was successfully provisioned in staging. Promoting the MCE upgrade to prod.

Upgrade MCE to 2.7 in production

---

components/multi-platform-controller/k-components/manager-resources/kustomization.yaml
components/multi-platform-controller/k-components/manager-resources/manager_resources_patch.yaml
components/multi-platform-controller/production-downstream/kustomization.yaml
components/multi-platform-controller/production/kustomization.yaml
components/multi-platform-controller/staging-downstream/kustomization.yaml
components/multi-platform-controller/staging/kustomization.yaml

Align MPC controller memory to be the same on all staging and production environments. Also reduce memory from 16Gi to 10Gi, rh01 is the most used cluster and memory is never going past 6Gi.

Configure MPC memory for staging and production

---

components/multi-platform-controller/production-downstream/host-config.yaml

Allow TGW routetable to manage the routing for the internet traffic

KFLUXINFRA-1000: Remove routing setup to support TGW route prod internal

---

components/build-service/production/base/kustomization.yaml

In 8475b04da, a patch was added to change build services manager resources but by mistake, as second "patches" section was added causing the patch in the original section to be ignored.
Fold both "patches" section into one so both resources and secret patches get applied.
[KFLUXBUGS-1880](https://issues.redhat.com//browse/KFLUXBUGS-1880)

Fix PAC secret in production build service

---

components/ui/development/kustomization.yaml
components/ui/production/kflux-ocp-p01/kustomization.yaml
components/ui/production/stone-prod-p01/kustomization.yaml
components/ui/production/stone-prod-p02/kustomization.yaml
components/ui/staging/kustomization.yaml

Repository: openshift/hac-dev
Changes between f97289a and 9522a36
- openshift/hac-dev#1013 feat([KFLUXBUGS-1372](https://issues.redhat.com//browse/KFLUXBUGS-1372)): improve the label of private image repo by @testcara [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1013))
- openshift/hac-dev#997 feat(HAC-5814): allow users to set context in UI by @CryptoRodeo [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/997))
- openshift/hac-dev#994 feat([KFLUXBUGS-1540](https://issues.redhat.com//browse/KFLUXBUGS-1540)): filter on Applications by @caugello [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/994))
- openshift/hac-dev#969 feat(import): add gitlab annotation by @abhinandan13jan [`lgtm,approved`] …

update hac-dev ui to latest(9522a36)

---

components/project-controller/production/kustomization.yaml

This introduces into production a change in which the controller watches also over the project and template resources.
https://github.com/konflux-ci/project-controller/pull/124

chore: promote project-controller to production

---

.github/workflows/kube-linter.yaml

For crossplane component helm chart inflation generator is used which needs to have "--enable-helm" option
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-88

chore(KFLUXVNGD-88): Add enable-helm option in github actions file

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml

Due to the amount of components on-boarding to Konflux, the load of MintMaker runs is increasing quite a lot. Let's reduce the frequency, at least untile we figure out how to improve the performances.

Run MintMaker every 4 hours instead of 2 hours

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
components/mintmaker/production/stone-prod-p01/cronjob-patch.yaml
components/mintmaker/production/stone-prod-p01/kustomization.yaml
components/mintmaker/production/stone-prod-p02/cronjob-patch.yaml
components/mintmaker/production/stone-prod-p02/kustomization.yaml

This change will be reverted after the new release of the customized schedule for managers is deployed, planned for tomorrow.
The change is not applied to p01 and p02 clusters.

Temporarily adjust Renovate jobs to run every 4 hours from Friday to Sunday

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml

The k8s CronJob schedule uses a syntax similar to Linux crontab, but it has a key difference: the day of the week field only accepts values from 0 to 6.

mintmaker: fix invalid k8s cronjob schedule

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
components/mintmaker/production/base/kustomization.yaml
components/mintmaker/production/base/manager_patches.yaml
components/mintmaker/production/stone-prod-p01/cronjob-patch.yaml
components/mintmaker/production/stone-prod-p01/kustomization.yaml
components/mintmaker/production/stone-prod-p02/cronjob-patch.yaml
components/mintmaker/production/stone-prod-p02/kustomization.yaml

This also removes the temporary adjustment to the Renovate job schedule.

Promote mintmaker from stage to prod

---

components/kubearchive/base/kustomization.yaml
components/kubearchive/base/rbac.yaml
components/kubearchive/development/kustomization.yaml
components/kubearchive/development/postgresql.yaml
components/kubearchive/staging/database-secret.yaml
components/kubearchive/staging/kustomization.yaml

Updating KubeArchive from 0.3.0 to 0.4.0. I deleted from the patch the resource quota for the sink and api component since that is part of the KubeArchive deployment yaml files (introduced by the OpenTelemetry instrumentation). The other changes are related to the yaml lint.

Upgrade kubearchvie to v0.4.0

---

argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/crossplane-control-plane.yaml
argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
components/crossplane-control-plane/OWNERS
components/crossplane-control-plane/base/kustomization.yaml
components/crossplane-control-plane/development/kustomization.yaml
components/crossplane-control-plane/production/kustomization.yaml
components/crossplane-control-plane/staging/kustomization.yaml
hack/deploy-argocd.sh

Initial crossplane component is added in the components of the infra-deployments.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-88

chore(KFLUXVNGD-88): Add crossplane component

---

argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/kustomization.yaml

This is not meant to be deployed to host, eaas or in-cluster.

Deploy crossplane to member clusters only

---

argo-cd-apps/overlays/development/delete-applications.yaml
configs/nvme-storage-configurator/base/daemonset.yaml
configs/proactive-scaler/base/deployments.yaml

We're replacing nodes with EBS Volumes to the nodes with Local NVMe Disks as default node pool.

fix(KFLUXINFRA-777): Changing NodeSelector and Toleration

---

argo-cd-apps/base/member/infra-deployments/konflux-ui/README
argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
argo-cd-apps/base/member/infra-deployments/konflux-ui/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/konflux-ui/base/ns.yaml
components/konflux-ui/staging/base/dex/dex.yaml
components/konflux-ui/staging/base/dex/kustomization.yaml
components/konflux-ui/staging/base/kustomization.yaml
components/konflux-ui/staging/base/proxy/kustomization.yaml
components/konflux-ui/staging/base/proxy/nginx.conf
components/konflux-ui/staging/base/proxy/proxy.yaml
components/konflux-ui/staging/base/route-and-oauth.yaml
components/konflux-ui/staging/stone-stg-rh01/add-service-certs-patch.yaml
components/konflux-ui/staging/stone-stg-rh01/dex-config.yaml
components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
components/konflux-ui/staging/stone-stg-rh01/oauth2-proxy-args-patch.yaml
components/konflux-ui/staging/stone-stg-rh01/remove-run-as-user-proxy-patch.yaml
components/konflux-ui/staging/stone-stg-rh01/set-hostname.yaml
components/konflux-ui/staging/stone-stg-rh01/set-redirect-uri.yaml
components/konflux-ui/staging/stone-stg-rh01/set-replicas-patch.yaml

Deploy the new UI to the public staging cluster so it can be tested. The deployment supports connecting from a frontend which run on a local machine. This is useful when developing the frontend.
Authentication to the new UI is done using dex and the OCP connector.

KFLUXINFRA-1058: Deploy the new UI to public stage

---

argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml

There is an issue where websockets connections
doesn't work with the new ui deployment. Turning off self healing will help debug the issue.

Turn off self healing for konflux-ui

---

components/konflux-ui/staging/base/proxy/proxy.yaml

For websockets the token should be processed in a certain way before sending it to the k8s API. It should be based64 encoded without padding [1].
The current implementation assumed a padding of 1 char, but it was seen that it can be 2 chars. Adjust the processing to remove any padding from the token.
[1] - https://github.com/kubernetes/kubernetes/pull/47740

Better token handling for websockets

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

We need to create the namespace early in the process so the ExternalSecrets can be synced right after (otherwise it fails).
This only adds a namespace. The rest of the change is things moved from the deploy.yaml files to the base/main file and then the deploy.yaml files regenerated which moved things around.

Add the tekton-logging namespace

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Blob SDK Go use by results uses standard enviornment. This changes to use use that.

Fix Environment Variables for tekton results api and s3

---

argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml

Since we use nodes with nvme in staging too, we need to enable proactive scaler otherwise it take too much time to add a node. In addition, we need staging to be configured the same way as prod so any test we run there are more representative of production environment.

Enable proactive scaler in staging

---

components/multi-platform-controller/production-downstream/base/kustomization.yaml
components/multi-platform-controller/production/kustomization.yaml

This is in order to  include the more detailed logging in SSH secret we
now have.

chore(KFLUXINFRA-930): Bump MPC in production

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Similar to https://github.com/redhat-appstudio/infra-deployments/pull/5044
We are getting "no space left on device" when building on arm VMs, increase the size to see if VM disk size is the issue.
[KFLUXINFRA-1141](https://issues.redhat.com//browse/KFLUXINFRA-1141)

Increase disk size of ART arm64 instance to 160GB

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
components/release/staging/external-secrets/release-monitor-secret.yaml
components/release/staging/kustomization.yaml

this PR adds the release-monitor secret to the release-service namespace to fix the slo exporter metrics after the dashboard graphs was fixed, showing the missing data from the release service.

chore: add release-monitor secrets

---

components/crossplane-config/base/kustomization.yaml
components/crossplane-config/base/secret.yaml

Remove crossplane-config secret file since argocd
might override the token generated.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-89

chore: Remove crossplane-config secret file

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Change back all ARM flavors to default disk size and create a new flavor, same as default one with larger disk. Create a new one to not increase default thus increasing running cost for all builds that do not need more space.
[KFLUXINFRA-1141](https://issues.redhat.com//browse/KFLUXINFRA-1141)

Create new ARM flavor with larger disk

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The update of LOGS_PATH is only relevant in staging and later in production, not development.

Update Tekton Results to v0.13.0-2

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

Includes https://github.com/konflux-ci/build-definitions/pull/1688 which bases the FBC pipeline off multi-arch, so expose the `build-platforms` additional parameter to the PipelineRun parameters.

feat(KONFLUX-5480): Update pipeline references

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This reverts commit 247d757c412a067eed746e753de94c202d59879a. Watcher is not starting due to invalid -kube-api-qps.

Revert "Pass QPS, Burst and Thread Flag to Results Watcher (#5055)"

---

components/konflux-ci/base/external-secrets/konflux-ci-repo-creator.yaml
components/konflux-ci/base/external-secrets/kustomization.yaml

[STONEBLD-2875](https://issues.redhat.com/browse/STONEBLD-2875)
- konflux-ci-repo-creator secret is a Quay token used for creating new repos in
https://quay.io/organization/konflux-ci
- Create the ExternalSecret in konflux-ci because it's going to be used in tasks
in build-definitions repository

add konflux-ci-repo-creator secret to konflux-ci

---

components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml

There was a missing link to the Konflux console in the PAC config.

KFLUXINFRA-1131: kflux-prd-rh02 update console urls

---

argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml

Public clusters doesn't need to have a dedicated overlay in the authentication app.

KFLUXINFRA-1131: Remove cluster path from authentication app

---

components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/scc-rbac.yaml

In the kflux-prd-rh02 cluster we don't deploy kubesaw which configure the pipelines service account in each namespace to have permissions to access the appstudio scc. Instead, give this permission to tekton's pipeline controller.

KFLUXINFRA-1131: Allow tekton to use the appstudio-scc

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

We had only Tekton Labels in vector, this adds PAC labels also.

Add PipelineAsCode labels selector to the forwarder log

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This was initially attempted here: https://github.com/redhat-appstudio/infra-deployments/pull/5055
And reverted here: https://github.com/redhat-appstudio/infra-deployments/pull/5066
Looking at this https://github.com/tektoncd/results/blob/main/cmd/watcher/main.go#L60-L80, looks like right options should not be `-kube-api-qps=50 -kube-api-burst=50 -threadiness=32`, but maybe `-qps=50 -burst=50 -threadiness=32`.
I have not tested this at all though :-/

feat: Pass QPS, Burst and Thread Flag to Results Watcher, attempt 2

---

components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml

The SA can already get secrets but this [stepaction](https://github.com/konflux-ci/build-definitions/tree/main/stepactions/eaas-copy-secrets-to-ephemeral-cluster/0.1) requires list permissions.

Allow the pipeline runner SA to list secrets

---

components/crossplane-config/base/rbac.yaml
components/crossplane-control-plane/base/kustomization.yaml

The composition creates a LimitRange so `crossplane-sa` is granted permission to manage them.

Deploy crossplane XNamespace composition

---

components/repository-validator/production/kustomization.yaml

This org is enforcing RH sso so it can be added to the allowed list.
[KFLUXINFRA-1169](https://issues.redhat.com//browse/KFLUXINFRA-1169)

Allow repos from quipucords organization

---

components/crossplane-control-plane/staging/provider-config.yaml

v1aplha1 doesn't have Extract option so updating it to v1beta1 in crossplane-control-plane ExternalSecret.

chore: Update the External Secret version in crossplane

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

The MRRC maven build pipeline for the whole MRRC release process is developed done in following PRs:
* https://github.com/konflux-ci/build-definitions/pull/1643
* https://github.com/konflux-ci/build-definitions/pull/1691 
We want to deploy these two pipelines to the kflux-prd-rh02 for user to do early use. This PR addressing the deployment.

KONFLUX-3273: Add build pipeline for MRRC release process

---

argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
argo-cd-apps/base/member/infra-deployments/konflux-rbac/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
components/konflux-rbac/production/base/kustomization.yaml
components/konflux-rbac/production/empty-base/kustomization.yaml
components/konflux-rbac/production/kflux-prd-rh02/kustomization.yaml

rh02 use our new architecture which doesn't include kubesaw. This requires creating ClusterRole that we be later assigned to Konflux users so they can use the system.

KFLUXINFRA-1131: RBAC manifests for rh02

---

components/crossplane-config/base/rbac.yaml
components/crossplane-control-plane/staging/provider-config.yaml

Our XNamespace composition references the ProviderConfig by a different name. It also assigns the `edit` ClusterRole so `crossplane-sa` must also be granted these permissions.

Fix the crossplane RBAC and staging ProviderConfig

---

components/authentication/base/everyone-can-view-patch.yaml

There are people supporting Konflux that do not belong to any official Konflux team that we want to grant view access to our clusters. A new rover group was created to put those people in so grant view role to that new group.
[KFLUXINFRA-1173](https://issues.redhat.com//browse/KFLUXINFRA-1173)

Grant everyone can view role to konflux-support

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The other tekton controllers processing pipelineRun have 4 replicas with 32 threads each. Results watcher only has one replica with 2 thread. Try to increase the processing capacity of watcher by configuring number of threads. The other options we use normally (qps and burst) cannot be configured yet as the version of results in production does not support them.
[KFLUXINFRA-1115](https://issues.redhat.com//browse/KFLUXINFRA-1115)

Increase results-watcher number of threads

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This prevent the operator from generating TektonConfig on start. Instead the TektonConfig stored in Git is used. This lead to race conditions in the past and we must have single source of truth (git).

Disable OSP operator TektonConfig generation

---

components/release/base/monitor/staging/configmap.yaml
components/release/base/monitor/staging/kustomization.yaml
components/release/base/monitor/staging/patches/env-secrets-patch.yaml

this PR adds the secret reference so the release-monitor can use it to check the release required endpoints

chore: add secret information to release-monitor

---

components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml

As part of the migration to the Logging Operator v6.0, the spec to define the Splunk key was changed; this reconciles our definition with the new spec.

KFLUXBUGS-1610 - Logging Operator update -  Update Splunk secret object to secretName & key

---

components/release/base/monitor/staging/patches/env-secrets-patch.yaml

this PR adds the reference of the pyxis cert/key to the release-monitor-service

chore: adding pyxis secret reference

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Looks like IBM cannot handle 50 (and even more so 100)  VM's in the single DC. The empiric value which work is about 30 VMs, if continue to start more VM they're dropping into `failed` state.

Reduce mumber of IBM VM's for Ocp-Art cluster account

---

components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/ui/production/kflux-ocp-p01/kustomization.yaml
components/ui/production/stone-prod-p02/kustomization.yaml

Reverts redhat-appstudio/infra-deployments#5169
kflux-ocp-p01 stone-prod-p02 do not support Application CRD. We need a different way to deploy Vector.

Revert "Update results prod internal"

---

argo-cd-apps/base/member/infra-deployments/konflux-info/konflux-info.yaml
argo-cd-apps/base/member/infra-deployments/konflux-info/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
components/konflux-info/base/kustomization.yaml
components/konflux-info/base/rbac.yaml
components/konflux-info/production/kflux-ocp-p01/info.json
components/konflux-info/production/kflux-ocp-p01/kustomization.yaml
components/konflux-info/production/kflux-prd-rh02/info.json
components/konflux-info/production/kflux-prd-rh02/kustomization.yaml
components/konflux-info/production/stone-prd-rh01/info.json
components/konflux-info/production/stone-prd-rh01/kustomization.yaml
components/konflux-info/production/stone-prod-p01/info.json
components/konflux-info/production/stone-prod-p01/kustomization.yaml
components/konflux-info/production/stone-prod-p02/info.json
components/konflux-info/production/stone-prod-p02/kustomization.yaml
components/konflux-info/staging/stone-stage-p01/info.json
components/konflux-info/staging/stone-stage-p01/kustomization.yaml
components/konflux-info/staging/stone-stg-rh01/info.json
components/konflux-info/staging/stone-stg-rh01/kustomization.yaml

Expose a configmap which is readable by all authenticated users that contains public information about the Konflux instance.
This information, for example, can be used by the UI, instead of hardcoding it in the UI codebase.

KFLUXINFRA-1183: Public Konflux information

---

components/cluster-as-a-service/base/argocd.yaml

The default limit of 2Gi results in OOMKilled errors in production.

Increase memory limit for EaaS argocd controller

---

components/crossplane-control-plane/base/configmap.yaml
components/crossplane-control-plane/base/cronjob.yaml
components/crossplane-control-plane/base/kustomization.yaml
components/crossplane-control-plane/base/rbac.yaml

Delete crossplane namespace claims periodically to prevent the compute provided.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-128

chore(KFLUXVNGD-128): Delete old crossplane namespace claims

---

components/authentication/base/grafana-view-only.yaml
components/authentication/base/kustomization.yaml

This Pull Request will do the following -
- Create a Cluster Role to provide view only access to in-cluster grafana
- Create a ClusterRoleBinding to allow users (part of konflux-grafana-viewers rover group) to use the Cluster Role

KFLUXINFRA-1129: View Only Cluster Role for in-cluster Grafana

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

- this has a fix for the bundle size limit hit
- this comes with pipeline 0.66.0 (https://github.com/tektoncd/pipeline/releases/tag/v0.66.0)
- this comes with pac 0.30.0 (https://github.com/openshift-pipelines/pipelines-as-code/releases/tag/v0.30.0)

Update OSP to 5.0.5-555 on staging

---

components/monitoring/grafana/base/grafana-app.yaml

Fix in-cluster grafana permissions to allow users of rover group `konflux-grafana-viewers` to have view-only access to the in-cluster grafana.
Related Pull Request -
- https://github.com/redhat-appstudio/infra-deployments/pull/5188

fix(KFLUXINFRA-1129): Fix in-cluster grafana permissions

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Remove enable-tekton-oci-bundles from production clusters. This configuration options was removed in Tekton v0.61.0.

Remove enable-tekton-oci-bundles TektonConfig

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

installer-terraform image takes a significant amount of time to build (for non-amd64 arches), and for ARM in requires the bigger disk. hence creating a CPU optimized flavor, which will result in faster speeds when compared to `linux-d160/arm64`

[OCP] Create new linux-d160-cxlarge/arm64 flavor

---

components/pipeline-service/base/rbac/kustomization.yaml
components/pipeline-service/base/rbac/tekton-logging/kustomization.yaml
components/pipeline-service/base/rbac/tekton-logging/pipeline-service-sre.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The way the Vector pods are deployed today it happened that when a new version was deployed, we ended up with 2 DaemonSets, with the pods of the old DaemonSets running and blocking the pods of the new DaemonSet. Deleting the DaemonSet/pods allowed the new DaemonSet to spawn its own pods. We need that flexibility as managers of the service.

Allow pipeline-service to delete logging pods

---

components/backup/production/kflux-prd-rh02/backup-s3-credentials-patch.yaml
components/backup/production/kflux-prd-rh02/backup-tenants-schedule.yaml
components/backup/production/kflux-prd-rh02/dpa-bucket-patch.yaml
components/backup/production/kflux-prd-rh02/dpa-kmskeyid-patch.yaml
components/backup/production/kflux-prd-rh02/kustomization.yaml

This Pull Request will configure the backup for newly provisioned cluster `kflux-prd-rh02`.
This Cluster is hosting `toolchain-member-operator` as well as `toolchain-host-operator`, this backup targets both of them.

KFLUXINFRA-1154: Configure Backup for kflux-prd-rh02

---

components/authentication/base/grafana-view-only.yaml

This pull request will create a ClusterRole and a Namespace specific RoleBinding to allow the users of konflux-grafana-viewers rover group to view the grafana dashboards. This will be a read-only access to the in-cluster grafana dashboards.

KFLUXINFRA-1129: In-Cluster Grafana Dashboard Access

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

The deployment Prometheus label is needed for monitoring project-controller's availability in RHOBS.

chore(KFLUXVNGD-136): export label deployment

---

components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
components/multi-platform-controller/production/stone-prd-rh01/manager_resources_patch.yaml

We have an issues where too many TaskRuns are causing the pod to use too much memory and be OOMKilled.

Temporarily increase MPC memory on rh01

---

components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml

Grant the appstudio-pipelines-runner serviceaccount permission to manage
namespaces.eaas.konflux-ci.dev resources.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-93

chore(KFLUXVNGD-93): Grant appstudio-pipelines-runner permissions to manage namespaces

---

components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This updates Results on the external prod clusters. Includes update allowing the pipelines service team to manage the Vector pods.

Update Results ext prod clusters

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kyverno/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/kyverno/staging/values.yaml

Kyverno policies will be added in a future PR.

add kyverno to staging

---

components/notification-controller/production/topic_region_add.yaml

The new definitions only apply for dev and stage, the production environment remains the same for now and therefor should not been updated.

revert production patch for notification-service

---

argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
components/kyverno/staging/values.yaml

Argocd doesn't do template substitution when determining the location of helm's values files, which we were relying on to pick up the values file for the helm chart.  To fix this, specify the values in the ApplicationSet itself.

kyverno: specify values inline

---

components/build-service/production/base/manager_resources_patch.yaml
components/build-service/staging/base/manager_resources_patch.yaml

The investigation was done by perf team and the result is [this issue](https://issues.redhat.com/browse/KONFLUX-5911) which this PR fixes.

Increase Build Service memory request to be bigger than actual average usage

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/namespace-lister/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/namespace-lister/OWNERS
components/namespace-lister/base/deployment.yaml
components/namespace-lister/base/kustomization.yaml
components/namespace-lister/base/namespace.yaml
components/namespace-lister/base/nginx.conf
components/namespace-lister/base/patches/with-header-auth.yaml
components/namespace-lister/base/proxy.yaml
components/namespace-lister/base/rbac.yaml
components/namespace-lister/base/route.yaml
components/namespace-lister/base/service.yaml
components/namespace-lister/staging/stone-stg-rh01/kustomization.yaml
components/namespace-lister/staging/stone-stg-rh01/rbac.yaml

This is largely for testing purposes, to see if this deployment configuration is functional.  As such, we're only going to deploy this to one of the member clusters for the time being, and we're not going to integrate this with the UI's nginx config until we have a stable deployment.

add namespace-lister deployment to staging

---

argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml

Occasionally, when reconciling some of Kyverno's CRDs, we get events that look like the following:
> CustomResourceDefinition.apiextensions.k8s.io "clusterpolicies.kyverno.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
According to [upstream documentation][1], it's because argocd by default uses `kubectl apply`, which stuffs the resource into the annotations metadata.  If the resource is too large, it'll be rejected by kubernetes for being larger than the annotations space allocated (262144 bytes).
Upstream recommends we use `Replace=true` as a sync option within the ApplicationSet as a workaround, but it appears there are a few places within argocd that don't acknowledge that setting.  They also recommend that server-side apply would also work as a …

kyverno: use server-side apply

---

components/namespace-lister/base/kustomization.yaml

Currently, when we generate the configmap for the proxy, kustomize will automatically append a hash to its name.  This breaks the proxy deployment, since it looks for a configmap with a specific name.
We can fix this either by disabling name suffix hashing or by injecting the name via a replacement.  The former is easier to implement, so opt to implement that method.

namespace-lister: disable configmap name suffix hashing

---

components/konflux-info/staging/stone-stg-rh01/info.json

The information will be used by the UI when
rendering the user access page and when creating
role bindings for users.

stage: Add RBAC details to konflux-public-info cm

---

components/cluster-as-a-service/base/clustertemplates.yaml

This removes unneccessary retries during cluster creation.

Bump hypershift-aws-template to 0.1.4

---

components/kubearchive/staging/database-secret.yaml

In 3586dfc28a8d4a90a782dcdf9fb1fce2cf4172e4, the key to extract the secret from was updated from:
```
- key: integrations-output/terraform-resources/appsres09ue1/stonesoup-infra-stage/kube-archive-staging-rds
```
to:
```
- key: |
integrations-output/terraform-resources/appsres09ue1/stonesoup-infra-stage/kube-archive-staging-rds
```
This was the cause of External Secret failing to extract value from vault, revert to what it was before.

Fix staging kubearchive external secret

---

components/pipeline-service/development/kustomization.yaml

By default the Minio images are pulled from docker.io, which makes the CI fail when the pull limit is reached. Use quay.io instead.

Update refs to Minio images

---

components/konflux-ci/base/repository.yaml
components/tekton-ci/base/repository.yaml

Update references to redhat-appstudio quay org to reflect move to konflux-ci.

feat(STONEINTG-948): Migrate redhat-appstudio/clair-in-ci

---

argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
components/konflux-rbac/staging/base/kustomization.yaml
components/konflux-rbac/staging/empty-base/kustomization.yaml
components/konflux-rbac/staging/stone-stg-rh01/kustomization.yaml

The cluster roles will be used for granting
permissions to users after we stop using kubesaw.
Right now those roles are needed by the UI team
for testing changes they make to the UI.

Deploy konflux-rbac to public staging

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

Optimized the vector configuration to avoid missing logs.

[Staging] Optimizing Vector Configuration to avoid missing logs

---

components/multi-platform-controller/production-downstream/base/kustomization.yaml
components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml

Update includes:
- Configurable volumes sizes for IBM (s390/ppc64le)
- Logging improvements/cleanup
- Fix for routines context which may help with better VM cleanups

Promote latest MPC version from stg to prod

---

components/knative-eventing/base/kustomization.yaml

Followup for #5291, the controller keeps failing. I keep not being able to reproduce it locally. Sorry about it.

Increase memory for Eventing mt-broker-controller

---

components/cluster-as-a-service/base/clustertemplates.yaml

This removes the limit on retries when trying to destroy clusters.

Bump hypershift-aws-template to 0.1.5

---

components/knative-eventing/base/kustomization.yaml

I talked with the Eventing team and they have a fix, meanwhile the solution is to provide more memory. I don't want to keep trying values, so I opted to remove the limit for memory instead. What do you think? This will be removed and a limit will be established again when the fix is merged and then its released. I will keep an eye on this.

Remove limit for one knative eventing component

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Looks like 200 wasn't enough: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-ose-installer-artifacts-hr9d2

[OCP] Bumping ppc disk from 200 to 400 GB

---

components/konflux-ci/base/kustomization.yaml
components/konflux-ci/base/pod-logs-reader-role.yaml
components/konflux-ci/base/pod-logs-reader-rolebinding.yaml

In konflux-ci namespace, appstudio-pipeline SA needs pod reader role to archive e2e-tests logs.

fix: add pod reader role to appstudio-pipeline SA

---

components/integration/production/base/kustomization.yaml

Included PRs:
- https://github.com/konflux-ci/integration-service/pull/995
- https://github.com/konflux-ci/integration-service/pull/991
- https://github.com/konflux-ci/integration-service/pull/994
- https://github.com/konflux-ci/integration-service/pull/986
- https://github.com/konflux-ci/integration-service/pull/974
- https://github.com/konflux-ci/integration-service/pull/974
- https://github.com/konflux-ci/integration-service/pull/982
- https://github.com/konflux-ci/integration-service/pull/982
- https://github.com/konflux-ci/integration-service/pull/983
- https://github.com/konflux-ci/integration-service/pull/981
- https://github.com/konflux-ci/integration-service/pull/977
- https://github.com/konflux-ci/integration-service/pull/987
- …

Promote integration-service from staging to production

---

components/kubearchive/base/kustomization.yaml
components/kubearchive/development/postgresql.yaml

This PR upgrades KubeArchive to version v0.9.0 which among other things contains a change to accomodate for RDS requirements of encryption. This should unblock KubeArchive from its current state (which is infinite restarts due to not being able to connect to RDS).

Upgrade KubeArchive to v0.9.0: TLS fix

---

components/has/k-components/manager-resources/manager_resources_patch.yaml

Long term, application-service-controller-manager memory usage is above its requests which makes it very fragile when there is a memory pressure on the cluster.
Fixes [KONFLUX-5891](https://issues.redhat.com//browse/KONFLUX-5891)

Increase application-service requests nearer to current usage

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Since builds doesn't seem to be starting

[OCP] Increasing linux-d400-large-ppc64le.max-instances to 30

---

components/namespace-lister/base/deployment.yaml

Until TLS certificates have been configured, disable serving over https.

namespace-lister: disable https temporarily

---

components/mintmaker/base/rbac/mintmaker-team.yaml

The controller sometimes leaves undeleted temporary configmaps/secrets
from renovate pipelineruns when bug happens. Grant team full access
to configmaps and secrets in mintmaker namespace for better self-service
capability, as other secrets and configmaps are safely managed by ArgoCD.

mintmaker: add configmaps and secrets permissions for mintmaker team

---

components/monitoring/grafana/base/dashboards/cm-dashboard.yaml

This transformation does have invalid fields which are ignored by kustomize version < 5.4.0. Starting with 5.4.0, kustomize uses strict unmarsheling so kustomize build command is failing. This change is needed to upgrade from gitops 1.12 to 1.15 which include ArgoCD version which uses kustomize version 5.4.3
[KFLUXINFRA-1211](https://issues.redhat.com//browse/KFLUXINFRA-1211)

Remove invalid fields from monitoring kustomize transformation

---

components/openshift-gitops/subscription.yaml

Upgrading OpenShift GitOps to 1.15 for Development Overlay.

KFLUXINFRA-1211: Upgrade OpenShift GitOps to 1.15

---

components/has/OWNERS

We should have updated this a long while ago. The application-service maintainers have moved on and are working on other things these days.

Update HAS owners

---

components/konflux-ci/base/external-secrets/kustomization.yaml
components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml

This PR adding a quay secret needed to push the artifacts to `quay.io/konflux-test-storage/konflux-team/build-definitions` repo.
Part of the story: https://issues.redhat.com/browse/STONEBLD-3025

feat: Add quay secret to push test artifacts

---

components/mintmaker/development/kustomization.yaml
components/mintmaker/production/base/kustomization.yaml
components/mintmaker/staging/base/kustomization.yaml

This change includes the refactoring. MintMaker now uses PipelineRuns instead of jobs.
This commit also brings back stage to its usual state (it was recentely changed to point to another branch). It updates development too.

Promote MintMaker prod

---

components/knative-eventing/OWNERS
components/kubearchive/OWNERS

Adding mafh413 and maruiz93, contributors of kubearchive as owners of kubearchive and knative components in konflux

Add maruiz93 and mafh314 as owners of kubearchive and knative

---

components/mintmaker/production/base/manager_patch.yaml

We are experiences memory peaks, it might happen to reach the limit in high cluster loads period. Let's increase the memory a bit to prevent the pod from crashing.

Improve MintMaker memory resources

---

components/mintmaker/production/base/kustomization.yaml
components/mintmaker/staging/base/kustomization.yaml

These PRs are in this update:
- https://github.com/konflux-ci/mintmaker-renovate-image/pull/88
- https://github.com/konflux-ci/mintmaker-renovate-image/pull/89
But most importantly we need a rebuild to fix [CWFHEALTH-3864](https://issues.redhat.com//browse/CWFHEALTH-3864)

Bump mintmaker-renovate-image

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This comes with:
- Tekton Pipelines: v0.66.0
- Tekton Triggers: v0.30.1
- Pipelines as Code: v0.31.0
- Tekton Chains: v0.23.0

Update OSP on staging

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This comes with:
- Tekton Pipelines: v0.66.0
- Tekton Triggers: v0.30.1
- Pipelines as Code: v0.31.0
- Tekton Chains: v0.23.0
Staging PR: https://github.com/redhat-appstudio/infra-deployments/pull/5409

Update OSP version on prod

---

argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

This reverts commit df73235785aa650efbd8afd975cf4141afa847b6.
Yesterday we discussed on "Konflux Performance WG weekly" that this NVMe permission problem is not up to Perf team to solve, so I'm going to stop looking into it, so we do not need it deployed on Stage.

Revert "KONFLUX-5670: Enable NVMe Disk Configuration (#5244)"

---

components/monitoring/prometheus/base/observability-operator/observability-operator.yaml

As detailed in this [KCS article](https://access.redhat.com/articles/7103797), the Observability Operator (OBO) will no longer be deployed automatically (by Hive) on ROSA clusters as of Jan 30th.
This means that the new Cluster Observability Operator (aka COO, the productized version of OBO), should be deployed on all Konflux clusters. 
Before rolling this out to production, we will test this only in the stone-stage-p01 cluster and validate. There will be a follow up PR where the production deployments will be added.

PVO11Y-4603 Deploy cluster observability operator

---

argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
components/kyverno/OWNERS
components/kyverno/staging/kyverno-values.yaml

Keeping the helm values inline to the applicationset is getting in our way, so we should move away from this if we can.
This copies the approach that the `tracing-workload-otel-collector` applicationset uses.

kvyerno: move helm values to file

---

components/namespace-lister/base/service.yaml

The servicemonitor will search for endpoints by label, and we're not setting any label on services, which will create endpoints.  This means that the servicemonitor isn't finding any metrics to use.
To fix this, apply the label that the servicemonitor is listening for.

namespace-lister: label service

---

components/konflux-ci/base/external-secrets/dockerhub-pull-secret.yaml
components/konflux-ci/base/external-secrets/kustomization.yaml
components/konflux-ci/base/serviceaccount.yaml

Cachi2 needs images from dockerhub and we are hitting rate limits from annonymous access

konflux-ci: add dockerhub pull secret

---

components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml

- when created this secret in the [last PR](https://github.com/redhat-appstudio/infra-deployments/pull/5377), target name was wrong
- added github-bot-token key in the secret, needed for interacting with github

fix: the target name of the test-artifacts-push-secret

---

components/konflux-ui/staging/base/proxy/nginx.conf
components/namespace-lister/base/deployment.yaml
components/namespace-lister/base/service.yaml

Namespace-lister now supports https connections, so use it instead of http.

Namespace-lister: use https instead of http

---

components/namespace-lister/base/metrics/monitor.yaml

The service monitor doesn't know anything about the service it's talking to in terms of TLS, so we need to provide the following information:
- A Certificate Authority for requests to authenticate against.
- A server name to verify that we're talking to the correct service.

namespace-lister: provide a tls config to ServiceMonitor

---

components/monitoring/prometheus/README.md
components/monitoring/prometheus/production/base/kustomization.yaml
components/monitoring/prometheus/staging/base/kustomization.yaml
components/monitoring/prometheus/staging/stone-stage-p01/kustomization.yaml

Observability Operator will no longer be installed by default on ROSA clusters starting Jan 30th 2025. Deploy Cluster Observability Operator, a productized version of OBO, in both stage and prod to keep the related Resources synchronized.

PVO11Y-4603 Install Cluster Observability Operator in stage and prod

---

components/release/production/kustomization.yaml

Included PRs:
- https://github.com/konflux-ci/release-service/pull/656
- https://github.com/konflux-ci/release-service/pull/658
- https://github.com/konflux-ci/release-service/pull/657
- https://github.com/konflux-ci/release-service/pull/652
- https://github.com/konflux-ci/release-service/pull/651
- https://github.com/konflux-ci/release-service/pull/648
- https://github.com/konflux-ci/release-service/pull/646
- https://github.com/konflux-ci/release-service/pull/647
- https://github.com/konflux-ci/release-service/pull/644
- https://github.com/konflux-ci/release-service/pull/641
- https://github.com/konflux-ci/release-service/pull/640
- https://github.com/konflux-ci/release-service/pull/639

Promote release-service from staging to production

---

components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml

during argo sync of this ExternalSecret..  resource is degraded with this error 
```
could not apply template: could not execute template: could not execute template: unable to execute template at key github-bot-commenter-token: unable to parse template at key github-bot-commenter-token: template: github-bot-commenter-token:1: bad character U+002D '-'
```
`-` character in the key name is causing the issue, so changed key name to use `_` instead.

fix: the secret key name and use `_` instead

---

components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml

Still we are getting this error
```
could not apply template: could not execute template: could not execute template: unable to execute template at key github-bot-commenter-token: unable to parse template at key github-bot-commenter-token: template: github-bot-commenter-token:1: bad character U+002D '-'
```
Removing the template part and use the secret as it is.

fix: remove template part from the external secret

---

components/namespace-lister/base/deployment.yaml
components/namespace-lister/base/kustomization.yaml

this PR releases some namespace-lister's performance improvements to staging for testing purposes

bump namespace-lister in staging

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

This is to resolve missing logs issue.

[Staging] Change Tekton Vector collection to in-memory and ack enabled

---

components/enterprise-contract/ecp.yaml

This removes the need to keep bumping the version
with automation. Instead the floating tag will
be updated after each update to ec-policies and
once that update has passed the EC CI in the
ec-policies repo.
For background:
https://issues.redhat.com/browse/EC-884
https://issues.redhat.com/browse/EC-952
Ref: [EC-951](https://issues.redhat.com//browse/EC-951)

Replace ec-release-policy tag with floating tag

---

components/vector-tekton-logs-collector/production/vector-helm-values.yaml

This is to resolve missing logs issue.

[Prod] Change Tekton Vector collection to in-memory and ack enabled

---

argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

Kyverno's deployments in the existing staging environments have stabilized at this point, so it's safe to continue the rollout to the rest of the staging clusters.

kyverno: rollout to all staging clusters

---

components/ui/production/kflux-ocp-p01/kustomization.yaml
components/ui/production/stone-prod-p01/kustomization.yaml
components/ui/production/stone-prod-p02/kustomization.yaml
components/ui/staging/kustomization.yaml

Repository: openshift/hac-dev
Changes between de23e42 and 198c611
- openshift/hac-dev#1033 feat([KFLUXUI-256](https://issues.redhat.com//browse/KFLUXUI-256)): support component.spec.containerImage as latestImage by @testcara [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1033))
- openshift/hac-dev#1035 fix: unblock component list loading from pipeline runs by @sahil143 [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1035))
- openshift/hac-dev#1034 fix: ec regex to extract voilation reports from tkn logs by @sahil143 [`lgtm,approved`] ([PR](https://github.com/openshift/hac-dev/pull/1034))

chore: udpate hac-dev to latest

---

components/sandbox/toolchain-host-operator/base/monitoring/kustomization.yaml
components/sandbox/toolchain-host-operator/base/monitoring/monitor.yaml
components/sandbox/toolchain-host-operator/base/monitoring/prometheus-network-policy.yaml
components/sandbox/toolchain-host-operator/base/monitoring/rbac.yaml
components/sandbox/toolchain-host-operator/base/monitoring/sandbox-registration-service-proxy.yaml
components/sandbox/toolchain-host-operator/base/monitoring/serviceaccount.yaml

update sandbox host-operator's ServiceMonitor

---

.tekton/mintmaker-prod-overlay-update.yaml

Add PipelineRun to automatically promote changes from staging to production.
When mintmaker staging kustomization.yaml is updated, the pipeline:
- Updates production kustomization.yaml with corresponding SHAs from staging
- Creates a pull request if any SHAs have changed
This automates the staging to production promotion workflow for mintmaker.

mintmaker: add staging to production promotion pipeline

---

components/monitoring/prometheus/base/observability-operator/observability-operator.yaml

This should prevent out-of-memory Pod killing of the Obervability Operator deployed by the Cluster observability operator.
This has a side effect of increasing limits of all pods managed by this operator.

PVO11Y-4624 Increase COO resource limits

---

components/kubearchive/base/kubearchive-maintainer.yaml
components/kubearchive/base/rbac.yaml

KubeArchive maintainers need permissions to
read the kubearchive resources clusterwide.

Add read perms of kac resources

---

components/monitoring/logging/staging/base/configure-clusterlogging.yaml

ArgoCD deployment fails with: Resource not found in cluster: observability.openshift.io/v1/ClusterLogging:cluster-logging
This fixes the incorrect apiVersion.

KONFLUX-5876 Fix incorrect apiVersion

---

components/monitoring/logging/staging/base/configure-clusterlogging.yaml

Changes do not seem to take effect on Pods. [Review of installation documentation](https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/logging/cluster-logging-deploying#logging-es-deploy-cli_cluster-logging-deploying) shows that the name of the resource must be set to "instance".

KONFLUX-5876 Correct the name of ClusterLogging

---

components/kubearchive/base/kustomization.yaml

KubeArchive's operator is being OOMKilled, it needs more memory. We don't know why this is the case, in theory nothing points to increased memory usage with increased cluster size, but looks like that is the problem.

KubeArchive: increase operator memory limit

---

components/authentication/base/konflux-admins.yaml

- the konflux-admin group should be able to patch releases.status

chore: konflux-admin can patch release status

---

components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml

This permissions is required in order tail logs
using opc.

Allow namespace admins to list and watch pods

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

For https://github.com/openshift-eng/ocp-build-data/pull/6096
Also includes a naming fix, where a PPC VM was named as `d400` when it configured for `d200`

[OCP] New c4xlarge VM flavor with higher disk space

---

components/kubearchive/development/postgresql.yaml

Based on [this issue](https://github.com/kubearchive/kubearchive/issues/806) the version of kubearchive database in the dev environment is upgraded from 16.2 to 16.6
Also, after trying the YAML out, I've seen that the `POSTGRESQL_REPLICATION_USE_PASSFILE` env var is expected to be a string and not a bool, so I've added quotes around to make it work.

Update postgres dev version

---

components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

When determining if a particular VM instance can be created, the VM flavor's maximum number of instances is compared to the current number of instances with the same `instance-tag` to ensure no more than the maximum number of VMs are created. Since the current configurations have all flavors using the same instance tag, the count of unique instances (flavors, in this case) is wrong. Adding per-platform/flavor instance tags should fix this.

Add per-platform instance tags

---

components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prd-m01/resources/tekton-results-s3-secret-path.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-s3-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-s3-secret-path.yaml

APPSRE is decommissioning appsre[s/p]07ue1 clusters. The namespaces and secrets were created already on new clusters, this PR is making us of them so we can delete the ones from former clusters after.
[KFLUXINFRA-1265](https://issues.redhat.com//browse/KFLUXINFRA-1265)

Use secrets from appsre[s/p]11ue1 cluster

---

components/monitoring/grafana/base/dashboards/release/kustomization.yaml
components/release/development/kustomization.yaml
components/release/development/release_service_config.yaml
components/release/production/release_service_config.yaml
components/release/staging/kustomization.yaml
components/release/staging/release_service_config.yaml

- the rsc needs to managed outside of the release
service so that clusters can have a specific version
for testing.
- A version can be deployed and managed by ArgoCD
via infra-deployments for a specific environment
- This PR only affects the development overlay
- includes contents of PR https://github.com/redhat-appstudio/infra-deployments/pull/5541

fix(RELEASE-1441): allow rsc in development

---

components/smee-client/base/deployment.yaml

The usage can peak to a bit more that 500Mi, set requests=limits=750Mi to guarantee that amount of memory and avoid container being OOMKilled.
[KONFLUX-5728](https://issues.redhat.com//browse/KONFLUX-5728)

Increase memory requests/limits of smee-client

---

components/konflux-ui/OWNERS
components/ui/OWNERS

Added OWNERS file for konflux-ui

add OWNERS for ui

---

components/namespace-lister/base/metrics/monitor.yaml

We don't label any of our services with the `apps: namespace-lister-metrics` label, so we shouldn't be using it in our service monitor to watch for metrics.

use correct label selector for metrics

---

components/cluster-as-a-service/base/clustertemplates.yaml
components/cluster-as-a-service/base/kustomization.yaml
components/cluster-as-a-service/base/priorityclass.yaml

Must only be merged after https://github.com/konflux-ci/cluster-template-charts/pull/18.

Over-provision ephemeral cluster control planes

---

components/multi-platform-controller/staging/host-config.yaml

In order to inexpensively test that the new per-platform instance tags added in a previous commit properly limit the number of instances running, the s390x and arm64 VM flavor maximum instances are temporarily decreased in staging. This will allow for verification that only the total number of instances of a specific "flavor" controls whether the maximum number of instances of that "flavor" has been reached.

Temporarily decrease max instances for testing

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

To provide faster Results API service to Konflux clients (UI and CLI), we create two separate deployments, one for the Results watcher and one for the Konflux clients.

Split Tekton Results API load

---

components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

Testing was blocked on the external staging cluster due to an unrelated
network issue. This reverts the maximum number of instances back to their
original values on the external cluster and decreases them to testable
values in the internal cluster.

Revert decrease on external & decrease on internal

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

A previous PR introduced that change, which was properly configured in the development overlay (CI), but not in the staging overlay.

Fix split Results API service staging

---

components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml

Implements [ASC-778](https://issues.redhat.com//browse/ASC-778)
Admins have access today to manage SAs and their permissions via kubesaw tiers. Making sure this stay consistent after migration. Corresponding ADR PR sent https://github.com/konflux-ci/architecture/pull/224

Provide access for admins to manage SAs

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The Results API service was split into two services. This fixes the certificate of the new service.

Fix Results API cert after service split

---

components/multi-platform-controller/staging-downstream/host-config.yaml

Testing has been completed regarding the maximum number of instances for a particular VM flavor, so this reverts the maximum number of instances back to their original values on the internal cluster.

Revert max instances decrease on internal

---

components/cluster-as-a-service/base/clustertemplates.yaml

This is currently causing issues with cleanup in production.
The recently upgraded ArgoCD no longer requires the workaround. The apps are getting stuck in the deleting state while the argocd controllers endlessly append duplicate entries to the finalizers list.

Remove finalizer workaround for cluster templates

---

components/kubearchive/base/rbac.yaml

Grant them admin access in the namespace where they deploy their application. This is needed to troubleshoot an issue on staging.

Grant admin access to kubearchive team

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Split Tekton Results API Service into two instances, one to service the Tekton Results Watcher and the other one for the Konflux UI + CLI. This will improve the experience for the Konflux users.

Split Tekton Results API service prod

---

components/konflux-ui/OWNERS

These permissions are temporary.
The konflux-core team will take care of deploying the new UI to all the clusters and then revert them

give konflux-core team ownership over konflux-ui

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml

The issue did not actually affect development, but we've seen it in staging. This brings the development overlay in sync with staging.

Fix Results API cert after service split - development

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Splitting the load of the Results API service, switched the watcher/controller related request  to a new pod which handles most of the load. With the original service now used only by users, it gets much less load (that was the purpose), but it triggers some false positives from the monitoring service. Here we switch the ServiceMonitor to the new pods running most of the load.

Read Results API service metrics from api-for-watcher

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The Service Monitor for Tekton Results needs to label with `job: tekton-results-api` since pagerduty alerts and grafana dashboards both depend on the `job` label. However the monitor needs to match both the normal `tekton-results-api` service as well as the new "writer" service `tekton-results-api-for-watcher`.
This PR adds the `app` and `app.kubernetes.io/component` labels to all `tekton-results` services, similar to what is done for tekton chains, in order for the ServiceMonitor to correctly match both API services and not the Watcher service.

Refactor results api labels and service monitor

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

After splitting the workload betwen two services, this updates the ServiceMonitor to monitor both.

Pull Results API metrics from both Services

---

components/monitoring/grafana/staging/kustomization.yaml

This is to make sure that the current peak (according to ticket) exists under the requested value to avoid issues when there is a memory pressure on the cluster, causing downtime.

[KONFLUX-5918] Declare resources grafana operator

---

components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

This pull request will add `c6gd.2xlarge` instance type for ARM64 Platform Builds, this instance type has a local NVMe Disk of 400GB attached. This disk will be configured and mounted during runtime to `/vat/tmp` and other directories and this should us enough enough room in `/var/tmp` directory.

KFLUXSPRT-1907: Adding New ARM Instance Type for Multi-Platform Build

---

argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
components/namespace-lister/empty-base/kustomization.yaml
components/namespace-lister/production/base/deployment.yaml
components/namespace-lister/production/base/kustomization.yaml
components/namespace-lister/production/base/metrics/kustomization.yaml
components/namespace-lister/production/base/metrics/monitor.yaml
components/namespace-lister/production/base/metrics/network_policy.yaml
components/namespace-lister/production/base/metrics/rbac.yaml
components/namespace-lister/production/base/metrics/service-account.yaml
components/namespace-lister/production/base/namespace.yaml
components/namespace-lister/production/base/network_policy.yaml
components/namespace-lister/production/base/patches/with-header-auth-email.yaml
components/namespace-lister/production/base/patches/with_cachenamespacelabelselector.yaml
components/namespace-lister/production/base/patches/with_header_auth_user.yaml
components/namespace-lister/production/base/rbac.yaml
components/namespace-lister/production/base/service.yaml
components/namespace-lister/production/kflux-prd-rh02/kustomization.yaml

The deployments for namespace-lister appear to be stable on the relevant staging cluster (`stone-stg-rh01`), so we can begin to roll this out to the relevant production clusters.
For now, the only cluster we wish to deploy to is `kflux-prd-rh02`, since the component `konflux-ui` has not been deployed to any other production clusters yet.  All other clusters affected by the `konflux-public-production` overlay will see no new resources added to the cluster.
Adding namespace-lister to konflux-ui's production proxy config will come in a separate PR.

deploy namespace-lister to production rh02

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

The metric and label will be used to monitor the quota for hypershift clusters provisioned with Environment as a Service.

Remote write hypershift metrics to RHOBS

---

argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml

Kuebearchive is only deployed on staging clusters and there is an issue so disable the auto sync to allow modifying the deployment in staging to troubleshoot the issue. This change will be reverted once troubleshooting is done.

Temporarily disable sync of kubearchive application

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

New VM flavors for all arches, with 320 GB disk space

[KFLUXSPRT-1933] d320 VM flavors

---

argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/workspaces/production/stone-prd-rh01/kustomization.yaml
components/workspaces/production/stone-prod-p02/kustomization.yaml
components/workspaces/staging/stone-stage-p01/kustomization.yaml
components/workspaces/team/migration/kustomization.yaml
components/workspaces/team/migration/temp-workspace-team-rbac.yaml

Need this acces to be able to run and debug the migration tool before infra team applies the migrate role bindings.
Partially implements [ASC-726](https://issues.redhat.com//browse/ASC-726)

Adding temp access to workspace team to read RoleBindings

---

argo-cd-apps/overlays/production-downstream/kustomization.yaml

Without this patch, argocd tries to pull the production manifests from the staging environment, which is not correct.
Fixes #5634.

ns-lister: apply prod overlay patch for prod deployments

---

components/namespace-lister/base/kustomization.yaml

Main changes released by this bump are releated to cache instrumentation and to dependencies.
* https://github.com/konflux-ci/namespace-lister/pull/79
* https://github.com/konflux-ci/namespace-lister/pull/69
* https://github.com/konflux-ci/namespace-lister/pull/59
* https://github.com/konflux-ci/namespace-lister/pull/65
* https://github.com/konflux-ci/namespace-lister/pull/60
* https://github.com/konflux-ci/namespace-lister/pull/80
* https://github.com/konflux-ci/namespace-lister/pull/73
* https://github.com/konflux-ci/namespace-lister/pull/70
* https://github.com/konflux-ci/namespace-lister/pull/77
* https://github.com/konflux-ci/namespace-lister/pull/75
* https://github.com/konflux-ci/namespace-lister/pull/78
* https://github.com/konflux-ci/namespace-lister/pull/76
* …

bump namespace-lister to latest version in staging

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Testing to see if a shorter tag name will prevent this error from popping up
```
step-build
mkdir -p ~/.ssh
if [ -e "/ssh/error" ]; then
#no server could be provisioned
cat /ssh/error
exit 1
fi
Error allocating host: bad request
Context info:
Platform: linux-d320-largecpu/ppc64le
File:     /opt/app-root/src/pkg/reconciler/taskrun/taskrun.go
Line:     457
```
ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1740584497902059?thread_ts=1740531053.708299&cid=C06Q309QUDV) for details

[OCP] update IBM tags

---

components/cost-management/base/external-service-account-secret.yaml
components/cost-management/staging/cost-mangement-external-secret-patch.yaml
components/cost-management/staging/kflux-stg-es01/cost-management-config-source-patch.yaml
components/cost-management/staging/kustomization.yaml
components/cost-management/staging/stone-stage-p01/cost-management-config-source-patch.yaml
components/cost-management/staging/stone-stg-host/cost-management-config-source-patch.yaml
components/cost-management/staging/stone-stg-rh01/cost-management-config-source-patch.yaml

PVO11Y-4650 - This is required to enable access the Konflux clusters data via service account to avoid needing OCM permissions. 
This should be merged after - https://issues.redhat.com/browse/KFLUXINFRA-1307

Add cost-management staging external secret

---

components/cost-management/base/kustomization.yaml
components/cost-management/production/cost-mangement-external-secret-patch.yaml
components/cost-management/production/kflux-ocp-p01/cost-management-config-source-patch.yaml
components/cost-management/production/kflux-prd-es01/cost-management-config-source-patch.yaml
components/cost-management/production/kustomization.yaml
components/cost-management/production/stone-prd-host1/cost-management-config-source-patch.yaml
components/cost-management/production/stone-prd-rh01/cost-management-config-source-patch.yaml
components/cost-management/production/stone-prd-rh02/cost-management-config-source-patch.yaml
components/cost-management/production/stone-prod-p01/cost-management-config-source-patch.yaml
components/cost-management/production/stone-prod-p02/cost-management-config-source-patch.yaml

PVO11Y-4650 - This is required to enable access to the production Konflux clusters data via the service account to avoid needing OCM permissions.
This should be merged after - https://issues.redhat.com/browse/KFLUXINFRA-1309

Add cost-management prod external secret

---

components/monitoring/prometheus/base/observability-operator/observability-operator.yaml

Red Hat catalog provides the COO operator now has a stable channel only.

PVO11Y-4655 - Update COO channel to stable

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml

This change is required for cost-management metrics operator to access the secret stored in vault.

PVO11Y-4650 - Add costmanagement-metrics-operator ns to cluster-secret-store

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Since 250 GB is the max limit for now. This VM to be used for ose-installer-artifacts

[OCP] linux-d250-largecpu variants

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

10 instances might be too low. Requesting the number to be at least the same as the default VM flavor

[ocp] increase default linux-large max-instances to 30

---

components/cost-management/base/kustomization.yaml
components/cost-management/base/rbac/cost-management-admin.yaml
components/cost-management/base/rbac/kustomization.yaml

Add role and rolebindings to manage cost-management operator

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Since `linux-d200-large-ppc64le` is working, we should be good with this new name `linux-d250-8x16-ppc64le`

[OCP] rename linux 250d variant

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

The batch max size is cutting logs short and the default value (which is also wrongly documented) cuts the logs at around 140KB size. With the value 524288000 I was able to store log files of size close to 10MB, which should be enough given the biggest step/container logs files I've encounted in Konflux are ~4.7MB.
Removed kubernetes_logs.max_read_bytes as it does not play a role in the logs storing and it was confusing.

Bump Vector (Results) batch max size

---

components/integration/OWNERS

This is because Pat has left the integration service team, and I would like to make his life a little bit better.
Signed-off-from: Dheeraj\<djodha@redhat.com>

chore: Remove Pat from integration-service's OWNERS file

---

argo-cd-apps/overlays/production-downstream/kustomization.yaml

We need to enable konflux-ui in the production clusters by applying the production overlay patch.

Enable konflux-ui on internal-production clusters

---

components/konflux-ui/staging/base/kustomization.yaml

Reverts redhat-appstudio/infra-deployments#5718/
Image is not released yet.

Revert "Deploy Namespaces to konflux-ui staging."

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

- Using bigger batches requires more memory
- Update batch max_bytes
- Remove internal_metrics source, not used by any sinc
- Remove S3 acknowledgements, not supported by the kubernetes_logs source

Tune Vector Results config

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging/host-config.yaml

An issue provisioning a c6gd2xlarge VM instance for the private staging cluster prompted a look at the host configuration for this platform. The AMI field for the private staging cluster in addition to instance tags for this platform are fixed in this commit.

Correct c6gd2xlarge platform host configurations

---

configs/etcd-defrag/base/cronjob.yaml

This change will pass the fragmentation thresold by environment variable to the debug pod

KFLUXINFRA-1269: Adding Environment Variable for ETCD Defragmentation

---

argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
components/namespace-lister/production/kflux-ocp-p01/kustomization.yaml

Deploys namespace-lister to the internal production cluster `ocp-kflux-p01`.

add namespace-lister to ocp-kflux-p01

---

hack/preview.sh

`mintmaker/development/kustomization.yaml` accumulates both `konflux-ci/mintmaker/config/default` and
`konflux-ci/mintmaker/config/renovate`. The original code results in the `config/renovate` is lost and `config/default` is accumulated twice.

fix: environment configuration for mintmaker in preview mode

---

components/namespace-lister/production/base/kustomization.yaml

Main changes released by this bump are releated to cache instrumentation and to dependencies.
Requires:

bump namespace-lister to latest version in production

---

components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml

There is no application-pipeline/ prefix here.

fix(KFLUXSPRT-2070): fix taskrun PaC url template for rh02

---

components/pipeline-service/development/kustomization.yaml

This PR aims to reduce the number of replicas specified for development related to the minio operator. Currently the replicas is set to 2, but the pods have a antiaffinity constraint in which they can't be in the same node as another pod called minio-operator. This results in the second replica not being deployed, leaving the deployment in a degraded state, so the `preview.sh` script can't progress.

Reduce minio replicas to 1 for development

---

components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json

The dashboard is only working in the external staging environment, removing the datasource should fix.

namespace-lister: remove datasource from grafana dashboard

---

components/crossplane-control-plane/base/kustomization.yaml

This change should fix an issue where ephemeral namespace names containing illegal dot characters couldn't be created.

Deploy latest crossplane configs

---

components/authentication/base/everyone-can-view.yaml
components/authentication/base/kustomization.yaml

Nodes, machines, machinesets and autoscallers resource are not aggregated in the view cluster role. Add these to our everyone can view roles.

Allow Konflux devs to see compute tab

---

components/namespace-lister/base/deployment.yaml
components/namespace-lister/base/kustomization.yaml

Add healthz and readyz checks, so that we have hooks to inform the pod controller if we're alive and if we're ready to serve requests.
Production clusters will follow in a separate PR.

namespace-lister: add healthz and readyz checks to staging

---

argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
components/kyverno/production/kflux-ocp-p01/kustomization.yaml
components/kyverno/production/stone-prd-rh01/kustomization.yaml
components/kyverno/production/stone-prod-p01/kustomization.yaml
components/kyverno/production/stone-prod-p02/kustomization.yaml

This enables the kyverno application on all clusters currently relevant to its deployment.  Enablement on each cluster will come in separate PRs.
This will save some time on review from the infra team, since enabling kyverno on each of the clusters won't require a review from them after this merges.

scaffold kyverno across all relevant clusters

---

components/mintmaker/base/rbac/mintmaker-team.yaml

Grant full pod control permissions to mintmaker-team within the mintmaker namespace.

mintmaker: grant pod management permissions to mintmaker-team

---

components/namespace-lister/production/base/kustomization.yaml
components/namespace-lister/production/base/network_policy_allow_from_konfluxui.yaml
components/namespace-lister/production/base/network_policy_allow_to_apiserver.yaml

This change allows the namespace-lister to only reach-out to the APIServer in production clusters

nslister: promote egress NetworkPolicy to prod

---

components/namespace-lister/production/base/deployment.yaml
components/namespace-lister/production/base/kustomization.yaml

Add healthz and readyz checks, so that we have hooks to inform the pod controller if we're alive and if we're ready to serve requests.

namespace-lister: add healthz and readyz checks to prod

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

To reduce the memory consumption and avoid OOM pod removal:
- Reduce the number of events by combining the log lines for multiple events into single event, avoiding storing the same event metadata for each event.
- Reduce the metadata we store for each event to only what's actually needed. Previously for each log line (~70 bytes), we were storing 3.5Kb and more of metadata.

Optimize Vector Results

---

configs/etcd-defrag/base/cronjob.yaml

This Pull request will add the successfulJobsHistoryLimit and change fragmentationThreshold to 15 percent for the testing purpose.

Add successfulJobsHistoryLimit to CronJob

---

components/cluster-as-a-service/base/clustertemplates.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml

This is to experiment without them in staging.
They should be avoided in development due to typical resource constraints.

Only enable pause pods in production

---

components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml

The job in charge of regenerating the secrets used for authentication was not restarting the proxy

konfluxui: fix job to create proxy's secrets

---

components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

This limits the Vector pods only to nodes used to run user pipelines.

Run Vector pods only on nodes running pipelines

---

components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml

ArgoCD errors synching the Job because the PodSpec is an immutable field.
This annotation will force the deletion of the job before creating the new version

konfluxui: add replace and force argocd annotation to job

---

components/vector-tekton-logs-collector/production/vector-helm-values.yaml

This limits the Vector pods only to nodes used to run user pipelines.

Run Vector pods only on nodes running pipelines prod

---

.chainsaw.yaml
.github/workflows/chainsaw-tests.yaml
.github/workflows/kube-linter.yaml
components/kyverno/chainsaw/kustomization.yaml
components/namespace-lister/base/kustomization.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-test.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-toolchain.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux-toolchain.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-toolchain.yaml
components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-unlabeled.yaml
components/namespace-lister/policies/ns-label/kustomization.yaml
components/namespace-lister/policies/ns-label/kyverno-background-konflux-ns-label-clusterrole.yaml
components/namespace-lister/policies/ns-label/namespace-enforce-label-clusterpolicy.yaml
hack/chainsaw/chainsaw-prepare.sh

This PR adds a kyverno ClusterPolicy to ensure that the new label used to identify tenant namespaces is present in already existing and new tenant namespaces.
The new label is `konflux-ci.dev/type: tenant` and will be added to every namespace with `toolchain.dev.openshift.com/type: tenant` (KubeSaw tenant namespaces) or `konflux.ci/type: user` (Workspace Manager tenant namespaces).
To test the ClusterPolicy, this PR introduces support for [kyverno chainsaw](https://github.com/kyverno/chainsaw).
A GitHub Action is added to run chainsaw as part of our CI. 

add kyverno policy for standardizing namespace's tenant label

---

components/cluster-as-a-service/base/clustertemplates.yaml
components/cluster-as-a-service/base/kustomization.yaml
components/cluster-as-a-service/base/priorityclass.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml

Testing in staging demonstrated that these pause pods didn't make much difference in overall performance and stability.

Disable pause pods in production for ephemeral cluster provisioning

---

components/tekton-ci/base/repository.yaml

The konflux-test repository was left over from the migration to konflux-ci.  The repository is no longer needed and is preventing the integration team from onboarding the konflux-test repo to konflux.

chore: remove konflux-test repository from tekton-ci namespace

---

components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

In order to simplify the documentation, add the flavors of VMs with larger disk on external prod so we no longer need to make distinction between internal and external in user documentation.

Add VMs with larger disks in RH01

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

We should have the same spec between environments for documentation simplicity but also for user experience, large in one environment should be the same on another one.

Align MPC VMs between p02 and rh01

---

argo-cd-apps/base/member/infra-deployments/release/release.yaml

this PR sets the ServerSideApply flag to argocd
syncOptions, to avoid errors syncing big chuncks
of text present in Release CRDs, that are added
to the object annotations.

 fix: add ServerSideApply to sync release-service

---

components/namespace-lister/base/patches/with_cachenamespacelabelselector.yaml

As  #5759 got merged, we can now rely on the new label in staging.

namespace-lister: filter by konflux-ci.dev label

---

.github/workflows/kyverno-policies-tests.yaml
components/kubearchive/development/kustomization.yaml
components/kubearchive/policies/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-kubeconfig-archive.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-toolchain.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
components/kubearchive/policies/.chainsaw-test/resources/expected-kubearchiveconfig.yaml
components/kubearchive/policies/.chainsaw-test/resources/kubearchive-crd.yaml
components/kubearchive/policies/.kyverno-test/kyverno-test.yaml
components/kubearchive/policies/bootstrap-namespace.yaml
components/kubearchive/policies/kustomization.yaml
components/kubearchive/policies/kyverno_rbac.yaml
components/kubearchive/policies/resources/expected-kubearchiveconfig-konflux.yaml
components/kubearchive/policies/resources/expected-kubearchiveconfig-toolchain.yaml
components/kubearchive/policies/resources/labeled-namespace-konflux.yaml
components/kubearchive/policies/resources/labeled-namespace-toolchain.yaml
components/kubearchive/staging/kustomization.yaml

This PR introduces a Kyverno policy in the development overlay to generate a KubeArchiveConfig in each tenant namespace.
As of now, tenant namespaces are labeled with either `toolchain.dev.openshift.com/type=tenant` or `konflux.ci/type=user`.
The PR also introduces a GitHub Action executing tests to validate the behavior of the proposed Generate Policy and provides to Kyverno the permissions required to generate the KubeArchiveConfigs.

kubearchive: add generate kyverno policy

---

components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml

Kyverno's background controller is getting OOMKilled. This change gives it more resources

kyverno: give more resources in prod rh01

---

.github/workflows/kube-linter.yaml

this PR updates the kustomize binary to 5.6.0 as
the current one (5.1.1) does not support the new
patching format.

feat: update kustomize binary

---

components/namespace-lister/production/base/patches/with_cachenamespacelabelselector.yaml

The new tenant label  has been rolled out in prod.
This PR configures the namespace-lister to use this one to filter namespaces

nslister: use the new tenant label in prod

---

components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

Pulling bitnami/kubectl from dockerhub directly may result in rate-limiting, since it appears docker wants users to have a subscription for pulling images.  To work around this for now, pull images via google's artifact registry mirror of dockerhub.
This registry will not be affected by the upcoming gcr.io outage.  See https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images for details on this mirror.

kyverno: pull kubectl from mirror.gcr.io in staging

---

components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

Like what we were seeing in stone-prd-rh01, the equivalent staging cluster doesn't have enough memory, so increase it.

kyverno: bump memory limits in stone-stg-rh01 to 1Gi

---

components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml

Pulling bitnami/kubectl from dockerhub directly may result in rate-limiting, since it appears docker wants users to have a subscription for pulling images.  To work around this for now, pull images via google's artifact registry mirror of dockerhub.
This registry will not be affected by the upcoming gcr.io outage.  See https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images for details on this mirror.

kyverno: pull kubectl from mirror.gcr.io in prod

---

components/integration/staging/base/manager_resources_patch.yaml

* increase integration stage memory limit since it met `OOMKilled` in [https://console-openshift-console.apps.stone-stg-rh01.l2vh.p1.openshiftapps.com/k8s/ns/integration-service/pods/[…]ler-manager-688576694b-shvsr/yaml](https://console-openshift-console.apps.stone-stg-rh01.l2vh.p1.openshiftapps.com/k8s/ns/integration-service/pods/integration-service-controller-manager-688576694b-shvsr/yaml)
```
containerStatuses:
- restartCount: 89
started: false
ready: false
name: manager
state:
waiting:
reason: CrashLoopBackOff
message: back-off 5m0s restarting failed container=manager pod=integration-service-controller-manager-688576694b-shvsr_integration-service(f3a99704-508c-4602-9136-cb09bb250374)
imageID: 'quay.io/konflux-ci/integration-service@sha256:ccd6960b2a54691d05d91f5d8c2ef80801256992b7fd15a …
```

increase integration stage memory limit

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml

Mintmaker SA has been granted the anyuid SCC becuase it needs to run its subscription-manager pod as root[1]. A side effect is that now it tries to run all of its pods as root by default. This is not secure and also conflicts with the setting runAsNonRoot: true, resulting in failing jobs. Explicitly run these cronjobs as a non-root user.
[1] https://github.com/konflux-ci/mintmaker/pull/222

Run Mintmaker DependencyUpdateCheck cronjobs as non-root

---

components/integration/development/kustomization.yaml
components/integration/staging/base/kustomization.yaml

rollback integration stage to version from intg pr 1048
* rollback integration development and stage to release
integration-service-lntnn-fcb8e94-plcl8 from
https://github.com/konflux-ci/integration-service/pull/1048

rollback integration development and stage to version from intg pr 1048

---

components/multi-platform-controller/staging-downstream/host-config.yaml

Create a various flavors of PPC machine, similar to what we have for amd and arm.
The main difference is ppc, we set the number or cores, which maps to virtual cores which maps to vCPU. So 0.25 core corresponds to the equivalent of 2 vCPU.

Create new flavors of ppc in internal staging

---

components/konflux-info/production/kflux-ocp-p01/info.json
components/konflux-info/production/kflux-prd-rh02/info.json
components/konflux-info/production/stone-prd-rh01/info.json
components/konflux-info/production/stone-prod-p01/info.json
components/konflux-info/production/stone-prod-p02/info.json
components/konflux-info/staging/stone-stage-p01/info.json

This data is used by the new UI to list the
available role users can use.

Add RBAC data to Konflux info for all clusters

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml

This reverts commit 1b94198aa9313c5579866a135783c90a4e2ba717.
Jobs are now not executable with user 1001120000 due to error:
unable to validate against any security context constraint ...

mintmaker: Revert mintmaker cronjobs security context change

---

components/integration/staging/base/manager_resources_patch.yaml

* Set the integration service staging memory memory requests equal to limits
* This helps avoid a scenario where the pod runs on a node that is already experiencing high memory usage, which could lead to the pod being killed

fix: set the integration staging memory requests equal to limits

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

- The update includes a new version produced by Konflux.
- Disable Tekton Results deployed automatically by the operator. Curently Results is deployed separately.

Update OSP dev and stage

---

components/integration/production/base/manager_resources_patch.yaml
components/integration/staging/base/manager_resources_patch.yaml

* Since the increased load and added functionalities are causing frequent restarts on staging and production clusters, increase the memory requirements and limits to 8192Mi

fix(KONFLUX-7357): increase integration service memory to 8gb

---

argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
components/kubearchive/base/kustomization.yaml

we released a new version of kubearchive and I updated the patches that we apply so that I didn't need to updated the previous gist. Also I re-enabled argocd sync for kubearchive

update kubearchive to v0.11.0 with the memory patch

---

components/multi-platform-controller/staging-downstream/host-config.yaml

There must be no space between the platform names.

Fix dynamic-platforms on stg-p01

---

argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

We got a request from ROSA SRE team to remove that from the master nodes to help with an ongoing issue on stg-rh01. Kepler must run on all the nodes so instead of trying to fix the issue, remove the whole component.
This power-monitoring was deployed even though could VMs are not well supported, and this is what we use. In addition, we do not want to run workloads that are not necessary which is the case for power monitoring, it is deployed but we do not absolutely need this, at least not for now.

Remove power monitoring from staging

---

components/vector-tekton-logs-collector/development/vector-helm-generator.yaml
components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-generator.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

The Helm chart used to deploy Vector reference the image stored in the Docker registry. With the image being pulled for each node running users' pipelines and CI jobs also pulling that image, we hit the rate limit on the Docker repo, fail to deploy Vector in a timely manner and miss logs from the users' pipelines. Here we switch to using image mirrored to Quay.

Use Vector mirrored image

---

components/release/production/kustomization.yaml

this PR updates the config of the release
service operator, to fix the configuration
for its metrics reachability.

fix: release operator config update

---

components/vector-tekton-logs-collector/production/vector-helm-generator.yaml
components/vector-tekton-logs-collector/production/vector-helm-values.yaml

The Helm chart used to deploy Vector reference the image stored in the Docker registry. With the image being pulled for each node running users' pipelines and CI jobs also pulling that image, we hit the rate limit on the Docker repo, fail to deploy Vector in a timely manner and miss logs from the users' pipelines. Here we switch to using image mirrored to Quay.

Use Vector mirrored image prod

---

components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json

This PR adds a panel in the namespace-lister Grafana Dashboard that shows the number of subjects stored in cache grouped by type

nslister-monitoring: add panel for subject types

---

components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
components/kubearchive/policies/bootstrap-namespace.yaml

Requires:
* #5645
This PR adds support for the new tenant label in the policy that generates the KubeArchiveConfig in each tenant namespace.

kubearchive's policy: add support for new tenant label

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

Standardize the VM flavors in PPC. Provide 2x8, 4x16, 8x32 and 16x64 VMs with both 100GB or 200GB.
CPU allocation on PowerPC does not work the same way as other architectures. Number of core is specified at the VM level, this maps to virtual core which maps to vCPU as each core/virtual core has 8 threads. Any fractional core gets rounded up to up to the nearest whole number. So 0.25 core gets rounded up to 1 virtual core/8vCPU but it will get 15 seconds per minute of CPU time making this the equivalent of a 2vCPU even of OS list 8 CPUs.

Add more PPc VM flavors in prod-p02

---

components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Standardize the VM flavors in PPC. Provide 2x8, 4x16, 8x32 and 16x64 VMs with both 100GB or 200GB.
CPU allocation on PowerPC does not work the same way as other architectures. Number of core is specified at the VM level, this maps to virtual core which maps to vCPU as each core/virtual core has 8 threads. Any fractional core gets rounded up to up to the nearest whole number. So 0.25 core gets rounded up to 1 virtual core/8vCPU but it will get 15 seconds per minute of CPU time making this the equivalent of a 2vCPU even of OS list 8 CPUs.

Add more PPc VM flavors in prd-rh01

---

components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml

Standardize the VM flavors in PPC. Provide 2x8, 4x16, 8x32 and 16x64 VMs with both 100GB or 200GB.
CPU allocation on PowerPC does not work the same way as other architectures. Number of core is specified at the VM level, this maps to virtual core which maps to vCPU as each core/virtual core has 8 threads. Any fractional core gets rounded up to up to the nearest whole number. So 0.25 core gets rounded up to 1 virtual core/8vCPU but it will get 15 seconds per minute of CPU time making this the equivalent of a 2vCPU even of OS list 8 CPUs.

Add more PPC VM flavors in prd-rh02

---

components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml

Similar as #5525 but giving maintainers and contributors these permissions to to tail logs (e.g. via `opc`).
As discussed in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1739344743638089?thread_ts=1739289575.061129&cid=C04PZ7H0VA8
/assign @gbenhaim @ralphbean @scoheb

Allow contributors and maintainers to list and watch pods

---

components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-toolchain.yaml
components/kubearchive/policies/.kyverno-test/kyverno-test.yaml
components/kubearchive/policies/bootstrap-namespace.yaml
components/kubearchive/policies/resources/expected-kubearchiveconfig-toolchain.yaml
components/kubearchive/policies/resources/labeled-namespace-konflux.yaml
components/kubearchive/policies/resources/labeled-namespace-toolchain.yaml

as https://github.com/redhat-appstudio/infra-deployments/pull/5759 and
https://github.com/redhat-appstudio/infra-deployments/pull/5812 got merged, we can
remove old labels from kubearchive's policy.

remove old ui labels from kubearchive's policy

---

components/konflux-ui/staging/base/proxy/proxy.yaml
components/konflux-ui/staging/stone-stage-p01/oauth2-proxy-args-patch.yaml
components/konflux-ui/staging/stone-stage-p01/remove-run-as-user-proxy-patch.yaml
components/konflux-ui/staging/stone-stg-rh01/oauth2-proxy-args-patch.yaml
components/konflux-ui/staging/stone-stg-rh01/remove-run-as-user-proxy-patch.yaml

remove workspaces manager from staging clusters

---

components/multi-platform-controller/staging-downstream/host-config.yaml

Creating large VMs does not work due to capacity issue, feature was backlogged to deal with this:
https://issues.redhat.com/browse/KONFLUX-7522

Remove 2 larger s390x VM size

---

components/smee/base/deployment.yaml

Based on https://issues.redhat.com/browse/SPRE-1255 and issue originated on https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1743183353400319?thread_ts=1743149867.743659&cid=C04PZ7H0VA8 we need to setup a livenesProbe to automate the process of restarting the Pod if failing for some reason

smee base - livenesProbe creation

---

argo-cd-apps/overlays/production-downstream/kustomization.yaml

The patch which sets the env for konflux-rbac
was missing in production-downstream.

Add missing env patch to konflux-rbac

---

components/release/development/release_service_config.yaml
components/release/production/release_service_config.yaml
components/release/staging/release_service_config.yaml

- use emptyDir for rh-push-to-registry-redhat-io-oci-ta.yaml

use emptyDir workspace for all oci-ta pipelines

---

components/release/base/kustomization.yaml
components/release/base/monitor-pipeline-role.yaml
components/release/base/release-pipeline-monitor-role.yaml

We want to create a service account that can be used by users to automate monitoring the status of their managed release pipelines. The thought for now is it will only require:
* get
* list
* watch
permissions for:
* pipelineruns
* pipelines
* pods
* pods/logs

Add Role For Monitoring Release Pipelines

---

components/smee-client/base/deployment.yaml
components/smee/base/deployment.yaml

Based on https://issues.redhat.com/browse/SPRE-1255, as well as for smee server, we need to set up a livenessProbe for the client.

smee-client - livenessProbe creation

---

components/kubearchive/staging/database-secret.yaml
components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml

[KFLUXINFRA-1412](https://issues.redhat.com/browse/KFLUXINFRA-1442): AppSRE has changed the integration that manages the Konflux RDS instances from `terraform-resources` to `external-resources`. This, in turn, requires a change to the vault secret paths for RDS instances in order to ensure the instances have the most up-to-date passwords.

Update staging RDS vault secret paths

---

components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/production/stone-prod-p02/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

AppSRE has changed the integration that manages the Konflux RDS instances from terraform-resources to external-resources. This, in turn, requires a change to the vault secret paths for RDS instances in order to ensure the instances have the most up-to-date passwords.

Update production RDS vault secret paths

---

components/monitoring/prometheus/base/rbac/monitoring-admin.yaml

Give the konflux-o11y-admins group additional access to allow debugging and fixing of Operator in broken state.

PVO11Y-4717 Add permissions to monitoring role

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Since we reduced number of core, there should be room for more, let's try.

Allow 50ppc VMs with default profile

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Since we reduced number of core, there should be room for more, let's try.

Allow 70ppc VMs with default profile

---

components/monitoring/prometheus/base/observability-operator/observability-operator.yaml

This should allow observability-operator pod to survive the initial memory spike before the usage stabilises. The largest memory spike was noted on the stone-prod-p02 cluster as 1.5Gi.
Sideffect of this is that this applies limits to ALL Operator pods, including prometheus-operator, perses-operator and webhook-admission.
This should not impact scheduling as limits are not considered during scheduling.
Existing proposal for configuring operator resource usage: https://github.com/operator-framework/operator-controller/issues/1507

PVO11Y-4717 Increase the limit to 4Gi

---

.github/workflows/chainsaw-tests.yaml

Chainsaw tests may leave artifacts on the cluster after executing tests, which might cause issues with later tests.  To address this, run each test suite independently and concurrently.
Fixes issues uncovered in #6062.

actions: run chainsaw tests concurrently

---

components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-appstudio-pipeline-clusterrole.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-rolebinding.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-rolebinding.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-rolebinding-appstudio-runner.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/resources/labeled-namespace-konflux.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/kustomization.yaml
components/konflux-ci/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
components/konflux-ci/staging/kustomization.yaml

this policy ensures that a rolebinding for the appstudio-pipeline-runner exists in every tenant namespace
Requires:

add policy to create appstudio-pipeline rolebinding in staging

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/vector-tekton-logs-collector/development/vector-helm-values.yaml
components/vector-tekton-logs-collector/staging/vector-helm-values.yaml

This updates Tekton Results to a version supporting multipart logs, enables that functionality in the configuration and sets Vector for storing logs with a timestamp suffix to prevent long running steps logs overriding.

Add support for Tekton Results multipart logs

---

.github/workflows/chainsaw-tests.yaml

> This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

use ubuntu-latest instead of ubuntu-20.04

---

components/konflux-rbac/OWNERS

add OWNERS for components/konflux-rbac

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/vector-tekton-logs-collector/production/vector-helm-values.yaml

This updates Tekton Results to a version supporting multipart logs, enables that functionality in the configuration and sets Vector for storing logs with a timestamp suffix to prevent long running steps logs overriding.

Add support for Tekton Results multipart logs prod

---

components/kubearchive/base/monitoring-servicemonitor.yaml
components/kubearchive/base/otel-collector-config.yaml

This PR adds `honorLabels: true` which will make [Prometheus to respect labels when they collide](https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/monitoring_apis/servicemonitor-monitoring-coreos-com-v1#spec-endpoints-2) and adds a couple more options on the OpenTelemetry side: don't add units to the metrics names and receive traces, even if they are just printed to debug.

Fix KubeArchive metrics collection

---

components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml

[`error`](https://kyverno.github.io/chainsaw/0.2.3/operations/error/) is NOT checking that the resource doesn't exist. Let's [`delete`](https://kyverno.github.io/chainsaw/0.2.3/operations/delete/) the resource and check that the operation failed.

fix chainsaw tests for bootstrap tenant ns policy

---

components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml

Some changes recently made to this policy are causing issues with kyverno, since the fields that were changed are immutable.  Renaming the policy should provide us with two benefits:
- Works around this issue by making a new resource entirely
- Make the policy's purpose clearer from its name.

rename tenant namespace boostrap policy

---

components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml

[`error`](https://kyverno.github.io/chainsaw/0.2.3/operations/error/) is NOT checking that the resource doesn't exist. Let's [`delete`](https://kyverno.github.io/chainsaw/0.2.3/operations/delete/) the resource and check the operation failed.

fix kubearchive policy's tests

---

components/konflux-rbac/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml

To allow kyverno to create the RoleBinding, the kyverno-background-controller's ServiceAccount needs to have the same permissions it wants to assign to someone else.

give kyverno permission to create appstudio-pipeline rolebinding

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Add a `d160-` flavore to all mNxlarge instances to host-config.yaml files of all production clusters. [Link](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1744243945937309) to the original konflux-users thread.

Fix for KFLUXINFRA-1473, which is the action item for KFLUXSPRT-2674

---

components/pipeline-service/production/base/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml

Updates PaC's custom console URL for production clusters:
* ocp-p01
* rh01
* p01
* p02

update PaC's custom console URL in prod

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/sandbox/toolchain-member-operator/staging/kustomization.yaml
components/sandbox/toolchain-member-operator/staging/patch-appstudio-pipelines-runner.yaml

Add the appstudio-pipelines-nested-containerization-scc. It is a copy of the regular appstudio-pipelines-scc, the only difference being the seLinuxContext.seLinuxOptions setting that allows (forces, in fact) the usage of the container_runtime_t label.
The container_runtime_t label is needed to enable buildah-in-kubernetes workflows with a more robust isolation mechanism (rather than chroot). See https://github.com/containers/buildah/issues/5818 for details.
Allow the appstudio-pipelines-runner ClusterRole - and by extension, the appstudio-pipeline ServiceAccount - to use the new SCC.
All in all, this should allow the appstudio-pipeline SA to set the container_runtime_t label on Pods (but not force, because the SA can still use the regular appstudio-pipelines-scc), making it possible to …

[dev+stage] Add SCC for nested containerization

---

components/monitoring/logging/base/install-logging-operator.yaml

[PVO11Y-4730](https://issues.redhat.com/browse/PVO11Y-4730)
Update needed due to error messages from pods: cluster-logging-operator reports an issue updating status: ‘Operation cannot be fulfilled on clusterlogforwarders; the object has been modified. Please apply changes to the latest version and try again

Update Cluster-logging operator to stable-6.1

---

components/build-service/base/build-pipeline-runner-rolebinding.yaml
components/build-service/base/kustomization.yaml

Since Build Service starts to manage Component build pipeline Service Account, it has to have the rights to run build pipelines to grant them to Components.

Grant Build Service rights to run build pipelines

---

components/smee-client/base/deployment.yaml
components/smee/base/deployment.yaml

We have created a new livenessProbe for smee-client, based on a simple echo "Service up" instead of choosing http check due to port forwarding issue.
Also, we have refined the livenessProbe for smee-base due to a warning error on Openshif.
Tracking ticket: https://issues.redhat.com/browse/SPRE-1255

livenessprobe for smee-client and refine of smee-base

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

For the upcoming release, we change the provisioning way for s390x from dynamic to static.
All machines are `bz2-16x64 ` with a 1TB volume mount as `/home`

Change s390x cobfiguration to static for ocp-art-p01

---

components/build-service/development/kustomization.yaml
components/build-service/staging/base/kustomization.yaml
components/image-controller/development/kustomization.yaml
components/image-controller/staging/base/kustomization.yaml

This PR promotes [Build Service](https://github.com/redhat-appstudio/infra-deployments/pull/6159) and[ Image Controller](https://github.com/redhat-appstudio/infra-deployments/pull/6156) changes together, to rollout dedicated build pipeline Service Account per Component model.

Rollout new Component Service Account model to staging

---

components/namespace-lister/base/kustomization.yaml
components/namespace-lister/base/rbac.yaml

We were allowing anyone who could access our metrics port to scrape our metrics, even though our servicemonitor was configured to use a bearer token to authenticate.  The latest build of namespace-lister addresses this issue.

allow authenticated metrics for namespace-lister

---

components/namespace-lister/production/base/kustomization.yaml
components/namespace-lister/production/base/rbac.yaml

Rolls out #6169 to production clusters.

prod: allow authenticated metrics for namespace-lister

---

components/release/development/release_service_config.yaml
components/release/staging/release_service_config.yaml

- enable emptyDirs for rh-advisory and rh-push-to-registry-redhat-io

feat(RELEASE-1532): use trusted artifacts

---

components/integration/development/manager_resources_patch.yaml

Set the imagePullPolicy for the integration service controller manager to 'Always' in development environmnts.  This will help speed up iteration for integration team devs

chore: make integration service imagePullPolicy Always for dev

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

Non-trusted artifact pipelines were added for newer functionality because we have both variants for the `docker-build` pipeline. While we can build these pipeline bundles, we don't need to offer them as an option to users unless there is a specific need for them.

Only suggest TA pipelines for newer functionality

---

components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

In b1f11c0a2aa04c446dd4180ad9dd9f3f384e1f90, the PaC URLs were changed in the src files but deploy.yaml files were not regenerated.

Fix PaC's custom console URL in prod

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml

Multi-architectural builds in the OCP cluster are timing out due to waiting for PPC VMs to be provisioned. To decrease the time needed to complete the build, a set of static VMs is provisioned so that the only wait time is for if a VM is at its current concurrency limit.

Configure OCP cluster to use static PPC64le VMs

---

components/build-service/production/base/kustomization.yaml
components/image-controller/production/base/kustomization.yaml

This PR promotes [Build Service](https://github.com/redhat-appstudio/infra-deployments/pull/6165) and[ Image Controller](https://github.com/redhat-appstudio/infra-deployments/pull/6164) changes together, to rollout dedicated build pipeline Service Account per Component model to production clusters.

Rollout new Component Service Account model to production

---

components/mintmaker/base/redis-cache/kustomization.yaml
components/mintmaker/base/redis-cache/redis-configmap.yaml
components/mintmaker/base/redis-cache/redis-deployment.yaml
components/mintmaker/base/redis-cache/redis-networkpolicy.yaml
components/mintmaker/base/redis-cache/redis-pvc.yaml
components/mintmaker/base/redis-cache/redis-service.yaml
components/mintmaker/development/kustomization.yaml
components/mintmaker/staging/base/kustomization.yaml

Redis will be used by renovate PLRs to store and retrieve cache in order to improve performance and decrease the number of API calls. Connection is not password protected, but a network policy exists to restrict access only to pods in the "mintmaker" namespace. I think that a password is unnecessary since it would complicate the deployment and no sensitive or important data will be stored in the database. The persistent volume exists to back up the data so that Redis can reload it after restart.
The memory limit was chosen somewhat arbitrarily, but we can increase it if high use is observed over time. OOM errors should not happen since Redis limit is configured lower than Openshift limit.

MintMaker: Deploy Redis for Renovate cache in stage

---

components/external-secrets-operator/staging/starting-csv-patch.yaml

We are starting at version 0.9.1 which is old, change to the latest version which support OLM.

Install External secret operator version 0.11.0 on staging

---

components/crossplane-control-plane/production/kustomization.yaml
components/crossplane-control-plane/staging/kustomization.yaml

OOMKilled errors are occurring with the default 1Gi limit.

Increase memory limit for crossplane controller in prod and staging

---

components/kubearchive/base/kubearchive-config.yaml

We want to archive resources at different points in time. Also Releases were meant to be archived on completion, not deletion (see https://github.com/redhat-appstudio/infra-deployments/pull/5479/files).

KubeArchive: change when resources are archived

---

components/konflux-ui/staging/base/proxy/nginx.conf
components/konflux-ui/staging/base/proxy/proxy.yaml
components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
components/kubearchive/base/kubearchive-routes.yaml

Configure nginx proxy in Konflux UI so it can access it from staging.
The KubeArchive API is exposed with an Openshift Route, the same way it's done for Tekton Results.
I've replicated the NGINX configuration for Tekton Results in Konflux UI, but I haven't tested it. Please, let me know if it needs any changes.

Expose KubeArchive API 

---

components/kyverno/development/kyverno-helm-values.yaml
components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

This will prevent the scale-to-zero job from being created.
This is not required in a GitOps environment, as the helm's `pre-delete` hook is not supported by ArgoCD and the effect of the scale-to-zero job will be reverted by ArgoCD itself.
cf:
* https://github.com/kyverno/kyverno/blob/77e2a860c8d0b66c65e2203d97348d19d2cb0136/charts/kyverno/templates/hooks/pre-delete-scale-to-zero.yaml#L11
* https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#helm-hooks

Disable kyverno WebhookCleanup job in dev and stg

---

components/knative-eventing/production/stone-prod-p02/kustomization.yaml

The ApplicationSet manifest for knative-eventing references deploying to stone-prod-p02, but no resources are actually deployed there.  Deploy knative-eventing's resources there just like the other clusters.

deploy knative-eventing to stone-prod-p02

---

components/release/base/cronjobs/remove-internal-requests.yaml

this PR fixes the case where a running IR is
wrongly removed by the cronjob due to the missing
completionTime field, that is only added after
finishing the IR run.

fix: running ir shold not be removed

---

components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Some changes were done without running the generate-deploy-config.sh script which keeps the deploy.yaml files aligned with the base. This PR does not introduce new changes, but just aligns the configs with the base.

Align pipeline-service base with cluster configs

---

.github/workflows/chainsaw-tests.yaml
components/kyverno/chainsaw/job_resources.yaml
components/kyverno/chainsaw/kustomization.yaml
components/kyverno/chainsaw/kyverno-helm-generator.yaml
components/kyverno/chainsaw/kyverno-helm-values.yaml
components/kyverno/chainsaw/namespace.yaml
hack/chainsaw/chainsaw-prepare.sh

This PR
* changes the order of steps for the chainsaw tests pipeline to make it faster
* changes default namespace of chainsaw tests to `konflux-kyverno` to match the other environments
* enforce Helm manifests are used also in the `chainsaw` overlay

make chainsaw tests more robust

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

Multi-architectural builds in the prod-p02 cluster are timing out due to waiting for PPC VMs to be provisioned. To decrease the time needed to complete the build, a set of static VMs is provisioned so that the only wait time is for if a VM is at its current concurrency limit. These static VMs are currently prefaced with "test" so testing them will not interfere with current builds.

Configure prod-p02 cluster to test static PVMs

---

components/release/production/release_service_config.yaml

- enable emptyDirs for rh-advisory and rh-push-to-registry-redhat-io in production

feat(RELEASE-1541): use trusted artifacts (#6147)

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

Only change the default platforms to not do a breaking change, then an announcement will be sent to ask users to stop using larger platform flavors in favor of default ones. The default platforms are running on static VMs that are large enough to accommodate larger build needs.
A follow up change will remove the larger flavors once users had time to migrate.
[KFLUXINFRA-1538](https://issues.redhat.com//browse/KFLUXINFRA-1538)
[KFLUXINFRA-1540](https://issues.redhat.com//browse/KFLUXINFRA-1540)

Change s390x and ppc64le to static VMs on P02

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

This 2 machines brings the count to 16 with 4 builds each for a total of 64 concurrent builds, par with ppc64le.
[KFLUXINFRA-1527](https://issues.redhat.com//browse/KFLUXINFRA-1527)

Add 2 more s390x machines for p02

---

components/konflux-rbac/production/base/konflux-viewer-user-actions.yaml
components/konflux-rbac/production/base/kustomization.yaml
components/konflux-rbac/staging/base/konflux-viewer-user-actions.yaml
components/konflux-rbac/staging/base/kustomization.yaml

Add the `konflux-viewer-user-actions` role. It provides the same rights the `konflux-contributor-user-actions `role provides.
It is required for the implementation of Public view feature.

add konflux-viewer-user-actions role to stg and prod

---

components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml

[KFLUXINFRA-1532](https://issues.redhat.com/browse/KFLUXINFRA-1532): Multi-architectural builds in the RH02 cluster are timing out due to waiting for PPC VMs to be provisioned. To decrease the time needed to complete the build, a set of static VMs is provisioned so that the only wait time is for if a VM is at its current concurrency limit. These static VMs are currently using a test platform so testing them will not interfere with current builds.

Configure RH02 cluster to test static PVMs

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Label mode required to export node cpu seconds metric

fix-up(PVO11Y-4652): Keep node cpu label

---

components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/chainsaw-test.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/invalid-systemauthenticated-rolebinding.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/tenant-namespace.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/valid-systemauthenticated-rolebinding.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/kustomization.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/kyverno_rbac.yaml
components/konflux-rbac/policies/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
components/konflux-rbac/staging/base/kustomization.yaml

This PR adds a Policy to restrict the Roles an user can share in a tenant namespace to `konflux-viewer-user-actions`.
It requires:

add restrict-binding-system-authenticated Policy

---

components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/chainsaw-test.yaml
components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/masters-rolebinding.yaml
components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/rolebinding.yaml
components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/tenant-namespace.yaml
components/konflux-rbac/policies/validate-rolebindings/invalid-subjects.yaml
components/konflux-rbac/policies/validate-rolebindings/kustomization.yaml
components/konflux-rbac/policies/validate-rolebindings/kyverno_rbac.yaml
components/konflux-rbac/staging/base/kustomization.yaml

Some groups should not be allowed access across the cluster for any reason.  Add a cluster policy to enforce this in the staging clusters.

konflux-rbac: disallow certain groups in rolebindings

---

components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

[KFLUXINFRA-1536](https://issues.redhat.com/browse/KFLUXINFRA-1536): Multi-architectural builds in the RH01 cluster are timing out due to waiting for PPC VMs to be provisioned. To decrease the time needed to complete the build, a set of static VMs is provisioned so that the only wait time is for if a VM is at its current concurrency limit. These static VMs are currently using a test platform so testing them will not interfere with current builds.

Configure RH01 cluster to test static PVMs (#6290)

---

components/build-service/development/kustomization.yaml
components/build-service/staging/base/kustomization.yaml

Updating build-service refs.
Included PR: https://github.com/konflux-ci/build-service/pull/427

build-service update

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

This change is part of https://issues.redhat.com/browse/KONFLUX-7680
Associated [PR](https://github.com/konflux-ci/build-definitions/pull/2268) on the build-definitions side

fix: use devel tag instead of commit_id tag for the pipeline bundles

---

components/konflux-rbac/production/base/kustomization.yaml

Disallow the following groups from being subjects in a rolebinding in a tenant namespace:
- `system:anonymous`
- `system:masters`
- `system:unauthenticated`
Staging appears to be stable, so it's likely safe to rollout to production.

rbac: disallow certain groups from rolebindings in prod

---

components/konflux-ui/staging/base/proxy/proxy.yaml

While KubeArchive does not support impersonation
the Konflux UI team need to have unblocked the
access to the Snapshots and Releases in staging
for KubeArchive.

Add temporary permissions to the nginx proxy sa

---

argo-cd-apps/base/member/infra-deployments/etcd-shield/etcd-shield.yaml
argo-cd-apps/base/member/infra-deployments/etcd-shield/kustomization.yaml
components/etcd-shield/OWNERS
components/etcd-shield/base/config.yaml
components/etcd-shield/base/deployment.yaml
components/etcd-shield/base/etcd_shield_alerts.yaml
components/etcd-shield/base/kustomization.yaml
components/etcd-shield/base/ns.yaml
components/etcd-shield/base/rbac.yaml
components/etcd-shield/base/service.yaml
components/etcd-shield/base/webhook.yaml
components/etcd-shield/staging/stone-stage-p01/kustomization.yaml
components/etcd-shield/staging/stone-stg-rh01/kustomization.yaml

Overview
========
etcd-shield is a load-shedding tool designed to provide a more consistent experience to users when an outage is occurring.  When a configured alert is firing, it denies the admission of pipelineruns into the cluster.
Currently, it's configured to watch for etcd's on-disk capacity (hence the name).  The database capacity limits are not stored as prometheus time-series entries, so we're forced to hard-code the current 8GiB limit in the PrometheusRule resource.
In the future, we could add more alerts to match on and more resources types for this service to deny.
Alert configuration
===================
The alert is configured to trigger at 95% capacity, and hold that trigger until capacity drops below 80%.  This is done to provide a buffer between when we stop allowing new …

etcd-shield: deploy to staging

---

argo-cd-apps/base/member/infra-deployments/etcd-shield/etcd-shield.yaml

Overwriting existing applicationsets is a bad idea, don't do it.

etcd-shield: fix ApplicationSet name

---

components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml

Remove s390x from dynamic platforms

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Update Tekton Results to the v0.14.0-4 downstream version. Allow earlier Kubernetes version (v1.28.0) as the Knative package dependency requires v1.30.0.

Update Results v0.14.0-4 prod

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
components/etcd-shield/base/etcd_shield_alerts.yaml

Two important changes:
- Pull etcd's maximum size from its own metrics, rather than hard-code it ourselves.  This is information it exposes, so use it.
- Actually deploy the applicationset as a part of the staging overlays.

etcd-shield: fixes

---

components/multi-platform-controller/production/stone-prd-rh01/external-secrets.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Add all the static host using a temporary platform name to be able to test them out without affecting prod. A follow up change will replace dynamic by static ones.
[KFLUXINFRA-1541](https://issues.redhat.com//browse/KFLUXINFRA-1541)

Add static s390x hosts for stone-prd-rh01

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

Announcement was sent to ask users to stop using larger platform flavors in favor of default ones. The default platforms are running on static VMs that are large enough to accommodate larger build needs.
[KFLUXINFRA-1561](https://issues.redhat.com//browse/KFLUXINFRA-1561)

Remove P02 larger dynamic s390x and ppc64le platforms

---

components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

With this one, we are only missing one to get to the 16 objective, which would allow to match the 64 concurrent builds we can do on PPC side.

Add one more s390x VM to rh01

---

components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml

This cluster cannot support IBM arch due to a conflict between OCP pods CIDR and IBM one. This is why we create p02, it is the replacement of p01. Until we retire p01, remove IBM from MPC as it might confuse people into thinking that p01 support IBM arch.

Remove IBM from stone-prod-p01

---

components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/temp-set-pipelines-default-scc.yaml

The current default appears to be set as `pipelines-scc`, which does not exist....
More context in [this slack thread](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1746731894794529?thread_ts=1746425126.665539&cid=C04PZ7H0VA8)

test correct default pipelines security group in kflux-rh02

---

components/authentication/base/everyone-can-view.yaml
components/kubearchive/base/kubearchive-config.yaml
components/kubearchive/base/kubearchive-maintainer.yaml
components/kubearchive/base/kustomization.yaml
components/kubearchive/policies/.chainsaw-test/resources/actual-kubeconfig-archive.yaml
components/kubearchive/policies/.chainsaw-test/resources/expected-kubearchiveconfig.yaml
components/kubearchive/policies/.chainsaw-test/resources/kubearchive-crd.yaml
components/kubearchive/policies/bootstrap-namespace.yaml
components/kubearchive/policies/kyverno_rbac.yaml
components/kubearchive/policies/resources/expected-kubearchiveconfig-konflux.yaml
components/release/staging/kustomization.yaml

This PR bumps KubeArchive to v1.0.0. This release includes breaking changes in the `apiVersion` of the KubeArchive CRDs: the group changes from `kubearchive.kubearchive.org` to `kubearchive.org` and the version changes from `v1alpha` to `v1`.
I tested it locally and Kyverno should create the new objects without any problems and I tried the deletion too. All existing `KubeArchiveConfig`s that are `kubearchive.kubearchive.org/v1alpha` need to have their `finalizer` removed and then deleted. I'm using:
```
kubectl patch -n <namespace> kubearchiveconfigs.kubearchive.kubearchive.org kubearchive -p '{"metadata": {"finalizers": []}}' --type=merge
kubectl delete -n <namespace> kubearchiveconfigs.kubearchive.kubearchive.org kubearchive
```
The CRD also needs to be deleted as far as I know, even if …

KubeArchive: bump to v1, breaking changes

---

argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml

Remove the patch deleting etcd-shield from production overlays.

etcd-shield: enable in production

---

components/konflux-rbac/production/base/konflux-builder-bot-actions.yaml

This is useful for summarizing why a pipelinerun failed.

Builder serviceaccounts should be able to inspect events

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml

#6332 adds some external labeling for es01 that is not being applied due to es01 clusters defaulting to the base kustomize configuration for monitoring-workload-prometheus.
Added es01 clusterDir so those clusters can use their own kustomize configuration instead.

fix(PVO11Y-4653): Add es01 clusterDir for monitoring-workload-prometheus

---

components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml

This change fixes the visibility problem maintainers and contributors
are facing in the New UI's User Access page.

add list RoleBindings to maintainers and contributors in staging

---

.github/workflows/kube-linter.yaml
.kube-linter.yaml

We're running a fairly outdated version of kube-linter; let's update it to the latest version.
Unfortunately, kube-linter has introduced some new lints, and some of the components in our repository aren't in compliance with them.  We'll need to disable them for now until these components are fixed.
As long as we're at it, let's also run kube-linter checks on push to `main`.  It should get sarif reports working on PRs, and we should check that commits that wind up in `main` are linted appropriately.

Bump kubelinter

---

components/kyverno/development/kyverno-helm-values.yaml
components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml

This PR increases the UpdateRequests Threshold for clusters where we are hitting the limit.
The old (default) value was 1000, so this PR doubles it.

Increase Kyverno UpdateRequests threshold

---

components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/temp-set-pipelines-default-scc.yaml

Reverts redhat-appstudio/infra-deployments#6353
This change did not resolve the issue, so the change is being reverted

Revert "test correct default pipelines security group in kflux-rh02"

---

hack/deploy-argocd.sh

During deployment the application controller struggles with processing all the Konflux applications because of missing resources. This cause it to crash (OOM) and because of that the deployment takes more time.
Increase resource limits.

dev: Increase Argo's application controller resource limits

---

components/enterprise-contract/ecp.yaml

This commit fixes an overwrite of the `ec-task-policy` floating tag in the EnterpriseContractPolicy.
Ref: [EC-1283](https://issues.redhat.com//browse/EC-1283)

Reset `ec-task-policy` to floating tag.

---

components/etcd-shield/base/etcd_shield_alerts.yaml
components/etcd-shield/production/base/etcd_shield_alerts.yaml

A severity level of `critical` is unsuitable, as it triggers a PagerDuty alert.  Decrease the severity level to warning as other alerts will trigger the appropriate response.

etcd-shield: decrease severity level to warning

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Tekton Pruner was initially enabled to help the Results Watcher workqueue from growing too big. With the recent optimizations that probably won't be required anymore. Furthermore, we suspect the pruner removing forcefully the pipelineruns could be the reason some taskruns are not properly stored by Results.

Disable Tekton Pruner

---

components/monitoring/grafana/base/dashboards/performance/kustomization.yaml

Updating the dashboards present in the performance directory to point to a new commit that extends them to include metrics from the additional controllers. This will improve visibility into Konflux's performance
```
external-secrets-operator-controller-manager
repository-validator-controller-manager
mintmaker-controller-manager
```
Note: Please do not merge this until the related changes are merged - https://github.com/redhat-appstudio/perfscale/pull/12

perfscale/grafana: Extending the Grafana dashboard(controllers-overview) to include data from more controllers

---

components/etcd-shield/base/etcd_shield_alerts.yaml
components/etcd-shield/production/base/etcd_shield_alerts.yaml

Expansion of pipelineruns causes etcd to fill up, even when we cut off at 80%.  Lower thresholds by 10% to give us more breathing room.

etcd-shield: decrease thresholds by 10%

---

components/etcd-shield/base/ns.yaml
components/etcd-shield/production/base/ns.yaml

It was used for debugging purposes, and has no business being set on the production nor staging clusters.

etcd-shield: remove cluster-monitoring label

---

components/etcd-shield/base/deployment.yaml
components/etcd-shield/production/base/deployment.yaml

The highlights:
- 3 replicas instead of 1, so etcd-shield is more resiliant to pods falling over
- disable leader election, since we don't need it for anything.

Etcd shield updates

---

components/mintmaker/production/base/kustomization.yaml

This commit promotes the latest images tested in stage to prod, as part of the weekly release for
MintMaker.
I monitored the deployment in stage and there were no errors. I also double-checked quay and the images were built without problem there.
I believe it is safe to promote this to prod.

MintMaker weekly release: promote stage to prod

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Reverts redhat-appstudio/infra-deployments#6405
Reverting the change as it looks it exposes some performance issues on the prod clusters. We can remove that again after the performance issues are resolved.

Revert "Disable Tekton Pruner"

---

components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml

Announcement was sent to ask users to stop using larger platform flavors in favor of default ones. The default platforms are running on static VMs that are large enough to accommodate larger build needs.
[KFLUXINFRA-1559](https://issues.redhat.com//browse/KFLUXINFRA-1559)

Remove rh02 larger dynamic s390x and ppc64le platforms

---

components/crossplane-control-plane/staging/kustomization.yaml
components/crossplane-control-plane/staging/testplatform-provider-config.yaml

Same as https://github.com/redhat-appstudio/infra-deployments/pull/6446 but for the staging environment.
/cc @amisstea

Add testplatform ProviderConfig in Staging

---

components/integration/development/kustomization.yaml
components/integration/production/base/kustomization.yaml
components/integration/staging/base/kustomization.yaml

promotes integration-service in order to grant greater permissions for integrationtestscenario/status resources for integration admins

chore: promote integration-service

---

configs/etcd-defrag/base/cronjob.yaml

* chore(deps): update konflux references
* Always compact ETCD before evaluating reclaimable space
* chore(deps): update registry.redhat.io/ubi9 docker tag to v9.6-1747219013
* Konflux build pipeline service account migration for defrag
[KFLUXINFRA-1644](https://issues.redhat.com//browse/KFLUXINFRA-1644)

Upgrade etcd-defrag image to latest revision

---

argo-cd-apps/overlays/development/delete-applications.yaml

This application deploys an external secret and we don't install ESO in development, because of that the deployment of development got broken.

Remove pulp-access-controller from development

---

components/kyverno/development/kustomization.yaml
components/kyverno/development/kyverno-helm-values.yaml

Due to a typo we were not disabling the scale-to-zero job as intended in the development overlay

fix kyverno dev overlay configuration

---

components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml

Kyverno background controller is restarting as it reached the threshold for UpdateRequests.

bump kyverno UpdateRequest threshold in rh01

---

components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml

Kyverno background is using all the CPU time we provided.
Let's give it more compute power

give more cpu to Kyverno background on rh01

---

components/namespace-lister/base/kustomization.yaml

At this point we migrated all the namespace to the new label. We are no more expecting any Namespace to be created with the `toolchain.dev.openshift.com` or the `konflux.ci` labels.

disable `mutate-namespace-enforce-label` policy in staging

---

argo-cd-apps/base/monitoring-workload-kanary/kustomization.yaml
argo-cd-apps/base/monitoring-workload-kanary/monitoring-workload-kanary.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/kustomization.yaml
components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
components/monitoring/kanary/README.md
components/monitoring/kanary/base/external-secrets/kanary-db-credentials.yaml
components/monitoring/kanary/base/external-secrets/kustomization.yaml
components/monitoring/kanary/base/kustomization.yaml
components/monitoring/kanary/base/rbac/kanary-maintainers.yaml
components/monitoring/kanary/base/rbac/kustomization.yaml
components/monitoring/kanary/staging/base/kanary-db-credentials-secret-path.yaml
components/monitoring/kanary/staging/base/kustomization.yaml
components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml

This commit establishes the new 'appstudio-kanary-exporter'
namespace and configures the associated GitOps deployment
for the Kanary signal exporter.
Key changes include:
- Creation of the 'monitoring-workload-kanary' ArgoCD ApplicationSet.
- Definition of the Kanary exporter component under 'components/monitoring/kanary/'.
- Updates to cluster secret store and RBAC to support the new namespace and component.
NOTES:
- This is deployed just for the stone-stage-p01 cluster by using the staging-downstream overlay.
- The base resources will still be deployed to any member cluster that may be added under the 'staging-downstream' cluster fleet. This is not ideal behavior, but it is not a breaking problem, since the exporter itself will only be deployed to that one cluster.
Related issue: …

feat(PVO11Y-4787): Setup Kanary signal deployment

---

components/image-controller/production/base/manager_resources_patch.yaml
components/image-controller/staging/base/manager_resources_patch.yaml

[STONEBLD-3526](https://issues.redhat.com//browse/STONEBLD-3526)

bump memory for image-controller

---

components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-kubesaw.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpconsole-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpingress-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpmonitoring-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-olm-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-samenamespace-clusterpolicy.yaml
components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml

we want to make sure kubesaw and kyverno are not competing on the same resources created during tenant bootstrapping.

exclude kubesaw managed namespace from tenant bootstrapping in stg

---

components/mintmaker/production/base/manager_patch.yaml

The mintmaker controller requires substantial memory resources when analyzing components and creating renovate pipelineruns. When the cluster lacks sufficient free resources to allocate to the mintmaker controller, it may crash due to OOM errors.
This change increases requests.memory to 3Gi to ensure the cluster allocates this amount when creating the controller pod. Since I'm not certain 3Gi will always be sufficient, I've set limits.memory to 4Gi, allowing the controller to obtain up to 4Gi if needed and if the cluster has available memory.
Note that resource growth from 3Gi to 4Gi is not guaranteed, if the cluster has no free resources, the controller may be unable to acquire additional memory beyond its request.

mintmaker (prod): increase memory allocation for controller

---

components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/tekton-chains-public-key-path.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/tekton-chains-signing-secret-path.yaml

Ansible playbook is putting the right path in deploy.yaml file but it should put the right path in patch file instead and generate ddeploy file using the script:
/hack/generate-deploy-config.sh -c components/pipeline-service/production
For now, fix the patch file manually, a follow up change will be done to fix ansible playbook.
[KFLUXINFRA-1636](https://issues.redhat.com//browse/KFLUXINFRA-1636)

Fix chain signing secret path.

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Config is set to 8 but ArgoCD is showing TektonConfig out of sync in all the production cluster, the live TektonConfig only has 4 buckets

Set number of OSP buckets to 4

---

components/multi-platform-controller/production-downstream/base/kustomization.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/aws-account.patch.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/aws-ssh-key.patch.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/external-secrets.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/ibm-account.patch.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/ibm-ssh-key.patch.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/kustomization.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/external-secrets.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/kustomization.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml

Having the secrets in the base is making things more complicated as some clusters do not need all the secrets and some others, secrets must be patched to have right path in vault.
As first step, duplicate the secrets in each cluster and adjust accordingly. We have a task to standardize the MPC secrets name, one this is done we will be able to remove duplication and created them in the base overlay.

Move secrets file to each internal MPC cluster folder

---

components/etcd-shield/base/deployment.yaml
components/etcd-shield/production/base/deployment.yaml

we don't need to set limit for cpu, we just require accurate request.

remove cpu limits for etcd-shield

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

In order to detect issues with Prometheus internal to each cluster, export the `prometheus_ready` metric.

PVO11Y-4772 - Export prometheus_ready metric for monitoring the internal prom instances.

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

The us-south datacenter is full for s390x. Remove 6 VMs from p02 to move them to the rhel cluster. Since 6 VMs can do 24 concurrent builds, reduce the power accordingly since there is no point of being able to do more ppc than s390x
[KFLUXINFRA-1639](https://issues.redhat.com//browse/KFLUXINFRA-1639)

Remove s390x and ppc VMs from p02

---

argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

It's already getting deleted in the parent overlay so if we
try to delete it again kustomize build fails.

Remove the deletion of nvme-storage app from downstream overlays

---

components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

Add all 8 ppc machines and only 3 s390x machines. We are missing 13 s390x machines that will be added once we sort it out with IBM/IT, we might need to move to another datacenter.
A follow up PR will be done with remaining machines.
[KFLUXINFRA-1638](https://issues.redhat.com//browse/KFLUXINFRA-1638)
[KFLUXINFRA-1639](https://issues.redhat.com//browse/KFLUXINFRA-1639)

Configure kflux-rhel-p01 s390x and ppc VMs

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This PR increases the memory resource limits for the following components to reduce OOM-related instability:
-     pipeline-metrics-exporter
Was occasionally consuming its full 6 GiB allocation, leading to instability.
Increased memory limits to improve reliability and prevent potential OOM issues.
-     tekton-pipeline-remote-resolver
Also observed to use up its full 8 GiB memory allocation intermittently.
Increased memory limits to improve reliability and prevent potential OOM issues.

updated the memory resource for tekton resources to prevent OOMKills

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Added CPU and memory limits for following Tekton resources:
* pipelines-as-code-controller
* pipelines-as-code-watcher
* pipelines-as-code-webhook
* pipelines-console-plugin
* tekton-chains-controller
* tekton-events-controller
* tekton-triggers-controller
* tekton-triggers-core-interceptors
* tekton-triggers-webhook
* tkn-cli-serve

update resource configurations for Tekton components

---

components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml

Private ones were updates [last week](https://github.com/redhat-appstudio/infra-deployments/pull/6585), showing no major problems.
Updates:
Provision/cleanup task names generation refactor to avoid duplicates
Searchable Platform labels for MPC tasks

Promote new MPC to the public prod clusters

---

components/kyverno/production/stone-prd-rh01/patch_background_controller_qps_burst.yaml

Bumping Kyverno background controller's QPS and Burst to test impact on
APIServer performances. Default values were 300 each.
```
containers:
- args:
- --enablePolicyException=false
- --enableReporting=validate,mutate,mutateExisting,imageVerify,generate
- --clientRateLimitQPS=2000
- --clientRateLimitBurst=2000
env:
- name: KYVERNO_SERVICEACCOUNT_NAME
```

increase QPS and Burst for Kyverno in prod rh01

---

components/kyverno/staging/stone-stg-rh01/kustomization.yaml
components/kyverno/staging/stone-stg-rh01/patch-background-controller-qps-burst.yaml

Bumping Kyverno background controller's QPS and Burst to test impact on APIServer performances. Default values were 300 each.
```
containers:
- args:
- --enablePolicyException=false
- --enableReporting=validate,mutate,mutateExisting,imageVerify,generate
- --clientRateLimitQPS=1000
- --clientRateLimitBurst=1000
env:
- name: KYVERNO_SERVICEACCOUNT_NAME
```

increase QPS and Burst for Kyverno in stg rh01

---

components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml

This change fixes the visibility problem maintainers and contributors are facing in the New UI's User Access page.
Follows up to #6373

 add list RoleBindings to maintainers and contributors in prod

---

components/kyverno/development/kyverno-helm-values.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

In prod rh01 kyverno is restarting because it can not renovate the lease.
We want to have leases that lasts at least `25 seconds`.
Kyverno accepts the flag `leaderElectionRetryPeriod` defaulted to `2s` (cf. https://kyverno.io/docs/installation/customization/#container-flags) and it's multiplying this factor for `6` to calculate the `LeaseDuration` value.
Bumping the `leaderElectionRetryPeriod` to `5s` will make the lease last at least `30s`.

kyverno: increase leader election retry period in dev and stg

---

components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

I do not know where the ones we had configured came from but they are not the right ones, use the ones I found in MPC AWS account.

Fix kflux-rhel-p01 MPC subnet and security group

---

components/backup/staging/stone-stage-p01/dpa-channel-patch.yaml
components/backup/staging/stone-stage-p01/kustomization.yaml
components/backup/staging/stone-stg-rh01/dpa-channel-patch.yaml
components/backup/staging/stone-stg-rh01/kustomization.yaml

The update is required for upgrading the cluster to 4.16.
```
openshift-adp/oadp-operator.v1.3.6 is incompatible with OpenShift minor versions greater than 4.15
```

KFLUXINFRA-1759: Update OCP DPA on stage

---

components/authentication/base/konflux-admins.yaml

This is needed in order to clean a clusterrolebinding
as part of a cleanup ([KFLUXINFRA-1627](https://issues.redhat.com//browse/KFLUXINFRA-1627)).

KFLUXINFRA-1763: Add apiGroup permissions to konflux-admin

---

components/crossplane-control-plane/base/kustomization.yaml
components/crossplane-control-plane/development/kustomization.yaml

Same as https://github.com/redhat-appstudio/infra-deployments/pull/6503.
I had to rename my fork from `danilo-gemoli/redhat-appstudio-infra-deployments` to `danilo-gemoli/infra-deployments` because there are some e2e tests that make assumptions on the fork name: the name should match this pattern `<your-org>/infra-deployments`.

upgrade crossplane environments

---

components/konflux-ui/production/base/proxy/nginx.conf
components/konflux-ui/production/base/proxy/proxy.yaml
components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
components/konflux-ui/production/kflux-prd-rh03/kustomization.yaml
components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
components/konflux-ui/production/stone-prod-p01/kustomization.yaml

Removing KubeArchive from UI configuration on production clusters, as KubeArchive is not installed on all production clusters, just p02. So this causes the proxy to CrashLoopBackOff because there is no host for nginx to communicate to.

KubeArchive: remove it from UI config

---

components/konflux-ui/staging/base/proxy/nginx.conf
components/konflux-ui/staging/base/proxy/proxy.yaml
components/konflux-ui/staging/stone-stage-p01/kustomization.yaml

This PR introduces a condition that if the KUBEARCHIVE_URL is not set, the `proxy_pass` is not set for NGINX.

KubeArchive: don't configure UI for p01

---

components/konflux-ui/staging/base/proxy/proxy.yaml

I introduced a typo, instead of `>>` I wrote `>` leading to the NGINX configuration file for kubearchive just contain `}`, causing the proxy to fail at startup.

KubeArchive: fix UI proxy config for positive case

---

components/kyverno/chainsaw/kyverno-helm-generator.yaml
components/kyverno/chainsaw/kyverno-helm-values.yaml
components/kyverno/development/kyverno-helm-generator.yaml
components/kyverno/development/kyverno-helm-values.yaml
components/kyverno/staging/stone-stage-p01/kyverno-helm-generator.yaml
components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-generator.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

From https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#helm-skip-tests
> By default, Helm includes test manifests when rendering templates. Argo CD currently skips manifests that include hooks not supported by Argo CD, including Helm test hooks.

disable kyverno's helm tests manifests in dev, chainsaw and stg

---

components/kueue/development/queue-config/cluster-policy.yaml

The operations key isn't required for generating rules.

dev: Remove the operations key from generate rule

---

components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

Not all our clusters configured equally,
some have a missing the  `sudo rm`  command admittance in order to run [build-vm-image](https://github.com/konflux-ci/build-definitions/blob/main/task/build-vm-image/0.1/build-vm-image.yaml#L205) task

Add required sudo command into config

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Decreasing the completed runs grace period will help with the etcd pressure.
The requeue interval (default 10m) was too long and it applies to finished pipelineruns, so we can retry faster.
The store deadline (default 10m) was matching the completed runs grace period which I think does not make much sense, especially given issues with taskruns not being stored. Increasing that value will  help, but could lead to pipelineruns kept on the cluster for longer. If that happens, we need to find the reason and fix that, as this is the final resort to remove stale pipelineruns.
With the current Vector configuration which is well optimized, logs are stored quite quickly (few secs delay), so there is no reason to wait that long. Once applied, we can check for logs not being stored and eventually …

Optimize timeouts for Tekton Results Watcher

---

components/knative-eventing/base/kustomization.yaml

* Increased memory limit as well because the pod keeps being restarted on production, testing first on staging.

Knative Eventing: Upgrade to improve memory usage

---

components/konflux-ui/staging/base/proxy/proxy.yaml

Currently the redirection made by the Konflux UI Nginx proxy to make KubeArchive API isn't working.
Even though the KubeArchive team does not have permissions to check the actual kubearchive.conf being used, we found this typo that is probably the culprit.
Before merging this PR it would be helpful though if someone with permissions can check the output of 
```
oc exec -n konflux-ui deploy/proxy -c nginx -- ls /mnt/nginx-generated-config/kubearchive.conf
```
in the public staging cluster so we can ensure that the content is what we expect and that we are not missing anything else

Fix typo in kubearchive.conf for Konflux UI nginx

---

components/multi-platform-controller/production-downstream/base/kustomization.yaml

This including the important fix:
[Comment out resizing block as it is not needed for static VMs ](https://github.com/konflux-ci/multi-platform-controller/commit/ccd22bfb87cde8de268f4a40e0217ebacf54e51e)

Update internal production with latest MPC version from staging

---

components/kyverno/development/kyverno-helm-values.yaml
components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml

Kyverno doesn't seem to support HTTPS on the metrics server natively even though the Helm chart allows to configure the ServiceMonitor for that.
Further investigation is needed, deferring it to another PR.

scrape kyverno metrics in dev and stage

---

components/policies/staging/base/konflux-rbac/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
components/policies/staging/base/konflux-rbac/validate-rolebindings/invalid-subjects.yaml

ArgoCD is complaining because some policies are OutOfSync.
Explicitly setting the skipBackgroundRequests and allowExistingViolations fields to their default values will fix.

kyverno: defaults for skipBackgroundRequests and allowExistingViolations

---

components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml

This including the important fix:
[Comment out resizing block as it is not needed for static VMs](https://github.com/konflux-ci/multi-platform-controller/commit/ccd22bfb87cde8de268f4a40e0217ebacf54e51e)

Update public production with latest MPC version from staging

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/kustomization.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/override-osp-version.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/update-config-for-osp-1-19.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

The `quay.io/openshift-pipeline/pipelines-index-4.15@sha256:a1f651150d5e361d64249d8b38ed21c5bb1e623d2d776ecec2a0ad2633fdaf63` index has been on staging since June 10

Update Pipelines Production to be in line with staging and devopment

---

argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
components/kubearchive/development/kustomization.yaml
components/kubearchive/staging/stone-stg-rh01/kustomization.yaml

This PR moves the SkipDryRunOnMissingResources to the application set so we can remove commonAnnotations and then use specific annotations for certain resources. The Job we use to update the database schema needs specific annotations.

KubeArchive: changing commonAnnotations

---

argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml

This PR aims to ignoreDifferences of a CRB that KubeArchive modifies in its activity. ArgoCD is trying to turn it back to the original state, which will make KubeArchive malfunction. This will be applied to all installations, which makes sense.

KubeArchive: ignoreDifferences in ClusterRoleBinding

---

components/repository-validator/production/kustomization.yaml

This commit allows the ibmstorage GitHub repository to be added to the production repository allow list.

Update production repository validator

---

components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml

Disabling this setting allows users to enumerate additional private repositories for which their Github Token will be scoped. Importantly, the additional private repositories can only be included in the token's scope if both repositories have the same Github App installed and the their respective Repository CRs exist in the same namespace, which is in line with Konflux's security model. 
Part of https://issues.redhat.com/browse/KONFLUX-8780

enable multi-repo Github App token scoping

---

components/smee-client/OWNERS
components/smee-client/staging/deployment.yaml
components/smee-client/staging/kustomization.yaml
components/smee-client/staging/sever-url-patch.yaml

The smee sidecar implements a health check loop that sends an event to the same server that the client listens on and verifies the client forwards it.
This addresses an issue in which the client freezes and stops forwarding events, while still looking alive.

feat(KFLUXVNGD-330): deploying smee sidecar in staging

---

components/smee/staging/deployment.yaml

Two containers had the same name

fix: rename one of the smee servers containers

---

components/smee/staging/deployment.yaml

Updated the memory request in the Smee server deployment from an incorrect value to the correct format, ensuring proper resource allocation.
Signed-off-by: Barak Korren <bkorren@redhat.com>

fix: correct memory request format in Smee deployment configuration

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

On the busiest production cluster, we see pipelineruns and more rarely taskruns are not reconciled timely resulting objects removed from the cluster before they are actually stored in the DB. With the updated values we wait longer before giving up and force remove the objects.
In addition we also scale up the number of replicas of the watcher controller. Once we see the effect of it, we can lower back the time values.

Update store deadline and pruner time values

---

components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/resources/scc-rbac.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/scc-rbac.yaml

Both `toolchain-member-operator` and `pipeline-service` components are deploying the appstudio-pipelines-runner. This is causing failures.
Requires:

fix appstudio pipelines runner cr conflict prod

---

components/etcd-shield/base/deployment.yaml
components/etcd-shield/base/kustomization.yaml

Etcd-shield has two sets of threads:
- One set queries alertmanager for etcd's state.
- One set handles admission requests.
These threads communicated by reading/writing serialized state to a configmap.  However, etcd-shield now supports communicating this state over memory shared between threads.  Configure etcd-shield to use this new IPC mechanism.

etcd-shield: use in-memory IPC in staging

---

components/monitoring/grafana/base/dashboards/kueue/dashboard.yaml
components/monitoring/grafana/base/dashboards/kueue/kueue.json
components/monitoring/grafana/base/dashboards/kueue/kustomization.yaml
components/monitoring/grafana/base/dashboards/kustomization.yaml

The dashboard will show:
- Kueue (and plugins) health status
- Cluster queue resource utilization
- Cluster queue Workloads status
- Cluster queue duration metrics for Workloads admission.

KFLUXINFRA-1734: Add a dashboard for Kueue

---

components/konflux-ui/production/base/proxy/proxy.yaml

I've included the same config we added in staging to make kubearchive accessible withink konflux-ui if the KUBEARCHIVE_URL parameter is set up.
Related: https://issues.redhat.com/browse/KFLUXINFRA-1629
Currently it's only set up for `stone-prod-p02`. Related: https://issues.redhat.com/browse/KFLUXINFRA-1778

Enable kubearchive access from nginx in prod if configured

---

components/backup/base/all-clusters/oadp/install-oadp.yaml
components/backup/staging/stone-stage-p01/dpa-channel-patch.yaml
components/backup/staging/stone-stage-p01/kustomization.yaml
components/backup/staging/stone-stg-rh01/dpa-channel-patch.yaml
components/backup/staging/stone-stg-rh01/kustomization.yaml

The update is required for upgrading the cluster to 4.16.
```
openshift-adp/oadp-operator.v1.3.6 is incompatible with OpenShift minor versions greater than 4.15
```
[KFLUXINFRA-1760](https://issues.redhat.com//browse/KFLUXINFRA-1760)

Upgrade OADP operator on all clusters

---

components/smee/staging/deployment.yaml

This eliminates the use of GET calls with side effects.

chore: move smee server sidecar to file based probe

---

components/smee-client/staging/deployment.yaml
components/smee/staging/deployment.yaml

Sidecar crashed as it went out of memory.

fix: increase smee sidecar memory

---

components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml

The _count metrics previously used are the number of observations for the workqueue latency, wheras the _sum metrics are the sum of the latency reported by all items in the queue. In order to get the average latency per item, the formula is `sum(rate(metric_sum))/sum(rate(metric_count))`
The previous graph was actually showing the number of items being processed, not their latencies.
Also note that because `reconcile_latency` metrics are in milliseconds, we divide the final number by `1000` since the graph is in units of seconds
Before this change the workqueue depth remains quite high in spite of the workqueue latency being "low"
After this change the workqueue depth correlate more appropriately. We can also see a big difference in the reconcile latency at times

Fix Tekton Results grafana dashboard rates

---

components/authentication/base/group-sync/kustomization.yaml
components/authentication/base/group-sync/test-platform-ci-admins-rover-group.yaml
components/authentication/base/kustomization.yaml
components/authentication/base/test-platform-ci-admins-can-view.yaml
components/authentication/k-components/ldap-url-patch/kustomization.yaml

Test Platform is in the middle of implementing a new feature (provision Test Platform ephemeral clusters from Konflux) and this would ease troubleshooting when things go sideways.
[Here](https://rover.redhat.com/groups/group/test-platform-ci-admins) the members who belong to the `test-platform-ci-admins` group.
Check https://github.com/konflux-ci/crossplane-control-plane/pull/33 to get more context about `testplatformclusters` and `xtestplatformclusters` objects.

Grant test-platform-ci admins permission to troubleshoot testplatformclusters Claim and XR

---

components/enterprise-contract/ecp.yaml

This commit updates references to the Enterprise Contract config repo from `enterprise-contract/config` to `conforma/config`.
Ref: [EC-1115](https://issues.redhat.com//browse/EC-1115)

chore: update references to ec config repo

---

components/authentication/base/test-platform-ci-admins-can-view.yaml

Follow up of https://github.com/redhat-appstudio/infra-deployments/pull/6925 but for viewing crossplance objects.

Grant test-platform-ci admins permission to view crossplane objects

---

components/konflux-ui/staging/base/proxy/proxy.yaml
components/kubearchive/development/kustomization.yaml

Include impersonation and remove old workaround
to enable the UI to access the KubeArchive API
with proper permissions.

Upgrade to KubeArchive v1.2.0

---

argo-cd-apps/overlays/development/delete-applications.yaml
components/etcd-shield/base/metrics/metrics-service.yaml
components/etcd-shield/base/metrics/monitor.yaml
components/etcd-shield/base/metrics/network-policy.yaml
components/etcd-shield/base/metrics/rbac.yaml

Reverts redhat-appstudio/infra-deployments#6834
We're seeing timeouts on etcd-shield's webhooks since this PR was merged.  A fix will be filed in a separate PR.

Revert "etcd-shield: fix metrics in staging"

---

components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

Those 2 profiles were on all the non dedicated clusters except p02. Users are requesting them on p02 to migrate some builds from rh01 to p02.

Add 2 MPC VM profiles to p02

---

components/etcd-shield/production/base/rbac.yaml

The metrics service for etcd-shield needs to be able to create TokenReviews and SubjectAccessReviews to ensure metrics clients have appropriate permissions to view metrics.  Since a RoleBinding is already configured to accept this, add the appropriate ClusterRole to give etcd-shield's service account permissions to create these resources.

etcd-shield: add ClusterRole for metrics auth

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Based on https://issues.redhat.com/browse/SPRE-1542 we are going to add the namespaces related with apiserver to monitor replica count as part of konflux_up signal

Adding apiserver namespaces to monitoringstack

---

components/smee-client/staging/deployment.yaml

It doesn't seem as the sidecar is leaking memory, but at the same time, its container does ask for more memory over time.
Setting GOMEMLIMIT should hopefully make its memory request stabilize.

chore: set GOMEMLIMIT for smee-sidecar in staging

---

components/cluster-as-a-service/base/clustertemplates.yaml

This version includes a new `fips` value and updated dependencies.

Use v0.1.7 of the hypershift-aws-cluster chart with EaaS

---

components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-test.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/authenticated-rolebinding.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-private-tenant-namespace.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-public-tenant-namespace.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-clusterrole-rolebinding.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-tenant-namespace.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/tenant-namespace.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/wrong-clusterrole-rolebinding.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kustomization.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kyverno_rbac.yaml
components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/set-tenant-namespace-visibility-clusterpolicy.yaml

[KFLUXINFRA-1522](https://issues.redhat.com/browse/KFLUXINFRA-1522)
This commit adds a Kyverno policy that adds the
`konflux-ci.dev/visibility`` label to any tenant namespace ands sets it to 'public' if the RoleBinding for the `system:authenticated group exists or to private otherwise. The policy is currently only added to the staging clusters for testing.
Assisted-by: Gemini

Create namespace visibility Kyverno policy

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Promoting the change from  #7013  to production
This update includes a feature to disable storing of incomplete PipelineRuns and TaskRuns aiming to reduce the calls on the k8s API server, decrease the workqueue size and improve the overal performance.

Update Results in Production, disable storing incomplete runs

---

components/integration/base/kustomization.yaml
components/integration/base/manage-resolutionrequests.yaml

Now that the integration service is creating resolutionrequests the integration team needs to be able to manage  resolutionrequests in order to debug issues that arise on the cluster

chore: give integration team permission to manage resolutionrequests

---

components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml

As part of testing Kueue, a large amount of pipelines will be run on the cluster. Increase the memory of the pipelines controller in order to allow it.

public-stage: Increase pipelines controller memory

---

components/mintmaker/base/external-secrets/brew-registry-redhat-io-pull-secret.yaml

Add the following lable to brew.registry.redhat.io secret:
mintmaker.appstudio.redhat.com/secret-type: registry
mintmaker will combine secrets with this label, and mount it to Renovate container, then podman/skopeo can use the combined secret for image pulling.

mintmaker: update brew.registry.redhat.io secret labels

---

components/smee-client/staging/kustomization.yaml
components/smee-client/staging/rbac.yaml

The team needs it in order to maintain the smee client.

stage: Give the Vanguard team admin permission on the smee-client ns

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Initial value (1.5Gi) was set as Gi, but the controller is transforming it to Mi (1536Mi) and it's "fighting" with ArgoCD over that value, blocking the TektonConfig update. So no real change here, the actual value will remain the same, only the representation is changed.

Set memory limit as Mi

---

components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml

Remove the s390x & ppc64le platforms from dynamic provisioning and add the 8 static PPC VMs to the host config.

Update kflux-osp-p01 MPC host config for IBM VMS

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

This update includes a fix, to skip reconciliation of stored PieplineRuns and TaskRuns.
Previous PR #7062 updated stage.

Update Tekton Results to v0.15.2-2 prod

---

components/cluster-as-a-service/base/multicluster-engine.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml

This adds support for provisioning OCP 4.18 with EaaS.

Upgrade MCE operator to 2.8 in prod

---

components/kubearchive/base/monitoring-servicemonitor.yaml
components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Due to how KubeArchive exposes metrics the `job` gets overwritten by a higher layer and it can't be changed, so we need to let `exported_job` to be passed to Prometheus. The reasoning behind that `honorLabels` is not honored is because users could potentially override labels as `namespace` leading to confusion and problems in metrics analysis. https://issues.redhat.com/browse/MON-793 and  PVO11Y-4845 for details.

KubeArchive: allow exported_job to reach Prometheus

---

components/monitoring/prometheus/base/rbac/monitoring-all-admin.yaml

This is necessary for debugging of said resources.

Allow o11y admins to view all monitoring resources in cluster

---

components/smee-client/base/deployment.yaml
components/smee/base/deployment.yaml

Upgrade gosmee to latest version, as preparation for installing smee sidecar in production

chore: upgrade gosmee image in production

---

components/monitoring/prometheus/base/rbac/kustomization.yaml

The new rolebinding was not deployed because it was not added to the kustomization file resources.

PVO11Y-4852 Fix: add new rolebinding to kustomization file

---

components/konflux-info/production/kflux-ocp-p01/info.json
components/konflux-info/production/kflux-prd-rh02/info.json
components/konflux-info/production/kflux-prd-rh03/info.json
components/konflux-info/production/kflux-rhel-p01/info.json
components/konflux-info/production/stone-prd-rh01/info.json
components/konflux-info/production/stone-prod-p01/info.json
components/konflux-info/production/stone-prod-p02/info.json
components/konflux-info/staging/stone-stage-p01/info.json
components/konflux-info/staging/stone-stg-rh01/info.json
hack/new-cluster/templates/konflux-info/info.json

related to [KONFLUX-8558](https://issues.redhat.com/browse/KONFLUX-8558), it is beneficial for the UI to be able to differentiate, if the current deployment is public or private

add deployment visibility to konflux-info

---

components/integration/production/base/kustomization.yaml

* Revert production version for integration service to the [5a79cbca6e8769fc9077dd11edca888d8058c74a](https://github.com/konflux-ci/integration-service/commit/5a79cbca6e8769fc9077dd11edca888d8058c74a) commit that's before the one that introduces the bug with webhooks preventing creation of an application through the UI

fix(KFLUXSPRT-4158): revert integration production to 5a79cbc

---

components/kubearchive/development/kustomization.yaml

Our operator is getting restarted due to etcd defrag that makes the leases unavailable for more than 15s, the default timeout for leases. I'm disabling the leader election since patching the timeout will take some days.

KubeArchive: disable leader election

---

components/konflux-rbac/base/konflux-integration-runner.yaml
components/konflux-rbac/base/kustomization.yaml
components/konflux-rbac/production/base/konflux-integration-runner.yaml
components/konflux-rbac/production/base/kustomization.yaml

Integration pipelines will eventually use new service accounts bound to this role.
Permissions for SpaceRequests are not included since toolchain is obsolete.
Assisted-by: cursor (claude-4-sonnet)

ClusterRole for integration pipeline service account runner

---

components/cluster-secret-store-rh/production/stone-prd-rh01/insights-secret-store.yaml

Trying to use the "consoledot-snyk" secret for [Subscription Watch](https://github.com/RedHatInsights/rhsm-subscriptions) (see https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/7660/diffs#88bfeccd05d09f58822ad7470f1e0a80599152a4_0_5).
ArgoCD is giving us this error.
```
error retrieving secret at .data[0], key: creds/konflux/app-sre-konflux, err: using cluster store "insights-appsre-vault" is not allowed from namespace "rh-subs-watch-tenant": denied by spec.condition
```
A very long slack rabbit hole led me here.

Allow rh-subs-watch-tenant access to insights-secret-store

---

components/kueue/development/queue-config/cluster-queue.yaml
components/kueue/development/queue-config/kustomization.yaml
components/kueue/development/queue-config/workload-priority-class.yaml
components/kueue/development/tekton-kueue/config.yaml
components/kueue/development/tekton-kueue/kustomization.yaml

- Add WorkloadPriorityClass resources (see workload-priority-class.yaml)
- Add tekton-kueue configuration with CEL expressions for:
- Multi-platform pipeline resource requests (linux-arm64, linux-amd64, linux-s390x, linux-ppc64le)
- Dynamic priority assignment based on PAC event types, service labels, and namespaces
- Support for both new and legacy multi-platform pipeline formats
- Update cluster queue with nominalQuota for multi-platform VMs:
- Add quotas for linux-arm64, linux-amd64, linux-s390x, linux-ppc64le (10 each)
- Configure tekton-kueue-config ConfigMap generation from config.yaml

feat: set pipeline priority and multi-platform build quotas for development

---

components/konflux-ui/staging/base/proxy/auth.conf
components/konflux-ui/staging/base/proxy/kubearchive.conf
components/konflux-ui/staging/base/proxy/kustomization.yaml
components/konflux-ui/staging/base/proxy/nginx.conf
components/konflux-ui/staging/base/proxy/proxy.yaml
components/konflux-ui/staging/base/proxy/tekton-results.conf
components/konflux-ui/staging/stone-stage-p01/kubearchive.conf
components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml

As owners of the KubeArchive component within Konflux we are going to be asked if the UI doesn't have access to the KubeArchive API and that could happen due to issues on the nginx configuration.
Due to this, I want to propose a refactor on how the different imported configurations within the `nginx.conf` file are exposed, not only doing changes on the `kubearchive.conf` part but also on the `tekton-results.conf` and `auth.conf` configuration files.
With these changes I am covering the following:
* Reduce what's done in the `generate-nginx-config` initContainer of the `nginx` pod. Now it only fills the `API_TOKEN` for the impersonation
* Exposing `tekton-results.conf` and `kubearchive.conf`as ConfigMaps that are directly mounted on the `nginx` container of the `nginx` Pod
* To disable …

Refactor nginx configs structure

---

components/knative-eventing/base/kustomization.yaml

We forked eventing and created a solution so the eventing controller does not create subjectaccessreviews, so the Kubernetes API is happier. When the solution lands into the latest eventing version we will update it accordingly and remove this patch.

Eventing: SubjectAccessReview fix

---

components/kueue/staging/base/tekton-kueue/config.yaml

MPC tracks some platforms as `linux/x86_64`, but kueue expects them to be `linux-x86-64`.  The CEL expressions we have for making platform requests produces `linux-x86_64`, which is not recognized as a platform and causes all pipelineruns with this platform to always be held in a pending state.
To fix this, have the CEL expressions replace the underscores in `x86_64` with `-`.  `x86_64` is the only platform with underscores, so no other platform will be affected by this change.

kueue: replace "_" with "-" in build platforms

---

components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

The RHEL rpm builds are building x86_64 using MPC VMs, not in cluster so change the MPC EC2 instances from m6a to m7a.
[KONFLUX-8247](https://issues.redhat.com//browse/KONFLUX-8247)

Replace rhel-p01 AMD VMs by m7a

---

components/multi-platform-controller/base/rbac/pod-debug-restart.yaml

Once debug pod is created, they need access to secret in MPC namespace to be able to connect to the MPC VMs.
Remove konflux-sre, we do not want to give secrets access to people outside of the infra team.

Gran konflux-infra member permissions to debug MPC

---

components/monitoring/grafana/base/dashboards/kueue/kueue.json

1. Optimize widget size and position.
2. Add widget for tekton-kueue cel evaluation failures
3. Add widget for the increase in the number of workloads
4. Add widget for the 99th percentile for wait time in the queue.
5. Add widget for the 99th percentile for pipeline deletion time.
6. Fix the query for the cpu usage which had an issue with many-to-many mapping between time series.

Update Kueue dashboard

---

components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml

We get errors because the threshold was reached.
rh01 already has the value configured to 4000.
Set the same value for p02.

Update Kyverno updateRequestThreshold in p02

---

components/namespace-lister/base/network_policy_allow_from_konfluxui.yaml

I'm pretty sure this is a typo.
If two entries appear in a list like this, they are "OR"'d together, like "any pod matching the namespace selectors" or "any pods matching the podselector [in this namespace]", which is not what we want.
Things are currently working, because the namespaceselector permits *any* pod in the matched namespaces, which includes the single target pod we wanted to permit.
By making this into a list of one rule, we'll permit only the matched pod in only the matched namespace to speak to this target pod.

Fix namespace-lister NetworkPolicy ingress rule

---

components/kyverno/development/kyverno-helm-values.yaml

Configure the lease values according to OCP's recommendations:
http://github.com/openshift/enhancements/blob/0f916a52af1a6fbdab0c5b80ae0e66c7a27efb6a/CONVENTIONS.md#handling-kube-apiserver-disruption
Also, enable the cleanup controller in the development env so this change can be tested.
Note, LeaseDuration and RenewDeadline are a function of the retryPeriod as can be seen in https://github.com/kyverno/kyverno/blob/418a845ff6cbc9c3c064ee56a633dd306a317ed8/pkg/leaderelection/leaderelection.go#L77-L78

development: Recommended lease config for kyverno

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Values calculated based on the resources consumed by pods in the past 7 days in stone-prd-rh01, stone-prod-p01, and stone-prod-p02, as seen in [this grafana query](https://grafana-access-appstudio-grafana.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/explore?schemaVersion=1&panes=%7B%22y99%22:%7B%22datasource%22:%22064f2b18-a714-4631-997b-1fe80bb695b5%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22max%20by%28deployment%29%20%28label_replace%28container_memory_working_set_bytes%7Bnamespace%3D%5C%22openshift-pipelines%5C%22,%20container%3D%5C%22%5C%22%7D,%20%5C%22deployment%5C%22,%20%5C%22$1%5C%22,%20%5C%22pod%5C%22,%20%5C%22%28%5B-a-z%5D%2B%29-.%2A%5C%22%29%29%5Cn%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22064f2b18-a714-4631 …

add resource limits and requests for pipelines staging

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

This commit exports two metrics that will be important for monitoring MintMaker service quality.
The metrics are already contributed to 'o11y', now we need to export them in order to have them available in the monitoring stack. (https://github.com/redhat-appstudio/o11y/blob/main/rhobs/recording/mintmaker_service_quality_recording_rules.yaml)

Export cluster RAM metrics for MintMaker

---

argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml

It appears that pulp should be in all clusters, not just the internal clusters.  It's already in the staging clusters and internal production, but we didn't remove the deletion patch from the public production overlays in #6561.
Remove the deletion patch so that pulp is deployed to the public production clusters.
Fixes: fbef70802 ("pulp to production (#6561)")

add pulp-access-controller component to public prod

---

argo-cd-apps/base/member/infra-deployments/konflux-kite/konflux-kite.yaml
argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
components/konflux-kite/base/deployment.yaml
components/konflux-kite/base/external-secrets/database-secret.yaml
components/konflux-kite/base/kustomization.yaml
components/konflux-kite/base/routes.yaml
components/konflux-kite/development/kustomization.yaml
components/konflux-kite/development/postgresql.yaml
components/konflux-kite/staging/stone-stg-rh01/kustomization.yaml

Deploy proof-of-concept Kite service to a public staging instance.
**Requires**:

Deploy Kite service to staging

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Also override the tkn-cli-serve image, as the image ref is broken in that latest release. tkn-cli-serveis not used anyway, so this should have no impact.

Set GIT_SSL_CAINFO env on Pipeline resolvers prod

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

This commit will change the max-instance for all the platforms specified in host-config making sure allowed number of instances do not exceed 250 instances.

KFLUXINFRA-1970: Change Max Instances for MPC Platforms

---

components/konflux-ci/base/kustomization.yaml
components/konflux-ci/base/test-runner-cluster-role.yaml
components/konflux-ci/base/test-runner-rolebinding.yaml

After moving test execution to rh03 cluster, appstudio-pipeline sa missing permission to get image-repositories causing the tests to fail, adding the needed ClusterRole and RoleBiding.

fix: adding rbac needed to run tests

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml

Tekton manager, which runs on Saturdays is currently broken, so we should skip its run on the upcoming Saturday. This change disables MintMaker from running during the entire day.
This solution was chosen because it's safer than doing a hasty prod deployment.

Disable MintMaker runs on Saturday

---

components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled-extra.yaml
components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml

We need to create the resources only when the namespace is promoted to tenant namespace. We can skip the other updates to the namespaces.

restrict update event for integration's ClusterPolicy

---

components/konflux-info/base/rbac.yaml

It is for: 
https://issues.redhat.com/browse/KFLUXUI-587
PR details:
It is just one-line-change PR to ensure the konflux-banner-configmap is public as part of konflux-public-info

feat: add the konflux-banner-configmap as parts of  konflux-public-info

---

components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled-extra.yaml
components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
components/policies/development/integration/kustomization.yaml

this PR will deploy the updated version of the  integration ClusterPolicy by recreating it with a different name and at the same time add a name prefix to the component's owned resources.
Requires

restrict update event integration policy

---

components/mintmaker/production/base/manager_patch.yaml

Temporarily increase controller pod memory allocation to address recurring OOMKilled errors when memory usage reaches the current limit.

mintmaker: increase memory limit to prevent OOMKilled

---

components/knative-eventing/base/kustomization.yaml

since July 4 it has restarted 44 times. Reason: OOM Killed

increase memory for knative-eventing imc-controller

---

components/release/base/e2e-release-pipeline-resources-role.yaml
components/release/base/kustomization.yaml

- The legacy components/authentication/base/everyone-can-view.yaml seemed to include this RBAC.
- it helps users determine if a Repository might point to be deleted secret for example.

add ability to view pac repositories

---

components/kueue/development/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
components/kueue/development/tekton-kueue/kustomization.yaml
components/kueue/staging/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
components/kueue/staging/base/tekton-kueue/kustomization.yaml

- Include the rules in the platform Prometheus. When included in the UWM Prometheus a label with the namespace name (tekton-kueue) is added to the rules, which breaks them.
- Don't use critical severity so the alerts won't show up for SRE platform (they are not interested in those alerts and shouldn't do anything with them).
- Add an alert for the success rate of requests to the tekton-kueue mutating webhook servers.

KFLUXINFRA-1986: Update Kueue alerting rules

---

components/konflux-kite/base/kustomization.yaml

Use a specific SHA for the tag. This should enable auto-tag updates as well?
Relies on #7445

feat(kite): use specific SHA for tag

---

argo-cd-apps/base/member/infra-deployments/kueue/kueue.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
components/kueue/production/base/kueue/kueue.yaml
components/kueue/production/base/kueue/kustomization.yaml
components/kueue/production/base/kueue/operator.yaml
components/kueue/production/base/kustomization.yaml
components/kueue/production/base/queue-config/kustomization.yaml
components/kueue/production/base/queue-config/mintmaker-local-queue.yaml
components/kueue/production/base/queue-config/workload-priority-class.yaml
components/kueue/production/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
components/kueue/production/base/tekton-kueue-monitoring/kustomization.yaml
components/kueue/production/base/tekton-kueue-monitoring/monitoring.yaml
components/kueue/production/base/tekton-kueue/config.yaml
components/kueue/production/base/tekton-kueue/controller-patch.yaml
components/kueue/production/base/tekton-kueue/kustomization.yaml
components/kueue/production/base/tekton-kueue/webhook-patch.yaml
components/kueue/production/kflux-prd-rh02/kustomization.yaml
components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
components/kueue/production/kflux-prd-rh02/queue-config/kustomization.yaml
components/kueue/production/kflux-prd-rh03/kustomization.yaml
components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
components/kueue/production/kflux-prd-rh03/queue-config/kustomization.yaml
hack/kueue-vm-quotas/generate-queue-config.sh

- All the files in production/base are a copy of the files from staging/base. Duplicate the files in order to have precise control on staging and production configurations.
- Enable the mutating webhook only on mintmaker pipelines until https://issues.redhat.com/browse/SRVKP-8255 is resolved.
- Don't deploy the external admission check controller since it's not ready for production yet.
- Update the script which generated the cluster queue nominal quotas from the host-config to include rh02 and rh03.
- Deploy an empty overlay for the rest of the production clusters in order to gradually deploy Kueue.

KFLUXINFRA-1956: Deploy Kueue on rh02 and rh03

---

components/mintmaker/base/cronjobs/create-dependency-update-check.yaml

This reverts commit b4bd31e2d653ceecf3c75dba5667cd3e0050052b, which disabled renovate runs on Saturday.
The blockers in the pipeline migration tool have been resolved, so we're fine to run tekton manager on Saturday.

mintmaker: re-enable renovate runs on Saturday

---

components/sandbox/toolchain-member-operator/staging/stone-stage-p01/kustomization.yaml
components/sandbox/toolchain-member-operator/staging/stone-stage-p01/ns.yaml

Member operator has been removed from the toolchain-member-operator namespace, so we can clean up all the remaining resources.  Remove all resources from the toolchain-member-operator-stone-stage-p01 application (except the namespace, since argocd requires at least one resource).

stone-stage-p01: remove member operator resources

---

components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml

Add large disk instances of the latest `arm64` and `amd64` instance types available in AWS. These instance types support newer cpu features required to build and test `vllm`. And the higher network and disk performance will accelerate the very resource-intensive `vllm` builds.

KFLUXINFRA-2015: Enable newer arm64 instance types (m7g+)

---

components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
components/kueue/staging/stone-stage-p01/queue-config/cluster-queue.yaml
components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
hack/kueue-vm-quotas/update-kueue-vm-quotas.py

Sort the data produced by update-kueue-vm-quotas.py in order to get a consistent output.
Update all the cluster queue as well.

Make queue generation script output deterministic

---

components/kubearchive/staging/stone-stg-rh01/otel-collector-config.yaml

Looks like the endpoint is expected to be a GRPC:
```
2025-08-08T09:03:54.488Z info internal/retry_sender.go:133 Exporting failed. Will retry the request after interval. {"error": "rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\"", "interval": "3.074100606s"}
```

KubeArchive: fix trace sending to konflux-otel

---

components/mintmaker/production/base/manager_patch.yaml

Set GOMEMLIMIT=7GiB so the Go runtime respects Kubernetes memory limits. Although the controller is allocated 8GiB memory, in large clusters (e.g., p02 with 5000+ components) it can still be OOMKilled, possibly due to the Go runtime ignoring container limits.

mintmaker: set GOMEMLIMIT to avoid controller OOMKilled crashes

---

components/vector-kubearchive-log-collector/base/kustomization.yaml
components/vector-kubearchive-log-collector/base/rbac.yaml

The kubearchive team should be able to check logs, do port-forwards and manipulate resources to troubleshoot potential issues in this component.

Make kubearchive admins of the product-kubearchive-logging component

---

components/tracing/otel-collector/staging/otel-collector-helm-values.yaml

Configure otel-konflux opentelemetry deployment with pipeline for metrics export.

PVO11Y-4876: Enable prometheus exporter/pipeline for Konflux opentelemetry in staging

---

components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
components/monitoring/prometheus/production/base/monitoringstack/writeRelabelConfigs.yaml
components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
components/monitoring/prometheus/staging/base/monitoringstack/writeRelabelConfigs.yaml

Those metrics will be used for creating SLO alerts.

KFLUXINFRA-2067: Push Kueue metrics to RHOBS

---

components/kubearchive/staging/base/external-secret.yaml

Updates should be managed by
the external secret operator

Make argo ignore the secret updates

---

components/authentication/base/konflux-admins.yaml

Enable konflux-admins to create and delete
projects / namespaces.

Enable konflux-admins to manage OCP projects

---

components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

- revert previous change which made PAC's watcher to have a single replica (it was done for testing and isn't needed anymore).
- update PAC images in staging. The PAC image contains a fix needed for running Kueue on all pipelineruns. https://issues.redhat.com/browse/SRVKP-8255

Update PAC on staging

---

components/mintmaker/staging/base/manager_patch.yaml

Change ENABLE_PROFILING env var value from boolean `true` to string `"true"` to resolve ArgoCD sync failure. Kubernetes env vars must be strings.

mintmaker: Fix YAML type error in mintmaker manager patch

---

components/kubearchive/staging/base/kustomization.yaml

Delete the original `kubearchive-logging` Secret available in the release to prevent the outofsync situation in argo

Delete the original secret

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Addresses [KONFLUX-9696](https://issues.redhat.com/browse/KONFLUX-9696)
Opening the PR to start CI, and QE tests are also being run. If CI and QE tests are successful this PR will replace or supersede https://github.com/redhat-appstudio/infra-deployments/pull/7619

update pipelines index image in development and staging

---

components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

p02 is a very busy cluster so raising some populat platfrom (m2x-160 and m4x-160) quotas a bit (+5 VM);
Due to IP number limit, it is has to be decreased from the general arm64 limit.

Add some more AWS quotas for AMD(160) and ARM(160) on p02

---

components/cluster-as-a-service/base/multicluster-engine.yaml
components/cluster-as-a-service/production/add-hypershift-params.yaml

This adds support for provisioning OCP 4.19 with EaaS.

Upgrade MCE operator to 2.9 in prod

---

components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml

Kyverno was tuned on rh01 where is we have the highest load so align the configuration of p02 with rh01.
The main reason is to address ongoing issues where background controller is getting OOMKilled but also to get all other fixes/tuning done on rh01.

Align prod-p02 kyverno config with prd-rh01 one

---

components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml

Based on the actual recording rules created on cluster-based grafana instances, we are adding a useful recording rule to measure latency (P95,p99, verb latency, etc) which is needed in order to complete the dashboard to monitor API Server performance.

feat(/SPRE-1819) Latency metric api server

---

components/konflux-ui/production/base/proxy/auth.conf
components/konflux-ui/production/base/proxy/kubearchive.conf
components/konflux-ui/production/base/proxy/kustomization.yaml
components/konflux-ui/production/base/proxy/nginx.conf
components/konflux-ui/production/base/proxy/proxy.yaml
components/konflux-ui/production/base/proxy/tekton-results-workspaces.conf
components/konflux-ui/production/base/proxy/tekton-results.conf
components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
components/konflux-ui/production/kflux-osp-p01/kubearchive.conf
components/konflux-ui/production/kflux-osp-p01/kustomization.yaml
components/konflux-ui/production/kflux-prd-rh02/kubearchive.conf
components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
components/konflux-ui/production/kflux-prd-rh03/kustomization.yaml
components/konflux-ui/production/kflux-rhel-p01/kustomization.yaml
components/konflux-ui/production/stone-prd-rh01/kubearchive.conf
components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
components/konflux-ui/production/stone-prod-p01/kubearchive.conf
components/konflux-ui/production/stone-prod-p01/kustomization.yaml
components/konflux-ui/production/stone-prod-p02/kustomization.yaml

After applying the changes in https://github.com/redhat-appstudio/infra-deployments/pull/7417 the nginx pod failed to start with the following error:
```
nginx: [emerg] open() "/mnt/nginx-generated-config/tekton-results.conf" failed (2: No such file or directory) in /mnt/nginx-additional-location-configs/tekton-results-workspaces.conf:7
```
This refactor was then reverted in https://github.com/redhat-appstudio/infra-deployments/pull/7706
In this PR I am reapplying the initial refactor with the needed fix to prevent the error.
Note that the 7th line in `components/konflux-ui/production/base/proxy/tekton-results-workspaces.conf` now shows 
`proxy_pass https://tekton-results-api-service.tekton-results.svc.cluster.local:8080;`
instead of 
`include …

Refactor nginx config in prod

---

components/sandbox/toolchain-member-operator/production/kflux-rhel-p01/kustomization.yaml

Same as #7726, but for the RHEL cluster.
Part of [KFLUXINFRA-2121](https://issues.redhat.com/browse/KFLUXINFRA-2121).

rhel: remove member-operator subscription

---

components/external-secrets-operator/base/operator-config.yaml

The main pod is getting OOMkilled due to it's usage above requests even if below limit. Increase the request to 512Mi to make this guaranteed allocation. Also reduce limit of other 2 pods to match their request.
Those number were tuned based on production rh01 and p02 where we have the most load.
[KONFLUX-9158](https://issues.redhat.com//browse/KONFLUX-9158)

Set memory request and limits to same values for ESO

---

components/sandbox/toolchain-member-operator/production/kflux-osp-p01/kustomization.yaml

To safely remove kubesaw, we need to first remove its subscription from this repository. Since the applicationset is not configured to automatically prune resources, the subscription will remain until we're ready to fully delete it.

Disable member-operator on osp-p01

---

components/knative-eventing/base/kustomization.yaml

Image was modified from v1.16.7 to increase the verbose flag for `klog`, which is used by the k8s golang library. With this will be able to see more logs related to the watchers.

Eventing: add klog verbose flag on the image

---

components/kubearchive/development/kubearchive.yaml
components/kubearchive/development/kustomization.yaml

This PR changes KubeArchive to the version published in this branch: https://github.com/rh-hemartin/kubearchive/tree/watchers-problems. Images and installation manifest created by hemartin. The changes applies only to staging clusters.

KubeArchive: make ApiServerSource monitor all the namespaces

---

components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml

This one is hitting 100% usage quite often so double it up until we have the real fix which is to not limit individual profile but limit at the subnet level instead.

Increase quota for linux extra fast on rh01

---

components/kubearchive/development/kustomization.yaml

change namespace for the ServiceAccount subject to product-kubearchive

Fix incorrect namespace in KubeArchive ClusterRoleBinding subject

---

components/kueue/staging/stone-stg-rh01/kustomization.yaml
components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
components/multi-platform-controller/staging/host-config.yaml

Revert the code addition in #7761 :
- Deleted `linux-test-arm64` platform from stone-stg-rh01 cluster
- Deleted patching of exclude `mshaposh-tenant` namespace from Kueue
The `linux-test-arm64` is no longer needed, It was used for testing `multi_platform_controller_waiting_tasks` metric.

deleted 'linux-test-arm64' platform from stone-stg-rh01

---

components/sandbox/toolchain-member-operator/production/kflux-osp-p01/kustomization.yaml
components/sandbox/toolchain-member-operator/production/kflux-osp-p01/ns.yaml

Removes all components and resources from the member sandbox component for kflux-osp-p01 except for the namespace, which will be removed at a later date.

kflux-osp-p01: remove member operator installation

---

components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

A new base image with rhel 9.6 was created, adding temporarily a platform to test it.
[KFLUXINFRA-2149](https://issues.redhat.com//browse/KFLUXINFRA-2149)

Add MPC VM to test new s390x base image

---

components/pipeline-service/production/base/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
hack/new-cluster/templates/pipeline-service/deploy.yaml
hack/new-cluster/templates/pipeline-service/resources/update-tekton-config-pac.yaml

This should reduce some load on the cluster when pull requests are updated over and over again. Earlier unnecessary PipelinesRuns will be cancelled and impose less load.
This was deployed to staging a few weeks ago in https://github.com/redhat-appstudio/infra-deployments/pull/7079. This catches things up in prod.
Additionally, I re-ordered a few settings on different clusters to make them consistent, and updated the hack/new-cluster/templates/ to reflect this change.

KONFLUX-134: Cancel in-progress PipelineRuns for updated pull requests (prod)

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The updated production index (https://github.com/redhat-appstudio/infra-deployments/pull/7795) reverted PaC v0.37.0 to v0.35.3 and reintroduced the issue from ITN-2025-0198. This change overrides the PaC image in Staging 
Post merge the pipelines-as-code-static TektonInstallerSet will need to be deleted in all staging clusters

override pac images to v0.37.0 in staging

---

components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/pentest-p01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

The updated production index (https://github.com/redhat-appstudio/infra-deployments/pull/7795) reverted PaC v0.37.0 to v0.35.3 and reintroduced the issue from ITN-2025-0198. This change overrides the PaC image in Production.
Follows https://github.com/redhat-appstudio/infra-deployments/pull/7802 
Post merge the pipelines-as-code-static TektonInstallerSet will need to be deleted in all production clusters for the update to rollout

 override pac images to v0.37.0 in prod 

---

hack/new-cluster/templates/pipeline-service/resources/scc-rbac.yaml

It's managed by konflux-rbac, so it shouldn't be a part of the templates for pipeline-service.

remove appstudio-pipelines-runner from new cluster templates

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml

This was requested in konflux-o11y forum Slack discussion. By disabling metric export, no alerts should fire for this cluster, as no metrics will be available in RHOBS.

Stop alerts on pentest cluster by disabling metrics export

---

argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
components/konflux-ui/production/pentest-p01/kubearchive.conf
components/konflux-ui/production/pentest-p01/kustomization.yaml

The recent `pentest-01` cluster doesn't have kubearchive on it.
The UI must include specific config file to disable it in the nginx reverse proxy.

Disable kubearchive from UI in pentest cluster

---

components/pipeline-service/production/base/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-osp-p01/deploy.yaml
components/pipeline-service/production/kflux-osp-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml

'Namespace' link in PRs check's Details is broken. This change will fix it.
Example PR: https://github.com/konflux-ci/namespace-lister/pull/154/checks?check_run_id=47756929239
* Actual value in Namespace Field: https://detailurl.setting.custom-console-url-namespace.is.not.configured/
* Desired value: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/konflux-tenant-ops-tenant

add custom-console-url-namespace in prod

---

components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/chainsaw-test.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-no-labels.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-with-virtual-annotation.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-with-virtual-label.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace-with-virtual-annotation.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace-with-virtual-label.yaml
components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace.yaml
components/policies/development/namespace-lister/deny-virtual-domain/deny-virtual-domain.yaml
components/policies/development/namespace-lister/deny-virtual-domain/kustomization.yaml
components/policies/development/namespace-lister/kustomization.yaml
components/policies/staging/base/kustomization.yaml
components/policies/staging/base/namespace-lister/kustomization.yaml

The namespace-lister is adding virtual labels and annotations to namespaces. We want to prevent other users to use them too.

add ClusterPolicy to deny reserved virtual domain

---

components/monitoring/prometheus/production/pentest-p01/cluster-id-label.yaml
components/monitoring/prometheus/production/pentest-p01/kustomization.yaml

Previous attempt to stop metric export did not work, as removing the cluster name from the list only caused the clusterDir value to not be set. The Application is still generated via the 'clusters' generator. Attempt to create an Application that manages no resources by modifying the cluster-specific component kustomization.

Stop alerts on pentest cluster by disabling metrics export v2

---

components/policies/development/namespace-lister/deny-virtual-domain/deny-virtual-domain.yaml

We are facing the validation error `admission webhook "validate-policy.kyverno.svc" denied the request: no unique match for kind Namespace`.
This change adds Group and Version in the ClusterPolicy's match.
Follows up to #7600

use Group/Version/Kind in deny-virtual-domain

---

components/konflux-ui/production/base/kustomization.yaml

Repository: konflux-ci/konflux-ui
Changes between 8677bb5484d4247048f6e0c9b50f2de5cad9a91d and e16d3ec760ad648f5fa43570bc9d5cb1c14202b0
- konflux-ci/konflux-ui#343 feat: support system alerts by @testcara [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/343))
- konflux-ci/konflux-ui#351 feat([KFLUXUI-658](https://issues.redhat.com//browse/KFLUXUI-658)): added option to select integration test configuration by @janaki29 [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/351))
- konflux-ci/konflux-ui#352 feat([KFLUXUI-607](https://issues.redhat.com//browse/KFLUXUI-607)): add icons for dark theme by @milantaky [``] ([PR](https://github.com/konflux-ci/konflux-ui/pull/352))
- konflux-ci/konflux-ui#357 feat([KFLUXUI-309](https://issues.redhat.com//browse/KFLUXUI-309)): removed …

promote ui to production

---

components/backup/staging/stone-stage-p01/backup-tenants-patch.yaml
components/backup/staging/stone-stage-p01/kustomization.yaml
components/backup/staging/stone-stg-rh01/backup-tenants-patch.yaml
components/backup/staging/stone-stg-rh01/kustomization.yaml

Rather than only including a select few resources in our tenant backups, let's include everything and filter out the resources we don't want.  For now, that means excluding pipelineruns, taskruns, and pods.
The first commit (c569e94) is a formatting change so that the kustomization manifests play better with `kustomize edit`.
The second commit (2f321be) adds patches to implement this on the staging clusters.  Until we're confident in this change and have validated that it works, hold off on rolling this out to the production clusters.

staging: use exclusion lists for resources

---

OWNERS

Allow o11y to approve changes related to their service ApplicationSets, which are located outside of the component folders.

Add o11y team members

---

components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml

The reason we reduced number of VMs was for the sum of them all to not exceed 250, which is the number of IPs we have on AWS side for MPC VMs.
The problem is this is artificially creating queues and user build are stuck in pending stated for up to hours sometime. We are working on a change to have a resource queue to make sure we do not create more than 250 VMs at the time otherwise we will get into provisioning issue because of lack of IPs.
We were supposed to land resource queue counting IPs before allowing MPC to create more VMs but the problem of long waiting time in the queue is worse than original problem being solved. For that reason, allow right away MPC to create up to 250 VMs of each type to unblock users and ip queue change will follow soon after.
Do the change on p02 first, …

Allow up to 250 VMs of each AWS type

---

components/kueue/development/queue-config/cluster-queue.yaml
components/kueue/development/tekton-kueue/config.yaml
hack/test-tekton-kueue-config.py

For each requested platform from AWS, request an IP by specifying the "aws-ip" resource in the pipeline's annotation using tekton-kueue CEL expressions.
This change will affect only the development overlay.
Requires: https://github.com/konflux-ci/tekton-kueue/pull/91

KFLUXINFRA-2161: Control AWS IP requests using Kueue

---

components/release/base/cronjobs/remove-expired-releases.yaml

this PR increases the limits of the pod that deletes old releases from the namespaces

fix(KFLUXSPRT-4896): increase pod requests/limits

---

components/knative-eventing/production/kflux-prd-rh03/kustomization.yaml

Replaced the whole kustomization to be able to replace resources. Resources that are not added can't be modified, so we wouldn't be able.

Eventing: change kflux-prd-rh03 image to be verbose

---

components/sandbox/toolchain-member-operator/production/kflux-prd-es01/kustomization.yaml

Needed to safely remove kubesaw from this cluster.

sandbox: remove member sub from prd-es01

---

components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/kustomization.yaml

Needed to safely remove kubesaw from this cluster.
Part-of: [KFLUXINFRA-2220](https://issues.redhat.com//browse/KFLUXINFRA-2220)

sandbox: remove host sub from ocp-p01

---

components/pipeline-service/development/main-pipeline-service-configuration.yaml

Using the same config used in stage/prod cluster for pipeline-service component so that rerun of push pipelineruns work on development clusters.

fix: use pac latest images in development overlays

---

components/vector-kubearchive-log-collector/staging/base/kustomization.yaml
components/vector-kubearchive-log-collector/staging/base/sa.yaml

After the refactor made in https://github.com/redhat-appstudio/infra-deployments/pull/7886 I removed unwillingly the grafana service account in staging. 
This PR is fixing that.

Fix readd grafana SA to staging

---

components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml

Both `/etc/cdi` and `/var/run/cdi` are valid locations for CDI config, with the latter overriding the former. Make both world-writable so config can be modified by users as necessary.
No need to `su - ec2-user`, Konflux workloads run as a newly-created random user. Making the directory world-writable is sufficient.

gpu instances: make /var/run/cdi world-writable

---

components/konflux-ui/OWNERS

To ensure the review does not reply on UI team, let us expand the owners.

feat: add the infra team as owners

---

components/kueue/production/kflux-ocp-p01/config.yaml
components/kueue/production/kflux-ocp-p01/kustomization.yaml
hack/test-tekton-kueue-config.py

Allow the ART team to decide their workloads priorities. If a priority isn't defined on the PLR using a label, choose the priority using the same way like on the other clusters.
Adjust the test to test tekton-kueue configs from all of the overlays.

ocp-p01: Support user defined workload priority class

---

components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/kflux-rhel-p01/external-secrets.yaml
components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

Before switching officially RHEL to the VMs in FRA datacenter, add one of each as a new platform so we can test them.
[KFLUXINFRA-2154](https://issues.redhat.com//browse/KFLUXINFRA-2154)

Temporarily add new RHEL s390x VMs in FRA

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/trust-manager/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/trust-manager/trust-manager.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
components/trust-manager/OWNERS
components/trust-manager/development/kustomization.yaml
components/trust-manager/development/trust-manager-helm-generator.yaml
components/trust-manager/staging/kustomization.yaml
components/trust-manager/staging/trust-manager-helm-generator.yaml

Trust Manager is a Kubernetes controller that distributes trust bundles (X.509 certificate authority certificates) across namespaces and automatically updates them when they change. It's part of the cert-manager ecosystem and helps with certificate management in Kubernetes clusters.
Adding trust-manager to development and staging environments
- add trust-manager development overlays
- add trust-manager kustomization
- using HelmChartInflationGenerator to install trust-manager
- add trust-manager argocd application set
- Use the cert-manager namespace
- update resources requests and limits in staging following Gamini review
- Not using base directory for the trust-manager component as it fails in the CI:
`Error when running kustomize build for components/trust-manager/base: Error: Error: …

feat(KFLUXVNGD-469): add trust-manager to development and staging

---

components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml

To prevent this errors seen in prod:
level=warn ts=2025-09-13T09:23:32.678944981Z caller=grpc_logging.go:76 method=/logproto.Pusher/Push duration=123.525µs msg=gRPC err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded when trying to create stream {stream=\"93e2e14a-22ad-411f-9e41-919660f87269-place-scripts\"}, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'kubearchive'"
I'm increasing the maximum number of streams.
I cannot decrease the cardinality because I need to have a label per container and we already have the minimum streams needed.

Increase the max global streams in prod

---

components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml

As part of the short-term strategy to fix the bug in reference, newer versions of the RHEL kernel are used in these images so that the RHEL team can verify if this fixes the issues they've been seeing. These images are based on RHEL 9.6 with kernel version 5.14.0-570.41.1.el9_6
Even if this is not the latest kernel, it matches what the static machines for IBM PowerPC use and it's not too far away from what the s390x machines are using, 5.14.0-570.37.1.el9_6.

KFLUXINFRA-2150 - Update AWS AMIs for x86_64 and ARM64 architectures

---

components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
components/konflux-rbac/production/base/konflux-viewer-user-actions.yaml
components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
components/konflux-rbac/staging/base/konflux-viewer-user-actions.yaml

Until we get the status of the Workload copied into the status of the Pipelinerun, let users see Workloads so they can understand the status of the Pipelinerun in the context of queuing.

Give users permission to view Kueue Workloads

---

components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
components/kyverno/production/kflux-osp-p01/kyverno-helm-values.yaml
components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
components/kyverno/production/pentest-p01/kyverno-helm-values.yaml
components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml

As reported in the bug in reference, the frequent restarts in kyverno pods seem related to the controllers being unable to communicate consistently with the cluster API server. A related investigation ([KONFLUX-7952](https://issues.redhat.com//browse/KONFLUX-7952)) found a correlation between these incidents and etcd going through a defragmentation.
This commit modifies the only available parameter in kyverno to control the leader election process, increasing 'leaderElectionRetryPeriod' to 26 seconds as recommended by the OpenShift convention document  [1]. Setting this value modifies the LeaseDuration to 156 seconds and the RenewDeadline to 130 seconds according to the kyverno source code [2].
[1] https://github.com/openshift/enhancements/blob/0f916a52af1a6fbdab0c5b80ae0e66c7a27efb6a/CONV …

KONFLUX-9160 - Recommended lease configuration for kyverno

---

components/build-service/production/kflux-osp-p01/webhook-config.json
components/build-service/production/stone-prod-p01/webhook-config.json
components/smee-client/production/kflux-osp-p01/sever-url-patch.yaml
components/smee-client/production/stone-prod-p01/sever-url-patch.yaml

[KFLUXINFRA-1786](https://issues.redhat.com//browse/KFLUXINFRA-1786)
Update the stone-prod-p01 and kflux-osp-p01 clusters's gosmee webhooks to point to the new gosmee server on the common external production cluster.

Update gosmee server webhooks

---

components/project-controller/production/kustomization.yaml

Update production deployment to use STAGE SHA b252edc9e91cb5e5ffb1834dd2c91bdcaa1d0569
This promotes 22 commits from STAGE including:
- Improved CRD comments and API documentation
- Fixed configure-pac loops (KFLUXVNGF-433)
- Multiple dependency updates and infrastructure improvements
Assisted-By: Cursor (Default model)

promote project-controller from STAGE to PROD

---

.github/workflows/gemini-dispatch.yml
.github/workflows/gemini-review.yml

Since most pull requests (PRs) are opened with a forked branch, the permissions being used are read-only by default because of GitHub. This causes errors to occur when the workflow attempts to write a comment to the PR. These permissions cannot be changed even with explicit configuration in the workflow, so the user will be expected to invoke the review workflow manually via a comment starting with `@gemini-cli /review`.
An additional workflow has been added to add a helper comment to the PR when it is opened. This comment will help the user get started with the Gemini AI assistant.

Remove trigger for pull_request open event

---

components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml

To continue with the SLO work, we need to create a dashboard for openshift-pipelines team. There is already a created dashboard in each cluster, but we need to create one in app-sre grafana instances, and for that we need to expose few metrics.

feat(SRVKP-8847) Exposing Stage Metrics

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/squid/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/squid/squid.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
components/squid/OWNERS
components/squid/development/kustomization.yaml
components/squid/development/squid-helm-generator.yaml
components/squid/staging/kustomization.yaml
components/squid/staging/squid-helm-generator.yaml

- Deploy squid to development and staging environments
- Exclude from production clusters 
- Should be rebase and merge only after https://github.com/redhat-appstudio/infra-deployments/pull/7918 will be merged

feat(KFLUXVNGD-416): deploy squid to development and staging

---

.github/workflows/kube-linter.yaml
components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-osp-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-prd-rh03/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-rhel-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/pentest-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
components/kubearchive/base/migration-job.yaml
components/kyverno/development/job_resources.yaml
components/kyverno/production/kflux-ocp-p01/job_resources.yaml
components/kyverno/production/kflux-osp-p01/job_resources.yaml
components/kyverno/production/kflux-prd-rh02/job_resources.yaml
components/kyverno/production/kflux-prd-rh03/job_resources.yaml
components/kyverno/production/kflux-rhel-p01/job_resources.yaml
components/kyverno/production/pentest-p01/job_resources.yaml
components/kyverno/production/stone-prd-rh01/job_resources.yaml
components/kyverno/production/stone-prod-p01/job_resources.yaml
components/kyverno/production/stone-prod-p02/job_resources.yaml
components/kyverno/staging/stone-stage-p01/job_resources.yaml
components/kyverno/staging/stone-stg-rh01/job_resources.yaml
components/pipeline-service/development/main-pipeline-service-configuration.yaml

Needed for #8216, since it appears the current version (v0.7.2) gives false warnings about pod disruption budgets.

ci: bump kubelinter to v0.7.6

---

.kube-linter.yaml
components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-osp-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-prd-rh03/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/kflux-rhel-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/pentest-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
components/kubearchive/base/migration-job.yaml
components/kyverno/development/job_resources.yaml
components/kyverno/production/kflux-ocp-p01/job_resources.yaml
components/kyverno/production/kflux-osp-p01/job_resources.yaml
components/kyverno/production/kflux-prd-rh02/job_resources.yaml
components/kyverno/production/kflux-prd-rh03/job_resources.yaml
components/kyverno/production/kflux-rhel-p01/job_resources.yaml
components/kyverno/production/pentest-p01/job_resources.yaml
components/kyverno/production/stone-prd-rh01/job_resources.yaml
components/kyverno/production/stone-prod-p01/job_resources.yaml
components/kyverno/production/stone-prod-p02/job_resources.yaml
components/kyverno/staging/stone-stage-p01/job_resources.yaml
components/kyverno/staging/stone-stg-rh01/job_resources.yaml
components/pipeline-service/development/main-pipeline-service-configuration.yaml

These were added on recommendation from a kube-linter check.  However, these fields have issues with gitops-style deployments through ArgoCD.
When jobs finish, they will automatically delete themselves, which ArgoCD picks up on.  It will try to recreate these jobs, since they're a part of the Application's manifests, which means all of the jobs in this repository are running far more frequently than intended.
To fix, remove all the ttl autoremoval fields for jobs added in #8233 and disable the warning in kube-linter entirely.
Fixes: 4912f74d2 ("ci: bump kubelinter to v0.7.6 (#8233)")

disable job autocleanup

---

components/repository-validator/staging/kustomization.yaml

Temporarily, to migrate internal services from appsre clusters to konflux common clusters, release team need stone-stage-p01 to access GH repos to validate things by running their e2e tests using those GH repos.

Allow release team repos on internal staging

---

components/squid/base/kustomization.yaml
components/squid/base/rbac.yaml
components/squid/staging/kustomization.yaml

Add permissions to squid
The CI is failing when using a helm-generator yaml file in base and directing the layouts to it, because both development and staging environments are referencing the same base kustomization file that contained the Helm generator. 
When the CI runs both environments in parallel, it tries to pull the same Helm chart into the same cache directory, causing a conflict.
Thats the reason we are using the same helm-generator yaml file in both development and staging.
BTW:
The values for staging will be modified later on.

chore: add permissions to squid

---

components/repository-validator/staging/kustomization.yaml

This reverts the change that allowed the release service team to use test repos on internal staging.

chore: bump repository-validator staging commit ref

---

components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml
components/multi-platform-controller/production-downstream/pentest-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
hack/new-cluster/templates/multi-platform-controller/host-config.yaml

Use Red Hat Cloud Access (BYOS) AMIs instead of regular PAYG AMIs that incur licensing fees.
The following changes were made:
ami-026ebd4cfe2c043b2 (RHEL-9.2.0_HVM-20230503-x86_64-41-Hourly2-GP2) -> ami-01aaf1c29c7e0f0af (RHEL-9.6.0_HVM-20250910-x86_64-0-Access2-GP3)
ami-03d6a5256a46c9feb (RHEL-9.2.0_HVM-20230503-arm64-41-Hourly2-GP2) -> ami-06f37afe6d4f43c47 (RHEL-9.6.0_HVM-20250910-arm64-0-Access2-GP3)
This PR continues the work started in https://github.com/redhat-appstudio/infra-deployments/pull/8251 and https://github.com/redhat-appstudio/infra-deployments/pull/8284.

Change RHEL AMIs to Cloud Access for Prod

---

argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml

kubearchive-logging: remove production deletion patch

---

components/mintmaker/production/base/kustomization.yaml

This is a change to remove the tekton schedule limitation, in response to an emergency raised by users

MintMaker: promote manual update to prod

---

components/policies/development/integration/bootstrap-namespace/kyverno-rbac.yaml

To allow kyverno to create the RoleBinding, the kyverno-background-controller's ServiceAccount needs to have the same permissions it wants to assign to someone else.
This change binds the Kyverno's background ServiceAccount to the `konflux-integration-runner` ClusterRole.

fix kyverno background permission for integration policies

---

components/kyverno/development/kustomization.yaml
components/kyverno/development/kyverno-helm-generator.yaml
components/kyverno/development/kyverno-helm-values.yaml
components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml

Bump kyverno to v1.15.2 by updating the helm chart to v3.5.2

kyverno: bump to v1.15.2 in development overlay

---

components/kubearchive/staging/stone-stage-p01/kustomization.yaml
components/kubearchive/staging/stone-stg-rh01/kustomization.yaml

The operator now creates watchers, so it is getting OOM.

KubeArchive: increase memory assigned to the operator

---

components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml

With the recent enabled logs we are now seeing the issue that was causing some logs to be missing:
```	
level=debug ts=2025-09-30T15:25:51.87843779Z caller=http.go:108 org_id=kubearchive msg="push request failed" code=500 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (10361786 vs. 4194304)"
```
I'm updating the GRPC max size limits for server and client following the config shown in https://grafana.com/docs/loki/latest/configure/#grpc_client
Note that in vector we have the maximum chunk size to be sent to loki set in 10MB, so that is the main issue. If we find problems with this setup we will need to reduce the chunks sent from vector to loki.

Allow bigger chunks of logs in loki

---

components/enterprise-contract/kustomization.yaml

This commit updates the references to the CRDs used as part of the enteprise contract service. The Enterprise Contract organization has migrated from `github.com/enterprise-contract` to `github.com/conforma` and the CRDs have been moved from
`github.com/enterprise-contract/enterprise-contract-controller` to `github.com/conforma/crds`.
Ref: [EC-1421](https://issues.redhat.com//browse/EC-1421)

update reference to enterprise-contract crds

---

components/build-templates/production/e2e-registry-redhat-io-pull-secret.yaml

The 'registry-redhat-io-pull-secret' is needed for e2e test pipelines that pull base images from registry.redhat.io. Previously, this secret was linked to the 'appstudio-pipeline' Service Account.
After recent changes that remove appstudio-pipeline compatiblity, it has become necessary to turn this secret into a "common" secret so that it gets linked to all Service Accounts created for e2e tests.

Set common-secret=true on e2e-test pull secret

---

components/repository-validator/production/kustomization.yaml

This reverts the change that allowed the release service team to use test repos on internal production.

chore: bump repository-validator prod commit ref

---

components/kubearchive/staging/stone-stg-rh01/kustomization.yaml

increase memory limit from 1500Mi to 3072Mi (3Gi)

KubeArchive: increase memory for operator in staging

---

components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-values.yaml

As part of the investigation of a user ticket where the VM seems to have run out of space while building [1],one of the agreed debug actions is to provide a VM with bigger disk to see if this fixes their problem. If it does, we would probably create a new instance with this amount of disk space but in a type m instance, as they're using now.
[1] https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1759754081471249?thread_ts=1759330105.097669&cid=C04PZ7H0VA8

kfluxinfra-2359 - Add instance with bigger disk to 'stone-prod-p02'

---

components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
components/kueue/staging/stone-stage-p01/queue-config/cluster-queue.yaml
components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-values.yaml
components/multi-platform-controller/production-downstream/kflux-osp-p01/host-values.yaml
components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-values.yaml
components/multi-platform-controller/production-downstream/stone-prod-p01/host-values.yaml
components/multi-platform-controller/production-downstream/stone-prod-p02/host-values.yaml
components/multi-platform-controller/production/kflux-prd-rh02/host-values.yaml
components/multi-platform-controller/production/kflux-prd-rh03/host-values.yaml
components/multi-platform-controller/production/stone-prd-rh01/host-values.yaml
components/multi-platform-controller/staging-downstream/host-values.yaml
components/multi-platform-controller/staging/host-values.yaml

This commit will add **linux-g64xlarge-amd64** profile to all the Konflux Environment as well as add a command 
_mkdir -p /etc/cdi /var/run/cdi_

KFLUXINFRA-2310: Add GPU Profile for all the Environments

---

components/kubearchive/development/kubearchive.yaml

The new changes we are testing are failing without printing errors, I have an idea but I need to confirm it by introducing this change that prints the error type.

KubeArchive: debug watchers errors

---

components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml

this is so we can check for OOM events from multiple prod namespaces and not just one

feat(SPRE-1268): updated monitoringstack endpoints for kube_pod_container_status_terminated_reason

---

components/kueue/development/kueue/kueue.yaml
components/kueue/production/base/kueue/kueue.yaml
components/kueue/staging/base/kueue/kueue.yaml

The kueue.yaml manifests have unusual indentation conventions, and they can cause issues with yaml autoformatting tools.  Adjust them to be more in line with standard conventions.
Split from #8461.

kueue: fix manifest formatting

---

components/konflux-ui/staging/base/proxy/proxy.yaml

I did not realize that the images are indexed by order in the proxy so commands were patched for incorrect container. This changes order into previous one and moves new container at the end.
https://github.com/redhat-appstudio/infra-deployments/pull/8556

fix(PVO11Y-4928): change order of containers
