redhat-appstudio/infra-deployments

components/build/build-templates/2-read-pipelines-binding.yaml

Extra text in yaml for pipelines role binding breaks the kustomize apply .
```Error: accumulating resources: accumulation err='accumulating resources from 'build-templates/': 'G:\Dev\infra-deployments\components\build\build-templates' must resolve to a file': recursed accumulation of path 'G:\Dev\infra-deployments\components\build\build-templates': accumulating resources: accumulation err='accumulating resources from '2-read-pipelines-binding.yaml': yaml: line 2: mapping values are not allowed in this context': got file '2-read-pipelines-binding.yaml', but 'G:\Dev\infra-deployments\components\build\build-templates\2-read-pipelines-binding.yaml' must be a directory to be a root```

syntax fix in yaml for ClusterRoleBinding

---

argo-cd-apps/base/has.yaml
argo-cd-apps/base/kustomization.yaml
components/has/catalogsource.yaml
components/has/kustomization.yaml
components/has/operatorgroup.yaml
components/has/subscription.yaml

This PR adds a component for HAS to the AppStudio staging environment.
In all, the following is done by this PR:
- `CatalogSource`, `OperatorGroup` and `Subscription` yaml files for the HAS operator added under `components/has`
- The catalogsource points to `quay.io/redhat-appstudio/application-service-catalog:sha-4f97678`
- The OperatorGroup targets the `application-service` namespace
- The Subscription installs the `application-service.v0.0.1` OLM bundle into the `application-service` namespace
- An ArgoCD application resource (has.yaml) added under `argo-cd-apps/base` that references the aforementioned `has` component.
I've also verified on my own OCP cluster that running `kustomize build argo-cd-apps/overlays/staging | oc apply -f -` properly deploys HAS:
This PR should not be merged …

Add Hybrid Application Service component

---

components/authentication/kustomization.yaml
components/authentication/view-has.yaml

Adds a role for viewing the `application-service` namespace on the staging cluster. Adds myself as one of the users with the role.

Add role for viewing application-service namespace

---

README.md
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/development/repo-overlay.yaml
hack/development-mode.sh
hack/upstream-mode.sh
hack/util-set-development-repos.sh
hack/util-update-app-of-apps.sh

This pr has a set of scripts and configurations that help with using this repository with your own cluster. 
Once you bootstrap, the root ArgoCD "app-of-apps", each of the component applications will each point to the upstream repository.  To enable development  test changes on your own cluster using the same gitops used to create staging, you replace the references to `https://github.com/redhat-appstudio/infra-deployments.git` with references to your own fork. The use of gitops means you can also easily share your config with others using the same bootstrap mechanism as staging. 
This PR includes a set of scripts that help with this, and minimize the changes needed in a fork. 
See the main README for usage instructions.
The usage of this PR required yq to update manifests see …

development mode scripts

---

README.md
argo-cd-apps/overlays/development/repo-overlay.yaml
hack/development-mode.sh
hack/upstream-mode.sh
hack/util-set-development-repos.sh
hack/util-update-app-of-apps.sh

This PR updates the script to support branches in dev mode.
The overlay is updated to include a targetRevision which is updated to the branch active when the script is run.  
You can maintain multiple separate branches in forks and switch between them by checking out the branch and running the development mode script.

support branches in dev mode

---

components/authentication/gitops-ci.yaml
components/authentication/has-ci.yaml
components/authentication/kustomization.yaml
components/authentication/user-ci-maintainer.yaml

This role allows users to elevate themselves to the role of a CI maintainer without granting unnecessary privileges:
* create secrets ( eventually would be replaced by SPI generated content )
* modify the 'pipeline' service account : would enable specification of pull secrets.
This PR grants @sbose78 pipeline-maintainer in the following namespaces:
* application-service
* gitops

Create a pipline maintainer role

---

argo-cd-apps/base/gitops.yaml
components/gitops/.tekton/event-listener.yaml
components/gitops/.tekton/kustomization.yaml
components/gitops/.tekton/pipeline.yaml
components/gitops/.tekton/trigger-template.yaml
components/gitops/.tekton/webhook-route.yaml
components/gitops/backend/allow-argocd-to-manage.yaml
components/gitops/backend/kustomization.yaml
components/gitops/kustomization.yaml

We got to dogfood our current tekton service and while doing so "dry run" what app studio would be creating for users' projects. 
On push to any branch in the https://github.com/redhat-appstudio/managed-gitops repo, a new tekton build would be triggered in the staging cluster itself. An image tagged with the git sha would be pushed to Quay.
* Emulated what App Studio would do: Pull a pipeline definition from the catalog into one's own namespace: components/gitops/.tekton/pipeline.yaml .  This would be same for every component.
* Created the "webhook" related objects.
For this to work, 
* I would be creating the image push `secret` on the cluster and linking the same from the pipeline sa. I've created a robot account in Quay for the same.
* To do the above, we need the …

add CI to gitops service

---

components/has/.tekton/event-listener.yaml
components/has/.tekton/kustomization.yaml
components/has/.tekton/pipeline.yaml
components/has/.tekton/trigger-template.yaml
components/has/.tekton/webhook-route.yaml
components/has/allow-argocd-to-manage.yaml
components/has/kustomization.yaml

We got to dogfood our current tekton service and while doing so "dry run" what app studio would be creating for users' projects. 
On push to any branch in the https://github.com/redhat-appstudio/application-service repo, a new tekton build would be triggered in the staging cluster itself. An image tagged with the git sha would be pushed to Quay. **This wouldn't conflict with the existing tags/tag format.**
* Emulated what App Studio would do: Pull a pipeline definition from the catalog into one's own namespace: components/has/.tekton/pipeline.yaml .  This would be same for every component.
* Created the "webhook" related objects.
For this to work, 
* I would be creating the image push `secret` on the cluster and linking the same from the pipeline sa. I've created a robot account in Quay …

Add ci for HAS

---

components/authentication/has-ci.yaml

As discussed on Slack here: https://coreos.slack.com/archives/C02CTEB3MMF/p1638393026127200
Adding myself to the has-ci role binding so that I temporarily can create secrets in the HAS namespace

Add johnmcollier to has-ci role

---

components/build/build-templates/docker-build.yaml
components/build/build-templates/java-builder.yaml
components/build/build-templates/nodejs-builder.yaml
components/build/build-templates/noop.yaml
hack/build/build.sh
hack/build/cleanup-pvc.sh
hack/build/deploy.sh
hack/build/maintainance-loop.sh
hack/build/package-bundle.sh
hack/build/poll-build.sh
hack/build/test-known-build.sh

- Openshift Pipelines 1.6 caused pinned version 1-5-0 missing in 1.6 bug
-  update test to build all three container, node.js (container and nodejs) and springboot java  example
- update scripts to manage build, autobuild and cleanup of pipelineruns and storage
- update build and cleanup scripts to use pv- name 
- new deploy.sh to deploy build image examples to prove working builds
- WIP for bundling of tekton tasks from build templates instead of scraping from NS

Update version pinning of tasks and new scripts 

---

components/has/catalogsource.yaml

Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
Updating the catalog image tag for onboarding the app service component operator that was merged https://github.com/redhat-appstudio/application-service/pull/18
This allows application service to have an `Application` & the `Component` custom resource

Update sha for app service catalog

---

components/authentication/user-ci-maintainer.yaml

Currently, the user-ci-maintainer role can only create secrets, but can't delete any ones that they have created. Updating the role to add the `delete` verb.

Add verb for deleting secrets to user-ci-maintainer role

---

README.md

There were a couple of places where cutting-and-pasting the examples didn't work, such as:
```
% .hack/build/build.sh https://github.com/jduimovich/single-container-app noop
zsh: no such file or directory: .hack/build/build.sh
```
Consistently using ./hack is safe.
Tested on 
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.5.crcbundle)

Consistently uses ./hack

---

.ci/openshift-ci/Dockerfile

This PR add the e2e framework binary from e2e tests container to the openshift ci test container and can be executed in every Openshift CI jobs.

Add e2e binary to Openshift CI test container

---

components/build/build-templates/bundle-config.yaml

- Update to the latest pipelines v0.1.1 which will not rebuild images if tag exists.
- 
-  V0.1.1 Pipelines definitions see - https://github.com/redhat-appstudio/build-definitions/pull/2

Use new pipeline definitions

---

components/build/clustertasks/analyze-devfile.yaml
components/build/clustertasks/appstudio-utils.yaml
components/build/clustertasks/cleanup-build-directories.yaml
components/build/clustertasks/image-exists.yaml
components/build/clustertasks/kustomization.yaml
hack/build/utils/cleanup-pvc.sh

- Updated Cluster Tasks to include new cleanup-build-directories utility
- enables cleanup to be scheduled as a trigger/cron job (TODO)
- version update to new container with task contents to v0.1.1 (https://github.com/redhat-appstudio/build-definitions)
How to test 
- run a bunch of builds `./hack/build/m2-builds.sh`
- install pull request 
- run `./hack/build/utils/cleanup-pvc.sh` 
- nothing will be deleted
- delete one or more builds using `oc delete pr <pipelinename>`
- run `./hack/build/utils/cleanup-pvc.sh` and the directories in the share pv will be reclaimed 
-

cleanup moved to be an AppStudioutils cluster task

---

components/has/.tekton/kustomization.yaml
components/has/.tekton/serviceaccount.yaml

The pipline sa was manually patched previously to contain the quay.io push secret

ensure pipeline sa always has the push secret specified

---

.ci/oci-e2e-deployment.sh

Current PR change the openshift ci scripts to include the execution of e2e tests in every PR checks.
The e2e binary was included in previous PRs: https://github.com/redhat-appstudio/infra-deployments/pull/43
Related issue: https://issues.redhat.com/browse/RHDP-416

Add e2e framework tests execution to infra-deployments

---

hack/build/prune-builds.sh
hack/build/utils/cleanup-pvc.sh

This PR makes the following changes 
- scripts to configured Openshift Pipelines to prune pipeline runs. 
- Use a taskrun to run ClusterTask which prunes PVC directories
- TODO -gitop'ify OSP config and use a cronjob to schedule taskruns

openshift pipeline pruner

---

README.md
hack/destroy-cluster.sh
hack/reduce-gitops-cpu-requests.sh
hack/sandbox-development-mode.sh
hack/sandbox-e2e-mode.sh

Changes introduced in this PR:
* Two scripts for installing Toolchain (Sandbox) operators in two kinds of modes:
* dev
* e2e
*  Added part in `destroy-cluster.sh` script for cleaning up the Sandbox stuff
* New `reduce-gitops-cpu-requests.sh` which sets all `resource.request.cpu` values to `50m` in `argocd/openshift-gitops` resource. The reason is that with the default size of the dev cluster, I wasn't able to install Sandbox operators along with the GitOps stuff - there wasn't enough of CPU in the cluster. 
Both of the sandbox-related scripts call this "reduce" script automatically.
* Changes in the README - feel free to fix my poor grammar :sweat_smile:

feat: add scripts for installing Toolchain (Sandbox) operators

---

argo-cd-apps/base/kustomization.yaml
argo-cd-apps/base/spi.yaml
argo-cd-apps/overlays/development/repo-overlay.yaml
components/spi/kustomization.yaml

This is a initial deployment if SPI components
- `service-provider-integration-operator` https://github.com/redhat-appstudio/service-provider-integration-operator
- `service-provider-integration-oauth` https://github.com/redhat-appstudio/service-provider-integration-oauth
Now both components are at the initial stage of **SPI V2** implementation  https://docs.google.com/document/u/1/d/1Agp8WMn5uSyzJBin1JfbgCIlKbGt5ziHV_aF2wT5eKc/edit?usp=drive_web&ouid=110694458140179268052
- `service-provider-integration-operator` provides CRDs https://docs.google.com/document/d/1ymo3DgBKdKAq0z1SNgM6PcOqpJyi4EDjO0HVBWPrYn4/edit
- `service-provider-integration-oauth` implemented OAuth2 flow for Github.
In this pr OAuth service configuration is represented as ` spi-oauth-config-xxx` and `spi-shared-secret` …

feat: Initial SPI components deployment

---

README.md
components/has/kustomization.yaml
hack/development-mode.sh
hack/upstream-mode.sh
hack/util-set-github-org

* Allow to set custom GitHub organization in development mode.
* Add arguments to ./hack/development-mode.sh for setting custom git
repository.

Development mode: Custom GitHub organization

---

components/authentication/kustomization.yaml

In my previous pr https://github.com/redhat-appstudio/infra-deployments/pull/60 I forget to add include view-spi.yaml to kustomization.yaml. This pr fixes this error.

fix: include view-spi.yaml to kustomization.yaml

---

components/authentication/view-spi.yaml

remapped spi-system view role to github's username of skabashnyuk
Context :
- https://github.com/redhat-appstudio/infra-deployments/pull/61
- https://github.com/redhat-appstudio/infra-deployments/pull/60

fix: remapped spi-system view role to github's username of skabashnyuk

---

components/spi/kustomization.yaml

Attempt to fix CrashLoopBackOff on staging.
Now configuration points to the deployment with 200Mi memory limit (2 times more).
See https://github.com/redhat-appstudio/service-provider-integration-operator/commit/de85e79d454817293a89fadcb3f7601cc336b252
Error not reproduced on RHPDS.

fix: Used SPI deployment with 200Mi memory limit for spi-operator

---

components/spi/kustomization.yaml

Used SPI deployment (https://github.com/redhat-appstudio/service-provider-integration-operator/pull/57) with 200Mi memory limit for spi-operator to avoid potential oom. Commit set the latest changes in main branch https://github.com/redhat-appstudio/service-provider-integration-operator/commit/ccc1d8a0b400aa3e47c10fa14040674252d3ae3d
Here we can see a peek usage 95.6 that is very close to the limit.
Here we have on staging. It is clear that we need more then 100Mi
Commit https://github.com/redhat-appstudio/infra-deployments/pull/64 by mistake points to the changes in oauth-service deployment https://github.com/redhat-appstudio/service-provider-integration-operator/commit/de85e79d454817293a89fadcb3f7601cc336b252

fix: Used SPI deployment with 200Mi memory limit for spi-operator to avoid potential oom

---

hack/util-set-github-org

@Michkov - could you please review? Any specific reason for using `replace` here?

fix(hack): do not fail setting secret if it doesn't exists yet

---

components/authentication/spi-ci.yaml

The goal of this pr is to give @skabashnyuk the ability to complete SPI installation on staging after https://github.com/redhat-appstudio/infra-deployments/pull/65. Before we will get an ability to store configuration as ExternalSecrets https://github.com/redhat-appstudio/infra-deployments/pull/46

Gives sbose and skabashnyuk a pipeline-maintainer role in spi-system namespace

---

components/authentication/kustomization.yaml

Include spi-ci.yaml resource to kustomization.yaml that was not added by mistake in https://github.com/redhat-appstudio/infra-deployments/pull/71

Include spi-ci.yaml resource to kustomization.yaml

---

components/gitops/.tekton/trigger-template.yaml

We've switched from multiple Dockerfiles, one for each component, to a single Dockerfile for all components (as seen in Argo CD). This PR updates the corresponding references within the managed-gitops repo.

GitOps Service: Update location of Dockerfile in GitOps' Tekton trigger template

---

hack/chains/check-pipelinerun.sh
hack/chains/check-taskrun.sh

Following the example set by @jduimovich in hack/build, here are two scripts in hack/chains that demonstrate how to verify signed taskruns.
See commit messages for further explanations.
As mentioned in the first commit, this doesn't work unless chains is installed, but it could be useful while working on the chains configuration, so I think there's no harm in merging early and often.
See also https://docs.engineering.redhat.com/x/zzd-Dw which shows how it works.
JIRA: [HACBS-37](https://issues.redhat.com/browse/HACBS-37)

Add bash scripts to demo chains signed taskrun verification

---

components/authentication/prune-has.yaml

🪓 
Discussed on slack - HAS seems to be crashing on start up, as it tries to reconcile hundreds of resources at once, Shoubhik suggested clearing out any old HAS CRs that have been left behind, as a one-time measure.

Add role for pruning old HAS resources

---

components/has/argocd-permissions.yaml
components/has/kustomization.yaml
components/spi/argocd-permissions.yaml
components/spi/kustomization.yaml

* `component/authentication` needs to be left out of the dev mode install.
* Move non-user specific rbac into components who need it even if that means there's repetition.

Move Argo CD specific permissions into the component(s) that need(s) it.

---

hack/bootstrap-cluster.sh

The goal of this PR is to streamline the deployment by:
- ensuring the user is logged with the right account (as by default they'll be logged as `developer` if they followed the CRC install documentation)
- Give the user the URL to connect to instead of the route and wait for the URL to be reachable before exiting the script.

Use the kubeadmin user when bootstrapping the cluster/Wait for Argo CD route to be up

---

components/gitops/.tekton/pvc.yaml
components/has/.tekton/pvc.yaml

Use newly created PVC in job to force PV assignement. On some cloud
providers the PV is assigned to PVC after PVC is being used.

Assign PVC by onetime job

---

hack/bootstrap-cluster.sh

Avoid looking at a screen like this while we wait:
error: the server doesn't have a resource type "appproject"
error: the server doesn't have a resource type "appproject"
error: the server doesn't have a resource type "appproject"
...
Error from server (NotFound): namespaces "openshift-gitops" not found
Error from server (NotFound): namespaces "openshift-gitops" not found
Error from server (NotFound): namespaces "openshift-gitops" not found
...
Follow the style introduced by @Roming22 when waiting for the Argo
CD URl to work, and show an OK when it's done.

Make hack/bootstrap-cluster.sh wait more calmly

---

components/gitops/.tekton/event-listener.yaml
components/gitops/.tekton/trigger-template.yaml
components/has/.tekton/event-listener.yaml
components/has/.tekton/trigger-template.yaml

Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
To be consistent with resources generation in application-service operator, we need to update `triggers.tekton.dev` API version from `v1alpha1` to `v1beta1`.

Update triggers.tekton.dev API version from v1alpha1 to v1beta1

---

README.md
argo-cd-apps/overlays/development/repo-overlay.yaml
components/authentication/spi-vault-admin.yaml
components/authentication/view-spi.yaml
components/spi/kustomization.yaml
components/spi/vault_role.yaml

Updates SPI deployment which now deploys own Vault instance.
Vault requires some manual setup after the deployment (see `README.md` patch). This requires some permissions to access vault pod and few other resources in spi-system namespace (see `vault_role.yaml` patch). This PR grants these permissions for Sergii Kabashniuk and Michal Vala (myself).
issue: https://issues.redhat.com/browse/SVPI-61

Svpi61 vault init

---

components/spi/kustomization.yaml
components/spi/vault_rolebinding.yaml

In https://github.com/redhat-appstudio/infra-deployments/pull/118 I forgot to include RoleBinding to vault admin role in `kustomization.yaml`. In this PR, I've moved the actual RoleBinding into SPI component (it lives only in spi-system namespace) and include it in SPI `kustomization.yaml`.

SVPI-61 - vault admin rolebinding

---

components/gitops/staging/job.yaml

This PR:
- Remove Argo CD resource hooks on the init job, which were preventing the sync from completing.

GitOps Service: remove Argo resource hooks on DB init job

---

components/build/.tekton/event-listener.yaml
components/build/.tekton/kustomization.yaml
components/build/.tekton/pvc.yaml
components/build/.tekton/serviceaccount.yaml
components/build/.tekton/trigger-template.yaml
components/build/.tekton/webhook-route.yaml
components/build/kustomization.yaml

- Add trigger-template which triggers pipelines for building images:
- redhat-appstudio/build-templates-bundle
- redhat-appstudio/appstudio-tasks
- redhat-appstudio/appstudio-utils
Configuration needed on stage:

Build: Automate build of build-templates-bundle and appstudio-utils

---

README.md
components/gitops/staging/appstudio-controller-rbac.yaml
components/gitops/staging/kustomization.yaml
components/gitops/staging/managed-gitops-appstudio-controller-deployment.yaml
components/gitops/staging/managed-gitops-clusteragent-deployment.yaml

- Updates the GitOps service staging cluster to pick up the following items:
- Add support for [GITOPSRVCE-97](https://issues.redhat.com/browse/GITOPSRVCE-97) [(PR)](https://github.com/redhat-appstudio/managed-gitops/pull/73): Create GitOpsDeployments for corresponding Application CR of AppStudio
- Add support for [GITOPSRVCE-70](https://issues.redhat.com/browse/GITOPSRVCE-70) [(PR)](https://github.com/redhat-appstudio/managed-gitops/pull/68) Add 'health' and 'sync status' fields to GitOpsDeployment CR status field
- Updates the README.md with information on how folks can invoke the GitOps Service API from the staging cluster.

GitOps Service: Adopt latest GitOps Service commits

---

README.md
hack/destroy-cluster.sh

Kustomize command is integrated to kubectl/oc, it's not used as
standalone command anymore.

Remove kustomize command dependency

---

components/build/tekton-results/kustomization.yaml
components/build/tekton-results/tekton-pipelines-namespace.yaml

Fix: Create missing namespace for tekton-resutls

---

openshift-gitops/subscription-openshift-gitops.yaml

Set of startingCSV causes that the version is installed and then updated
version by version to newest.

Avoid installation of multiple openshift-gitops for new clusters

---

components/build/pipelines-as-code/kustomization.yaml

This change in the Pipelines-as-Code version is because the latest version doesn't give an error if there is a bundle in pipelineRef.
PR for the resolver: https://github.com/openshift-pipelines/pipelines-as-code/pull/427

change PaC to latest version 

---

components/build/tekton-results/allow-argocd-to-manage.yaml
components/build/tekton-results/kustomization.yaml

Fix of #157 
@sbose78 is this enough? Or do you expect better fencing? Currently tekton-results define in tekton-pipelines these resources:
ClusterRole
ClusterRoleBinding
ConfigMap
Deployment
Job
Namespace
RoleBinding
Route
Service
ServiceAccount
StatefulSet

Allow argoCD manage tekton-pipelines namespace

---

components/authentication/view-build-service.yaml

A followup from recently merged #172.
These are the current devs in the enterprise contract team. This
change allows team members permission to inspect the tekton chains
configuration and watch the chains controller logs, which should be
useful for troubleshooting and generally looking at chains in the
stage cluster.

Contract team view permission for tekton-chains

---

components/authentication/view-has.yaml

This access is intended primarily to access HAS CI logs on Openshift.

Add brunoapimentel to view HAS

---

components/authentication/tenants/kustomization.yaml
components/authentication/tenants/redhat-namespace.yaml

This is a reversible change - we hope to manage tenants/orgs more efficiently in future.

Setup a tenant namespace for Red Hat ( HACBS )

---

components/authentication/tenants/shbose.yaml

Need because role aggregation wasn't setup ( and might make sense not to )

allow sbose78 to create release strategies(hacbs)

---

components/build/tekton-chains/chains-certs.yaml

When accessing the OpenShift internal image registry via
`image-registry.openshift-image-registry.svc`, the TLS certificate is
issued by the Service CA, so we also need that certificate added to the
`chains-ca-cert` ConfigMap.

Add service CA to the chains-ca-cert ConfigMap

---

components/build/tekton-chains/allow-argocd-to-manage.yaml
components/build/tekton-chains/kustomization.yaml

I'm not sure I know exactly why we need this, but I'm copying #158
as suggested by @Michkov.

Allow argocd to manage tekton-chains namespace

---

hack/chains/README.md
hack/chains/create-signing-secret.sh

The key pair secret will now be created automatically using a Gitops
hook, so no need to explain how to create one manually.

Remove instructions for chains signing secret

---

hack/chains/kaniko-cosign-verify.sh
hack/chains/rekor-image-lookup.sh
hack/chains/rekor-verify-taskrun.sh

Not super important, but it makes the rekor-image-lookup.sh script
more versatile and hence more generally useful.

Support digest param in rekor-image-lookup script

---

hack/chains/README.md
hack/chains/config.sh
hack/chains/pipeline-quay-demo.sh

We no longer need to tweak the chains configuration
when using quay.io since it now supports storing attestations,
see https://issues.redhat.com/browse/PROJQUAY-3386

Enable quay.io push demo oci attestation storage

---

README.md
hack/reduce-gitops-cpu-requests.sh
hack/setup/install-pre-req.sh

* Simplifies README to use the new convenience scripts.
* Fixes an error in `hack/reduce-gitops-cpu-requests.sh`: 
```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 8, column 1
```
* Separates the `hack/setup/install-pre-req.sh` and `hack/setup/prepare-crc.sh` scripts, because it's easier to understand and use them when they're not chained together.

Cleanup bootstrap

---

hack/chains/kaniko-cosign-verify.sh

When the Kaniko chains demo results in pushing to the internal OpenShift
registry with this the `cosign verify*` is run in-cluster using Tekton
tasks defined in redhat-appstudio/build-definitions#37.
Ref. https://issues.redhat.com/browse/HACBS-106

Demo script for running in-cluster cosign tasks

---

components/build/openshift-pipelines/patch-tekton-config-rb.yaml
components/build/openshift-pipelines/patch-tekton-config-sa.yaml
components/build/openshift-pipelines/pruner-configuration-job.yaml
components/build/tekton-results/ingress-annotation-job.yaml

* Pruner configuration under openshift-pipelines
* Avoid deletion of sync jobs, rather use default policy

Move pruner configuration job under openshift-pipelines

---

hack/build/analyze-devfile.sh
hack/build/build-deploy.sh
hack/build/build-quay.sh
hack/build/build.sh
hack/build/m2-builds.sh
hack/build/repo-to-pipeline.sh
hack/build/templates/default-build-bundle.yaml
hack/build/utils/install-secrets.sh

This PR removes the need to have a devfile build pipeline as per this cleanup of https://github.com/redhat-appstudio/build-definitions/pull/36 
The processing of the devfile extract the location of the dockerfile, the path and the outterloop deployment from the devfile.yaml.  
- process devfiles outside pipelines as devfile-build pipeline is being removed
- configure quay deploy from build script by passing quay on the command line
CLI is compatible and is now build.sh <repo> <pipelinename / auto:optional> <quay:optional>

updates to scripts to support devfiles

---

components/build/pipelines-as-code/kustomization.yaml

ArgoCD is setting `app.kubernetes.io/instance` to argoCD app - https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing.
Pipelines-as-code has it set directly in yaml to `default`. That's why
we can see warning in ArgoCD -> `CustomResourceDefinition/repositories.pipelinesascode.tekton.dev is part of applications build and default`

Avoid ArgoCD SharedResourceWarning on build app

---

components/authentication/view-build-service.yaml

Allow to vdemeester and Michkov see pods and logs in openshift-operators
namespace to inspect why Tekton pruner is not running.

Allow to see openshift-operators namespace

---

hack/util-set-github-org

Using `sed` with `-i` flag on a Mac (BSD) [behaves differently than on a Linux machine (GNU)](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux) and it fails when replacing the GITHUB_ORG in "has" kustomize template
Using `yq` solves this problem for both platforms
1. Make sure you have `yq v4.x` installed
2. Run
```bash
export MY_GIT_FORK_REMOTE=<origin, or whatever points to your git remote> MY_GITHUB_ORG=<your github org> MY_GITHUB_TOKEN=<your github token with permissions "repo" and "delete_repo">
./hack/bootstrap-cluster.sh preview
oc get configmap application-service-github-config -n application-service -o jsonpath={.data.GITHUB_ORG}
```

fix: use yq for replacing github org in has tmpl

---

components/build/.tekton/pvc.yaml
components/e2e-tests/.tekton/pvc.yaml
components/gitops/.tekton/pvc.yaml
components/has/.tekton/pvc.yaml
components/spi/.tekton/pvc.yaml
hack/bootstrap-cluster.sh

PVC which are used by CI are not used until CI is triggered.
PVCs are created but not Bound due toStorageClass configuration
WaitForFirstConsumer. Allow Pending PVC to be marked as Healthy instead
of simulating first customer by job.

Allow Pending PVC caused by WaitForFirstConsumer strategy

---

components/build/tekton-results/kustomization.yaml
components/build/tekton-results/patch-tekton-results-api-no-auth.yaml
hack/build/set-tkn-results.sh

Using temporary image build from https://github.com/tektoncd/results/pull/170
When merged and released we should switch back to upstream.

Disable authorization on tekton-results-api

---

components/build/openshift-pipelines/openshift-pipelines-feature-flags.yaml

- Enable TEP-0059 https://github.com/tektoncd/pipeline/pull/4085
- Build definitons repository is ready for this change

Tekton - enable tekton-scope-when-expressions-to-task

---

components/build/tekton-chains/chains-controller-deployment.yaml
components/build/tekton-chains/kustomization.yaml

In a forked repository[1] we have fixes from unreleased Tekton Chains
version, until the nightly builds are available from upstream[2]. This
should unblock the end to end tests[3].
[1] https://github.com/hacbs-contract/chains
[2] see https://issues.redhat.com/browse/HACBS-263
[3] https://issues.redhat.com/browse/HACBS-278

Use forked Tekton Chains image

---

hack/chains/.yamllint
hack/chains/README.md
hack/chains/check-yaml.sh
hack/chains/pipeline-quay-demo.yaml

Adding documentation to README regarding yamllint installation and
usage to validate kube/openshift resources.
Signed-off-by: Rob Nester <rnester@redhat.com>

HACBS 45 - Add YAML lint documentation

---

components/authentication/view-spi.yaml
components/spi/vault_rolebinding.yaml

Gives Lukas Krejci view and spi-vault-admin  roles. That is necessary to complete  `Use devsandbox proxy/kcp SSO token as auth token` https://issues.redhat.com/browse/SVPI-81

Gives Lukas Krejci view and spi-vault-admin  roles

---

hack/chains/README.md

Doing this helps the Gitops sync complete, otherwise you get
endless failure:
one or more objects failed to apply, reason: namespaces
"application-service" not found. Retrying attempt #432 at 7:25PM.
I believe it's because the pvc-cleaner objects try to use the
application-service namespace which isn't created if you don't
install the has appliction.

Mention gitops sync workaround in chains readme

---

components/authentication/group-sync/github-redhat-appstudio.yaml
components/authentication/group-sync/group-sync-ci.yaml
components/authentication/group-sync/kustomization.yaml
components/authentication/group-sync/namespaces.yaml
components/authentication/group-sync/subscription.yaml
components/authentication/group-sync/view-group-sync.yaml
components/authentication/kustomization.yaml
components/authentication/view-build-service.yaml

Sync teams from github org redhat-appstudio as groups in Openshift.
Post merge action:

Enable github groups sync

---

hack/preview-template.env
hack/preview.sh

This commits allows to override the Release operator image by setting the new image and tag in the RELEASE_IMAGE_REPO and RELEASE_IMAGE_TAG variables. It also allows to modify the reference to the SHA containing the operator resources.

Allow to override RELEASE operator references

---

hack/chains/copy-public-sig-key.sh
hack/chains/create-signing-secret.sh
hack/chains/release-pipeline-with-ec-demo.sh

It copies it to a secret in your current project/namespace so it can
be used conveniently without requiring access to the secret in
tekton-chains which includes the protected secret key.
Inspired by:
https://github.com/redhat-appstudio/build-definitions/pull/56
https://github.com/redhat-appstudio/infra-deployments/pull/293

Bash script to copy the chains public sig key

---

components/build/tekton-chains/chains-controller-deployment.yaml

Use a nightly-build image because the current latest version, 0.8.0,
contains several bugs that make Chains unusable for our use case. Once
version 0.9.0 is published, change this reference to that.

Use upstream patched version of chains

---

components/authentication/release-ci.yaml
components/authentication/view-release.yaml

To be able to set quay credentials for Pipelines-as-code pipelines

Release-ci auth access for Michkov

---

hack/chains/end-to-end-demo.sh
hack/chains/release-pipeline-with-ec-demo.sh

This runs the build and the sample release pipelines. The main goal of the demo is to showcase how the test stream results from the build pipeline are picked up by the Enterprise Contract verify task run in a release pipeline.
Ref. https://issues.redhat.com/browse/HACBS-357
Also includes:
[Pipeline parameter for verify-enterprise-contract](https://github.com/redhat-appstudio/infra-deployments/commit/eba205ea9c03e9334e58e0e32380722f39ad50d1)
We need to provide the `PIPELINERUN_NAME` parameter to the `verify-enterprise-contract` task. This allows it being specified via environment variable `BUILD_PIPELINE_RUN`, and in case it is not specified the script auto-guesses a PipelineRun that has a TaskRun with a result named `HACBS_TEST_OUTPUT`.

End to end demo script for enterprise contract

---

components/gitops/staging/argo-cd.yaml
components/gitops/staging/kustomization.yaml

This PR temporarily disables the `ArgoCD` resource in `gitops-service-argocd` namespace from our service repo, switching to a version with `logLevel: "debug"` enabled on the repo server, application controller, and API server. The contents is otherwise unchanged.

Temporarily enable debug in gitops-service-argocd namespace

---

components/gitops/staging/argo-cd.yaml

This PR:
- With the current configuration of the Argo CD instance on `gitops-service-argocd` namespace, Argo CD will register thousands of watches (one for each namespace with the `argocd.argoproj.io/managed-by: gitops-service-argocd` label) to the cluster.
- Argo CD registers a watch for each API resource, per namespace.
- Since OpenShift clusters have 250+ API resources, and there are 50+ user namespaces on the cluster, this is a lot of watches.
- This PR switches the Argo CD instance in the `gitops-service-argocd` namespace to a resource allow list, which should significantly reduce the number of watches.

Add a resource allow-list to gitops-service-argocd namespace

---

components/gitops/staging/kustomization.yaml

This PR:
- Updates the common GitOps Service image to pull in the fix from https://github.com/redhat-appstudio/managed-gitops/pull/112

Update GitOps Service to latest commit: 7e142808ef95f386f389348f39cef64a70ff670a

---

hack/preview-template.env
hack/preview.sh

https://issues.redhat.com/browse/PLNSRVCE-185
We need to be able to bootstrap a cluster with a specific version/commit of `build-service` in openshift-ci in order to run e2e tests against it (on a PR basis).
After running this, you should have a custom image (`quay.io/psturc/build-service:[PLNSRVCE-185](https://issues.redhat.com//browse/PLNSRVCE-185)`) of `build-service` deployed on a cluster
```bash
export MY_GIT_FORK_REMOTE=<REPLACE-ME> MY_GITHUB_ORG=<REPLACE-ME> MY_GITHUB_TOKEN=<REPLACE-ME> BUILD_SERVICE_IMAGE_REPO=quay.io/psturc/build-service BUILD_SERVICE_IMAGE_TAG=PLNSRVCE-185 BUILD_SERVICE_PR_OWNER=psturc BUILD_SERVICE_PR_SHA=f372978f986771304d8b89b4078abdfcf3c5655e
./hack/bootstrap-cluster.sh preview
```
Verified:
```bash
➜  infra-deployments git:(PLNSRVCE-185) oc get pods -n …
```

allow overriding build-service config

---

hack/chains/end-to-end-demo.sh

If the pipeline service account has not yet been created the `hach/chains/end-to-end-demo.sh` script will fail if it tries to link the `release-demo` Docker pull secret to it. This adds loop to wait until it has been created by the Tekton operator before proceeding with the demo.

Wait for the pipeline service account in e2e demo

---

components/build/shared-resources/infra-deployments-pr-creator.yaml
components/build/shared-resources/kustomization.yaml
components/build/shared-resources/shared-resources-components.yaml

SharedSecret for update-infra-deployments task in build-definitions.
Secret shared with AppStudio/HABCS services to be used for creating PR
in infra-deployments based on merged PR in service repository.

PLNSRVCE-255 - Create sharedSecret for infra-deployments-update task

---

argo-cd-apps/base/enterprise-contract.yaml
argo-cd-apps/overlays/development/repo-overlay.yaml
components/enterprise-contract/kustomization.yaml

Cretes the EnterpriseContractPolicy CRD from the enterprise-contract-controller[1] repository.
Ref. https://issues.redhat.com/browse/HACBS-244
[1] https://github.com/hacbs-contract/enterprise-contract-controller

EnterpriseContractPolicy CRD

---

.ci/openshift-ci/Dockerfile

Signed-off-by: Stephanie <yangcao@redhat.com>
this PR updates ci to use go 1.17 image

update ci to go 1.17

---

hack/chains/end-to-end-demo.sh
hack/chains/release-pipeline-with-ec-demo.sh

Seems that the `skopeo-copy` cluster task is no longer available. Or that is, none of the cluster tasks are available. This installs it via the Tekton Hub if it's not already present and switches to using the non-cluster task in the `release-pipeline-with-ec-demo.sh`.

Install `skopeo-copy` task in the e2e demo

---

components/build/shared-resources/scc.yaml

csi-scc must allow to run as root same as pipelines-scc

CSI-SCC: Sync with pipelines-scc

---

components/build/shared-resources/add-user-workload-shared-secret-scc-clusterrole.yaml
components/build/shared-resources/kustomization.yaml
components/build/shared-resources/redhat-appstudio-user-workload-sharedsecret.yaml

Let's see if I correctly interpreted your instructions @Michkov 
Running `export MODE=preview; ./hack/bootstrap-cluster.sh $MODE`, after that completes, I got the following:
```
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments  (jira-plnsrvce-248)$ oc get sharedsecret
NAME                             AGE
redhat-appstudio-staginguser     0s
redhat-appstudio-user-workload   0s
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments  (jira-plnsrvce-248)$ oc get clusterrole pipelines-scc-clusterrole -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole"," …
```

PLNSRVCE-248: create shared secret redhat-appstudio-user-workload

---

components/build/shared-resources/shared-resources-components.yaml
components/e2e-tests/.tekton/kustomization.yaml
components/e2e-tests/.tekton/pipelines-as-code.yaml

Tekton is adopted as a primary CI and CD ( images builds ) for e2e-tests

Add PaC for e2e-tests

---

components/authentication/view-build-service.yaml

This binds the view cluster role to the members of the `Enterprise Contract` GitHub Team on CI related namespaces.
I'm assuming that the group membership is synced with GitHub.

View access for CI related namespaces to EC team

---

components/authentication/view-build-service.yaml

This binds the view cluster role to the members of the `Enterprise Contract` GitHub Team on the `build-templates` namespace. We need this to be able to view the Tekton TaskRuns/PipelineRuns and logs run for the https://github.com/redhat-appstudio/build-definitions repository.

View access for build-templates for the EC team

---

README.md

Created a small section in the main README to point to the e2e-tests repo since there has been some confusion where the suite lives.

docs: point to e2e-tests repo

---

components/spi/kustomization.yaml

Add session cookie configuration SameSite=None and Secure=true 
https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/92
Context https://issues.redhat.com/projects/SVPI/issues/SVPI-113 [HAC-dev] no active oauth flow found for the state key

SPI OAuth service update v0.5.5

---

components/spi/kustomization.yaml

- Refactor the ServiceProviderError to contain details about the error obtained from the service provider https://github.com/redhat-appstudio/service-provider-integration-operator/pull/139 
- Memory limit https://github.com/redhat-appstudio/service-provider-integration-operator/commit/7abc78001694bb3e6da3240f8b99102935307a6a

SVPI-133 Improved Github SP error handling && increased memory limit for operator

---

components/build/tekton-chains/chains-controller-deployment.yaml

Fixes nil pointer dereference error when pipelinerun exceeds its
timeout.

Update chains controller

---

components/has/manager_resources_patch.yaml
hack/preview-template.env
hack/preview.sh

https://issues.redhat.com/browse/PLNSRVCE-290
It would be useful to be able to override the default ["quay.io/redhat-appstudio/user-workload"](https://github.com/redhat-appstudio/application-service/blob/4dfb289796d77827420d591cc1a6c150c51992a4/main.go#L107) "image push" repo via env var, so e2e-tests could leverage that and test the repo protection with a custom repo URL.

add option to override HAS default image push repo

---

argo-cd-apps/base/enterprise-contract.yaml

The Rekor Deployment specifies the access mode ReadWriteOnce for its
PVC. This access mode restricts the corresponding persistent volume from
being used by more than one Node at the same time.
This is usually not a problem. The Rekor Deployment specifies a single
replica (thus a single Node is used). However, when a new version of the
Deployment is being rolled out, there will be a brief period where two
pods will exist. One for the previous version of the Deployment, another
for the new version. If the two Pods are not scheduled on the same Node,
the newest Pod will not be able to start due to "Multi-Attach error",
causing a dead lock.
This commit changes the Deployment strategy to "Recreate" to ensure that
at most a single Pod exists.
A long-term solution would likely involve changing …

Fix staging rekor instance

---

.ci/openshift-ci/Dockerfile

We don't need e2e container at this level and removing installation of yq. Yq installation will be added to e2e scripts to install it with GITHUB TOKEN

Remove yq installation from container tests

---

components/build/jvm-build-service/kustomization.yaml

Quota is applied on stage, limiting number of pods to 50. Enabling
taskrun pods removal using env variable.

jvm-build-service: update version, enable pod deletion

---

components/spi/kustomization.yaml

Include :
- Removed file-retriver Demo UI. It was not properly configure on staging and never used.
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/128
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/138
- https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/99
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/146
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/133
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/147
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/151
- https://github.com/redhat-appstudio/service-provider-integration-operator/pull/148

Update spi to v0.6.0

---

components/authentication/view-build-service.yaml

Part of ec-task setup involves getting the cosign pub key and adding it as a secret to the managed workspace.
```
cosign public-key --key k8s://tekton-chains/signing-secrets > "$tempDir/cosign.pub"
kubectl create secret generic $COSIGN_SECRET_NAME -n "$NAMESPACE" --from-file="$tempDir/cosign.pub"
```

add release team to be able to get cosign pub key

---

.ci/oci-e2e-deployment.sh
components/build/kustomization.yaml
hack/build/templates/default-build-bundle.yaml

Some tests no longer use the hardcoded `appstudio-e2e-test` namespace anymore (for creating apps, components, pipelines etc.).
This has caused that these tests started failing, because those namespaces don't contain the `redhat-appstudio-registry-pull-secret` secret used to authenticate when pushing the built image to quay.io.
To fix this, we need to create a shared secret that will be consumed by the pipelinerun created in any namespace on the cluster.
(The creation of the shared secret was added quite some time ago to [e2e-tests repository's CI scripts](https://github.com/redhat-appstudio/e2e-tests/blob/a0c27237bfee12e208b46c7ff88d3f5b7a3efbe5/scripts/install-appstudio-e2e-mode.sh#L64), but I haven't realized it needs to be updated here as well)

fix: ci: create shared secret

---

hack/preview-template.env
hack/preview.sh

The newly added variable will be leveraged to allow the proper exectution of jvm-build-service e2e tests. 
See https://github.com/redhat-appstudio/jvm-build-service/pull/103.

Allow the override of the default build bundle when running preview

---

components/authentication/kustomization.yaml
components/authentication/prune-olm-has.yaml

There's some old OLM resources leftover from when we briefly deployed HAS as an OLM bundle. They're no longer needed, and seem to be orphaned from ArgoCD, so I'm adding a role to my stage user to allow myself to clean them up.

Allow John to prune old HAS OLM resources

---

components/authentication/prune-olm-has.yaml

Should be `operators.coreos.com` not `operators.coreos.com/v1alpha1`

Fix typo in APIGroup for has-olm-pruner role

---

hack/chains/README.md

If you don't start the enterprise-contract app you won't get the
enterprise contract controller and its related CRD which is used by
EC for defining policy configuration.

Fix crc bootstrap guide for chains/ec development

---

hack/preview.sh

Build component is pretty big which is causing that sometimes it fails
with 'context deadline exceeded'

fix: ignore 'context deadline exceeded' issue

---

components/build/jvm-build-service/system-config.yaml

The CI for JVM build service is running in the jvm-build-service
namespace, we need to enable JVM support for this namespace to activate
the cache.

Enable the JVM cache in CI namespace

---

components/spi/oauth_route.yaml

As part of https://issues.redhat.com/browse/SVPI-117 added `part-of` label on spi-oauth-route

added part-of label on spi-oauth-route

---

components/authentication/view-e2e-tests.yaml

This is to help us troubleshoot e2e tests.

Grant Enterprise Contract to view e2e namespace

---

.ci/oci-e2e-deployment.sh

Reverts the change in #549 as we have landed the fix in
redhat-appstudio/e2e-tests#158 for the issue that required skipping the
tests in the first place.

Un-skip Enterprise Contract e2e tests

---

components/build/jvm-build-service/kustomization.yaml

As part of the next step following the merging of https://github.com/redhat-appstudio/jvm-build-service/pull/105 and in particular what is noted in https://github.com/redhat-appstudio/jvm-build-service/blob/650846d2011d745b82c72cd59cf1e2398daeddfa/deploy/cache/base/deployment.yaml#L1-L3 we are removing the reference to the yaml that defines the jvm-build-service cache in the `jvm-build-service` namespace 
@Michkov @stuartwdouglas @phillip-kruger @brunoapimentel @psturc FYI

remove cache instance in jvm-build-service namespace

---

hack/chains/end-to-end-demo.sh

For https://github.com/redhat-appstudio/infra-deployments/blob/1f096e2721e3df056c492e96ab5346222312a551/hack/chains/end-to-end-demo.sh#L138 the output bundle task was TASK_BUNDLE=quay.io/redhat-appstudio/appstudio-tasks:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0-2
but when we use  verify-enterprise-contract-v2, task task.tekton.dev/verify-enterprise-contract-v2 should be in bundle quay.io/redhat-appstudio/appstudio-tasks:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0-3
$ tkn bundle list quay.io/redhat-appstudio/appstudio-tasks:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0-2
task.tekton.dev/s2i-java
task.tekton.dev/s2i-nodejs
task.tekton.dev/sanity-inspect-image
task.tekton.dev/sanity-label-check
task.tekton.dev/sast-go
task.tekton.dev/sast-java-sec-check
task.tekton.dev/sast-snyk-check …

fix end-to-end-demo.sh to use verify-enterprise-contract-v2

---

components/build/tekton-chains/chains-secrets-config.yaml

The job chains-certs-configuration is expected to be the sole manager of
the chains-ca-cert secret. This is needed to ensure Chains can properly
access cluster-internal services like the integrated registry. As
recommended by the docs[0], use the --force-conflicts flag to ensure the
PostSync hook can properly update the CA secret used by Chains.
[0] https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
https://issues.redhat.com/browse/HACBS-1028

Force sync of chains-ca-cert secret

---

hack/preview.sh

Some of the [recent CI runs were failing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/177/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1562369417759690752) due to an error in E2E tests caused by an incomplete installation of tekton resources (tekton CRDs missing / pipeline SA did not get created in specified timeout in OpenShift test project)
This additional check should ensure that E2E tests won't be run until all required tekton resources are installed and ready

fix: preview: wait for tekton components/resources

---

hack/setup/prepare-crc.sh

Recent versions of CRC on Mac often install it into a path with a space character.  We need to surround $CRCBINARY with quotes.
Tested on macos with:
CRC version: 2.7.1+8b30b973
OpenShift version: 4.11.0
Podman version: 4.1.1

add quotes around $CRCBINARY

---

components/integration/kustomization.yaml
components/release/kustomization.yaml

This is in place of https://github.com/redhat-appstudio/infra-deployments/pull/644/ and https://github.com/redhat-appstudio/infra-deployments/pull/642/ since they need to go in at the same time

integration-service and release-service update

---

components/build/README.md
components/build/build-service/kustomization.yaml
components/build/kustomization.yaml
components/has/kustomization.yaml

Set global hacbs tekton bundle so it can be used directly in hacbs
workflow.

PLNSRVCE-624: set hacbs tekton bundle key

---

components/authorization/cluster/everyone-view.yaml
components/authorization/cluster/kustomization.yaml
components/authorization/kcp/kustomization.yaml
components/authorization/kcp/members-view-everything.yaml
components/authorization/kcp/view-everything.yaml

let's try to make the names more consistent and not to mix/confuse them:
* for cluster:
* `all-view` -> `everyone-view` (saying that everyone has `view` role)
* ` all-view-everything` -> `everyone-view` (to not confuse with the ClusterRole defined for kcp)
* for kcp:
* the role is `view-everything` (because it grants permission to view everything)
* analogically `members-view-all` -> `members-view-everything`
plus fixed the `jcollier` -> `johnmcollier`

fix: naming of CRs & CRBs

---

hack/configure-kcp.sh

two fixes for `configure-kcp.sh` script
1. when running in CPS in `root` the admin doesn't have permission to create anything there - so we need to ignore any failures
2. when it configures a new cluster (via ArgoCD secret) pointing to the kcp workspace, we need to refresh the apps

hard apps refresh when new kcp is configured

---

.ci/oci-e2e-deployment.sh

Currently there's a 1h (default) timeout for running e2e. Since the number of tests is growing and takes more time to finish, we are sometimes hitting the limit. If that happens, tests get interrupted and a CI check is marked as failed.
This is a temporary solution until we enable parallel e2e test run for infra-deployments (which was already enabled for e2e-tests repo)

fix: increase timeout for e2e

---

README.md
hack/configure-kcp.sh
hack/destroy.sh

* makes the workspace names configurable
* if `root` is not used as root workspace, then use shorter name of the compute workspace
* add more stuff to README

improve workspace name handling & README

---

hack/preview.sh

`[[ -n "${JVM_BUILD_SERVICE_PR_OWNER}" && ${JVM_BUILD_SERVICE_PR_SHA} ]] && yq -i e "(.spec.pruner.keep = 1000)" $ROOT/components/build/openshift-pipelines/config.yaml`
produced the desired result in my local branch
/assign @Michkov 
@stuartwdouglas @dwalluck FYI this hopefully resolves our pipelinerun pruning during our service registry build tests

bump tekton operator pipelinerun pruner keep threshold for jvm-build-servivce PRs

---

components/build/jvm-build-service/system-config.yaml

This will be needed for https://github.com/redhat-appstudio/jvm-build-service/pull/212 to pass CI.
Once this is merged into infra-deployments we can change this to reference https://github.com/redhat-appstudio/jvm-build-service/pull/212/files#diff-8944c42fd2615afea6412ddd9d9d14643e29ee78ae8d5019364e396dcd70871dR11 to keep them in sync automatically.

Add tags for gradle versions in the builder images

---

.gitignore
README.md
components/ckcp/cert-manager.yaml
components/ckcp/certs.yaml
components/ckcp/deployment.yaml
components/ckcp/kustomization.yaml
components/ckcp/namespace.yaml
components/ckcp/pvc.yaml
components/ckcp/route.yaml
components/ckcp/service.yaml
hack/bootstrap.sh
hack/configure-kcp.sh
hack/flags.sh
hack/install-ckcp.sh
hack/preview-template.env
hack/preview.sh
hack/util-set-github-org

Adding two preview modes:
- preview-ckcp - creates containerized KCP inside target cluster, useful for e2e testing
- preview-cps - connects to CPS instance, requires to create `hack/cps-kubeconfig` manually
Usage:
```
./hack/bootstrap.sh -m preview-ckcp
or
./hack/bootstrap.sh -m preview-cps
```
And then for each change just run `./hack/preview.sh`

Initial implementation of preview-ckcp and preview-cps

---

hack/bootstrap.sh
hack/install-ckcp.sh

With these changes:
* I can run `install-ckcp.sh` on its own independently of using the preview vars
* I can customize the target of the ckcp kubeconfig
* `bootstap.sh` script doesn't override the KCP_KUBECONFIG
I'm trying to avoid relying on two kcp kubeconfig variables `CPS_KUBECONFIG` & `KCP_KUBECONFIG` - I would love to use only one `KCP_KUBECONFIG`

make install-ckcp.sh independent of preview vars

---

README.md
hack/bootstrap.sh
hack/flags.sh
hack/preview-template.env
hack/preview.sh

Use only one kcp kubeconfig defined as a variable `KCP_KUBECONFIG`. 
The file is not overridden, nor copied anywhere - it's being used as it is. 
In the case of ckcp, the kubeconfig is taken from the running ckcp via a temp file.

use one kcp kubeconfig

---

README.md
hack/bootstrap.sh
hack/configure-kcp.sh
hack/flags.sh
hack/install-ckcp.sh
hack/preview-template.env

- Separate install-ckcp.sh from bootstrap.sh
- Use only KCP_KUBECONFIG and CLUSTER_KUBECONFIG directly
- Allow to define ROOT_WORKSPACE for default KCP workspace
- Add check of KCP client and KCP server version
- Add check of kubeconfig files

Unify code to use one preview mode

---

hack/quicklab/README.md
hack/quicklab/setup-nfs-quicklab.sh
hack/quicklab/templates/deployment.yaml
hack/quicklab/templates/rbac.yaml
hack/quicklab/templates/storageClass.yaml
hack/quicklab/templates/test-pvc.yaml

These are still valid (and required) when using a cluster provisioned by quicklab.

Copy quicklab scripts from pre-kcp branch

---

hack/flags.sh

ignore 
```
error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
```
when running kcp locally

ignore could not parse version error

---

hack/configure-kcp.sh

Figured out that hard refresh is not enough for loading the newly added cluster definition and that the Applications has to be sync-replaced. :man_shrugging:

sync replace after configuring kcp

---

components/build/pipelines-as-code/kustomization.yaml

v0.11 was skipped due to issues with updating status back to github using GitHub App.
@ralphbean @sbose78 @MatousJobanek This is not critical fix but we would like to verify that v0.12 is not having issues as v0.11.

Update PipelinesAsCode to v0.12

---

components/build/tekton-chains/chains-controller-deployment.yaml

This new image for the Chains controller includes a patch that significantly reduces the amount of times the Chains controller is invoked to reconcile resources.
https://issues.redhat.com/browse/HACBS-1162

Fix perf issue on Chains controller

---

argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/development/repo-overlay.yaml
components/authorization/kcp/base/bind-apiexports.yaml
components/authorization/kcp/base/everyone-bind-apiexports.yaml
components/authorization/kcp/base/kustomization.yaml

let's allow everyone bind all APIExports in the SP workspaces (for now) - to make testing in CPS easy and simple.
Reason: It's not possible to bind the APIExport of HAS. 
cc @johnmcollier

allow everyone bind all APIExports

---

README.md

Preview mode was failing for me because my yq version was out of date (v4.9.x), moving up to v4.27.x fixed things.
I'm sure preview mode works with older yq versions than just 4.27.x, but I figured it was most straightforward to specify the latest version.

Specify yq version in readme

---

components/spi/base/config.yaml
hack/preview-template.env
hack/preview.sh

The sharedSecret is no longer a thing in SPI so we should not configure it here.

Remove sharedSecret from SPI config

---

components/ckcp/deployment.yaml
components/ckcp/pvc.yaml
hack/preview.sh

- Increase PVC size of ckcp to 5Gi
- Increase memory of ckcp to 4Gi
- Update identity hash only when it's resolved

Increase resources of ckcp, keep unresolved IdentityHash

---

hack/configure-kcp.sh
hack/create-user-workspace.sh
hack/flags.sh
hack/install-pipeline-service.sh
hack/preview.sh

- Access workspaces directly, not needed to go via ROOT_WORKSPACE
- Allow to define HOME_WORKSPACE

Convert ROOT_WORKSPACE='~' to full path in flags.sh

---

hack/preview.sh

The last PR wasn't rebased and reintroduced this bug, breaking hacbs in dev envs

Fix variable quoting in preview.sh for APIExports

---

hack/preview.sh

Do not look just for hacbs string but for components/hacbs since it's looking to absolute path.
Fixes #793

preview fix: filter hacbs by folder components/hacbs

---

README.md
hack/install-ckcp.sh

`./hack/install-ckcp-sh --destroy` first deletes argoCD applications and ckcp and kcp namespaces. Useful for new ckcp creation and bootstraping the cluster.

Add '--destroy' param to install-ckcp.sh

---

components/authorization/kcp/base/members-view-everything.yaml

SSO login takes `redhat.com` with the id. 

Added domain address for sso login

---

hack/install-pipeline-service.sh
hack/preview-template.env

Script for installation of pipeline-service now requires TEKTON_RESULTS_DATABASE_USER and TEKTON_RESULTS_DATABASE_PASSWORD env

Set TEKTON_RESULTS creds for pipeline-service

---

components/ckcp/certs.yaml
hack/configure-kcp.sh
hack/flags.sh
hack/preview-template.env
hack/util-validate-preview-env.sh

This PR contains the following changes.
A new option CKCP_SYNCER_USE_INTERNAL_SERVICE  in preview mode will allow the syncer to connect to ckcp via the local kubernetes service instead of the public route. 
This is required when the local kube (CRC) has an IP of 127.0.0.1 as the syncer will try to connect to the public API endpoint and cannot reach it.
There is a new utility that warns if new vars are found in preview-template and not in preview.env so than when updates are made end users can easily know they may need to resolve their their preview.env files .

Connect Syncer to Local  CKCP via internal service

---

argo-cd-apps/app-of-apps/all-applications.yaml
argo-cd-apps/base/application-api.yaml
argo-cd-apps/base/application-service.yaml
argo-cd-apps/base/authorization-in-cluster.yaml
argo-cd-apps/base/authorization-in-kcp.yaml
argo-cd-apps/base/build-service.yaml
argo-cd-apps/base/enterprise-contract.yaml
argo-cd-apps/base/gitops-appstudio-service.yaml
argo-cd-apps/base/gitops-core-service.yaml
argo-cd-apps/base/integration-service.yaml
argo-cd-apps/base/jvm-build-service.yaml
argo-cd-apps/base/release-service.yaml
argo-cd-apps/base/spi.yaml

Default foreground prunning is creating finalizer foregroundDeletion which block removal of the resource in KCP environment. With background policy the resources are removed.

Use background pruning

---

components/hacbs/jvm-build-service/base/kustomization.yaml
components/hacbs/jvm-build-service/overlays/dev/kustomization.yaml

@Michkov I was able to verify this with https://github.com/redhat-appstudio/jvm-build-service/pull/313 
With these, I was able to get jvm build service "demo'able" on KCP per my recent messages in the team's slack channel and [PLNSRVCE-762](https://issues.redhat.com//browse/PLNSRVCE-762)
That said, I'm guessing this needs changes directed by you, and I'll add some disclaimers / questions as in line comments below to confirm/deny that
@stuartwdouglas FYI

PLNSRVCE-762: add IMAGE_TAG,IMAGE_REPO env vars to jvm bld svc

---

README.md

Reason why to use
- GNU `sed`:
[Link to a problematic code](https://github.com/redhat-appstudio/infra-deployments/blob/f73d31362cc973cf2f62fafe19e00e3ed86476f2/hack/preview.sh#L131)
https://stackoverflow.com/a/5734237
- opennsl v3
[Link to a problematic code](https://github.com/openshift-pipelines/pipeline-service/blob/037effab03503dc6c87175513d5615044b3cb502/images/kcp-registrar/bin/register.sh#L255)
Default version of openssl on Mac (LibreSSL 2.8.3) returns an error "`poll error`" after executing this command ^
There is no easy workaround

docs: update readme with note about sed, openssl (on Mac OS)

---

hack/install-pipeline-service.sh

This change should solve the issue of this repository breaking unexpectedly from changes happening on the main branch of the pipeline service repository
Signed-off-by: Romain Arnaud <rarnaud@redhat.com>

Use the v0.8.0 tag for pipeline-service

---

components/hacbs/jvm-build-service/base/self-binding.yaml

@Michkov this fixes the 
```
- lastTransitionTime: "2022-10-24T15:28:39Z"
message: '1 unexpected and/or invalid permission claims (showing first 1): unexpected/invalid
claim for serviceaccounts. (identity "")'
reason: InvalidPermissionClaims
severity: Error
status: "False"
type: PermissionClaimsValid
```
both you and I saw in CPS, local bootstraps, etc.
From my preview cluster with this branch:
```
gmontero ~ $ oc get apibinding jvm-build-service -o yaml
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
kcp.dev/cluster: root:users:zu:yc:kcp-admin:redhat-hacbs
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"apis.kcp.dev/v1alpha1","kind":"APIBinding","metadata":{"annotations":{"argocd …
```

rm jvm-bld-srvc apibinding entries (allow populate from repo)

---

hack/create-user-workspace.sh

https://github.com/redhat-appstudio/infra-deployments/pull/865 introduced cluster workspace type support to the `create-user-workspace.sh` script.
As a result of this change, a user would encounter the following error when running this script:
```
▶ hack/create-user-workspace.sh appstudio
Accessing the home workspace:
Current workspace is "root:users:sp:yy:rh-sso-username".
Creating & accessing appstudio workspace 'appstudio':
Error: clusterworkspaces.tenancy.kcp.dev "appstudio" is forbidden: workspace type root:redhat-appstudio:appstudio does not exist
```
Revering the workspace type back to `root:universal` as was done previous to https://github.com/redhat-appstudio/infra-deployments/pull/865

revert workspace type to `root:universal`

---

.ci/oci-e2e-deployment.sh
hack/preview.sh

`main` branch in e2e-tests repo no longer contains the script for SPI init

fix: SPI init script default URL

---

components/build/tekton-chains/chains-controller-deployment.yaml
components/build/tekton-chains/kustomization.yaml

The changes in Tekton Chains required by the Pipeline Service have been merged upstream (PipelineRun Attestations). Use that version instead of a fork.

Use upstream version of Tekton Chains - 0.13.0

---

components/application-api/overlays/dev/apiexport.yaml
components/spi/overlays/dev/apiexport.yaml
hack/preview.sh

APIExports are needed sooner then ArgoCD apps are applied. Generate placeholders to take IdentityHashes, ArgoCD updates them later

preview: generate missing APIExports

---

components/spi/kustomization.yaml
components/spi/operator-limits-patch.json

Trying to mitigate the problem reported in https://issues.redhat.com/browse/SVPI-261 that we think is probably caused by a large number of SPI-related resources in the cluster.
Note that this should be a `pre-kcp`-specific fix, because the recent versions of SPI should contain code to automatically clean up the stale, unused resources.

increase the memory limit of the operator to overcome the operational problems on the staging cluster.

---

argo-cd-apps/overlays/development/delete-applications.yaml

Pack-broker does not work out-of-box, it requires manual secret creation.

Disable pack-broker on development environments

---

argo-cd-apps/base/application-api.yaml
argo-cd-apps/base/kustomization.yaml
argo-cd-apps/overlays/development/repo-overlay.yaml
components/application-api/OWNERS
components/application-api/kustomization.yaml

Adds the application-api component as it was not present on the pre-kcp branch. 
Newer versions of the HAS and gitops components do not have the CRDs in their kustomize manifests, so it's necessary to add the application-api kustomize manifests in infra-deployments. As we had a separate component for application-api on the KCP-branch, I figure it makes sense to do so as well for the non-KCP branch.

Add application-api component

---

hack/util-patch-spi-config.sh

The usual `<routeName>-<namespace>.apps.<clusterBaseURL>` is different on CRC. This solution should be more generic.

fix: use correct URL in SPI configmap when deployed on CRC.

---

components/authentication/prune-has.yaml

Updates the existing has-pruner cluster role to include listing of snapshots & snapshotenvironmentbindings.

Update HAS Pruner role to include listing of Snapshots/Bindings

---

components/build/tekton-chains/chains-config.yaml

This aligns with the current plan to not have Rekor enabled initially, but introduce it post-mvp phase.

Disable rekor integration

---

components/authentication/everyone-can-view.yaml
components/authentication/group-sync/github-redhat-appstudio-sre.yaml
components/authentication/group-sync/kustomization.yaml

I configured a new GH app in the redhat-appstudio-sre repo - we use the `stage` team as the gate for authenticating users in the stage cluster

grant cluster view to only stage members from redhat-appstudio-sre

---

hack/preview.sh

fixes an issue seen on Mac OS
```
sed -i "s/rekor-server.enterprise-contract-service.svc/rekor.apps.cluster-fqdv9.fqdv9.sandbox2624.opentlc.com/" .../infra-deployments/argo-cd-apps/base/enterprise-contract.yaml
sed: 1: "/...": unterminated substitute pattern
```

fix: update sed cmd for compatibility with mac os

---

components/spi/overlays/staging/config-patch.json

I accidentally forget to set the correct vault route. 
This is how it looks

Fixed incorrect vault route url

---

components/authentication/everyone-can-view.yaml

Allow to view managed-gitops and jvmbuildservice CRs.

Extend view to jvmbuildservice and managed-gitops groups

---

components/shared-resources/kustomization.yaml
components/shared-resources/redhat-appstudio-staginguser-secret.yaml
components/shared-resources/shared-resources-components.yaml

Old pipelines are requiring to have shared secret available even if it's empty. Should not be needed when we switch to new bundles without shared-secret dependency.

Return shared secret which is used by hacbs-service-core bundle

---

argo-cd-apps/base/internal-services.yaml
argo-cd-apps/base/kustomization.yaml
components/authentication/internal-services.yaml
components/authentication/kustomization.yaml
components/internal-services/OWNERS
components/internal-services/README.md
components/internal-services/internal_service_request_role.yaml
components/internal-services/internal_service_request_role_binding.yaml
components/internal-services/internal_service_request_service_account.yaml
components/internal-services/internal_service_service_account_token.yaml
components/internal-services/kustomization.yaml

- As part of HACBS-1443, we have developed an operator that will run on a private, internal cluster provided by AppSRE.
- This operator will reach out to the HACBS cluster to watch for InteralRequest CRs and execute internal pipelines.
- This PR created the objects needed for the operator to watch the CRs

Add SA, Role and RoleBindings for Internal Services Controller

---

components/tekton-ci/kustomization.yaml
components/tekton-ci/namespace.yaml

PipelineRuns are being managed by PipelineAsCode annotation on PipelineRun.

PLNSRVCE-939: skip tekton-pruning on tekton-ci namespace

---

hack/preview.sh

Before this fix, the condition in the heredoc in `while` was evaluated/executed just once and thus it never succeeded.
This fixes it.

fix wait for reg. service in preview.sh

---

components/dev-sso/keycloak-realm.yaml

This is needed, because for using this keycloak in CI we need to be able to easily obtain token (skip the OAuth2 flow).
With this change it will be possible to use
```
curl -s -k -d 'client_id=sandbox-public' -d 'password=<PASSWORD>' -d 'username=<USERNAME>' -d 'grant_type=password' <KEYCLOAK_URL>/auth/realms/testrealm/protocol/openid-connect/token |jq -r .access_token
```

STONE-249 Enable direct access grants in dev keycloak realm

---

components/monitoring/grafana/base/grafana-app.yaml

This PR fixes the current access failures in 
https://grafana-appstudio-workload-monitoring.apps.appstudio-stage.x99m.p1.openshiftapps.com

Updated authentication org and team for grafana

---

components/enterprise-contract/kustomization.yaml

This will be used by the e2e tests and will allow for pinning the policy version.

Create entry for the ec-policy source in the ec-defaults configmap

---

hack/destroy-cluster.sh

Re-bootstrap will hang if dev-sso is not removed in advance.

Some namespaces are not removed yet

---

components/pipeline-service/pipelines-as-code/kustomization.yaml

* Locally tested ✔️, `pipeline-service` argocd application is green in Argo CD Dashboard with PAC v0.15.0.
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>

Upgrade PAC to v0.15.0

---

components/tekton-ci/serviceaccount.yaml

The secret is used during the build Pipeline to push the image to the registry. This is done by mounting the secret, thus the secret is defined under `secrets` in the `pipeline` `ServiceAccount`. However, in order for Chains to re-use the secret to push image signatures and attestations, the secret must be a "pull secret" defined under `imagePullSecrets`

Use pull secret as imagePullSecret in tekton-ci

---

components/monitoring/grafana/README.md

This PR 
* updates the grafana oauth token to make it non-expiring till tha grafana sa is explicitly deleted.
* updated manual commads to make it suitable for current stage setup

Updated README to make it explicit and grafana oauth token non expiring

---

components/authentication/build.yaml
components/authentication/pipeline-service-sre.yaml

Pipeline Service team should be able to maintain the following components:
- openshift-piplines/tekton-pipelines
- tekton-results
- tekton-chains
- pipelines-as-code

Add Pipeline Service team permissions

---

components/monitoring/prometheus/base/prometheus-servicemonitors.yaml

- Override default value 30sec and set it 15sec as it is set in other ServiceMonitors

Align SPI's scrape interval with other ServiceMonitors

---

components/authentication/everyone-can-view.yaml
components/build-templates/e2e/role.yaml
components/build-templates/e2e/rolebinding.yaml

add roles and rolebindings around buildpipelineselectors
* add permissions to read buildpipelineselectors for authenticated users
* add permissions to pipeline SA in tekton-ci namespace to administer buildpipelineselectors in build-templates-e2e namespace

fix: buildpipelineselectors roles, rolebindings

---

components/dev-sso/keycloak-realm.yaml

Sometimes testing locally with keycloak token is hard because we need to update the token every 5 minutes. This PR just update the token lifetime to 2hrs

Increase the dev sso tokens to 2h.

---

components/monitoring/grafana/base/grafana-app.yaml
components/monitoring/grafana/base/grafana.ini
components/monitoring/grafana/base/kustomization.yaml

- Service provider's dashboard 
- SPI components state  dashboard
- Dedicate to SPI's SLO dashboard
We decided to use individual configmaps per dashboard to make sure we are not hitting the limit 1Mb per configmap.

Provision SPI's grafana dashboard

---

components/monitoring/prometheus/base/prometheus-servicemonitors.yaml

Enable ServiceMonitor for build-service and jvm-build-service.
'jvm-build-service' provides metrics already. 
'build-service' will provide metrics after merge of #1119
[PLNSRVCE-984](https://issues.redhat.com/browse/PLNSRVCE-984)

Build services Prometheus monitor

---

components/shared-resources/globally-shared-secrets-clusterrole.yaml
components/shared-resources/snyk-shared-secret.yaml

Infra-update pipelines for components CI are using old pipelineruns which are still pointing to old snyk-secret. Returning it.

hotfix: Return shared snyk secret used by infra-update

---

components/tekton-ci/repository.yaml

Add the "spray" proxy for Pipelines as Code to our CI infrastructure. This will enable tests driven by Pipelines as Code.
Note that this component will be deployed on StoneSoup host clusters. A respective ArgoCD app will be created in the future once infra deployments supports host cluster ArgoCD applications.

Add sprayproxy to tekton-ci

---

components/monitoring/prometheus/base/servicemonitors/gitops-service.yaml
components/monitoring/prometheus/base/servicemonitors/kustomization.yaml

Add GitOps Service' Prometheus ServiceMonitors/ClusteRoleBindings. Up-to-date with recent refactoring of Prometheus YAMLs.

Add GitOps Service' Prometheus ServiceMonitors/ClusteRoleBindings

---

components/monitoring/grafana/base/kustomization.yaml

Add link to GitOps Service Grafana dashboard JSON, in GitOps Service repository.

GitOps Service: Add Grafana dashboard JSON

---

hack/build/build-via-appstudio.sh

Registry-auth support was removed in [PLNSRVCE-910](https://issues.redhat.com//browse/PLNSRVCE-910) and it's replaced by secrets linked to the serviceaccount.

fix: build-via-appstudio.sh - link secret

---

components/monitoring/grafana/base/grafana-app.yaml
components/monitoring/grafana/base/kustomization.yaml

Adds Build Service dashboards introduced in [this PR](https://github.com/redhat-appstudio/build-service/pull/107).

Add build-service grafana dashboards

---

components/monitoring/grafana/base/build-service/kustomization.yaml
components/monitoring/grafana/base/dora-metrics/kustomization.yaml
components/monitoring/grafana/base/kustomization.yaml
components/monitoring/grafana/base/managed-gitops/kustomization.yaml
components/monitoring/grafana/base/release-service/kustomization.yaml
components/monitoring/grafana/base/spi/kustomization.yaml

To avoid git conflicts moving grafana configurations of services to sub-folders.
Action required -> if you have update set in .tekton folder then update file path.

grafana: move component code to subfolders

---

components/sprayproxy/kustomization.yaml
components/sprayproxy/servicemonitor-rbacproxy/auth-proxy-clusterrolebinding.yaml
components/sprayproxy/servicemonitor-rbacproxy/kustomization.yaml
components/sprayproxy/servicemonitor-rbacproxy/servicemonitor.yaml

@adambkaplan @bamachrn @gbenhaim - changes stemming from the call between Gal, Bama, and I last week, plus the merge of https://github.com/redhat-appstudio/sprayproxy/pull/19
PR is based off of the latest multi-cluster branch

PLNSRVCE-1022: add kube-rbac-proxy related rback for sprayproxy; add sprayproxy servicemonitor; bump sprayproxy git/image sha

---

argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
components/sprayproxy/kustomization.yaml

See tail end of https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1675779040727089
/assign @gbenhaim 
/assign @adambkaplan 
@ramessesii2 @avinal FYI

make sprayproxy namespace name consistent across relevant repositories

---

components/enterprise-contract/default-ecp.yaml

Collections in EC are a way of specifying a subset of the EC rules that should be applied. Change the default configuration to specify that EC should use the "minimal" of rules.
The idea is that a brand new user is not likely to want the full set of EC checks, which includes some Red Hat specific requirements.
JIRA: [HACBS-1615](https://issues.redhat.com//browse/HACBS-1615)

Configure a cut-back set of EC rules by default

---

components/authentication/gitops.yaml
components/authentication/kustomization.yaml

- Fix an issue with duplicate role names
- Add `gitops-component-maintainer.yaml` new file to `kustomization.yaml`

Update GitOps Maintainers and maintainer role: fix duplicate role names in kustomize.yaml

---

components/authentication/gitops-component-maintainer.yaml

- As described in the title, switch to single-quotes from quotation marks

Update GitOps Component Maintainer Role YAML: fix quotes

---

components/monitoring/grafana/base/managed-gitops/kustomization.yaml

Another stab at attempting to pull in the GitOps Service Dashboard :smile: 
JIRA: https://issues.redhat.com/browse/GITOPSRVCE-341

GitOps Service: Update to latest dashboard contents on managed-gitops repository

---

components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml

- This PR goes along with https://github.com/openshift-pipelines/pipeline-service/pull/473 opened on Pipeline Service.
- Adds the required Service Monitor and cluster role binding in order to scrape metrics from the custom pipeline service metrics exporter.

Added ServiceMonitor for pipeline-service

---

components/authentication/gitops.yaml
components/gitops/staging/kustomization.yaml

- Move to the kustomize overlay in managed-gitops repo which is used to configure Stonesoup member cluster
- Update RB -> CRB, as it was incorrectly set previously
- Update to latest commit

GitOps: multi-cluster - Move to GitOps' Stonesoup member cluster kustomize overlay

---

components/pipeline-service/kustomization.yaml

This will also include changes to expose the public-key secret in the tekton-chains namespace to all users of the clusters to allow users to decode tekton-chains signed payloads.

Update pipeline service to have the custom exporter changes

---

components/tekton-ci/repository.yaml

So far, I was running this on my own tenant namespace. I'm going to be moving this off to the tekton-ci Component as part of this PR.

add image-controller to main CI

---

docs/development/deployment.md

I tried to click on the development configuration link on [preview mode for your clusters section](https://redhat-appstudio.github.io/infra-deployments/docs/development/deployment.html#preview-mode-for-your-clusters) which pointed me to a [non-existing link](https://redhat-appstudio.github.io/infra-deployments/argo-cd-apps/overlays/development/). 
I have corrected the url.

docs: fixed wrong url for development config

---

argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml

The sprayproxy overlay doesn't have any cluster specific overlay, so it can be omitted from the ApplicatioSet definition.

Fix source path for sprayproxy

---

components/dev-sso/keycloak-realm.yaml

Add a role to keycloak user `user1` to manage users. 
The `user1` will add a new user per test run. Having a unique user per test helps track user actions in logs in case something fails.

Update keycloak user

---

hack/preview-template.env
hack/preview.sh

e2e runs are now running in release-service PRs.
This is copied and adapted from what's done
for build-service.
See: https://issues.redhat.com/browse/HACBS-1669

feat: Enable deployment from release-service PRs

---

components/authentication/base/group-sync/github-redhat-appstudio-sre.yaml
components/authentication/base/group-sync/github-redhat-appstudio.yaml
components/gitops/production/base/kustomization.yaml
components/gitops/staging/base/kustomization.yaml

authentication: Skip on missing resources
Since the authentication app installs the GroupSync CR and Subscription
, it should skip the dry run for checking if there are missing
resources.
gitops: Skip on missing resources
Since Gitops installs the ArgoCD CR and Subscription for
openshift-gitops, it should skip the dry run for checking if there are
missing resources.

Skip on missing

---

components/monitoring/prometheus/production/base/kustomization.yaml
components/monitoring/prometheus/production/stone-prd-m01/kustomization.yaml
components/monitoring/prometheus/production/stone-prd-m01/monitoring-prometheus-oauth-config-path.yaml
components/monitoring/prometheus/production/stone-prd-rh01/kustomization.yaml
components/monitoring/prometheus/production/stone-prd-rh01/monitoring-prometheus-oauth-config-path.yaml

This PR adds `prometheus-oauth2-proxy` secrets to the prod environment using external secrets 

Added external secrets for stone-prod-prometheus

---

components/gitops/production/stone-prd-m01/gitops-service-postgres-rds-config-path.yaml
components/gitops/production/stone-prd-rh01/gitops-service-postgres-rds-config-path.yaml

Update GitOps external secrets references, to new RDS secrets within app-interface
JIRA: [GITOPSRVCE-418](https://issues.redhat.com/browse/GITOPSRVCE-418)

GitOps: Update references to prod RDS vault secrets

---

argo-cd-apps/base/member/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml

Some of the monitoring applications requires cluster specific overlay, so it should be reflected in the ApplicationSet.

monitoring: Add path to cluster overlays

---

components/monitoring/logging/stagging/base/kustomization.yaml
components/monitoring/prometheus/production/base/kustomization.yaml
components/monitoring/prometheus/stagging/base/kustomization.yaml

Some of the resources were missing because the were no pointer from the overlay to the required base.

monitoring: Add missing pointers to base

---

components/dev-sso/keycloak-realm.yaml

As a new change in chrome is introduced, now it is expected that keycloak has a scope `nameandterms` which is not by default present in a keycloak. Adding it to the default scopes of a `cloud-services` client in keycloak.
PR introducing breaking change: https://github.com/RedHatInsights/insights-chrome/pull/2284/files
Temporary fix before this PR is merged: https://github.com/RedHatInsights/insights-chrome/pull/2289

Add scope for a client.

---

argo-cd-apps/base/member/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
argo-cd-apps/overlays/production/kustomization.yaml

This PR updates the logging deployment menifests from prometheus to logging for fluentd

Fix logging deployment to the clusters

---

components/shared-resources/globally-shared-secrets-clusterrole.yaml
components/shared-resources/kustomization.yaml
components/shared-resources/scc.yaml

I could not find any jira trackers for this yet (not surprising, 4.13 does not GA until April) but I wanted to register some placeholders somewhere to possibly help remind us when the time comes

move to 4.12 version of sharead resources, including official images; add reminders for moves to OCP 4.13, 4.14

---

components/pipeline-service/base/testing/kustomization.yaml
components/pipeline-service/base/testing/ns.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml
hack/bootstrap-member-cluster.sh
hack/secret-creator/create-plnsvc-secrets.sh

Bump pipeline-service version to get latest updates:
- Upgrade openshift-pipelines to 1.9
- pipeline-service-storage argocd app to provide storage backends in
developer mode
- Upgrade tekton-results:
- REST endpoint for tekton-results api
- Tekton-results logging

Bump pipeline-service version

---

components/pipeline-service/base/testing/kustomization.yaml
components/pipeline-service/base/testing/rbac.yaml

The testing NS and its related resources are used to run pipeline-service smoke tests.

Add testing NS for pipeline-service

---

components/enterprise-contract/ecp.yaml

Due to https://issues.redhat.com/browse/OCPBUGS-8428, this rule may cause unnecessary violations.

Skip step_image_registries in the minimal ECP

---

hack/hac/installHac.sh

it to existing Stonesoup instance.
Give you have access to c-rh-c cluster (used by console.redhat.com for ephemeral environments), this script can install HAC onto namespace on that cluster and wire it up to your instance of Stonesoup.
This script is ment to be used mainly in CI for deploying Ephemeral HAC alongside ephemeral Stonesoup to test these together.

STONE-524 - Add script for installing ephemeral HAC & wiring

---

components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml

We need to get fluentd to set the log retention period for us.  Otherwise, every time we get a new tenant, its logs have a retention period of "forever".
Docs: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/cloudwatch/ 
How it's done manually: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention
Terraform example: https://docs.bridgecrew.io/docs/logging_13 
I couldn't find a Kustomize example other than the one from Banzai.

add log retention for new log groups

---

components/monitoring/grafana/base/external-secrets/kustomization.yaml
components/monitoring/grafana/base/external-secrets/monitoring-grafana-oauth-config.yaml
components/monitoring/grafana/production/kustomization.yaml
components/monitoring/grafana/production/monitoring-grafana-oauth-config-path.yaml
components/monitoring/grafana/staging/kustomization.yaml
components/monitoring/grafana/staging/monitoring-grafana-oauth-config-path.yaml

We should have access to one grafana (connected to all the prometheus and logging) per env

Added grafana oauth2-proxy secret from vault

---

argo-cd-apps/base/member/infra-deployments/o11y/o11y.yaml

The o11y component doesn't have any cluster specific overlay.

Remove cluster dir from o11y overlay path

---

components/enterprise-contract/ecp.yaml
components/enterprise-contract/kustomization.yaml
components/enterprise-contract/role.yaml
components/enterprise-contract/rolebinding.yaml

**Why**
`ec-defaults` configmap in `enterprise-contract-service` namespace should be readable by all users/SA on a cluster (currently our e2e tests in build-definitions repo fail because of the missing permission for tekton-ci SA):
```
Message: "configmaps \"ec-defaults\" is forbidden: User \"system:serviceaccount:tekton-ci:pipeline\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"enterprise-contract-service\"",
```
This PR adds the required clusterrole and rolebinding
**Verification**
```
❯ oc new-project test
❯ oc get $(oc get secret -n test -o name | grep pipeline-token-) -o json | jq -r .data.token | base64 --decode | pbcopy
❯ oc login --token <copied-SA-token>
❯ oc get configmap ec-defaults -n enterprise-contract-service -o name
configmap/ec-defaults
```

feat: view permissions for EC configmap

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/production/kustomization.yaml

This PR disables stonesoup custom promethues in favour of enabling UWM through OCM

Removed ArgoCD pointers for appstudio custom prometheus

---

hack/quicklab/templates/deployment.yaml

registry.k8s.io replaces k8s.gcr.io. Announcement: https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

Update image registry link

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/pac-app-name.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/pac-app-name.yaml

Update the name developers see when Pipelines as Code sends Checks API results back.
Production: "Red Hat Trusted App Pipeline"
Staging: "RHTAP Staging"

Set application name for PaC

---

components/hac-pact-broker/imagestream.yaml

Remove `imagestream` resource from pact-broker. It's not used for our deployments.

Remove unused imagestream

---

components/monitoring/prometheus/production/base/kustomization.yaml
components/monitoring/prometheus/staging/base/kustomization.yaml

A number of monitoring-related yaml files were removed on a previous commit, but were still being referenced elsewhere. This commit removes those references.

fix: remove dead references in monitoring overlays

---

components/authentication/base/sandbox-sre-admins.yaml

add necessary SpaceRequst permissions to sandbox-sre admins to be able to configure SA that updates SpaceRequest sub-resources
cc @mfrancisc

add neccessary SpaceRequst permissions to sandbox-sre admins

---

components/enterprise-contract/ecp.yaml

The collections key in the EC policy configuration is now deprecated. The preferred way now is to use include with the @collection syntax, so let's use that in the default ECP CRs.
Ref: https://issues.redhat.com/browse/HACBS-2044

contract: Use new collection format in default ECP

---

argo-cd-apps/base/local-cluster-secret/host-on-local-cluster/kustomization.yaml

As part of [RHTAP-687](https://issues.redhat.com//browse/RHTAP-687), ArgoCD is migrated to a dedicated cluster that isn't going to run any host applications. For allowing the migration we need to delete the local-cluster secret, but while the migration is on going, we need to keep the current ArgoCD instance working.

chore(RHTAP-687): Don't prune local cluster secret

---

argo-cd-apps/overlays/staging/kustomization.yaml

Since ArgoCD isn't going to deploy any application on the control plane cluster, there is no need for the local secret.

chore(RHTAP-687): Remove local cluster secret from stage

---

argo-cd-apps/k-components/disable-auto-sync/disable-auto-sync.yaml
argo-cd-apps/k-components/disable-auto-sync/kustomization.yaml
argo-cd-apps/overlays/staging/kustomization.yaml

As part of the migration of ArgoCD to a new cluster, disable autosync.

chore(RHTAP-687): Disable autosync on staging

---

argo-cd-apps/overlays/production/kustomization.yaml

Need to migrate the ArgoCD instance to a new cluster.

chore(RHTAP-687): Disable autosync on production

---

argo-cd-apps/overlays/production/kustomization.yaml

Since ArgoCD isn't going to deploy any application on the control plane cluster, there is no need for the local secret.

chore(RHTAP-687): Remove local cluster secret from prod

---

argo-cd-apps/overlays/production/kustomization.yaml

The migration of ArgoCD to a new cluster was completed.

chore(RHTAP-687): Enable autosync on production

---

argo-cd-apps/app-of-app-sets/base/all-application-sets.yaml

To be on the safe side, avoid accidental deletion of all the application sets when the root app is removed.

Remove ArgoCD finalizer from app-of-appsets

---

components/monitoring/README.md
components/monitoring/prometheus/development/dummy-service-service-monitor.yaml
components/monitoring/prometheus/development/dummy-service.yaml
components/monitoring/prometheus/development/kustomization.yaml

The service monitors defined under the monitoring component are non-functional at the moment. This commit is providing a template for a service monitor, along with a dummy service which to be monitored.
Individual component will use this template service monitor as baseline to create monitors for their services.

chore(STONEO11Y-83): add template service monitor

---

components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml

The value of the s3 endpoint in tekton-results-s3 secret is missing the
URL scheme (host copied as it is from Vault) this makes connections from
tekton-results fail. This patch adds the "https://" scheme

Add scheme to endpoint value of s3 secret

---

components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml

- This change follows the instructions provided for a dummy-service service account.
- It fixes the issue with the metrics exporter not being able to access PipelineRuns on the cluster.

Update the servicemonitor file for pipeline-service

---

components/pipeline-service/staging/stone-stg-m01/tekton-results-s3-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/tekton-results-s3-secret-path.yaml

s3 buckets for staging  were created with `stg` in the bucket's name instead of `stage` because the latter conflicts with s3 buckets of old staging still not deleted from AWS.
Vault path for corresponding secrets was updated accordingly

plnsvc: update path of vault credentials for s3 in staging

---

components/monitoring/grafana/base/kustomization.yaml

Allow to first install subscription and then CRDs used by it.

RHTAP-825: fix grafana deployment

---

argo-cd-apps/overlays/development/kustomization.yaml
components/monitoring/grafana/base/build-service/dashboard.yaml
components/monitoring/grafana/base/build-service/kustomization.yaml
components/monitoring/grafana/base/dora-metrics/dashboard.yaml
components/monitoring/grafana/base/dora-metrics/kustomization.yaml
components/monitoring/grafana/base/has/dashboard.yaml
components/monitoring/grafana/base/has/kustomization.yaml
components/monitoring/grafana/base/jvm-build-service/dashboard.yaml
components/monitoring/grafana/base/jvm-build-service/kustomization.yaml
components/monitoring/grafana/base/managed-gitops/dashboard.yaml
components/monitoring/grafana/base/managed-gitops/kustomization.yaml
components/monitoring/grafana/base/release-service/dashboard.yaml
components/monitoring/grafana/base/release-service/kustomization.yaml
components/monitoring/grafana/base/spi/dashboard.yaml
components/monitoring/grafana/base/spi/kustomization.yaml

feat(STONEO11Y-163): Grafana dashboards
Since we use the operator for deploying Grafana, a CR for each dashboard
should be created.
Fix development patch for Grafana
The patch referenced the wrong ApplicationSet.

feat(STONEO11Y-163): Grafana dashboards

---

components/authentication/base/gitops-component-maintainer.yaml

This allows team members with the `gitops-component-maintainer` to upgrade the OpenShift GitOps operators on member clusters, via OpenShift Web Console OLM install plan.
(Based on investigation and discussion on https://github.com/redhat-appstudio/infra-deployments/pull/1556)

Allow GitOps maintainers to upgrade OpenShift GitOps operator via InstallPlans

---

components/external-secrets-operator/kustomization.yaml
components/external-secrets-operator/operator-config.yaml
components/external-secrets-operator/subscription.yaml

By deploying the eso in its own namespace, it can be upgraded independently from other operators.

Deploy external-secrets operator in a dedicated ns

---

components/sprayproxy/base/kustomization.yaml
components/sprayproxy/production/kustomization.yaml
components/sprayproxy/staging/kustomization.yaml

- Update sprayproxy deployment link and image, but only for staging kustomize overlay.
-- Deployment should be updated to include harden sprayproxy api route fix.
-- Image should be updated to include improvement: log forwarding requests.
- Moved base spraypoxy url to the overlay kustomization.yaml to provide opportunity apply deployment changes only for staging vs. production.

PLNSRVCE-1281: Update sprayproxy component for staging kustomize overlay

---

components/gitops/openshift-gitops/overlays/production-and-dev/subscription-openshift-gitops.yaml

This PR:
- Moves OpenShift GitOps up to 1.8 on production member clusters, and updates the dev mode `Subscription` version, as well.
- Staging was previously moved up to 1.8 earlier in the week, and no issues were found.

GitOps: Upgrade OpenShift GitOps up to gitops-1.8 channel

---

components/monitoring/logging/base/install-logging-operator.yaml

It's unused and we get errors on ArgoCD that we shouldn't created it on a managed cluster.

chore(STONEO11Y-84): Remove openshift-operators-redhat namespace

---

components/monitoring/logging/base/install-logging-operator.yaml

Because we are using managed clsuters, the openshift-operators ns
is created automatically by hive. When trying to created it using
ArgoCD we are getting the following error:
one or more objects failed to apply, reason: admission webhook "namespace-validation.managed.openshift.io" denied the request: Prevented from accessing Red Hat managed namespaces

 chore(STONEO11Y-84): Don't create openshift-operators

---

components/has/production/kustomization.yaml
components/has/staging/kustomization.yaml

https://issues.redhat.com/browse/DEVHAS-259
We've noticed in the past when HAS has either crashed / been evicted / gone down for some reason, that there can be a significant delay (e.g. https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1681233397095549), until HAS becomes available again.
While only one instance of HAS will ever be reconciling at a time, having multiple instances available to assume the lease and become leader (and resume reconciliation) upon HAS crashing, should significantly reduce downtime.

[DEVHAS-259] Increase number of replicas for HAS

---

components/has/base/kustomization.yaml

Adds the Service Monitor defined in the HAS repo. Part of work done in https://issues.redhat.com/browse/DEVHAS-272
Updated version of https://github.com/redhat-appstudio/infra-deployments/pull/1733 which was accidentally closed

[DEVHAS-272] Add HAS Service Monitor

---

components/has/production/kustomization.yaml
components/has/staging/kustomization.yaml

Kustomize didn't like mixing patches where `path` was specified, and also not specified. So explicitly specifying it for all patches

[DEVHAS-259] Fix replicas patch for HAS in production

---

components/authentication/base/has-admin.yaml
components/authentication/base/kustomization.yaml

After updating the tokens for HAS on Vault, bouncing the HAS pod(s) may be necessary. Adding a simple admin role for myself, @kim-tsao, and @maysunfaisal to do so.

Add role for bouncing HAS pods after token rotation

---

components/tekton-ci/production/kustomization.yaml

Tested with
```
cd components/tekton-ci
kustomize build production
```

Fixing mismatched file names in kustomize reference

---

components/authentication/base/inspect-pods.yaml

One of the clusters rules had a missing group/version field.

Add missing group/version in auth app

---

components/has/base/kustomization.yaml
components/has/development/kustomization.yaml
components/has/production/kustomization.yaml
components/has/staging/kustomization.yaml

Based on errors in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_application-service/307/pull-ci-redhat-appstudio-application-service-main-application-service-e2e/1652114871954706432, I'm wondering if having two links to kustomize overlays in https://github.com/redhat-appstudio/application-service is tripping up the tests. Moving the prometheus overlays (which are only needed in staging and production) to confirm.

[HAS] Move prometheus to staging and production overlays

---

components/monitoring/grafana/base/grafana-app.yaml

Limit login to Grafana UI.
Only users with access to 'appstudio-grafana' namespace will get access to Grafana UI.

chore(STONEO11Y-169): limit login to grafana

---

components/dora-metrics/base/kustomization.yaml
components/monitoring/grafana/base/dora-metrics/kustomization.yaml

Move dora metrics service monitor to its repository, as per new instructions.

move dora metrics service monitor to its repository

---

components/monitoring/grafana/base/migration/OWNERS
components/monitoring/grafana/base/migration/migration-team-dashboard.json

- Add OWNERS file for the migration Grafana dashboard
- Add a panel to the migration Grafana dashboard to check the pod latency for each task viewable by namespace

Pod latency migration dashboard

---

components/sprayproxy/base/kustomization.yaml
components/sprayproxy/base/team-support-rbac.yaml

So the pipeline service team has a situation where as part of our current access to the various staging/prod environments, we do not have access to the sprayproxy namespace, since it is deployed as part of the sandbox/codeready toolchain host (vs. member) side of things.
That hampers our support of course
Per discussion with @amfred in https://redhat-internal.slack.com/archives/C04F4NE15U1/p1683316863120999 she had a straight forward solution.  Create RBAC specific for our team to only view that namespace.
Here is my offering to handle that for both staging / production by including in the base dir.
Unfortunately, the `hack/bootstrap-host-cluster.sh` command does not seem to go through the sprayproxy path, so some guidance on local testing, or validating via review, is appreciated. …

give pipeline-service team view access to the sprayproxy namespace for support

---

components/tekton-ci/base/external-secrets/snyk-shared-token.yaml

https://github.com/redhat-appstudio/build-definitions/blob/b18bbcbd64df838fcf5cc62d9147087a763098bf/pipelines/core-services/snyk-secret.yaml expects so

create snyk-shared-secret since

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

Upgrade Pipeline-Service
- change default SA for Pipelines to appstudio-pipeline    
- align tekton-results logs with [ADR-6](https://issues.redhat.com//browse/ADR-6)

   Upgrade Pipeline-Service

---

hack/build/build-via-appstudio.sh
hack/build/setup-namespace.sh

This is script for setting namespace which is not managed by toolchain operator. For testing purposes only.

Add script for setup namespace for appstudio execution

---

components/integration/kustomization.yaml

Manual update since the workflow on push was broken.
This PR updates the integration service to the latest commit which has only changes for [STONEINTG-419](https://issues.redhat.com//browse/STONEINTG-419) and has no dependabot-related updates in it in order to comply with the code-freeze exception.

Update integration service for STONEINTG-419

---

components/sprayproxy/production/kustomization.yaml

New features added:
- Add GitHub webhook validation - https://github.com/redhat-appstudio/sprayproxy/pull/37
- Add forwarding request timeout - https://github.com/redhat-appstudio/sprayproxy/pull/40
- Limit proxy request size - https://github.com/redhat-appstudio/sprayproxy/pull/43

Update sprayproxy version prod

---

argo-cd-apps/base/tekton-ci/tekton-ci.yaml

Since the serviceaccount was changed to appstudio-pipeline we need to update argoCD definition to not update linked secret appstudio-pipeline-dockercfg-*

RHTAP-872: tekton-ci: fix SA update - ignore native secret

---

components/monitoring/grafana/base/grafana-app.yaml

Rename Grafana datasource to `prometheus-appstudio-ds` so it will be caught when using templating with `.*(appstudio)-.*` regex

chore(RHTAPWATCH-242): rename Grafana datasource

---

components/monitoring/prometheus/README.md
components/monitoring/prometheus/base/monitoringstack/kustomization.yaml
components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
components/monitoring/prometheus/development/monitoringstack/cluster-type-patch.yaml
components/monitoring/prometheus/development/monitoringstack/kustomization.yaml
components/monitoring/prometheus/development/monitoringstack/observability-operator.yaml
components/monitoring/prometheus/production/kustomization.yaml
components/monitoring/prometheus/production/monitoringstack/cluster-type-patch.yaml
components/monitoring/prometheus/production/monitoringstack/kustomization.yaml
components/monitoring/prometheus/staging/kustomization.yaml
components/monitoring/prometheus/staging/monitoringstack/cluster-type-patch.yaml
components/monitoring/prometheus/staging/monitoringstack/kustomization.yaml

Install the observability operator and use monitoring stack to create a prometheus instance that federates the platform prometheus instance.
Later on, remote-write configs will be added to this instance so that we forward selected metrics to RHOBS.

chore(RHTAPWATCH-269) deploy prometheus using obo

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/development/update-tekton-config-performance.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/update-tekton-config-performance.yaml

As part of trying to isolate the performance impact of the TektonConfig performance tuning options, this PR controls the setting directly from infra-deployments, vs. changing the tektonconfig in pipeline-service and then update to the new version of pipeline-service here
I have verified the behavior via an infra-deployments bootstrap preview using this branch and an OCP cluster I personally provisioned.

PLNSRVCE-1325:  patch tektonconfig so performance setting are reverted to upstream defaults

---

components/authentication/base/component-maintainer.yaml

Removes roles for the `pods/exec` subresource from the component maintainer role, as it should not be needed

Remove pods/exec from component maintainer role

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/update-tekton-config-performance.yaml

* Added overlay for the performance settings so that default settings
are used in production until we are ready to activate tuned settings
* Rename pipelines-scc to appstudio-pipelines-scc
* Update pipeline-service-exporter-reader ClusterRole to watch
pipelineruns and task runs, and get customresourcedefinitions
* Align Pipelines Controller logs with [ADR-6](https://issues.redhat.com//browse/ADR-6)
* Use downstream image for tekton chains
* Add more ArgoCD sync-wave and phases
* Set 'enable-api-fields: beta' in OSP

Update pipeline-service in production

---

components/pipeline-service/base/servicemonitors/kustomization.yaml
components/pipeline-service/base/servicemonitors/tekton-results-service-monitor.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

Adds two service monitors to pipeline-service for Tekton Results api and watcher.

Add Results ServiceMonitor to pipeline-service

---

components/tekton-ci/base/repository.yaml

Adding hacbs-test repo because of regular building of an image.

feat(STONEINTG-362): adding PAC to hacbs-test repo

---

components/tekton-ci/base/external-secrets/kustomization.yaml
components/tekton-ci/base/external-secrets/slack-webhook-notification-secret.yaml

Sync secret from vault with webhooks urls for slack so that pipeline will be able to notify failures via slack.

STONEBLD-29: add slack notification secret for tekton-ci

---

components/pipeline-service/base/servicemonitors/tekton-results-service-monitor.yaml

Tekton results exports metrics over HTTP and not HTTPS. Changing that requires upstream update of code, which is not given will be accepted. As a fix here we change the scheme to HTTP.

Fix Tekton Results servicemonitors scheme

---

components/pipeline-service/production/base/kustomization.yaml

- move prod to the version in staging we just vetted with https://github.com/redhat-appstudio/infra-deployments/pull/1948
- note as we just saw with staging, this bump in pipeline-service does not change the version of the core pipeline/task controllers; it will roll out metrics exporter because of the limit change, and the chains controller because the internal image registry CA were removed

PLNSRVCE-1310: bump pipeline service prod to vetted staging version

---

components/monitoring/prometheus/README.md
components/monitoring/prometheus/base/uwm-config/uwm-config.yaml

- Set the retention time to 3d
- Set the retention size to 10GiB
- These settings would only apply to production and staging clusters 
- Update README file

chore(RHTAPWATCH-241): Increase UWM prometheus retention duration and size

---

argo-cd-apps/overlays/production/kustomization.yaml

- Correctly set production overlays for remote-secret.
- Without this override, it is fallback to `staging` overlay

Correctly set production overlay for remote-secret operator

---

components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml

Fluentd collectors are incompatible with Splunk ClusterLogForwarder configuration.
As detailed in
https://docs.openshift.com/container-platform/4.13/logging/cluster-logging-external.html#logging-forward-splunk_cluster-logging-external
fluentd is not supported with the Splunk Log Forwarder configuration.
Therefore, this commit swaps fluentd with vector.

RHTAPWATCH-322: Fluentd collectors are incompatible with Splunk ClusterLogForwarder configuration

---

components/build-service/development/kustomization.yaml
components/build-service/development/pac-webhook-insecure-ssl-patch.yaml

Disables PaC webhhok TLS verification for dev mode in order to avoid creation of commonly trusted TLS certificates for dev clusters.

Make PaC webhook SSL check configurable

---

components/release/kustomization.yaml
components/release/release-pipeline-resources-clusterrole.yaml

Release PipelineRuns need access to Custom Resources in dev and managed namespaces. This commit adds a ClusterRole to provide those permissions. We can then create RoleBindings in the namespaces we need to pull from so that the pipelineruns can access the resources.

feat(HACBS-2310): add clusterrole for release pipelines

---

components/pipeline-service/development/update-tekton-config-performance.yaml
components/pipeline-service/staging/base/update-tekton-config-performance.yaml

Based on findings in https://issues.redhat.com/browse/RHTAP-979 and confirmation in slack https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1687355774619199 with @pmacik and @jhutar we are switching to the larger scale tekton pipeline controller settings
Following the standard bump dev/staging first, then when confirmed staging looks OK, bump to prod.
Note, as of this comment
- tekton-pipelines-controller in stg-rh01 is at around 50 MiB of memory, around 2m of cpu, and around 400 KiB of FS
- in stg-multi tenant, we are at around 400 MiB memory, anywhere from 10m to 45m cpu, and 12 MiB FS
@Roming22 @adambkaplan FYI

PLNSRVCE-1326: switch tekton pipeline controller to larger scale settings in dev/stage

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Several metrics were included inside the service monitor for federating the platform Prometheus instance, which are meant to be used for billing-related recording rules.
It's uncertain at the moment whether those metrics are going to be used in this context (i.e. processed to rules in RHOBS), but in any case, the way that they are currently being scraped is excluding tenants namespaces, which means we're needlessly sending metrics from unrelated namespaces to RHOBS.
This change remove those metrics from the list of metrics to be federated.

fix: remove unneeded metrics from federation

---

components/pipeline-service/production/base/update-tekton-config-performance.yaml

staging has looked good since https://github.com/redhat-appstudio/infra-deployments/pull/1991 merged yesterday
No restarts.
cpu/mem/fs either the same on slightly less impactful both rh and multi stagings
promoting the changes to prod
@jhutar @pmacik FYI

PLNSRVCE-1326: switch tekton pipeline controller to larger scale settings in prod

---

components/tekton-ci/base/repository.yaml
components/tekton-ci/production/kustomization.yaml
components/tekton-ci/production/plnsvc-ci-secret.yaml

This PR is to move Pipeline Service CI to RHTAP production
1. Added Pipeline Service Repository CR
2. Created an ExternalSecret for use of Pipeline Service CI

PLNSRVCE-1124-Move CI to StoneSoup Prod MVP

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

* This is a part of chore([RHTAPWATCH-110](https://issues.redhat.com//browse/RHTAPWATCH-110)): Differ between uncategorized pipelines and deployments, adding "label_app_kubernetes_io_managed_by" label to the monitoringstack.

chore(RHTAPWATCH-110): Add "label_app_kubernetes_io_managed_by" label to the monitoringstack

---

components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml

Per conversation with @amisstea , as this folder is not being processed (he indicated there were some errors in sibling folders), removing the exporter service monitor from infra-deployments, and we'll define in pipeline-service repo, as other components are doing.
https://github.com/openshift-pipelines/pipeline-service/pull/685 is adding to pipeline-service
I am leaving the SA and RBAC definitions for now, in case this subfolder gets reactivated, and those artifacts become useful again.
@adambkaplan @ramessesii2

PLNSRVCE-1069: remove servicemonitor definition that is not currently being processed

---

components/monitoring/grafana/base/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

Since 12862f674f40f65cf94d48691e3fe1a2d3bf95a6 we have
- added Grafana charts for pipeline controller resources
- define the exporter servicemonitor in pipeline-service repo
- various CI related changes which do no impact dev/stage/prod
- we are also bumping the charting ref in addition to the main pipeline-service refs

bump pipeline service in dev/staging

---

hack/preview.sh

The application was not created during the given timeout which failed the script. Increasing the timeout should solve the problem.
Related issue: [HAC-4343](https://issues.redhat.com/browse/HAC-4343)

Fix timeout for remote-secret-controller-in-cluster-local

---

components/pipeline-service/production/base/kustomization.yaml

Pull in the https://github.com/redhat-appstudio/infra-deployments/pull/2015 changes to dev/staging into production.  Note:  the https://github.com/redhat-appstudio/infra-deployments/pull/2015/files#diff-d99d1444c5e672b40e18d7e3637b32e4722598a1e086575e084da610d3455dc5 change from the prior PR should already be available in prod.
Examination of stage looks good after about 18 hours.
Reminder - any e2e results do not stem from this change, as we are only changing prod, and the e2e's work off dev (vs. stage or prod)

bump pipeline service in prod

---

components/monitoring/grafana/base/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

Pull in the exporter pivot to controller based collection, and removal of the duplicate (with upstream) completion duration historgram.

bump pipeline service in dev/stage

---

components/tekton-ci/base/repository.yaml

This isn't in use yet. This will be replaced by https://docs.google.com/document/d/1oTtgDr7caQzTY7qzXH1UUYdk9EV4MqCT22gxwUaM_1Y/edit#heading=h.orkzaa7nxhu0

remove CI config for external-secrets

---

components/monitoring/grafana/base/managed-gitops/kustomization.yaml

Updated ServiceMonitors based on managed-gitops and references to grafana dashboard
Jira link - https://issues.redhat.com/browse/GITOPSRVCE-563

Update ServiceMonitors and reference to the grafana dashboard

---

components/monitoring/grafana/base/managed-gitops/kustomization.yaml

Remove disableNameSuffixHash, as recommended as a solution to the lack of dashboard refresh that was mentioned on https://github.com/redhat-appstudio/application-service/pull/318/files
JIRA: https://issues.redhat.com/browse/GITOPSRVCE-563

Remove generatorOptions from dashboard configmap gen

---

components/enterprise-contract/kustomization.yaml

The ec-defaults ConfigMap in the enterprise-contract-service namespace contains values for which policy and data refs to use when creating a new EnterpriseContractPolicy resource. However, we have moved away from using this ConfigMap for this purpose. Although the values still exist, they are no longer updated by automation.
The automation now keeps a few EnterpriseContractPolicy resources up to date. This commit removes the values from the ConfigMap in order to avoid confusion.
NOTE: The ConfigMap is still useful for determining the most up to date ref for the ec Tekton Task. There are no plans to change this.
https://issues.redhat.com/browse/HACBS-2315

Remove unused ec configmap keys

---

components/monitoring/prometheus/README.md
components/monitoring/prometheus/development/kustomization.yaml
hack/bootstrap-cluster.sh
hack/preview.sh

- OBO (Observability operator) is not deployed by default
- Adding --obo/-o to enable obo deployment in development environment
Examples:   
`./hack/bootstrap-cluster.sh preview --obo`
`./hack/bootstrap-cluster.sh preview -o`

fix(RHTAPWATCH-356): obo conflicts when using OSD on AWS

---

components/image-controller/base/kustomization.yaml
components/integration/kustomization.yaml
components/release/kustomization.yaml

The `preview.sh` script throws an error when it comes to executing `kustomize build` for the following projects:
- `components/image-controller`
- `components/integration`
- `components/release`
The error seems related to the Patches field in the `kustomization.yaml` files:
```
ERROR='[{"lastTransitionTime":"2023-07-03T09:22:48Z","message":"rpc error: code = Unknown desc = `kustomize build .components/image-controller/development` failed exit status 1: Error: accumulating resources: accumulation err='\''accumulating resources from '\''../base'\'': '\''.components/image-controller/base'\'' must resolve to a file'\'': couldn'\''t make target for path '\''.components/image-controller/base'\'': invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of …
```

Fix components kustomization files

---

components/pipeline-service/staging/base/greedy-pruner.yaml
components/pipeline-service/staging/base/kustomization.yaml

Change the pruner settings to aggressively delete finshed PipelineRuns. This change has been requested as part of the investigation around performance testing.

Change pipeline pruner behavior in Staging

---

components/tekton-ci/base/namespace.yaml

The existing configuration done for [PLNSRVCE-939](https://issues.redhat.com//browse/PLNSRVCE-939) keeps PipelineRuns forever. With the change PipelineRuns are kept for 24 hours to give time to developers to investigate before being pruned.

Keep PipelineRuns for 24h in tekton-ci

---

hack/preview.sh
hack/spi/remote-secret-init.sh
hack/spi/spi-init.sh
hack/spi/utils.sh
hack/spi/vault-init.sh

The present PR splits `vault-init` of `service-provider-integration-operator` repo into `vault-init`, `spi-init`, and `remote-secret-init` in order to create a new set of scripts designed for specific infra-deployments use cases for `develop` environment.
With this change, the `infra-deployments` repo will have the spi scripts and it will not call the script in `service-provider-integration-operator` repo.
https://issues.redhat.com/browse/SVPI-518
- Set the required environment variables, such as: `MY_GIT_FORK_REMOTE`, `MY_GITHUB_ORG`, and `MY_GITHUB_TOKEN`
- Run `./hack/bootstrap-cluster.sh preview --keycloak --toolchain` script on infra-deployments dir
Before following the steps on https://github.com/redhat-appstudio/e2e-tests#install-appstudio-in-e2e-mode, please set the following …

SVPI-518: split vault-init into vault-init, spi-init, and remote-secret-init scripts

---

components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/pipelines-as-code-namespace.yaml
components/pipeline-service/staging/base/pipelines-as-code-secret.yaml

The 1.11 bump https://github.com/redhat-appstudio/infra-deployments/pull/1985 and its moving of PaC from `pipelines-as-code` namespace to `openshift-pipeilnes` namespace did not account for refs to the old namespace.
Currently the gitops rollout in staging per https://argocd-server-argocd-staging.apps.stonesoups01ue1.2d3m.p1.openshiftapps.com/applications/argocd-staging/pipeline-service-stone-stg-m01?view=tree&resource= is incomplete and currently stuck on
```
one or more objects failed to apply, reason: namespaces "pipelines-as-code" not found. Retrying attempt #115 at 7:04PM.
```
when processing the `pipelines-as-code-secret` defined in infra-deployments

fix the rollout of 'pipelines-as-code-secret' in staging

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml

Pipelines-as-code externalsecret is being deployed to openshift-pipelines namespace

Allow access vault-secret store from openshift-pipelines

---

components/sprayproxy/staging/add-backends.yml

In OSP 1.11 the PaC resources are deployed under the openshift-pipelines namespace which also changes the endpoints where requests are forwarded.

Update sprayproxy backends after OSP 1.11 upgrade

---

components/tekton-ci/base/external-secrets/github-secret.yaml
components/tekton-ci/base/external-secrets/kustomization.yaml

Add github-read-only-token to ExternalSecrets so that the secret is not created manually but by operator.

tekton-ci: github-read-only-token from ExternalSecrets

---

components/tekton-ci/base/external-secrets/integration-github-token.yaml
components/tekton-ci/base/external-secrets/kustomization.yaml

This is required in order to trigger GH workflow from tekton-ci.

feat(STONE-485): add integration github token secret from vault

---

components/monitoring/grafana/base/release/kustomization.yaml
components/release/kustomization.yaml

The release-service update needs to run paired with an e2e-test change, so creating the update manually.

chore(HACBS-2290): manual release-service update

---

components/tekton-ci/base/repository.yaml

Enable clair-in-ci-db repo for tekton-ci.

Include clair-in-ci-db repo

---

components/monitoring/grafana/base/managed-gitops/gitops-service-argocd-dashboard.yaml
components/monitoring/grafana/base/managed-gitops/kustomization.yaml

The contents of the dashboard that monitors the Argo CD instance in `gitops-service-argocd` is already part of the ConfigMap, we just need to create the corresponding `GrafanaDashboard` CR.

monitoring: Add GitOps Service's Argo CD Dashboard

---

components/authentication/staging/kustomization.yaml
components/authentication/staging/results-cluster-viewer.yaml

what I think an initial permission bump in staging only would look like so either @sayan-biswas or myself could start prototyping direct viewing of logs / records of results in staging only
Of course let me know @sayan-biswas if I misremembered the resources / verbs needed

PLNSRVCE-1381: prototype adding cluster-wide results viewing to some pipeline-service team members

---

components/monitoring/README.md
components/monitoring/grafana/base/build-service/dashboard.yaml
components/monitoring/grafana/base/dora-metrics/dashboard.yaml
components/monitoring/grafana/base/generic-dashboards/controller-runtime-controllers-detail_rev1.json
components/monitoring/grafana/base/generic-dashboards/dashboard.yaml
components/monitoring/grafana/base/generic-dashboards/go-processes_rev1.json
components/monitoring/grafana/base/grafana-app.yaml
components/monitoring/grafana/base/grafana-operator.yaml
components/monitoring/grafana/base/has/dashboard.yaml
components/monitoring/grafana/base/jvm-build-service/dashboard.yaml
components/monitoring/grafana/base/kustomization.yaml
components/monitoring/grafana/base/managed-gitops/dashboard.yaml
components/monitoring/grafana/base/migration/dashboard.yaml
components/monitoring/grafana/base/spi/dashboard.yaml

We are upgrading the Grafana Operator from v4 to v5 as part of a fix to [RHTAPWATCH-8](https://issues.redhat.com//browse/RHTAPWATCH-8) (Somtimes the Grafana insnace is not reachable)
Upgrade to Grafana Operator v5:
- Update Grafana Operator to v5.3.0
- Update Grafana deployment yaml
- Update the APIs in all CRs (Datasources, Dashboards)
- Remove datasource definition from `generic-dashboards`
- Update README file
Notes
Dashboards that their source is in the team's repository were not updated to fit the new API.  
After this PR will get merge these dashboards would not be presented in Grafana.  
We will update the teams' dashboards in their repositories.  
These are the dashboards and repositories:
- Integration - https://github.com/redhat-appstudio/integration-service/blob/main/config/graf …

Fix(RHTAPWATCH-8): Upgrade to Grafana Operator v5

---

components/monitoring/grafana/base/grafana-operator.yaml

The operator group should get deployed before the subscription, otherwise we are getting:
```
failed to populate resolver cache from source
operatorgroup-unavailable/appstudio-grafana:
found 0 operatorgroups in namespace appstudio-grafana: expected 1
```

Deploy Grafana's operator group first

---

components/monitoring/grafana/base/dashboards/managed-gitops/gitops-service-argocd-dashboard.yaml

Update gitops-service-argocd-dashboard CRD with Grafana Operator v5 api and `instanceSelector`

fix(RHTAPWATCH-8): Update gitops-service-argocd-dashboard CRD

---

components/tekton-ci/base/serviceaccount.yaml

Tekton-ci secret has been renamed in #2181, fixing to proper value

Fix: rename tekton-ci secret

---

components/tekton-ci/base/repository.yaml

The o11y repo was accidentally removed from the tekton-ci component which prevents CI from running for the o11y repo.
This change reintroduces the repo

fix: reinstate the o11y repo in tekton-ci

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/pipelines-as-code-namespace.yaml
components/pipeline-service/production/base/pipelines-as-code-secret.yaml
components/sprayproxy/production/add-backends.yml

This is moving our bump to 1.11 openshift pipelines in staging to prod
Aside from the basic version bump, this PR approximates the following PRs that were made to staging only:
- https://github.com/redhat-appstudio/infra-deployments/pull/2108
- https://github.com/redhat-appstudio/infra-deployments/pull/2094
Also note, the following PRs were processed at the time we went to 1.11 in staging, but are considered to already be applicable to the prod env:
- https://github.com/redhat-appstudio/infra-deployments/pull/2096
- https://github.com/redhat-appstudio/infra-deployments/pull/2102
Also NOTE/REMEMBER - the e2e's are NOT affected by this PR since the work off the developer overlay, which has been at 1.11 since the staging bump.
I will place a hold on this until all the reviewers sign off (as …

PLNSRVCE-1350: move to openshift-pipelines 1.11 in prod (porting changes used for staging)

---

components/image-controller/base/kustomization.yaml

Using image directly from the build pipeline, because released one never come out.

Update image-controller image

---

argo-cd-apps/base/member/infra-deployments/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/segment-bridge/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/production/kustomization.yaml
components/segment-bridge/OWNERS
components/segment-bridge/README.md
components/segment-bridge/base/kustomization.yaml
components/segment-bridge/base/serviceaccount.yaml
components/segment-bridge/development/kustomization.yaml
components/segment-bridge/production/kustomization.yaml
components/segment-bridge/staging/kustomization.yaml

Deploy a component for the User Journey effort as segment-bridge. This is needed in order to have a Service account with read permissions to the Namespaces resources from the member clusters. Those resources will be used in a script that'll map between events and cluster's owner

chore(RHTAPWATCH-376): segment-bridge member-cluster component

---

hack/secret-creator/set-docker-hub-pull-secret.sh

This should be appstudio-pipeline as used by the build-service.

Link docker-io-pull secret to the correct service account

---

argo-cd-apps/base/host/kustomization.yaml
argo-cd-apps/base/host/segment-bridge/kustomization.yaml
argo-cd-apps/base/host/segment-bridge/segment-bridge-host.yaml
argo-cd-apps/base/member/infra-deployments/segment-bridge/kustomization.yaml
argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge-member.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
components/authentication/base/segment-bridge.yaml
components/segment-bridge/README.md
components/segment-bridge/base/kustomization.yaml
components/segment-bridge/base/serviceaccount.yaml

Deploy a component for the User Journey effort as segment-bridge. This is needed in order to have a Service account with read permissions to the UserSignup resources from the host cluster. Those resources will be used in a script that'll  map between cluster usernames and SSO ID's

chore(RHTAPWATCH-351): segment-bridge component deployment

---

components/authentication/base/kustomization.yaml

since segment-bridge needs to create resources on
the toolchain-host-operator, which doesn't have a component of its own, those resources are created through the authentication component.
While this will probably change later on, during the last change the connection between the resource yaml and the component was not made. this fix it.

chore: segment-bridge on authentication component

---

hack/spi/vault-init.sh

Refactor vault-init to keep keys in a specific file in order to make them reachable in a second attempt, for example, in case the secret is not created in the first attempt.
https://issues.redhat.com/browse/SVPI-567
- Set the required environment variables, such as: `MY_GIT_FORK_REMOTE`, `MY_GITHUB_ORG`, and `MY_GITHUB_TOKEN`
- Run `./hack/bootstrap-cluster.sh preview --keycloak --toolchain` script on infra-deployments dir
Before following the steps on https://github.com/redhat-appstudio/e2e-tests#install-appstudio-in-e2e-mode, please set the following environment variables:
```
export INFRA_DEPLOYMENTS_ORG=rsoaresd
export INFRA_DEPLOYMENTS_BRANCH=SVPI-567
```

SVPI-567: refactor vault-init to keep keys in a specific file

---

components/authentication/base/segment-bridge.yaml

The apiGroups set in the segment-bridge configuration to access toolchain-host-operator were wrong.
This PR fix it by changing it to toolchain.dev.openshift.com.

chore: segment-bridge has the right usersignup access

---

hack/build/setup-pac-integration.sh
hack/preview-template.env

**Background:**
Please see the doc [RHTAP Quality Testing Workflow](https://docs.google.com/document/d/13M5WjmIXwVsExNVK_xk4YINFqohVvZw4gwLAZTPdq-k/edit)
**Changes:**
When deploying RHTAP, Passing PAC_GITHUB_APP_WEBHOOK_SECRET as parameter to configure secret pipelines-as-code-secret. This allows Pac in the ephemeral cluster to handle requests sent from the GitHub App

Support Pac in ephemeral cluster to  work with QE SprayProxy

---

components/gitops/base/authentication/gitops-clusterroles.yaml

Allow a single team member (myself) to delete SnapshotEnvironmentBindings: this will be used to clean up old SnapshotEnvironmentBindings that are orphaned due to https://issues.redhat.com/browse/RHTAPBUGS-498

managed-gitops: update cluster role to allow cluster maintenance of SnapshotEnvironmentBindings

---

ci/teams/rhtap-servicerelease/external-secrets/infra-deployments-pr-creator.yaml
ci/teams/rhtap-servicerelease/external-secrets/kustomization.yaml
ci/teams/rhtap-servicerelease/external-secrets/slack-webhook-notification-secret.yaml
ci/teams/rhtap-servicerelease/release-build.yaml
ci/teams/rhtap-servicerelease/release-external-secrets.yaml
ci/teams/rhtap-servicerelease/release-strategy.yaml

- Use for rhtap-build and rhtap-gitops
- Add new external-secrets needed for introduced tasks

Use rhtap-service-push release pipeline

---

components/pipeline-service/staging/base/update-tekton-config-pac.yaml

Initially set in a earlier PR, two configuration options were missing, now added.

Fix links to RHTAP console from the PR

---

ci/teams/rhtap-servicerelease/external-secrets/kustomization.yaml
ci/teams/rhtap-servicerelease/external-secrets/pyxis-secret.yaml
ci/teams/rhtap-servicerelease/release-strategy.yaml

- pull in pyxis secret from vault using external-secrets
- refer to new secret in release-strategy

use external-secrets for pyxis

---

components/authentication/base/kustomization.yaml

sandbox-sre-admins.yaml has been moved to
./components/sandbox/base/rbac/, this is causing fail of sync of authentication component.

fix: authentication is not having sandbox-sre-admins.yaml

---

hack/setup/install-pre-req.sh

Adding RHEL to the OS case check for the pre-reqs script, and "not supported" messages for unmatched cases.

add support for RHEL to pre-reqs script

---

components/gitops/production/stone-prd-m01/gitops-team-member-namespaces.yaml
components/gitops/production/stone-prd-m01/kustomization.yaml
components/gitops/staging/stone-stg-m01/gitops-team-member-namespaces.yaml
components/gitops/staging/stone-stg-m01/kustomization.yaml

- On staging MT, allow GitOps Service Team members group to access `jgwest-tenant`
- On prod MT, allow only  `jgwest` github user id to access `jgwest-tenant`

Allow GitOps team members to access jgwest-tenant namespace where it is available

---

argo-cd-apps/base/tenants-config/kustomization.yaml
argo-cd-apps/base/tenants-config/tenants-config.yaml
argo-cd-apps/overlays/production/kustomization.yaml

Add a new application set that will generate application for RH each tenant defined in https://github.com/redhat-appstudio/tenants-config Each tenant has a directory with the name if his/hers namespace. The generate application will be associated with the "tenants-config" project that restricts which resources can be deployed, to which namespaces and clusters. The project is defined using app-interface.

RHTAP-1495: AppSet for RH users configurations

---

argo-cd-apps/base/tenants-config/tenants-config.yaml

- ApplicationSet.argoproj.io "tenants-config" is invalid: spec.generators[0].git.repoURL: Required value

RHTAP-1495: correct typo in tenants-config

---

components/gitops/base/authentication/gitops-clusterroles.yaml

As requested [on RHTAP Slack](https://redhat-internal.slack.com/archives/C02C3SE8QS2/p1692913633009639), there are a number of SpaceRequests that are orphaned in a couple of namespaces on RHTAP staging. This grants access to us to allow us to delete them.

Add RBAC to fix orphaned SpaceRequests on staging

---

components/monitoring/prometheus/development/dummy-service.yaml

KubeLinter output:
```
> kube-linter lint components/monitoring                                 
KubeLinter development
No lint errors found!
```
Also verified the dummy-service pod runs in a dev env and its metrics are still being collected successfully.

fix(RHTAPWATCH-456): Resolve kubelinter warnings for monitoring component

---

components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
components/pipeline-service/base/external-secrets/kustomization.yaml
components/pipeline-service/base/external-secrets/pipelines-as-code/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/pipelines-as-code-secret-deleteme.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/pipelines-as-code-namespace.yaml

After switching to OSP 1.11, PaC is deployed through the OSP operator and into the openshift-pipelines namespace. The old pipelines-as-code namespace became redundant and after some validation period we are removing it. Only the staging environment should be affected while the generated manifests for production are kept unchanged.

Remove pipelines-as-code namespace refs staging

---

components/monitoring/grafana/base/dashboards/build-service/OWNERS

Build team has automation that updates reference to grafana dashboard. In order to merge updates, we need this permissions.

Add mmorhun to build-service grafana dashboard owners

---

argo-cd-apps/base/tenants-config/tenants-config.yaml

In order for configuring components usings ArgoCD, we need to ignore changes to the
build.appstudio.openshift.io/request annotation (it's being removed by the build controller).

Ignore differences for build request annotation

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/pipelines-as-code-secret-path.yaml
components/pipeline-service/production/base/update-tekton-config-pac.yaml

We now deploy PaC through the OSP operator, so the configuration is read from the TektonConfig CR. The change has been validated in Staging. CLEANUP: pipelines-as-code-secret-path.yaml was a leftover from a previous change and it was not used.

Remove PaC ConfigMap Prod

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

Fixes the 'URL prefix is not supported' warning during the 'kustomize build'.

Remove git:: prefix from resources urls in pipeline-service

---

components/authentication/base/kustomization.yaml
components/authentication/base/rhtap-admins.yaml

The managed built-in role dedicated-admins grants access to secrets in all namespaces and we do not want that. Create a new cluster role which will used instead of dedicated-admins and that role does not have the right to list secrets.
The initial set or rules proposed in this change was put together by inspecting the dedicated-admins role, which is an aggregated cluster role. Some permissions might be missing as this is an initial proposal only and we can add missing ones as we find them.
[RHTAPSRE-168](https://issues.redhat.com//browse/RHTAPSRE-168)

Create rhtap-admins cluster role and binding

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

argocd_app_info metrics was accidentally remote-written to RHOBS which caused alerts to be fired for it. This change stops that.

fix(RHTAPWATCH-515): stop forwarding argocd metrics to rhobs

---

components/authentication/base/rhtap-admins.yaml

This is part of dedicated admin and was missing in original change[1] to replace dedicated-admins by rhtap-admins.
[RHTAPSRE-168](https://issues.redhat.com//browse/RHTAPSRE-168)
[1]616fc37f64b20c31677f91a2c7175948cadc6923

Grant rhtap-admins access to user.openshift.io resources

---

components/pipeline-service/production/base/kustomization.yaml

Includes these commits:
[allow ingress annotation overwrite](https://github.com/openshift-pipelines/pipeline-service/commit/528d66ca0ac052daddb9db844daf94535430401c)
[update operator/gitops/argocd/pipeline-service/metrics-exporter/kusto…](https://github.com/openshift-pipelines/pipeline-service/commit/532acec5d86ffe83992565bc4d4cd6913b8a29c7)
[add tekton chains grafana dashboard](https://github.com/openshift-pipelines/pipeline-service/commit/34211efea5a7e7012e5f0c283048746930517e77)
[update operator/gitops/argocd/pipeline-service/tekton-results/kustomi…](https://github.com/openshift-pipelines/pipeline-service/commit/ea3ef24d9d65ab1ea3ee7c103078472b4a2c1002)
[Remove TLS_HOSTNAME_OVERRIDE](https://github.com/openshift-pipelines/pipeline-service/commit/7d6a86c687bc0f3bc32d43d81d237f08673c2334) …

bump pipeline-service prod to the same level that has been vetted in stage

---

components/pipeline-service/production/base/pipelines-as-code-secret.yaml
components/pipeline-service/staging/base/pipelines-as-code-secret.yaml
components/sprayproxy/production/pipelines-as-code-secret.yaml
components/sprayproxy/staging/pipelines-as-code-secret.yaml

The current frequency generates a long outage of PaC when the credentials are rotated. In order to keep the disruption to a minimum, the frequency is increased to 5 minutes.

Increase the frequency of PaC secret refresh

---

argo-cd-apps/base/all-clusters/infra-deployments/enable-dvo-for-all-cluster/enable-dvo.yaml
argo-cd-apps/base/all-clusters/infra-deployments/enable-dvo-for-all-cluster/kustomization.yaml
argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
configs/enable-dvo-for-all-cluster/configure-dvo.yaml
configs/enable-dvo-for-all-cluster/install-dvo.yaml
configs/enable-dvo-for-all-cluster/kustomization.yaml

* This PR installs Deployment-Validation-Operator(DVO) in all RHTAP clusters.
* DVO works as a second level of checking on the installed CRs as kube-lint in the CI.
* This is part of the following best practices effort https://issues.redhat.com/browse/RHTAPSRE-93

Install dvo on rhtap clusters

---

argo-cd-apps/overlays/development/delete-applications.yaml
configs/enable-dvo-for-all-cluster/install-dvo.yaml

* DVO is used for doing a second level of installed CRs in the cluster.
* We need this in stage and prod, so excluding the CI and dev
*  the issues are handled with prometheus metrics.

Remove dvo from rhtap dev and CI

---

argo-cd-apps/base/host/ingresscontroller/ingresscontroller.yaml
argo-cd-apps/base/host/ingresscontroller/kustomization.yaml
argo-cd-apps/base/host/kustomization.yaml
argo-cd-apps/overlays/development/kustomization.yaml
configs/ingresscontroller/kustomization.yaml
configs/ingresscontroller/timeout-patch.yaml

Set connectionIdleTimeout for the Default Ingress Controller to 30 Minutes (Rosa Clusters) to match the Sandbox Cluster Configuration for the Default Ingress Controller.

Set connectionIdleTimeout for the Default Ingress Controller

---

argo-cd-apps/overlays/production/kustomization.yaml

- forgot to remove reference to ci-workspace

RHTAPREL-435: fix missing overlay

---

components/tekton-ci/base/repository.yaml

- allow release-service to be built as native component in RHTAP
- PipelineAsCode fails if the repo is defined in tekton-ci
- See https://github.com/redhat-appstudio/tenants-config/pull/55

RHTAPREL-435: remove release-service from tekton-ci

---

components/monitoring/grafana/base/dashboards/kustomization.yaml
components/monitoring/grafana/base/kustomization.yaml

Deploy the Grafana availability probe from o11y to infra-deployments.
To allow deploying resources to multiple namespaces from monitoring/grafana kustomization file, I had to move the namespace field from the top-level file to the dashboards directory. Other than resources inside the dashboards dir, all existing resources here already had the namespace explicitly provided, so no change was needed there elsewhere.

chore(RHTAPWATCH-518): deploy grafana probe from o11y repo

---

components/authentication/base/admin-checker/admin-checker-sa.yaml
components/authentication/base/admin-checker/cronjob.yaml
components/authentication/base/admin-checker/external-secrets/kustomization.yaml
components/authentication/base/admin-checker/external-secrets/rhtap-infra-secrets.yaml
components/authentication/base/admin-checker/kustomization.yaml
components/authentication/base/admin-checker/namespace.yaml
components/authentication/base/kustomization.yaml
components/authentication/production/kustomization.yaml
components/authentication/production/rhtap-infra-secrets-patch.yaml
components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml

Both cluster-admins and dedicated-admins groups should have no permanent members. We add people to those groups as a temporary measure only. This cron checks if there are members in those groups and if there are, send a notification to team-rhtap-infra slack private channel.
To send the notification, the cron calls a slack workflow URL which accept clusterName, userNames aand groupName as parameters. The workflow then compose a message and send it to the team-rhtap-slack channel, e.g.:
```
Hi, this is a friendly reminder to not forget to remove the following
admin access:
cluster name: https://console-openshift-console.apps.somecluster.com
group: cluster-admins
user names: hares
```
[RHTAPSRE-29](https://issues.redhat.com//browse/RHTAPSRE-29)

Add a cron job to send notification about cluster/dedicated-admins

---

components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml

To build upon the scripts constructed for RHTAPBUGS-256, being able to access the `ClusterResourceQuota` defined for secrets quota defined in https://github.com/codeready-toolchain/host-operator/blob/e0e1f34678c7da11dcb426975d887c4540e1283c/deploy/templates/nstemplatetiers/appstudio/cluster.yaml#L91-L103 is required
Then we can compare secret accounts per namespace with the quotas defined.  
Looks like existing RBAC should let is examine events around secret creation being prevented because of quota.

PLNSRVCE-1328: allow access to clusterresourcequota for SOP for per namespace secrets quota

---

components/sandbox/base/olm-restart/cronjob.yaml

* set cpu/memory requests/limits
* run container with read only file system
* run container as non root user
* Change image as using latest tag is prohibited and image used only had latest tag

Fix olm-restart kube-linter issues

---

components/authentication/base/rhtap-admins.yaml

The InternalRequest resource permits elevated access outside of the RHTAP member cluster. Only the release pipeline service account should be managing these.

Remove rights for rhtap-admin on internalrequests

---

components/authentication/base/admin-checker/cronjob.yaml

Before last OCP upgrade, the command
`oc get group "${group}" -o jsonpath='{.users}'` was returing `[]` when no users were in the group, now it returns `<nil>`. Adjust script to support both use cases.

Fix admin-checker cron on empty list of users

---

components/gitops/base/authentication/gitops-clusterroles.yaml

Temporarily enable write RBAC on `ValidatingWebhookConfiguration`, to allow us to debug the root cause of https://issues.redhat.com/browse/RHTAPBUGS-862.

managed-gitops: temporarily all component maintainer to modify WebhookConfiguration

---

components/perf-team-prometheus-reader/base/serviceaccount.yaml

Upon service account creation, both kubernetes.io/service-account-token and kubernetes.io/dockercfg secrets are created automatically, no need to create them explicitly.
In addition, this secret was causing the perf-team-prometheus-reader applications to be permanently out-of-sync.

Remove unneeded secret for perf-team-prometheus-reader

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

status label was missing in the LabelKeep list so it couldn't be accessed for the spi metric on the app-sre grafana. This change enables the status label.

fix(RHTAPWATCH-542): Add status label to the spi metric on app-sre

---

components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml

This fixes the issue on both staging and production.

ClusterLogging instance is constantly on OutOfSync status in Argo

---

components/gitops/staging/base/kustomization.yaml

Disable the temporary webhook that was enabled by https://github.com/redhat-appstudio/infra-deployments/pull/2546

managed-gitops: disable temporary Environment webhook on staging

---

components/pipeline-service/production/base/kustomization.yaml

Includes:
[fix issues of pipeline-service test](https://github.com/openshift-pipelines/pipeline-service/commit/81454e7a3c38fc1b1f145b5cb1d537417e195192)
[update operator/gitops/argocd/pipeline-service/metrics-exporter/kusto…](https://github.com/openshift-pipelines/pipeline-service/commit/0dec9dbdbef0ac6cc33ce2803b7ee87d43178826)
[fixed error that unable to find a match 'python3-devel-3.11.5'](https://github.com/openshift-pipelines/pipeline-service/commit/8757ada7c033b21dc59720267d2643a9c8c08b86)
[Fix kube-linter issues](https://github.com/openshift-pipelines/pipeline-service/commit/b707aab8929f8a0a766f69132907a56823a6c7fb)
[Optimizing the process of ROSA destroying](https://github.com/openshift-pipelines/pipeline-service/commit/e6c4eb75235c23243961c047fac83c0993b7eb3a)
other that the …

bump pipeilne-service prod to same level as stage

---

components/gitops/staging/base/kustomization.yaml

#2560 was delivered to staging to verify the functionality, however, there are additional errors that are occuring, so reverting to fix.
This reverts commit 89971ca4b6fa1f8ab872c8b7e5fa02d797d4c89d.

managed-gitops: Revert #2560 from staging, "update components/gitops/staging/base/kustomization.yaml (#2560)"

---

components/tekton-ci/base/repository.yaml

- removed PaC repo for internal-services so the GH repo can be onboarded to RHTAP

chore(RHTAPREL-435): remove internal-services PaC repo

---

components/authentication/base/rhtap-admins.yaml

1. oadp.openshift.io (dataprotectionapplications, cloudstorages)
2. velero.io (backups, restores, schedules)

Added permissions for the following apiGroups

---

components/sprayproxy/staging/add-backends.yml
components/sprayproxy/staging/add-webhook-secret.yaml
components/sprayproxy/staging/change-backends.yaml
components/sprayproxy/staging/change-webhook-secret.yaml
components/sprayproxy/staging/kustomization.yaml

GH_APP_WEBHOOK_SECRET is defined in the config at the repo level so using a "patch add" was resulting in duplicated variable:
```
spec:
template:
spec:
containers:
- args:
env:
- name: GH_APP_WEBHOOK_SECRET
- name: GH_APP_WEBHOOK_SECRET
valueFrom:
secretKeyRef:
key: webhook.secret
name: pipelines-as-code-secret
```
Instead, patch the varialble using a strategic merge. In addition to fix the duplicate, this methodology do not rely on container or variable indices so also change the SPRAYPROXY_SERVER_BACKEND to use same mechanism for robusness and consistency reasons.

Fix staging sprayproxy duplicated GH_APP_WEBHOOK_SECRET

---

components/sprayproxy/production/add-backends.yml
components/sprayproxy/production/add-webhook-secret.yaml
components/sprayproxy/production/change-backends.yaml
components/sprayproxy/production/change-webhook-secret.yaml
components/sprayproxy/production/kustomization.yaml

GH_APP_WEBHOOK_SECRET is defined in the config at the repo level so using a "patch add" was resulting in duplicated variable:
```
spec:
template:
spec:
containers:
- args:
env:
- name: GH_APP_WEBHOOK_SECRET
- name: GH_APP_WEBHOOK_SECRET
valueFrom:
secretKeyRef:
key: webhook.secret
name: pipelines-as-code-secret
```
Instead, patch the variable using a strategic merge. In addition to fix the duplicate, this methodology do not rely on container or variable indices so also change the SPRAYPROXY_SERVER_BACKEND to use same mechanism for robustness and consistency reasons.
[PLNSRVCE-1477](https://issues.redhat.com//browse/PLNSRVCE-1477)

Fix prd sprayproxy duplicated GH_APP_WEBHOOK_SECRET

---

components/pipeline-service/production/base/kustomization.yaml

Includes 
[Enable completed_run_grace_period for tekton-results](https://github.com/openshift-pipelines/pipeline-service/commit/b2626be4fc649b5184b8bf3e661bbc46319c884b)
[Fix TektonConfig](https://github.com/openshift-pipelines/pipeline-service/commit/db423b0030f4a0e886fdf7ce7f81e3c95e08d20e)
[Optimizing the process of ROSA provisioning in CI](https://github.com/openshift-pipelines/pipeline-service/commit/f74b260c32715977dcc7acc20a3b28e8cbac1454)
[Set Set cpu/memory requests/limits for tekton-results-api init contai…](https://github.com/openshift-pipelines/pipeline-service/commit/47c14a4acc7b99647ac7fabfef201af337725579)
[Set cpu/memory requests/limits for chains-secret-generation container](https://github.com/openshift-pipelines/pipeline-service/commit/7daba2740a9be1b2d8fc673a5dc7d35f57ba …

bump pipeline-service prod to current stage level

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Since the metrics pipeline service uses for its app sre alerts originate from the openshift-pipelines namespace, they are considered in-cluster prometheus metrics and must be officially declared to be scraped by app sre grafana
@redhat-appstudio/pipeline-service @amisstea  fyi / ptal

PLNSRVCE-1470: add the metrics/labels pipeline service wants scraped by app sre grafana

---

components/sandbox/base/kustomization.yaml
components/sandbox/base/monitoring/prometheus-network-policy.yaml

add network policy to allow traffic from appstudio-monitoring to toolchain-host-operator

add network policy for proxy-metrics

---

components/perf-team-prometheus-reader/base/kustomization.yaml
components/perf-team-prometheus-reader/base/perf-team.yaml

This is for Perf&Scale team to be able to read secret created for the service account.

feat: Adding perf team that maintains perf-team-prometheus-reader NS

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Minor fix to https://github.com/redhat-appstudio/infra-deployments/pull/2633
the namespace in the regex refers to the namespace label of our metrics, which is where the pipelinerun is running, not where the metrics-exporter or tekton controller is running
so we are trying to include all tenants plus the `tekton-ci` namespace where all of appstudio's CI run on in the RHTAP prod cluster

PLNSRVCE-1470: minor fix to add the metrics/labels pipeline service wants scraped by app sre

---

components/pipeline-service/production/base/kustomization.yaml

* Fix pac-secret-reaper CronJob
* Update operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml
* Create a CronJob to fix [RHTAPBUGS-256](https://issues.redhat.com//browse/RHTAPBUGS-256)
* optimize alert query; revert incorrect millisecond to second conversion fix
* remove panel using faulty upstream latency metric
* fix missing millisecond to second conversion in grafana dashboard execute overhead query
* Set cpu/memory requests/limits for tekton-results-api/api

Update Pipeline Service in production

---

components/monitoring/prometheus/README.md

Adding a new section to the monitoring stack documentation that should explain why metrics or labels might be missing from AppSRE Grafana and how to troubleshoot that.

doc(RHTAPWATCH-554): troubleshooting missing metrics and labels

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

The namespace part of the regex for pipelinerun metrics in the federation servicemonitor was misconfigured.
Removing the namespace limitation as we should be good without it.

fix(RHTAPWATCH-561): remove servicemonitor namespace limitations

---

argo-cd-apps/base/tenants-config/tenants-config.yaml

- additional label required.
- tell ArgoCD to ignore differences in ReleasePlan for the label /metadata/labels/release.appstudio.openshift.io~standing-attribution

feat(RHTAPREL-675): ignore differences in releaseplans (#2684)

---

components/multi-platform-controller/production/host-config.yaml

OOM kills were happening with t4g.small, changing to a larger VM for more memory.
Addresses: https://issues.redhat.com/browse/RHTAPBUGS-953

Bump vm size for ephemeral arm multi-platform builds

---

argo-cd-apps/base/tenants-config/tenants-config.yaml

By default, Argo CD uses the ignoreDifferences config just for computing the diff between the live and desired state which defines if the application is synced or not. However during the sync stage, the desired state is applied as-is.
The patch is calculated using a 3-way-merge between the live state the desired state and the last-applied-configuration annotation. This sometimes leads to an undesired results. This behavior can be changed by setting the RespectIgnoreDifferences=true sync option.
Taken from https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/

tell ArgoCD to respect the ignoreDifferences

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

This PR is to add few new metrics for Gitops-Service monitoring. Few metrics we need for adding new panels in [RHTAP SLO dashboards](https://grafana.stage.devshift.net/d/rhtap-slos/rhtap-slos?orgId=1&var-datasource=rhtap-observatorium-production&from=now-28d&to=now&refresh=1h) are missing, hence updating [MonitoringStack configurations](https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml) as mentioned in this [doc](https://github.com/redhat-appstudio/infra-deployments/tree/main/components/monitoring/prometheus#troubleshooting-missing-metrics-and-labels). 
https://issues.redhat.com/browse/GITOPSRVCE-751

[Managed-Gitops] Add metrics.

---

argo-cd-apps/base/member/infra-deployments/backup/backup.yaml

The original change introducing backup component was using clusterDir which is not set. Instead of defining the clusterDir for each possible cluster as it is done in other places:
```
- list:
elements:
- nameNormalized: stone-stg-m01
values.clusterDir: stone-stg-m01
- nameNormalized: stone-stg-rh01
values.clusterDir: stone-stg-rh01
- nameNormalized: stone-prd-m01
values.clusterDir: stone-prd-m01
- nameNormalized: stone-prd-rh01
values.clusterDir: stone-prd-rh01
```
Simply use the normalized name of the cluster which correspond to the folder structure within the backup component. This is a better solution as we do not need to hardcode the cluster names in the backup component.
[RHTAPSRE-215](https://issues.redhat.com//browse/RHTAPSRE-215)

Fix backup application path

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/development/metrics-exporter-trace.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/metrics-exporter-trace.yaml

I want some detail on our new consolidated alert metric as I compare it with the existing multi metric alert query
Sorted out the gitops / kustomize approach here after https://github.com/openshift-pipelines/pipeline-service/pull/860 with @Roming22 
Also tested against a personally provisioned cluster with boostrap-cluster.sh preview -t

turn on metrics exporter trace in dev/stage

---

README.md
docs/development/deployment.md
hack/preview-template.env

The instructions present as comments in the preview.env file are not
sufficient for a new member trying to set up their development
environment for the first time.
Add a section in the documentation that explains what needs to be set in
preview.env and how to set up the prerequisites.
\+ instructions for how to verify that your deployment works
\+ instructions for testing your code changes

Improve development documentation

---

components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml

Build-service now supports the Tekton v1 style of pipelineRefs, see https://github.com/redhat-appstudio/book/pull/146.

Update BuildPipelineSelector to new syntax

---

components/pipeline-service/production/base/kustomization.yaml

Brings into prod these commits which are in staging as of this PR's creation:
[update scheduled alert panel to only use successful pipelineruns with…](https://github.com/openshift-pipelines/pipeline-service/commit/cad76877d5abd32d1c9f7943a928ad2e07bcf9f1)
[fix threshold color for 2 alert panels](https://github.com/openshift-pipelines/pipeline-service/commit/f18c544fcc483663acdb8928a343934be8252022)
[fix the issue of rosa cli by upgrading to 1.2.29](https://github.com/openshift-pipelines/pipeline-service/commit/4fc1aa6e9fa0bae3b0f77e307d313cab9577430a)
[Fix images definitions](https://github.com/openshift-pipelines/pipeline-service/commit/5b5a32f929af2e709027c1546d847303b97e7a46)
[Update base images SHA in Dockerfiles](https://github.com/openshift-pipelines/pipeline-service/commit/45a81b8c1 …

bump prod pipeline service level to what we have in staging

---

components/image-controller/base/external-secrets/quaytoken.yaml

Quay.io doesn't allow preserving old token when new one is created. To avoid long outages, setting ExternalSecret refresh time to 15 minutes.

Set Image Controller quay token refresh interval to 15 minutes

---

components/sandbox/base/kustomization.yaml
components/sandbox/base/rbac/edit-secrets.yaml
components/sandbox/base/rbac/kustomization.yaml
components/sandbox/toolchain-member-operator/base/rbac/kustomization.yaml
components/sandbox/toolchain-member-operator/base/rbac/register-cluster-extra-member-permissions.yaml

move register cluster extra permissions from sandbox-sre so all necessary manifests are applied via ArgoCD and not through sandbox-cli

move register cluster extra permissions from sandbox-sre

---

hack/preview.sh

Fixes the wrong image name for remote-secret e2e job setup.
Context: https://issues.redhat.com/browse/SVPI-684

Fix remote-secret image name

---

argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
argo-cd-apps/base/member/infra-deployments/backup/kustomization.yaml

The is no point using a merge generator to merge cluster with an empty list generators. Remove the list generator as it is empty anyway.

Simplify backup ApplicationSet generators

---

argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
argo-cd-apps/base/member/infra-deployments/backup/kustomization.yaml

Reverts redhat-appstudio/infra-deployments#2793
This changed worked on staging but does not in production, let's revert for now and I will reopen another PR with same change including fix for production.

Revert "Simplify backup ApplicationSet generators"

---

components/build-templates/production/e2e-quay-push-secret.yaml
components/build-templates/production/kustomization.yaml
components/build-templates/staging/e2e-quay-push-secret.yaml
components/build-templates/staging/kustomization.yaml

There is a quay-push-secret in the build-templates-e2e namespace, but
nobody knows how it got there. The other quay-push-secret (the one in
tekton-ci) got rotated and now the one in build-templates-e2e is
invalid.
Attempt to fix the issue by copy-pasting the quay-push-secret external
secret from tekton-ci to build-templates-e2e.

Add quay-push-secret to build-templates-e2e namespace in stage and prod

---

components/sandbox/base/rbac/view-spacebindingrequests.yaml

I need to investigate SpaceBindingRequests CRs on PROD and STAGE clusters. 
Specifically right now for the spacebindingrequests migration controller task : https://issues.redhat.com/browse/ASC-432 , in order to double check any failed SpaceBindingRequest object.

enable mfrancisc to view spacebindingrequests 

---

components/build-templates/base/e2e/role.yaml
components/build-templates/base/e2e/rolebinding.yaml

Currently the namespace does not have any admins. Previously it was managed manually with the role of cluster wide admin. We need people with admin access in the cluster to setup the secrets there - they weren't managed by infra-deployments configuration before but only manually, so we don't the names of the secrets currently in place.

Add admins for build-templates-e2e namespace

---

components/backup/base/oadp/dpa.yaml
components/backup/base/oadp/install-oadp.yaml
components/backup/base/oadp/kustomization.yaml
components/backup/staging/stone-stg-rh01/dpa-bucket-patch.yaml
components/backup/staging/stone-stg-rh01/dpa-kmskeyid-patch.yaml
components/backup/staging/stone-stg-rh01/kustomization.yaml

This change is installing oadp operator, configuring the DataProtectionApplication to use the proper credentials and aws bucket in stg-rh01 cluster.
A backup schedule will be created in a follow up change. Once this  change is in, we will test backup once manually before creating a schedule.

Install oadp operator in stg-rh01 cluster

---

components/backup/base/external-secret.yaml
components/backup/base/oadp/install-oadp.yaml

Make sure backup components can install without having to intervene. ArgoCD tried to create dpa before the oadp was installed causing the whole backup application to be stuck as syncing.
Set sync-wave of the install in the following order: OperatorGroup, Subscription, ExternalSecret and then DataProtectionApplication.

Fix installation order of backup components

---

components/integration/base/external-secrets/kustomization.yaml
components/integration/base/external-secrets/pipelines-as-code-secret.yaml
components/integration/staging/kustomization.yaml
hack/build/setup-pac-integration.sh

* create pipelines-as-code-secret under integration-service NS to be used by integration test pipeline, I copy the vault path from https://github.com/redhat-appstudio/infra-deployments/tree/main/components/pipeline-service because we decide to use the vault from pipeline-service team
* add base/development/staging/production folder under components/integration
* update argo-cd-apps/base/member/integration/integration.yaml to get value from environement

fix(STONEINTG-608): create secret for pac used by integration-service

---

components/build-templates/production/e2e-serviceaccount.yaml
components/build-templates/production/kustomization.yaml
components/build-templates/staging/e2e-serviceaccount.yaml
components/build-templates/staging/kustomization.yaml

1. make sure the appstudio-pipeline service account in the build-templates component goes to the build-templates-e2e namespace
2. link the existing registry.redhat.io secret to ^ serviceaccount

build-templates-e2e: set service account namespace

---

components/monitoring/grafana/base/kustomization.yaml

Deploy the grafana availability exporter from o11y to infra-deployments.
Signed-off-by: Homaja Marisetty <hmariset@redhat.com>

chore(RHTAPWATCH-580): deploy prometheus exporter from o11y

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

We have combined the 2 seperate histograms used each for our execution and overhead alert queries into one metric.  This reduces the number metric queries required for our alerts by half, and also allows us to filter pipelieruns that incorrectly corrupt our overall averages (because they only take a few seconds to complete)
Note - I will remove the original metrics we added for the pipeline-service after the app sre grafana panels have been updated in both app sre stage and prod.

PLNSRVCE-1537: add new combined/filtered pipeline service alert metrics to app sre in-cluster prometheus list

---

components/build-templates/production/e2e-serviceaccount.yaml

Having it in imagePullSecrets is not enough, it was not discovered in the build-task.

Link the registry secret as a mountable secret

---

components/backup/base/oadp/install-oadp.yaml

Version 1.3.0 was released so upgrade to that version since we did not start to take backups. Let's upgrade now and test backup with latest version.

Upgrade OADP operator to channel 1.3

---

components/backup/base/external-secret.yaml
components/backup/base/oadp/backup-tenants-schedule.yaml
components/backup/base/oadp/dpa.yaml
components/backup/base/oadp/kustomization.yaml

Is it not supported to use wildcards in the includedNamespaces so exclude the namespaces we do not want instead. That way, we might backup more than needed but that is better than less.
Schedule the backup twicee a day, at 1:30 UTC which is outside of working hours from GMT-8(5:30PM) to 
GMT+5:30(7:00AM) and at 13:30 UTC which is 12 hours after first backup to minimise work loss in case on an
incident.
Move the ExternalSecret to the -2 sync wave, since it can be done at same time operator is being installed. Move DPA to -1 sync wave as we need this to be created before backup schedule.

Add backup schedule for tenants namespaces

---

components/backup/base/oadp/backup-tenants-schedule.yaml

This section is updated by the application, we should not have it in the object definition.

Remove status section from backup schedule

---

components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml

In order to invesitate issues around bundle processing, we need to be able to inspect the API from the resolution.tekton.dev API group like ResolutionRequests
Otherwise you get
```
gmontero ~ $ oc get resolutionrequests
Error from server (Forbidden): resolutionrequests.resolution.tekton.dev is forbidden: User "gabemontero" cannot list resource "resolutionrequests" in API group "resolution.tekton.dev" in the namespace "tekton-ci"
gmontero ~ $ 
```

add resolution.tekton.dev to pipeline service sre permissions

---

components/backup/base/oadp/backup-tenants-schedule.yaml

Without the OwnerReferences in the backup created by the schedule, ArgoCD was deleting the backup object as they were created.

Add owner references to backup created by schedule

---

components/tekton-ci/base/repository.yaml

This is causing problems as we onboard EC to RHTAP. RHTAP is saying "Git repository is already handled by Pipelines as Code" and refusing to create the custom build pipeline PR.
IIUC the existing PaC pipelines in this repo were experimental and should not be mission critical. The tekton bundles being created by those are also pushed by the GitHub actions workflow.
Ref: [EC-289](https://issues.redhat.com/browse/EC-289)

Remove PaC config for ec-cli repo

---

components/tekton-ci/base/external-secrets/clair-in-ci-db-github-token.yaml

Migrating clair-in-ci-db github token into separate key withint integration-service away from build-service namespace.

fix(STONEINTG-694): tekton-ci - clair-in-ci-db token

---

components/tekton-ci/base/external-secrets/kustomization.yaml

Clair-in-ci-db secrets is not creeated due the error in kustomize

fix(STONEINTG-694): fix broken kustomize for tekton-ci

---

components/authentication/base/rhtap-admins.yaml

This is needed sometimes e.g. when a finalizer is stuck and preventing deletion of the PipelineRun.
```
oc patch <pipeline-run> --type merge -p '{"metadata":{"finalizers":null}}'
```

Allow RHTAP admins to patch PipelineRun

---

.tekton/pipeline/rhtap-staging-e2e.yaml
argo-cd-apps/base/promotion/kustomization.yaml
argo-cd-apps/base/promotion/promotion.yaml
argo-cd-apps/overlays/staging/kustomization.yaml
components/promotion/base/appstudio-gitops-service-argocd-argocd-application-controller-clusterrolebinding.yaml
components/promotion/base/appstudio-pipelines-runner-rolebinding.yaml
components/promotion/base/external-secrets/infra-deployments-pr-creator.yaml
components/promotion/base/external-secrets/kustomization.yaml
components/promotion/base/external-secrets/stage-test-e2e.yaml
components/promotion/base/kustomization.yaml
components/promotion/base/namespace.yaml
components/promotion/base/promotion-maintainers-rb.yaml
components/promotion/base/repository.yaml
components/promotion/base/serviceaccount.yaml
components/promotion/staging/stone-stg-rh01/infra-deployments-pr-creator.yaml
components/promotion/staging/stone-stg-rh01/kustomization.yaml
components/promotion/staging/stone-stg-rh01/stage-test-e2e.yaml

- This configuration is meant for running the rhtap stage promotion pipeline added via [PR](https://github.com/redhat-appstudio/infra-deployments/pull/2383)

Configure RHTAP stage promotion testing setup

---

argo-cd-apps/base/promotion/promotion.yaml

The Promotion applicationset was creating one application per cluster, including the in-cluster which is control plane cluster.
Since we only want it on stone-stg-rh01, add a selector in the applicationset to select cluster with the
"appstudio.redhat.com/rh-member-cluster" label, which only stone-stg-rh01 has.

Deploy promotion application only on stg-rh01

---

components/cluster-secret-store/staging/kustomization.yaml
components/cluster-secret-store/staging/rhtap-promotion-staging-patch.yaml

In 37533f6aee79b78dea775ce2b4ed16813b93818e, promotion component was created and 2 external secrets added in the rhtap-promotion-staging namespace.
These external secrets were not able to get value from the secret store because secret store access is limited to a list of namespaces.
Add the rhtap-promotion-staging namespace in the list of allowed ones using a patch only applied in staging, as we do not want that in production overlay.

Grant access to secret store from rhtap-promotion-staging namespace

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Apparently, the metric that I need is not getting forwarded from the rhtap clusters to rhobs
I chatted with @yftacherzog about this and he's been working with me regarding my alert rules too.
Jira Ticket
https://issues.redhat.com/browse/GITOPSRVCE-750

GITOPSRVCE-750: Add metric

---

argo-cd-apps/overlays/production/kustomization.yaml

Without this, the productions applications were deployed from the staging folder.

Apply prd overlay patch to both segment-bridge applications

---

components/monitoring/grafana/base/dashboards/integration/kustomization.yaml

SnapshotInvalidTotal metric removed from integration-service
grafana panel "Snapshot Attempts Invalid Total" removed

fix(STONEINTG-654): remove SnapshotinvalidTotal metric

---

components/enterprise-contract/download-service.yaml
components/enterprise-contract/kustomization.yaml

With this the ec CLI referenced from the EC Tekton Task bundle, i.e. the `verify_ec_task_bundle` key of the `ec-defaults` ConfigMap, will be used to download all `ec` binaries from all images in the multi-arch ec CLI image, feed to a emptyDir volume and served via Apache HTTPD running on the cluster. The URL those will be propagated to the `ConsoleCLIDownload` resource, which in turn will make those downloads available on the OpenShift Console.
Ref: https://issues.redhat.com/browse/EC-278

Add ec CLI downloads to OpenShift Console

---

.tekton/tasks/get-git-token.yaml

Error:
```
RHTAP Staging / RHTAP Staging / rhtap-staging-e2e-
Failure snippet:
task check-merge-label has the status "Failed":
--git-owner GIT_OWNER --git-repo GIT_REPO --pr-number
PR_NUMBER
check-pr-label.py: error: argument --token/-t: expected one argument
```

Fix staging get github token

---

components/build-service/README.md
components/build-service/base/external-secrets/pipelines-as-code-secret.yaml
components/build-service/production/pipelines-as-code-secret-patch.yaml

both services share the same secret, it should be loaded from the pipeline service vault now.
https://issues.redhat.com/browse/STONEBLD-1893

Use PaC secret from pipeline service vault

---

components/release/base/release-pipeline-resources-clusterrole.yaml

ReleaseStrategies are deprecated so it needs to be removed from the Role. In addition, we need to delete InternalRequests. The Role contains now that verb for this resource.

fix: update release role

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml

* [Update binaries](https://github.com/openshift-pipelines/pipeline-service/commit/e72b74cea4b8bf3e49264de1b44682a49a3eba9f)
* [Set cpu/memory requests/limits for tekton-results-watcher/watcher](https://github.com/openshift-pipelines/pipeline-service/commit/e450e96a7401cdf16c58d9f2395b5bbd1f8d6e58)
* [Fix kube-linter issues for pac-secret-reaper CronJob](https://github.com/openshift-pipelines/pipeline-service/commit/9d4f80facd669d7bd0bda4e030be4978e2859995)
* [Use namespace best practices for kustomize](https://github.com/openshift-pipelines/pipeline-service/commit/6735c1e5a7733e506db4770ab06c65804d2ec457)
* [update operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml](https://github.com/openshift-pipelines/pipeline-service/commit/8604ea7b7a9605a66daa68ebbe08643d44e94a …

upgrade Pipeline Service in Prod

---

hack/preview.sh

This PR is to fix bug [RHTAPBUGS-903](https://issues.redhat.com/browse/RHTAPBUGS-903). Sometimes Tekton CRDs need a few mins to be ready, this PR is to make sure all of Tekton CRDs to be ready before running tests.

wait for Tekton CRDs to be ready

---

components/build-templates/production/e2e-registry-redhat-io-pull-secret.yaml
components/build-templates/production/e2e-serviceaccount.yaml
components/build-templates/production/kustomization.yaml
components/build-templates/staging/e2e-serviceaccount.yaml

[STONEBLD-1999](https://issues.redhat.com//browse/STONEBLD-1999)
- New service account rhtap-e2e-tests-pull-secret is created in customer
portal Registry Service Accounts management page. This service account
contains the token required for authentication by registry.redhat.io.
- Secret registry-redhat-io-pull-secret is created under vault path
production/build/build-templates-e2e. Its content is copied from the
service account manually.
- The token is syned to production cluster via an ExternalSecret
resource.
- ServiceAccount is updated to link the token.
- Since e2e-tests runs on production cluster only, all these changes
apply to production only. The ServiceAccount for staging is updated to
not link the secret.

STONEBLD-1999: use new registry.redhat.io secret for e2e-tests

---

components/build-service/OWNERS
components/monitoring/grafana/base/dashboards/build-service/OWNERS

Update the build service dashboards to match the build-service owners. At the moment only mmorhun can merge build service update PRs because the dashboard is also updated.

Update build-service dashboard owners

---

components/tekton-ci/base/repository.yaml

Removed o11y component which is using the tekton-ci facility from RHTAP to enable custom build pipeline.

chore(RHTAPWATCH-579): Remove o11y repository from infra-deployments

---

argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
components/build-service/staging/base/kustomization.yaml
components/build-service/staging/stone-stage-p01/kustomization.yaml
components/build-service/staging/stone-stage-p01/pipelines-as-code-secret-path.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/resources/pipelines-as-code-secret-path.yaml

The internal cluster uses a different webhook url, so it needs its own Github app.

RHTAPSRE-292: Add Github app for the internal cluster

---

components/ui/base/proxy/proxy.yaml

nginx requires some directories to be writeable, and because the container's file system is readonly, we need to mount a writeable volume.

RHTAPSRE-281: Mount empty dirs to the ui proxy

---

components/ui/base/proxy/proxy.yaml

Apparently, the nginx process doesn't create the "nginx" directory under /var/log, so mount the volume to /var/log/nginx for solving it.

RHTAPSRE-281: Mount nginx logs volume

---

.github/workflows/kube-linter.yaml

Now that all issues have been fixed, fail the check if new kube-linter issues are found.
[RHTAPSRE-139](https://issues.redhat.com//browse/RHTAPSRE-139)

Fail kube-linter check if issues are found

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

There seems to be a critical bug in Tekton Results when check_owner is set to false.

Revert pipeline-service

---

components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This is a proper rollback of the check_owner issue.

Update pipeline-service in prd/stg

---

components/authentication/base/rhtap-admins.yaml

As RHTAP admin I'm trying to update the rolebindings in toolchain-host-operator, but getting a permissions error:
```
....
rolebindings.rbac.authorization.k8s.io "install-operator-sandbox-sre-cd-host" is forbidden: User "mfrancisc" cannot update resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "toolchain-host-operator"
```

add update verb for rolebinding resources

---

components/build-service/staging/stone-stage-p01/add-webhook-target-patch.yaml
components/build-service/staging/stone-stage-p01/kustomization.yaml

The internal cluster fetches webhook events through the go-smee server, thus the Webhook url target should be for the go-smee server.

RHTAP-2116: Webhook target for the internal cluster

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml
components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
components/monitoring/logging/base/install-logging-operator.yaml
components/monitoring/logging/base/logging-operator-prerequisite/kustomization.yaml
components/monitoring/logging/base/logging-operator-prerequisite/namespace.yaml
components/monitoring/logging/base/logging-operator-prerequisite/operatorgroup.yaml
components/monitoring/logging/production/base/kustomization.yaml
components/monitoring/logging/staging/base/kustomization.yaml
components/monitoring/logging/staging/stone-stage-p01/kustomization.yaml

All the clusters we had so far were ROSA classic, i.e. control plane nodes part of the cluster nodes. On those clusters, openshift-logging namespace and operatorgroup are already created and managed by hive.
The new stone-stage-p01 is a ROSA HCP(Hosted Control Plane) cluster and on those, the openshift-logging namespace and operatorgroup are not created/managed.
Move staging and production kustomize files into nested base folders and change logging argocd application to use base as default clusterDir. On stone-stage-p01, override the cluster dir to point to staging/stone-stage-p01 which include the base plus namespace and operatorgroup.
Also set argocd syn waves of a few resources to make sure the are created in the right order.
[RHTAPWATCH-695](https://issues.redhat.com//browse/RHTAPWATCH …

Create logging namespace and operatorgroup on stone-stage-p01

---

components/tekton-ci/base/repository.yaml

In EC-331, the EC team is moving all of the EC builds to their own tenant, rhtap-contract.

Remove EC components from tekton-ci

---

components/enterprise-contract/kustomization.yaml

The enterprise-contract-controller repository produces a container image. This is meant to run a Kubernetes controller. However, the controller is never deployed in konflux. (It is actually not deployed anywhere!). The repo is solely used to host the EC CRDs.
This commit removes references to the unused controller.

Remove unused controller image reference

---

components/pipeline-service/development/update-tekton-config-performance.yaml
components/pipeline-service/staging/base/update-tekton-config-performance.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

The ratio between replicas and buckets is based on the findings from the joint openshift-pipelines and RHTAP performance team endeavor around HA and continual openshift-pipelines performance analysis.

PLNSRVCE-1525: bump tekton pipeline controller to 2 replicas and 4 buckets

---

components/monitoring/logging/development/kustomization.yaml

This overlay is empty for the moment so add empty resources otherwise kustomize build was failing and preventing us to setup a kustomize build as a pre-merge check.
[RHTAPSRE-309](https://issues.redhat.com//browse/RHTAPSRE-309)

Fix kustomize build of logging development overlay

---

argo-cd-apps/overlays/staging-downstream/kustomization.yaml
argo-cd-apps/overlays/staging-downstream/staging-downstream-overlay-patch.yaml
components/multi-platform-controller/staging-downstream/external-secrets.yaml
components/multi-platform-controller/staging-downstream/host-config.yaml
components/multi-platform-controller/staging-downstream/kustomization.yaml

Add 2 vms (arm and amd64) that will be used by the multi-arch controller.
ATM, add static vms, until we will decide which account should host dynamically created vms.

RHTAPSRE-340: Add build vms to the internal env

---

components/smee/staging/route.yaml

FIlter traffic tp the Gosmee server so that only traffic from GitHub, GitLab and our internal clusters will be accepted.

feat(RHTAPWATCH-660): IP filter for smee sever

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml

updated the prod base kustomization.yaml, followed by running 
`for dir in stone-*; do cd $dir/resources && kustomize build . > ../deploy.yaml; cd -; done`
from the `components/pipeline-service/production` subdir
Included changes:
- [expose controller HA fields for possible gitops override](https://github.com/openshift-pipelines/pipeline-service/commit/de5809f2532b129640c4a00aae76a363be67dcbe)
- [Update binaries](https://github.com/openshift-pipelines/pipeline-service/commit/69ec92caf434740355b65fa29386f128822b0457)
- [Disable OSP pruner](https://github.com/openshift-pipelines/pipeline-service/commit/8074097f59e32ef8a91d8e8292420e3877b6199f)
- [Fix update of ROSA cli version](https://github.com/openshift-pipelines/pipeline-service/commit/00b73c982d4ad1969cc73ad14f50442b690e49ed)
- [update …

bump pipeline servicve prod to current staging level

---

components/sandbox/toolchain-host-operator/development/kustomization.yaml
components/sandbox/toolchain-member-operator/development/kustomization.yaml

This overlay is empty for the moment so add empty resources otherwise kustomize build was failing and preventing us to setup a kustomize build as a pre-merge check.
[RHTAPSRE-309](https://issues.redhat.com//browse/RHTAPSRE-309)

Fix kustomize build of toolchain development overlay

---

components/smee/staging/route.yaml

The IP filter configuration string for the Smee server included a trailing newline that caused it to be ignored.
Also adding comments to warn future developers touching this.

fix(RHTAPWATCH-660): Smee server IP filter fix

---

components/integration/base/delete-snapshots.yaml
components/integration/base/kustomization.yaml

Users are increasingly running into issues with their snapshot quota and the integration team is currently best suited too recognize these issues as they occur.  Giving the integration team permission to delete snapshots across all namespaces will decrease customer complaints and prevent them from having to recognize and resolve the issue themselves. Once Snapshot GC has been implemented this permmission can be revoked.

feat: Allow integration team to delete snapshots

---

components/pipeline-service/staging/base/greedy-pruner.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Remove OSP pruner configuration

---

components/pipeline-service/production/base/bump-exporter-mem.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml

With the increase of activity in rhtap prod and where the controller-runtime based metrics exporter starts at with its need to watch all pipelineruns and taskruns, 512Mi is no longer sufficient.  I do see regularly GC occurring, but sufficient spikes lead to OOM restarts of some frequency.  This is also in line with other controllers which have to listen for all pipelinerun/taskruns in every namespace.

bump exporter mem limit in prod

---

components/tekton-ci/base/repository.yaml

As part of https://issues.redhat.com/browse/DEVHAS-588, the HAS team is migrating its builds to the rhtap-has tenant

Remove application-service from tekton-ci

---

components/pipeline-service/production/base/update-tekton-config-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml

This copies the updates that have been running in staging since https://github.com/redhat-appstudio/infra-deployments/pull/3051 merged. The ratio between replicas and buckets is based on the findings from the joint openshift-pipelines and RHTAP performance team endeavor around HA and continual openshift-pipelines performance analysis.  This also involves running 'for dir in stone-*; do cd $dir/resources && kustomize build . > ../deploy.yaml; cd -; done' from the 'components/pipeline-service/production' subdirectory

PLNSRVCE-1525:  bump prod tekton pipeline controller to 2 replicas and 4 buckets

---

.github/workflows/kube-linter.yaml

The kustomize build step was considered a success even if kustomize build failed. Change implementation to fail the step if at least one of kustomize build commands fail.
Exclude the k-components from the search as some of them are used for sharing patches between overlays. Those components do not build on their own and they get built through the included overlays.
Instead of using a for loop as before, change implementation to use xargs so kustomize build command can run in parallel and print error message so we know which folder did not build. This brings down the execution time from 3 minutes to 1.
[RHTAPSRE-309](https://issues.redhat.com//browse/RHTAPSRE-309)

Fail kustomize build step on failure

---

components/pipeline-service/production/base/bump-results-watcher-mem.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml

Over the course of about a week we have seen the results watcher on prd-rh01  have to OOM about once a day.  During the day, we have observed garbage collection, and seen mem usage go up and down some.  But as prd-rh01 is our most used cluster, it is the one that has bumped into the 2Gi limit too often.  The other 3 clusters, while still having activity, have not observed leak behavior.  We have engaged upstream with some profiling data from our personal clusters to see if there is some sort of edge case.  But the simpler step first step to bump prod, and then continue to monitor, and see if we have just hit a new limit with more onboarding.
To simplify the change, and in case we see more uptick in prd-m01, I'm updating both prods.

bump results watcher watcher container to 3Gi

---

components/sandbox/toolchain-host-operator/base/monitoring/kustomization.yaml
components/sandbox/toolchain-host-operator/base/monitoring/prometheus-network-policy.yaml

Try to fix issue with ServiceMonitor not being available

enable UWM to scrape toolchain-host-operator namespace

---

components/dev-sso/keycloak-realm.yaml

The user sign-up in HAC tests started to fail due to the new scope added [here](https://issues.redhat.com/browse/RHCLOUD-29135). Adding a new scope also to the keycloak.
https://issues.redhat.com/browse/HAC-5624

fix(test): add api.console scope to keycloak

---

components/gitops/staging/stone-stg-m01/gitops-service-postgres-rds-config-path.yaml
components/gitops/staging/stone-stg-rh01/gitops-service-postgres-rds-config-path.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-s3-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-s3-secret-path.yaml

The RDS and S3 resources moved from cluster app-sre-stage-01 to appsres07ue1. The databases and bucket were not re-created, they are the same on AWS side. The only thing that change is the location of the secrets we extract as the secrets names include the name of the cluster it is created on.
[RHTAPSRE-310](https://issues.redhat.com//browse/RHTAPSRE-310)

Extract Gitops and plnsvc app-sre secrets from new cluster

---

components/integration/base/delete-snapshots.yaml

In 07dfa001f6f573ab9025496e0fa9bd83c1bb499b, this ClusterRole was added but the apiVersion should have been `rbac.authorization.k8s.io/v1`, not `authorization.openshift.io/v1`.
This is causing issues as ArcoCD cannot create the resource and status is forever stuck as syncing.

Fix delete-snapshots ClusterRole

---

.github/workflows/kube-linter.yaml

Version 0.6.6 contains a new liveness check. We do have a few liveness issues already so use previous version for now. Once we fix all issues, we will revert to use latest again.

Fix kube-linter version to 0.6.5

---

components/authentication/base/group-sync/group-sync.yaml

Replace `Infra Team` group by `konflux-infra`

---

components/authentication/base/konflux-admins.yaml
components/authentication/base/kustomization.yaml

Replace `RHTAP Admins` group by `konflux-admins`

---

components/build-service/base/rbac/build-admin.yaml
components/build-service/base/rbac/build-maintainer.yaml
components/build-templates/base/e2e/rolebinding.yaml
components/image-controller/base/rbac/image-controller-admin.yaml
components/image-controller/base/rbac/image-controller-maintainer.yaml
components/tekton-ci/base/tekton-ci-maintainers-rb.yaml

Use new group names which are aligned with new service name but also with the names of new Rover groups. Having both GitHub and Rover group names aligned will allow to have clusters auth with either GitHub or Red Hat SSO without having any difference in the RBACs.

Replace `Build [Admins] team` groups by `konflux-build[-admins]`

---

components/dora-metrics/base/rbac/dora-metrics.yaml

Replace dora-metrics RBAC users by `konflux-qe-admins` group

---

components/monitoring/grafana/base/kustomization.yaml
components/monitoring/grafana/development/kustomization.yaml
components/monitoring/grafana/production/kustomization.yaml
components/monitoring/grafana/staging/kustomization.yaml

Updated o11y kustomization files to update the image automatically. Instead of updating in base update the image commit ref separately in all 3 envs

chore: Update the o11y kustomization files

---

components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
components/pipeline-service/base/rbac/openshift-pipelines/pipeline-service-sre.yaml
components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
components/pipeline-service/base/testing/rbac.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/sprayproxy/base/rbac/pipeline-service-sre.yaml

Replace `Pipeline Service` group by `konflux-pipeline-service`

---

components/integration/production/manager_resources_patch.yaml

Currently in production integration-service is using ~600Mi of memory and ~200mi of CPU.
Updating requests accordingly.

chore(integration-service): update controller resources

---

components/enterprise-contract/download-service.yaml

There's a script which is responsible for setting up the download service for Enterprise Contract. This script runs as part of the initContainer for the Deployment.
Prior to this commit, if there were any errors while executing the script, the script would wait forever.
This commit changes the behavior to allow the script to exit on errors and report some information about the failure. The idea is that if there is some sort of timing issue, OpenShift will retry executing the container again. This leverages that instead of entering a pseudo-deadlock state.
This is an attempt to fix RHTAPBUGS-1106, or to at least provide more information if the error does happen again.

Do not swallow errors on ec downloads

---

components/internal-services/internal-services.yaml
components/release/base/release-team.yaml

Use new group name which is aligned with new service name but also with the name of the Rover group. Having both GitHub and Rover group names aligned will allow to have clusters auth with either GitHub or Red Hat SSO without having any difference in the RBACs.

Replace `Release Team` group by `konflux-release-team`

---

components/monitoring/logging/base/rbac/logging-admin.yaml
components/segment-bridge/rbac/segment-bridge.yaml

In order to support both GH and RH SSO authentication, we cannot use usernames as they wont be the same on both sides.
Having both a GitHub and Rover group will allow to have the RBACs the same on both type of clusters and group sync will take care of populating the group with right users.
Use new groups which are aligned with new service name but also with the name of new Rover groups.
Once this change is done, the former groups `o11y` and `Logging Admins` will be deleted.

Use new konflux-o11y[-admins] groups

---

components/integration/base/delete-snapshots.yaml

Replace `Integration Team` group by `konflux-integration`

---

components/backup/base/all-clusters/kustomization.yaml
components/backup/base/all-clusters/servicemonitor.yaml

I tested this by applying the ServiceMonitor to a dev cluster with the OADP operator manually installed and configured to backup to a local minio instance.

Add a ServiceMonitor to collect OADP/velero metrics

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

Reporting the impacted backup schedule will be useful in upcoming alerts.

Keep `schedule` label on remote written metrics

---

components/enterprise-contract/OWNERS

We can't seem to get pass the `Konflux Staging / Konflux Staging` check for the EC automatic updates for PRs like #3176. The issue seems to be related to this message found in the check status and the Pipelines as code controller logs:
```
User ec-automation[bot] is not allowed to run CI on this repo.
```
The `/ok-to-test` doesn't seem to make much difference and `Konflux Staging / Konflux Staging` check is a required check for whatever reason.
This severely blocks our ability to deliver changes, and the only alternative to get passed this check seems to be to add the `ec-automation[bot]` as an owner, in this case as an approver.

Add `ec-automation[bot]` as approver

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
components/monitoring/logging/production/stone-prod-p01/kustomization.yaml

It seems that stone-prod-p01 (even though it's a classic ROSA) doesn't have the operator group pre installed.

RHTAPSRE-376: Deploy operator group for the openshift-logging operator

---

components/authentication/base/rh-idp/group-sync/konflux-rover-groups.yaml

Change configuration of Rover groups sync to prune the ones deleted from Rover.

Prune the deleted Rover groups

---

components/segment-bridge/base/serviceaccount.yaml

In order to support both GH and RH SSO authentication, we cannot use usernames as they wont be the same on both sides.
Having both a GitHub and Rover group will allow to have the RBACs the same on both type of clusters and group sync will take care of populating the group with right users.

Use GH group for RBACs in segment-bridge component

---

components/authentication/base/rh-idp/everyone-can-view-patch.yaml
components/perf-team-prometheus-reader/base/perf-team.yaml

Also add the new group to the everyone can view role for RH IdP.

Replace `Performance` group by `konflux-performance`

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml

There was a typo in the name of the cluster.

Fix cluster name for internal staging Prometheus

---

components/gitops/base/authentication/gitops-clusterrolebindings.yaml
components/gitops/production/base/authentication/gitops-rolebindings.yaml
components/gitops/production/stone-prd-m01/gitops-team-member-namespaces.yaml
components/gitops/staging/base/authentication/gitops-rolebindings.yaml
components/gitops/staging/stone-stg-m01/gitops-team-member-namespaces.yaml

In order to support both GH and RH SSO authentication, having both a GitHub and Rover group will allow to have the RBACs the same on both type of clusters and group sync will take care of populating the group with right users.
Use new groups which are aligned with new service name but also with the name of new Rover groups.
The members of the 2 new konflux groups are the same as old ones. Create the groups even though gitops service is deprecated as we need to support internal cluster using RH SSO before gitops is removed.

Use new konflux-gitops[-admins] groups

---

components/has/base/rbac/has-admin.yaml
components/has/base/rbac/has.yaml
components/has/staging/rbac/has-exec.yaml

In order to support both GH and RH SSO authentication, we cannot use usernames as they wont be the same on both sides.
Having both a GitHub and Rover group will allow to have the RBACs the same on both type of clusters and group sync will take care of populating the group with right users.

Use GH group for RBACs in has component

---

components/sandbox/base/rbac/sandbox-sre-admins.yaml
components/sandbox/toolchain-host-operator/base/rbac/sandbox-sre-admins.yaml
components/sandbox/toolchain-member-operator/base/rbac/register-cluster-extra-member-permissions.yaml
components/sandbox/toolchain-member-operator/base/rbac/sandbox-sre-admins.yaml

In order to support both GH and RH SSO authentication, we cannot use usernames as they wont be the same on both sides.
Having both a GitHub and Rover group will allow to have the RBACs the same on both type of clusters and group sync will take care of populating the group with right users.
Replace users by new group named konflux-core, defined here[1] for GH and there[2] for Rover.
[1]https://github.com/orgs/redhat-appstudio/teams/konflux-core
[2]https://rover.redhat.com/groups/group/konflux-core

Use GH group for RBACs in sandbox component

---

components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

the bump from https://github.com/redhat-appstudio/infra-deployments/pull/3205 did not employ the new process from @prietyc123 @Roming22 to run `kustomize build`

complete bump pipeline-service prod to version in staging

---

components/ui/staging/kustomization.yaml

Internal cluster needs https://github.com/openshift/hac-dev/pull/902 commit or later for the GH app flow to work correctly, which includes fix for https://issues.redhat.com/browse/RHTAPBUGS-1128

Bump UI in the internal cluster

---

.tekton/build-service-prod-overlay-update.yaml
.tekton/image-controller-prod-overlay-update.yaml
components/tekton-ci/base/repository.yaml

We are observing below error in PaC logs when it tried to run the pipeline for this [commit](https://github.com/redhat-appstudio/infra-deployments/commit/70a19c3acc36b7d305dd290bc74a46658370b5f9)
```
{"level":"error","ts":"2024-02-06T14:35:45.424Z","logger":"pipelinesascode","caller":"events/emit.go:46","msg":"failed to match pipelineRuns: cannot find referenced task git-clone. if it's a remote task make sure to add it in the annotations","provider":"github","event-id":"014832e0-c4fd-11ee-99ea-355f6aba0e9b","event-sha":"70a19c3acc36b7d305dd290bc74a46658370b5f9","event-type":"push","namespace":"rhtap-promotion-staging","stacktrace":"github.com/openshift-pipelines/pipelines-as-code/pkg/events.(*EventEmitter).EmitMessage\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/pkg/events/e …
```

fix: move the production update pipelines to run under tekton-ci ns in prod

---

components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

this pulls in the updates from https://github.com/redhat-appstudio/infra-deployments/pull/3213
And then pull the 2 updates since then:
https://github.com/openshift-pipelines/pipeline-service/pull/916
https://github.com/openshift-pipelines/pipeline-service/pull/931
Something has happened to our update infra deployments PAC job.  We have some clues, but want to get this bump going first.
@enarha @Roming22 FYI

pipeline-service update (manual)

---

components/pipeline-service/staging/base/chains-signing-secrets.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/resources/tekton-chains-signing-secret-path.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-m01/resources/tekton-chains-signing-secret-path.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
components/pipeline-service/staging/stone-stg-rh01/resources/tekton-chains-signing-secret-path.yaml

Once this migration is completed, the secret will managed through Vault, simplifying the backup/restore process of a cluster.
A second secret is created, to ensure that the data of the new secret matches the existing secret.
The second step will be to rename the ExternalSecret so it replaces the existing secret.
When promoted to production, the External secret definition should be moved from the 'staging/base' folder to the 'base' folder.

Add scaffolding to migrate the chains secret to Vault

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/update-tekton-config-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

https://github.com/redhat-appstudio/infra-deployments/pull/3244 checks out in staging
matches with https://github.com/redhat-appstudio/infra-deployments/blob/0792841eb605315900c3cef42028a5af0a26810b/components/pipeline-service/staging/base/kustomization.yaml#L11
which matches https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/staging/base/kustomization.yaml#L11 as I type

PLNSRVCE-1526: bump prod to staging level, including the operator proxy webhook replica bump

---

components/pipeline-service/staging/base/chains-signing-secrets.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

@hugares was right. The namespace needs to be specified. The reason is that the `default` namespace does not have access to Vault, and the sync fails with:
```
{"level":"error","ts":1707504807.3176591,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"tekton-chains-signing-secret","namespace":"default"},"error":"using cluster store \"appsre-stonesoup-vault\" is not allowed from namespace \"default\": denied by spec.condition","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconc …
```

Fix pipeline-service signing-secrets-vault configuration

---

components/pipeline-service/development/update-tekton-config-performance.yaml
components/pipeline-service/staging/base/update-tekton-config-performance.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

PLNSRVCE-1526: bump eligible tekton controllers and webhooks in openshift-pipelines to 2 replicas

---

components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/development/update-tekton-config-performance.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/update-tekton-config-performance.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

the automatic infra-deployments update failed because we removed the chains replica exposure, so this manual update accounts for that

PLNSRVCE-1526: pipeline-service update (manual)

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/update-tekton-config-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

I'm curious if the same timing issue we saw in staging with gitops and tekton operator trying to update the tektonconfig concurrently takes hold now that the chains bump has been removed
it got resolved when the next, unrelated infra-deployments PR merged which sorted out the update ordering from those 2 items

PLNSRVCE-1526: bump prod to staging level, including the remote-resolver,pac replica bumps

---

components/authentication/base/all/component-maintainer.yaml
components/monitoring/grafana/base/kustomization.yaml
components/monitoring/grafana/base/rbac/grafana-maintainers.yaml
components/monitoring/grafana/base/rbac/kustomization.yaml

Component maintainer is an existing ClusterRole giving permissions extra permissions on installplans, serviceaccounts, secrets, pods and deployments, see exact definition here[1].
Grant components-maintainer role to konflux-o11y for the grafana components, i.e. appstudio-grafana namespace.
Also add the delete deployments permission in component-maintainer as this is needed for grafana but it make sense to add for all components maintainers.
[1]https://github.com/redhat-appstudio/infra-deployments/blob/main/components/authentication/base/all/component-maintainer.yaml

Grant grafana component maintainer to o11y team

---

components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/tekton-chains-signing-secret-name.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This change completes the migration of the Chains signing secret to Vault in staging.
Once validated a similar change will be promoted to production.

Rename plnscv ExternalSecret target

---

components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/tekton-chains-signing-secret-name.yaml

This change completes the migration of the Chains signing secret to Vault in production.
Additional info:
* Staging specific config is removed as part of the prod activation.
* `signing-secrets` needs to be manually deleted for the gitops sync to be successful.
* `signing-secrets-vault` needs to be manually cleaned up.

Rename plnscv ExternalSecret target in prd

---

components/integration/production/kustomization.yaml

Reverts redhat-appstudio/infra-deployments#3256, reverting removal of v1alpha1 version together with webhook.

Revert "Promote integration-service from staging to production"

---

components/sandbox/toolchain-host-operator/base/proxy/proxyplugin.yaml

There was a typo in the route name.

Fix proxyplugin route

---

components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Even thought the secret is created by the ExternalSecret, the
TektonInstallerSet was taking over the secret ownership preventing the
ExternalSecret from managing the secret.
Set secret as orphan as we want the value to be updated if if change in
vault but we do not want to take ownership of the secret as it is
created by TektonInstallerSet.

Set pipeline signing-secrets to orphan

---

components/integration/development/kustomization.yaml
components/integration/development/snapshotgc_inputs_patch.yaml

Add env var to cronjob that will take precedence over the value provided in the cronjob definition.

chore: add env var to snapshotgc cronjob

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

pulls in the changes merged into staging from https://github.com/redhat-appstudio/infra-deployments/pull/3277
verifications included
- @jkhelil making sure tenants can build things with alpha feature enabled
- @gabemontero validating that results was successfully reconciling/pruning pipelinesruns, and api server logs look clean with successful Get/Create invocations
- @gabemontero validating that the exporter was at the latest level and properly generating stats

bump pipeline-service in prod to staging level

---

components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Bump refs to the latest commit on the pipeline-service repo, but only update the deployment for one of the staging clusters (stone-stg-rh01). With switching to nightly builds considered significant change, we take step by step approach and start with single cluster.

Update pipeline-service, manual, stone-stg-rh01 only

---

components/pipeline-service/production/base/bump-exporter-mem.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

after monitoring exporter memory usage in prod-rh01 over a few weeks, it is my conclusion that increased load there has rendored the current 1Gi limit as tight
GC is occurring, but load on Konflux has simply increased a bunch.

bump pipeline metrics exporter mem in prod

---

components/pipeline-service/development/increase-results-pruner-gracePeriod.yaml
components/pipeline-service/development/kustomization.yaml

Following Konflux-bug 348, increasing the time period before Results Pruner kicks in to prune executed PipelineRuns from 10m to 2h.
There have been few instances where the PipelineRuns fail but we can't find the exact cause of failure because PipelineRun is already pruned. Konflux e2e demands to have PipelineRuns stored in the cluster for a longer period in order to proceed with tests, and further debugging by devs if needed.
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>

increase Tekton Results pruner gracePeriod for Dev env

---

components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml

After switching one of the staging clusters (stone-stg-rh01) to the OSP nightly builds, now we switch the remaining two clusters (stone-stg-m01 and stone-stage-p01).

pipeline-service update manual

---

argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

This will remove the backup application from the delete group list, which prevents applications from being deployed in overlays.

RHTAPSRE-400: Remove Backup Application from Delete Group List

---

components/pipeline-service/production/base/bump-results-watcher-mem.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

per @hugares recent feedback in a metrics exporter related PR, I just today saw results watcher restarted when it was denied moving past 2.01 G, where I was only setting limit to 3Gi.
This PR addresses that, employing the well know best practice of having requests=limit.

make request watcher mem req/limit equal to better ensure we get the amount of mem desired

---

components/pipeline-service/staging/base/bump-results-watcher-mem.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/update-results-watcher-performance.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

Similar to what we did for the tekton pipelines controller, we are bumping the knative tuning parameters for controller worker thread count to the recommended, higher scale, non development, settings. Unfortunately, results/watcher bypasses the api clientqps/burst command line args that knative provides, and it is at an old enough knative level that it does provide the environment variable overrides for those settings. So we bypass that tuning at this time.  We are also bumping cpu request/limits and mem limit (again) based on recent obsevations.
We are finally moving forward with the worker thread bump since we have the goroutine/memory lead sorted out.
FYI the recently discovered pruning issue in stage https://issues.redhat.com/browse/PLNSRVCE-1679 is unrelated to the mem leak fix …

KFLUXBUGS-863: bump stg results watcher controller tuning

---

.github/workflows/kube-linter.yaml

Recently, we started to see timeout errors while running kustomize
build:
```
URL is a git repository': hit 27s timeout running
'/usr/bin/git fetch --depth=1
https://github.com/redhat-appstudio/jvm-build-service 1f980ef8f4540dc09fcfc8454972418a7c114404'
```
I am not sure what changed on GitHub side as the kube linter check has
been using 8 threads to run kustomize build of the various components
folder for a few months without any issue.
Reducing the number of threads from 8 to 4 seems to fix the issue. I say
`fix` because the pattern to reproduce the issue is not well defined. We
will try with that and see if it solves the issue.

Reduce from 8 to 4 threads to run kustomize build

---

components/backup/base/host/schedules/backup-toolchain-host-schedule.yaml

Backing up a list of resources can lead to incomplete backup, e.g. if a CRD is added without updating the back up list.
To be on the safe side, change the backup to include all resources in toolchain-host-operator and restore procedure will explicitly mention which resources to restore. Doing it that way will cost a bit more on the AWS storage but has the huge advantage of covering the case of CRD being added later. Backup will include it and restore procedure might not but can be adjusted when restore is performed.

Backup all resources in workspaces host namespace

---

components/monitoring/grafana/base/dashboards/integration/kustomization.yaml

On [STONEINTG-761](https://issues.redhat.com/browse/STONEINTG-761) we made changes in metrics of integration-service , this PR as follow up to update in infra-deployments to point monitoring grafana to latest integration-service.

fix(stoneinteg-761): update the kustomization to latest integration-service

---

components/integration/development/kustomization.yaml
components/integration/staging/base/kustomization.yaml

This accidentally overwrote newer version with old image
Reverts redhat-appstudio/infra-deployments#3357

Revert "integration-service update"

---

components/tekton-ci/base/external-secrets/kustomization.yaml
components/tekton-ci/base/external-secrets/quay-push-secret-konflux-ci.yaml
components/tekton-ci/base/serviceaccount.yaml
components/tekton-ci/production/kustomization.yaml
components/tekton-ci/production/quay-push-secret-konflux-ci.yaml

The purpose is to support a migration of container images from quay.io/redhat-appstudio to quay.io/konflux-ci.

KONFLUX-2040: Add robot push token for quay.io/konflux-ci

---

components/pipeline-service/production/base/bump-results-watcher-mem.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/base/stay-at-1-13-until-nightly-revert-sorted.yaml
components/pipeline-service/production/base/update-results-watcher-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

it was decided with infra team that the use if nightlies would be put on hold until communication, doc, support, scheduling is fully vetted
otherwise, this pulls in the first iteration of the results watcher mem leak fix
and associated perf related turning for results
See https://github.com/redhat-appstudio/infra-deployments/pull/3389 for the PR by PR list from the pipeline-service repo

KFLUXBUGS-863: bump results to stage level to address memory leak, help performance; keep at OSP 1.13 for now

---

components/tekton-ci/base/serviceaccount.yaml

After b1ce8f527d607725f3a9ae062873166354567bcf, the tekton-ci namespace contains two dockercfg secrets for quay.io authentication (both linked to the appstudio-pipeline SA). One of them has permissions for the redhat-appstudio org, the other one for the konflux-ci org. But since both of them contain auth for "quay.io", when the secrets get merged to produce the final auth file, only one of them wins. Given that our CI has lost permissions for pushing to the redhat-appstudio org, it seems that konflux-ci wins.

tekton-ci: unlink quay-push-konflux-ci secret

---

components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

recent memory leak or hung grpc call issues may require development support running 'oc exec' into the results watcher pod to collect goroutine dumps and/or pprof data
initially I am intentionally restricting this ability to only the tekton-results namespace
see refs like https://stackoverflow.com/questions/48118125/kubernetes-rbac-role-verbs-to-exec-to-pod for perms around exec'ing into pods

add pod/exec permissions in tekton-results namespace  to pipeline-service-sre related rbac

---

components/pipeline-service/development/increase-results-pruner-gracePeriod.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/development/reduce-watcher-cpu-mem-reqs.yaml

see https://redhat-internal.slack.com/archives/C02FTKEMBU1/p1710173062721049
also, when editing the development kustomization.yaml file I found an yaml formatting problem with the 
`increase-restuls-pruner-gracePeriod.yaml` file being listed as a path, but not deployment target listed
This stems https://github.com/redhat-appstudio/infra-deployments/pull/3340 that was authored by @ramessesii2 and approved by @Roming22 
I've taken a stab and fully enabling it, thinking the bump to 2 hours makes sense for e2e's in order to allow for must gather to obtain pipelineruns without fear of them getting pruned
however, if instead @ramessesii2 @Roming22 you all think that file and override should be removed altogether, please let me know
rh-pre-commit.check-secrets: …

KFLUXBUGS-1150: reduce watcher cpu/mem reqs for smaller e2e clusters; finish enabling widening of prune interval for e2e

---

argo-cd-apps/overlays/staging/kustomization.yaml
argo-cd-apps/overlays/staging/migration.patch.yaml

This pull request will disable `sync_policy` for the Staging Public ArgoCD instance. We are migrating this ArgoCD instance to appsre managed OSD Cluster.

RHTAPSRE-429: Disabling Sync Policy for Staging Public ArgoCD

---

components/authentication/base/all/konflux-admins.yaml

Create a new GH/rover group named konflux-sre to include SRE people and grant them konflux-admins.
Another option would have been to add them to konflux-admins group but I prefer to not do that. In fact, I would like to delete that group and grant konflux-admins role to teams who should have it, like konflux-sre.
[RHTAPSRE-425](https://issues.redhat.com//browse/RHTAPSRE-425)

Grant konflux-admins to konflux-sre team

---

hack/quickcluster/setup-nfs-quickcluster.sh

If restart of nfs.service fails, try to restart nfs-server.service instead.

Update setup-nfs-quickcluster.sh to work with RHEL-8

---

components/integration/development/kustomization.yaml
components/integration/development/manager_resources_patch.yaml
components/integration/production/base/kustomization.yaml
components/integration/production/base/manager_resources_patch.yaml
components/integration/staging/base/kustomization.yaml
components/integration/staging/base/manager_resources_patch.yaml

Integration Service needs to establish a way to configure a console url to be used for reporting links in gitHub.
This is the way how we would create ConfigMap containing link to specific environment which will be then fetched by pipeline adapter in integration service.

feat(STONE-812): IS mapping to console URL

---

components/tekton-ci/base/serviceaccount.yaml

[STONEBLD-1832](https://issues.redhat.com//browse/STONEBLD-1832)
Tekton should handle the secret linked in the `secrets:' section, which will be merged into the ~/.docker/config.json.

Link registry.redhat.io credential in SA secrets

---

components/gitops/development/core_service_resources_patch.yaml
components/gitops/development/gitops-service-argocd.yaml
components/gitops/development/kustomization.yaml
components/gitops/development/service_agent_resources_patch.yaml

related to https://github.com/redhat-appstudio/e2e-tests/pull/1077

fix: reduce resource requests/limits for gitops

---

components/release/base/cronjobs/remove-expired-releases.yaml

This PR changes the output temp directory used by the cronjob `remove-expired-releases`

fix: release-expiration cronjob incorrect directory

---

argo-cd-apps/app-of-app-sets/konflux-public-production/change-source-path.yaml
argo-cd-apps/app-of-app-sets/konflux-public-production/change-target-namespace.yaml
argo-cd-apps/app-of-app-sets/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/migration.patch.yaml
argo-cd-apps/overlays/konflux-public-production/production-overlay-patch.yaml
argo-cd-apps/overlays/production/migration.patch.yaml

This PR will make the following changes:

RHTAPSRE-431: Migrating Konflux Public Production (ArgoCD) to appsrep05ue1

---

components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml

- Add `kube_deployment_status_replicas_available` metric
- Update namespace for `kube_deployment_spec_replicas` metric

chore(RHTAPWATCH-886): add konflux metrics to service monitor

---

argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/migration.patch.yaml

This pull request enables auto-sync for the production argocd instance running on `appresp05ue1` cluster and this will also remove older overlays `staging` and `production`

RHTAPSRE-431: enable auto sync for production argocd instance

---

components/build-service/production/base/increase-build-controller-memory.yaml
components/build-service/production/base/kustomization.yaml

On rh01, the pod is getting OOMKilled. This change is temporary to increase the memory limit. Once we have the working number, the change will be done in build-service repository.

Increase memory of production build controller

---

components/monitoring/grafana/base/dashboards/integration/kustomization.yaml

A follow up to work done in [STONEINTG-761](https://issues.redhat.com/browse/STONEINTG-761) , 
metrics were removed from instagration-service grafana dashboard , 
this PR is about update the kustomization to point to latest integration-service

fix(stoneinteg-761): update integration grafana dashboards 

---

components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml

We use Vault to store signing-secrets as a way to backup this secret and get it recreated on the cluster it its get deleted. To get it back in the cluster, ExternalSecret is used as usual to extract value from Vault and put in in signing-secrets secret.
Since this secret is created by created/managed by TektonInstallerSets, the ExternalSecret is configured to create the secret as orphan if it does not exists, meaning that it creates it without setting the owner reference so ES and TIS do not fight over the ownership.
Because ES is not setting ownership, the secret created was getting pruned by ArgoCD as soon as ES was creating it.
Fix this issue by adding the annotation
`argocd.argoproj.io/sync-options: Prune=false` to the secret being created by ES.

Configure ArgoCD to not prune signing-secrets secret

---

components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

A change was done in 41ead0ca351cf3ea69ccf2f47c2f22ce86d8340b but I forgot to regenerate the deployment files.

Regenerate pipeline service deployments

---

components/pipeline-service/production/base/bump-exporter-mem.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

monitoring exporter for the last few days, I still see GC occurring and memory reductions, but it simply day to day is closer to the current 2Gi memory limit than it used to be

adjust exporter mem to account for increased prod load

---

components/pipeline-service/production/base/bump-results-watcher-replicas.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

During triage of the prod-rh01 results RDS lock contention query hand issue, noticed for the first time since we enabled multiple watcher replicas that both replicas were processing objects, vs. one acting and the primary and processing object, and the other replica acting as a standby.
We could not find an instance of a pipeline run or task run being processed by both replicas, but there are too many to effectively search for.
Removing this variable of 2 replicas manipulating the same DB entries leading to the lock contention.
@hugares @sayan-biswas FYI

go back to 1 watcher replica, asses impact on prod-rh01 results RDS hang

---

components/pipeline-service/production/base/bump-results-api-resources.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

- set limits CPU to 3000m and memory 1Gi
- set request CPU to 1000m and memory 500Mi
Signed-off-by: Avinal Kumar <avinal@redhat.com>

bump tekton results api pod resources

---

components/build-service/production/base/increase-build-controller-memory.yaml
components/build-service/production/base/kustomization.yaml

Reverts redhat-appstudio/infra-deployments#3465 with increase memory workaround because newer version of Build Service with the memory limit changes has been released.

Revert "Increase memory of production build controller"

---

argo-cd-apps/base/keycloak/keycloak.yaml
argo-cd-apps/base/keycloak/kustomization.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
argo-cd-apps/overlays/staging-downstream/kustomization.yaml
components/keycloak/base/konflux-workspace-admins/kustomization.yaml
components/keycloak/base/konflux-workspace-admins/rbac.yaml
components/keycloak/base/kustomization.yaml
components/keycloak/production/base/kustomization.yaml
components/keycloak/staging/base/kustomization.yaml

For creating new workspaces in the internal cluster a keycloak user should be created. Provide the permissions to manage keycloak users to the `konflux-workspace-admins` group.

RHTAPSRE-353: RBAC for creating workspaces in internal clusters

---

components/pipeline-service/development/chains-deployment-perf-bump.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/chains-deployment-perf-bump.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

I'm not sure if these new args are just ignored, or rejected as invalid, if we don't have a version of chains installed that actually processes them.  We should find out with the e2e's, as I've updated the developer overlay with this change
But if it does cause a failure, then getting the correct openshift pipelines version will serve as the verification that everything is correct
FYI I duplicated the policy we use for core tekton controller, which comes from https://github.com/tektoncd/pipeline/blob/main/docs/tekton-controller-performance-configuration.md 
@lcarva @enarha @rupalibehera  FYI / PTAL

KFLUXBUGS-24: bump dev/stage overlay chains deployment to use performance arguments

---

components/pipeline-service/production/base/chains-deployment-perf-bump.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

Included PRs:
- https://github.com/openshift-pipelines/pipeline-service/pull/969
- https://github.com/openshift-pipelines/pipeline-service/pull/981
we've vetted https://github.com/redhat-appstudio/infra-deployments/pull/3496 in stage including tests from @lcarva 
though this also has @ralphbean 's tekton-ci to konflux-ci change with the pac gitauth secret
I think this is OK @enarha @ralphbean but with going to prod we probably need a sign off from you guys on that

KFLUXBUGS-24: bump prod overlay chains deployment to use performance arguments

---

components/integration/development/kustomization.yaml
components/integration/development/manager_resources_patch.yaml
components/integration/production/base/kustomization.yaml
components/integration/production/base/manager_resources_patch.yaml
components/integration/production/stone-prod-p01/console-url-config-patch.json
components/integration/production/stone-prod-p01/kustomization.yaml
components/integration/staging/base/kustomization.yaml
components/integration/staging/base/manager_resources_patch.yaml
components/integration/staging/stone-stage-p01/console-url-config-patch.json
components/integration/staging/stone-stage-p01/kustomization.yaml

* Adds a new configuration template of task URL to a new envvar so it can be used by integration service
* Override the default stage console URL configuration to account for the different console base URL

feat(STONEINTG-844): add configuration template of task URL

---

components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml

Use new email in toolchain config, former one will be decommissioned.
[KFLUXINFRA-423](https://issues.redhat.com//browse/KFLUXINFRA-423)

Replace rhtap-infra by konflux-infra email

---

components/monitoring/grafana/base/dashboards/integration/kustomization.yaml

Following to [STONEINTG-761](https://issues.redhat.com/browse/STONEINTG-761) , this is to update integration grafana pointing to the  latest integration-service

fix(stoneinteg-761): update tag for integration grafana dashboard

---

components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml

This has been replaced by the dedicated SpaceProvisionerConfig CRs and is being removed from the ToolchainConfig CRD altogether.
Note that the deployed version of the sandbox host operator no longer uses this configuration and only looks at the configuration provided by the SpaceProvisionerConfig so this should be safe to do. Nevertheless, this PR only updates the staging cluster configuration and if all goes well, the same can be applied to prod.
There is a separate PR doing the same thing on prod: https://github.com/redhat-appstudio/infra-deployments/pull/3517

Remove capacityThresholds from the ToolchainConfig on staging

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

These commits are technically included:
[fix wait_for_pipelines debug](https://github.com/openshift-pipelines/pipeline-service/commit/e605798a3007da71f9d812273b97249a77b5635a)
[Revert "add config for enabling tekton results dbssl"](https://github.com/openshift-pipelines/pipeline-service/commit/91776680abc5935af19695150f709421429bda85)
[update operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml](https://github.com/openshift-pipelines/pipeline-service/commit/41ee6fe4915125880e1c8bb09f5892396da4cd2b)
[add config for enabling tekton results dbssl](https://github.com/openshift-pipelines/pipeline-service/commit/5e38cd44d8455e77def659ea116a684c5cfa4320)
But in reality all that is being changed is the version of the metrics exporter, as we had to revert Avinal's SSL change …

bump prod to staging level

---

components/backup/staging/stone-stage-p01/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-host/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-m01/backup-s3-credentials-patch.yaml
components/backup/staging/stone-stg-rh01/backup-s3-credentials-patch.yaml
components/remote-secret-controller/overlays/staging/stone-stg-m01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/staging/stone-stg-rh01/aws-credentials-path-patch.yaml
components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/staging/stone-stg-rh01/spi-aws-credentials-path-patch.yaml

We're migrating all the resources from `stonesoups01ue1` to `appsres05ue1`. The app interface merge request has been merged, therefore we need to update the secret paths in infra-deployments.

KFLUXINFRA-470: Replace stonesoups01ue1 with appsres05ue1 in Secret Paths

---

argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
components/authentication/staging/base/kustomization.yaml
components/authentication/staging/stone-stg-host/kustomization.yaml

RH sso is configured as an identity provider already on those clusters. Change the authentication component to use rh-idp folder instead of github which will sync the groups from rover instead of github.
Since all the clusters staging clusters now use rh-idp, change staging/base and get rid of special case for stone-stg-host.
[KFLUXINFRA-132](https://issues.redhat.com//browse/KFLUXINFRA-132)

Move stone-stg-m01 and stone-stg-rh01 authentication to rh-idp

---

components/backup/production/stone-prd-host1/backup-s3-credentials-patch.yaml
components/backup/production/stone-prd-m01/backup-s3-credentials-patch.yaml
components/backup/production/stone-prd-rh01/backup-s3-credentials-patch.yaml
components/backup/production/stone-prod-p01/backup-s3-credentials-patch.yaml
components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
components/remote-secret-controller/overlays/production/stone-prd-m01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/production/stone-prd-rh01/aws-credentials-path-patch.yaml
components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml

We're migrating all the Konflux resources from `stonesoupp01ue1` to `appsrep05ue1`. This requires to update the secret paths or configurations containing `stonesoupp01ue1` with `appsrep05ue1`.

KFLUXINFRA-471: Replacing stonesoupp01ue1 with appsrep05ue1 in Secret Paths

---

argo-cd-apps/overlays/development/delete-applications.yaml
components/sandbox/toolchain-host-operator/development/kustomization.yaml
components/sandbox/toolchain-member-operator/development/kustomization.yaml

Both applications point to an empty folder, kustomize resources wise. Remove both ArgoCD applications and they empty folders to remove the possible confusion. Toolchain is not deployed using ArgoCD in development overlay.

Delete toolchain host and member application from dev overlay

---

argo-cd-apps/base/quality-dashboard/kustomization.yaml
argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
components/quality-dashboard/OWNERS
components/quality-dashboard/base/backend/kustomization.yaml
components/quality-dashboard/base/dex/kustomization.yaml
components/quality-dashboard/base/frontend/kustomization.yaml
components/quality-dashboard/base/kustomization.yaml
components/quality-dashboard/base/rbac/kustomization.yaml
components/quality-dashboard/base/rbac/quality-dashboard.yaml
components/quality-dashboard/development/kustomization.yaml
components/quality-dashboard/staging/external-secrets/kustomization.yaml
components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
components/quality-dashboard/staging/kustomization.yaml
docs/_data/navigation.yml
docs/misc/quality-dashboard.md
hack/bootstrap-host-cluster.sh
hack/destroy-cluster.sh
hack/preview-template.env
hack/secret-creator/quality-dashboard/.gitignore
hack/secret-creator/quality-dashboard/create-quality-dashboard-secrets.sh
hack/secret-creator/quality-dashboard/dex-config-template.yaml

https://issues.redhat.com/browse/KONFLUX-2244
Based on this PR: https://github.com/redhat-appstudio/infra-deployments/pull/2676
Deployment of QD can be validated on a dev cluster by following instructions in `docs/misc/quality-dashboard.md`

chore: re-add quality dashboard

---

components/integration/production/base/kustomization.yaml

Fix the typo in the environment variable definition.

fix: CONSOLE_URL_TASKLOG for prod integration-service

---

components/pipeline-service/staging/base/update-tekton-config-performance.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

quick workaround to maximize computing capacity for the `tekton-pipelines-webhook` webhook getting periodic context deadline exceeded errors reported in 
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1713275865233269
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1713252235282299
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1713180672587489
@hugares @gbenhaim @savitaashture @khrm @enarha 

stage: bump tekton-pipeline-webhook to 6 minimum replicas to avoid intermittent context deadline exceeded performance issues

---

argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
components/spacerequest-cleaner/production/kustomization.yaml

Promote the spacerequest cleaner cronjob to production, after it successfully ran in staging.

chore(RHTAPWATCH-766): spacerequest cleaner to production

---

components/pipeline-service/production/base/update-tekton-config-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

the prod version of https://github.com/redhat-appstudio/infra-deployments/pull/3574
to reiterate from there ^^ on sufficiently sized personal cluster I was able to update the development overlay to 6 and successfully bootstrap, etc.

prod: bump tekton-pipeline-webhook to 6 minimum replicas to avoid intermittent context deadline exceeded performance issues

---

components/quality-dashboard/base/rbac/quality-dashboard.yaml

The role was missing the `get` permission.

Allow qe admins to get secrets in quality-dashboard namespace

---

argo-cd-apps/base/all-clusters/infra-deployments/kubesaw-common/kubesaw-common.yaml
components/sandbox/common/kustomization.yaml
components/sandbox/common/namespace.yaml
components/sandbox/common/olm-restart/kustomization.yaml

The deployment was failing due to the missing namespace. Create the namespace resource and also add the namespace directive in the kustomization file to create all resources in the namespace.
[ASC-503](https://issues.redhat.com//browse/ASC-503)

Fix deployment of kubesaw-common application

---

components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml

Brings in https://github.com/openshift-pipelines/pipeline-service/commit/9d129d83d3023c52075eb3d3ebea085fb5350c3c

PLNSRVCE-1692: bump prod pipeline service level to stage level

---

argo-cd-apps/base/all-clusters/infra-deployments/kubesaw-common/kubesaw-common.yaml
components/sandbox/common/kustomization.yaml
components/sandbox/common/namespace.yaml
components/sandbox/common/olm-restart/kustomization.yaml

There is a velidation webhook that blocks namespaces that contains string kube.

Renaming kubesaw-common namespace to bypass validation rules

---

components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml

This field is causing ArgoCD to be out of sync as it add the field but OCP is removing it as it is not part of CRD definition.

Remove unsupported defaultTier from ToolchainConfig

---

components/tekton-ci/base/repository.yaml

https://issues.redhat.com/browse/KONFLUX-2245
First part of moving manifests for ci-helper-app to infra-deployments

chore: add ci-helper-app Repository CR

---

components/image-controller/development/kustomization.yaml
components/image-controller/staging/base/kustomization.yaml

Included PRs:
- https://github.com/redhat-appstudio/image-controller/pull/100
- https://github.com/redhat-appstudio/image-controller/pull/101
- https://github.com/redhat-appstudio/image-controller/pull/106
- https://github.com/redhat-appstudio/image-controller/pull/105

Image controller update to dev & stg

---

components/remote-secret-controller/overlays/production/base/kustomization.yaml
components/spi/overlays/production/base/kustomization.yaml

Included PRs:
- https://github.com/konflux-ci/remote-secret/pull/402
- https://github.com/konflux-ci/remote-secret/pull/417
- https://github.com/konflux-ci/remote-secret/pull/418
- https://github.com/konflux-ci/remote-secret/pull/421
- https://github.com/konflux-ci/remote-secret/pull/425
- https://github.com/konflux-ci/remote-secret/pull/403
- https://github.com/konflux-ci/remote-secret/pull/424
- https://github.com/konflux-ci/service-provider-integration-operator/pull/926
- https://github.com/konflux-ci/service-provider-integration-operator/pull/923
- https://github.com/konflux-ci/service-provider-integration-operator/pull/915
- https://github.com/konflux-ci/service-provider-integration-operator/pull/917
- https://github.com/konflux-ci/service-provider-integration-operator/pull/930
- …

Promote SPI/RemoteSecret from staging to prod

---

components/tekton-ci/base/repository.yaml

Tekton-ci repo config has to be updated.

STONEINTG-840: migrate clair-in-ci-db to konflux-ci org

---

components/release/base/cronjobs/remove-expired-releases.yaml

This commit increases the memory and cpu set for remove-expired-releases cronjob.

fix: increase cpu and mem for release cleanup cronjob

---

components/tekton-ci/base/repository.yaml

hacbs-test has been renamed to konflux-test and moved under konflux-ci org

feat(STONEINTG-839): hacbs-test migration

---

components/integration/development/kustomization.yaml
components/integration/development/manager_resources_patch.yaml
components/integration/production/base/kustomization.yaml
components/integration/production/base/manager_resources_patch.yaml
components/integration/staging/base/kustomization.yaml
components/integration/staging/base/manager_resources_patch.yaml

* Set the overall pipeline timeout to 3h = 2h(tasks) + 1h(finally)
See more in the [Tekton docs](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#configuring-a-failure-timeout).

fix(KFLUXBUGS-1218): add pipelineRun timeout environment vars

---

components/backup/production/stone-prd-host1/backup-s3-credentials-patch.yaml
components/backup/production/stone-prd-m01/backup-s3-credentials-patch.yaml
components/backup/production/stone-prd-rh01/backup-s3-credentials-patch.yaml
components/backup/production/stone-prod-p01/backup-s3-credentials-patch.yaml
components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
components/gitops/production/stone-prod-p01/gitops-service-postgres-rds-config-path.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/resources/tekton-results-database-secret-path.yaml
components/pipeline-service/production/stone-prod-p01/resources/tekton-results-s3-secret-path.yaml
components/remote-secret-controller/overlays/production/stone-prd-m01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/production/stone-prd-rh01/aws-credentials-path-patch.yaml
components/remote-secret-controller/overlays/production/stone-prod-p01/aws-credentials-path-patch.yaml
components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml
components/spi/overlays/production/stone-prod-p01/spi-aws-credentials-path-patch.yaml
hack/hac/installHac.sh

AppSRE is migrating resources running on `appsrep05ue1` to `appsrep09ue1`. Infra Deployments for Konflux consume those resources in the form of the vault secrets, meaning those paths will be changed with this migration.
This PR will update the vault secret paths containing `appsrep05ue1` with `appsrep09ue1`.

KFLUXINFRA-567: Replacing appsrep05ue1 to appsrep09ue1

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
components/monitoring/logging/staging/kflux-stg-es01/kustomization.yaml

This cluster does not have the operatorgroup so deploy the logging operator prerequisites.
[KFLUXINFRA-554](https://issues.redhat.com//browse/KFLUXINFRA-554)

Fix logging operator installation on kflux-stg-es01

---

components/monitoring/logging/base/logging-operator-prerequisite/kustomization.yaml
components/monitoring/logging/base/logging-operator-prerequisite/namespace.yaml

This was added to the prerequisite folder for stone-stage-p01 when it was HCP cluster but on ROSA clusters, the namespace already exists and cannot be tampered with as it is protected by admission web hook.
This is the reason why logging application is always out of sync on stone-prod-p01 and now the same is happening on kflux-stg-es01 as it will happen on stone-stage-p01 once ongoing re-installation is completed.

Do not create openshift-logging namespace

---

components/integration/base/kustomization.yaml
components/integration/base/manage-integrationtestscenarios.yaml

* The integration team is currently best suited to deal with issues with IntegrationTestScenario resources
* Giving the integration team permission to manage IntegrationTestScenarios across all namespaces will decrease customer complaints and prevent them from having to recognize and resolve the issue themselves

feat: allow integration team to manage integrationtestscenarios

---

components/tekton-ci/base/repository.yaml

[STONEBLD-1987](https://issues.redhat.com//browse/STONEBLD-1987)
When trying to onboard build-service to Konflux, we get
53: Git repository is already handled by Pipelines as Code
In order to be able to onboard to Konflux, the Repository has to be removed from the tekton-ci namespace.

tekton-ci: remove build-service PaC Repository

---

components/ui/production/kustomization.yaml

Mainly to get https://github.com/openshift/hac-dev/pull/926 in, but bumping the others as well.

Bump hac-dev, chrome service, chrome frontend tags

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml

An idea I had @enarha to bypass the results bump I'm getting performance QE to help me test with https://github.com/redhat-appstudio/infra-deployments/pull/3616
Rather than pick up the results image bumps like you see in https://github.com/redhat-appstudio/infra-deployments/pull/3616/files#diff-e961bdc3a405dfda1b39ed17ee82576bb68e2a35e9288e7de208e695e4ee5944R1497
We could force dev/stage/prod to specific sha's of the results image from here in infra deployments, and effectively pin the version here.
That way, if your operator bump is ready to merge before the testing completes with https://github.com/redhat-appstudio/infra-deployments/pull/3616 we could include something like this in the PR that does your operator bump without having to revert the results bump in …

pin results image until watcher mem leak fix is deemed ok

---

argo-cd-apps/base/eaas/kustomization.yaml
argo-cd-apps/base/eaas/some-component/kustomization.yaml
argo-cd-apps/base/eaas/some-component/some-component.yaml
argo-cd-apps/k-components/deploy-to-eaas-cluster-merge-generator/eaas-cluster-label-selector.yaml
argo-cd-apps/k-components/deploy-to-eaas-cluster-merge-generator/kustomization.yaml
argo-cd-apps/overlays/production-downstream/kustomization.yaml
argo-cd-apps/overlays/staging-downstream/kustomization.yaml
components/some-component/base/kustomization.yaml
components/some-component/base/namespace.yaml
components/some-component/production/kustomization.yaml
components/some-component/staging/kustomization.yaml

This change add a new eaas folder where we can put all ArgoCD applications specific to that cluster type.
To have a complete skeleton, add a dummy application/component named `some-component`, to be replaced with real one.

Create first application/component on eaas cluster

---

components/pipeline-service/development/enable-step-actions.yaml
components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

This is a workaround for passing artifacts between tasks in an integration pipeline where workspaces backed by persistent volumes are not available. It was one of the suggestions proposed during last week's community architecture call on the topic of passing around ephemeral cluster credentials after they've been provisioned.

Enable Tekton StepActions in dev and staging

---

argo-cd-apps/base/ci-helper-app/ci-helper-app.yaml
argo-cd-apps/base/ci-helper-app/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
components/backup/base/member/schedules/backup-tenants-schedule.yaml
components/ci-helper-app/OWNERS
components/ci-helper-app/base/kustomization.yaml
components/ci-helper-app/base/rbac/ci-helper-app.yaml
components/ci-helper-app/base/rbac/kustomization.yaml
components/ci-helper-app/development/kustomization.yaml
components/ci-helper-app/staging/external-secrets/ci-helper-app-secrets.yaml
components/ci-helper-app/staging/external-secrets/kustomization.yaml
components/ci-helper-app/staging/kustomization.yaml
components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
docs/_data/navigation.yml
docs/misc/ci-helper-app.md
hack/bootstrap-host-cluster.sh
hack/destroy-cluster.sh
hack/preview-template.env
hack/secret-creator/create-ci-helper-app-secret.sh

[KONFLUX-2245](https://issues.redhat.com//browse/KONFLUX-2245)
* [ci-helper-app](https://github.com/konflux-ci/ci-helper-app) won't be deployed to dev/test env by default, the plan is to deploy it only in staging
* the validation was done locally by deleting [this part](https://github.com/redhat-appstudio/infra-deployments/pull/3643/files#diff-5d86190d9437c923d52539a453aff2af6eabfbdbc5cb2a5b466082002d16d427R91-R96) and setting up [required env vars](https://github.com/redhat-appstudio/infra-deployments/pull/3643/files#diff-d06ff763d99c81add8827eb9d1f3d99d1ce2ae43eaf235926a0bccfad78c5d2aR142-R145), followed by running `preview` script
* the required secrets are already present in vault

chore: add ci-helper-app

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
components/build-service/base/kustomization.yaml
components/build-service/base/rbac/build-config.yaml
components/build-service/base/rbac/kustomization.yaml

will be used in future instead of build selectors
[STONEBLD-2276](https://issues.redhat.com//browse/STONEBLD-2276)

Build config for build pipelines for build-service,

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/development/tekton-pipelines-controller-pods-log-access-rbac.yaml
components/pipeline-service/development/update-tekton-config-features.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/base/tekton-pipelines-controller-pods-log-access-rbac.yaml
components/pipeline-service/staging/base/update-tekton-config-features.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

with @jkhelil on PTO, I had a cycle or two and was able to test results locally using the test chains pipeline from pipeline-service deploying this branch locally
simple test case worked find
also, bifrost is now off of stg-p01 so we can update that as well
so I've cloned https://github.com/redhat-appstudio/infra-deployments/pull/3562 and created this PR to add p01
let's merge and soak in stage for a bit
@lcarva FYI

SRVKP-4361: enable results-from sidecar-logs for pipelines

---

argo-cd-apps/base/ci-helper-app/ci-helper-app.yaml

Only deploy the application on clusters with label `appstudio.redhat.com/ci-helper-app: "true"`, i.e. stone-stg-rh01.

Deploy ci-helper-app only on clusters with matching label

---

argo-cd-apps/base/local-cluster-secret/all-in-one/kustomization.yaml
argo-cd-apps/overlays/development/delete-applications.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml

ApplicationSet was added to development overlay to then be deleted. Simplify this by not adding in the first place.
Since both staging and production downstream are based on public staging overlay, they inherit the quality-dashboard  ApplicationSet but we do not have a cluster labeled with
`appstudio.redhat.com/quality-dashboard: "true"` so not application are created. Delete the ApplicationSet from those overlays.

Only deploy quality-dashboard ApplicationSet on public staging

---

components/ci-helper-app/base/rbac/ci-helper-app.yaml
components/quality-dashboard/base/rbac/quality-dashboard.yaml

we want to be able to restart pods for QD and ci-helper-app on staging cluster in cases when for example secrets get updated in vault

chore: qd: konflux-qe-admins perms for pods

---

components/keycloak/README.md
components/keycloak/base/configure-keycloak.yaml
components/keycloak/staging/stone-stage-p01/set-ocp-idp.yaml
components/keycloak/staging/stone-stage-p01/set-redirect-uri.yaml
components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
components/ui/staging/fed-modules.json
components/ui/staging/set-hostname.yaml

PAC: Update console routes for internal staging
UI: Update routes for staging
Keycloak: Update staging routes
Add missing config to the OCP IDP
The sync mode which decides how users are imported was missing.
FORCE means the user will get updated in Keycloak every time he/she
logins.

Update routes for internal staging and update Keycloak IDP config

---

components/keycloak/base/namespace.yaml
components/keycloak/base/rhsso-operator.yaml
components/sandbox/toolchain-host-operator/base/kustomization.yaml
components/sandbox/toolchain-host-operator/base/ns.yaml
components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml
components/sandbox/toolchain-member-operator/base/kustomization.yaml
components/sandbox/toolchain-member-operator/base/ns.yaml
components/sandbox/toolchain-member-operator/base/olm/toolchain-member-operator.yaml

Sync waves for Keycloak
Deploy the namespace, operator group, subscription, and then
all the rest. Otherwise CRs are failed to get deployed.
Improve sandbox deployment
1. Create the namespace for the host and member components.
2. Use sync waves because there are dependency between the resources.

Improve deployment

---

components/multi-platform-controller/staging/external-secrets.yaml
components/multi-platform-controller/staging/host-config.yaml

This PR will make the following changes --
- Replace RHEL Base images with Blessed Images
- Make use of spot instances
- New AWS Account for provisioning multi-arch VM(s)

KFLUXINFRA-570: Config Change for Multi-Arch Builds Public Staging

---

components/build-service/production/base/kustomization.yaml

[STONEBLD-2336](https://issues.redhat.com//browse/STONEBLD-2336)
The build-service commit ref got automatically promoted in
5056de658b40f80a3e8a80f409ed36a0fed6ab0a without the corresponding image
ref update.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

build-service: fix prod image reference

---

components/monitoring/grafana/base/dashboards/release/kustomization.yaml
components/release/development/kustomization.yaml
components/release/production/kustomization.yaml
components/release/staging/kustomization.yaml
hack/preview.sh

This commit updates the `release-service` reference
as result of migration to `konflux-ci` from `redhat-appstudio`
more details parent EPIC:
https://issues.redhat.com/browse/RHTAPREL-800

feat(RELEASE-230): update release service ref to konflux ci org

---

components/multi-platform-controller/staging/host-config.yaml

Blessed AMI(s) are encrypted with KMS Keys from Another AWS Account.
That would require some spike story to use them for the Multi-Platform Controller.

Reverting to Old AMIs

---

components/multi-platform-controller/staging/host-config.yaml

Removing Spot Instance Option for Multi-Platform Build.
We must handle the scenario to run an on-demand instance when the capacity is full.

Removing Spot Instance Option for Multi-Platform Build

---

components/build-templates/base/e2e/rolebinding.yaml

`rhtap-build-tenant:appstudio-pipeline` SA needs the same level of privileges that our `tekton-ci:appstudio-pipeline` sa has, to be able to run the e2e-tests in `build-templates-e2e` namespace of production cluster.
This PR adds required role-binding for `rhtap-build-tenant:appstudio-pipeline` SA to run e2e-tests in build-templates-e2e ns.
Part of the story: https://issues.redhat.com/browse/STONEBLD-2353
After the source-build image is built, we will run the e2e-tests through the integration-pipeline added in [this PR](https://github.com/redhat-appstudio/build-tasks-dockerfiles/pull/85)

feat: Add ability to run the e2e-tests from rhtap-build-tenant ns

---

components/integration/production/base/kustomization.yaml

The snapshot garbage collector reference has gone out of sync so it's not being updated by the promotion script anymore.

fix: sync snapshotgc reference in integration component

---

components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
components/sandbox/toolchain-host-operator/production/stone-prod-p02/network-policy.yaml

The OCP router needs access to the host operator namespace since it has routes in it.
In addition, the proxy used by the UI needs to access the registration service.

Router and UI proxy access for the registration service

---

components/sandbox/toolchain-host-operator/base/proxy/proxyplugin.yaml
components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
components/sandbox/toolchain-host-operator/production/stone-prod-p01/space-provisioner-configs.yaml
components/sandbox/toolchain-host-operator/production/stone-prod-p02/space-provisioner-configs.yaml
components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml

Without it, the host crds are failed to be synced.

Skip dry run on missing resources for sandbox host

---

components/keycloak/base/configure-keycloak.yaml

Without it, the keycloak crds are failed to be synced.

Skip dry run on missing resources for keycloak

---

components/backup/base/all-clusters/oadp/dpa.yaml
components/backup/base/host/schedules/backup-toolchain-host-schedule.yaml
components/backup/base/member/schedules/backup-tenants-schedule.yaml
components/backup/base/member/schedules/backup-toolchain-member-schedule.yaml

Without it, the backup crds are failed to be synced.

Skip dry run on missing resources for backup

---

components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml

The pods in the olm namespace need to access the catalog source pod which run on the toolchain-host-operator namespace.

sandbox-host: Allow traffic from olm namespace

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

The name of the pipeline in the bundle is "docker-build" not "docker-builder".

Build CM - fix docker build pipeline name

---

components/integration/development/manager_resources_patch.yaml
components/integration/production/base/manager_resources_patch.yaml
components/integration/staging/base/manager_resources_patch.yaml

A fix for https://github.com/redhat-appstudio/infra-deployments/pull/3763, we should use `console-url` as configMap name.

fix(STONEINTG-861): update intg configMap name for CONSOLE_NAME

---

components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml

Implements: [ASC-541](https://issues.redhat.com//browse/ASC-541)
Also changing the default target from m01 to rh01. There is no need to manually move workspaces after this change is merged

Enable auto-approval for external prod

---

components/integration/development/kustomization.yaml

* add 'Konflux Dev version' to CONSOLE_NAME  development env configuration file

fix(STONEINTG-861): add 'Konflux Dev version' to CONSOLE_NAME

---

components/release/base/release-pipeline-resources-clusterrole.yaml

This commit updates the release-pipeline-resources-clusterrole to be able to patch Releases. The get verb is also required in order to patch successfully. The reasoning behind this is we want a future task in release-service managed pipelines to update the Release.Status with the created artifacts.

feat(RELEASE-935): update release-pipeline clusterrole

---

components/repository-validator/production/kustomization.yaml
components/repository-validator/staging/kustomization.yaml

* Allow repository  github.com/parodos-dev/serverless-workflows
[KFLUXINFRA-563](https://issues.redhat.com//browse/KFLUXINFRA-563)

Update repo validator config to latest revision

---

argo-cd-apps/base/eaas/cluster-as-a-service/cluster-as-a-service.yaml
argo-cd-apps/k-components/deploy-to-all-clusters/all-clusters-label-selector.yaml
components/cluster-as-a-service/base/argocd.yaml
components/cluster-as-a-service/base/cluster-aas-operator.yaml
components/cluster-as-a-service/base/clustertemplatequotas.yaml
components/cluster-as-a-service/base/clustertemplates.yaml
components/cluster-as-a-service/base/kustomization.yaml
components/cluster-as-a-service/base/multicluster-engine.yaml
components/cluster-as-a-service/base/namespaces.yaml
components/cluster-as-a-service/base/rbac.yaml
components/cluster-as-a-service/development/add-base-domain-param.yaml
components/cluster-as-a-service/development/kustomization.yaml

Also included is a fix for some Konflux Apps being undesirably deployed to the ephemeral clusters provided by the cluster-as-a-service component.

Add cluster-as-a-service resources

---

components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

Continuing the work on #3693 , this changeenable Tekton StepActions in the production cluster.
It is a workaround which allows passing artifacts between tasks in an integration pipeline where workspaces backed by persistent volumes are not available

chore(RHTAPWATCH-1021): enable Tekton StepActions in production

---

argo-cd-apps/base/all-clusters/infra-deployments/enable-tekton-tracing/enable-tekton-tracing.yaml
argo-cd-apps/base/all-clusters/infra-deployments/enable-tekton-tracing/kustomization.yaml
argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
argo-cd-apps/base/all-clusters/infra-deployments/tracing-workload-otel-collector/kustomization.yaml
argo-cd-apps/base/all-clusters/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
argo-cd-apps/k-components/inject-infra-deployments-repo-details/kustomization.yaml
argo-cd-apps/overlays/development/kustomization.yaml
argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
argo-cd-apps/overlays/production-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
argo-cd-apps/overlays/staging-downstream/kustomization.yaml
components/tracing/OWNERS
configs/enable-tekton-tracing/enable-tekton-tracing.yaml
configs/enable-tekton-tracing/kustomization.yaml

Initial Tracing support in Konflux.  Supports Tekton pipeline tracing forwarded to a local OpenTelemetry collector.  Future work includes a local instance of Jaeger for visualization and forwarding to SaaS provider(s).

PVCORE-4213 - Initial tracing commit

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml
components/enterprise-contract/ecp.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
All the images built in build-definitions CI now get released to the
quay.io/konflux-ci organization.
Replace the relevant redhat-appstudio[-tekton-catalog] references in
this repo with konflux-ci[/tekton-catalog] references.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

Migrate build-definitions redhat-appstudio images

---

components/build-service/production/stone-prod-p02/webhook-config.json

The smee-client on p02 is listening to "redhathook13" not redhathook12.

fix: make build-service smee webhook url match smee-client for p02

---

components/application-api/kustomization.yaml
components/tekton-ci/base/repository.yaml

Updates the `application-api` references to mention its new organization as the repo has been moved.

Update application-api refs

---

components/multi-platform-controller/production/host-config.yaml

These are not for general use but at the moment we have no way of limiting this to specific namespaces.

KONFLUX-3382 Add fast VM's for openshift AI

---

components/multi-platform-controller/production/host-config.yaml

There was a copy/paste error that used an AMI with the wrong arch.

Fix fast pool AMI

---

components/release/base/cronjobs/remove-expired-releases.yaml
components/release/development/kustomization.yaml
components/release/production/kustomization.yaml
components/release/staging/kustomization.yaml
hack/preview.sh

This commit updates the release-service quay references to the new location in the konflux-ci quay org. It also updates the references to the latest commit, as this is the only one available in the new org.

feat(RELEASE-977): migrate release-service to konflux-ci

---

components/build-templates/production/e2e-quay-push-secret.yaml

This change updates the push secret so tests can push to the konflux-ci quay org.

Update name of e2e push secret

---

components/mintmaker/base/external-secrets/kustomization.yaml
components/mintmaker/base/external-secrets/registry-redhat-io-pull-secret.yaml

This new external secret is the registry.redhat.io pull secret which will be used by Renovate in Mintmaker to check container images.

Add external secret for Mintmaker

---

components/mintmaker/base/renovate-config.yaml

The correct manager for the rpm lockfile in Mintmaker is rpm.

Correct Mintmaker's configuration for rpm lockfile

---

components/konflux-ci/base/repository.yaml
components/tekton-ci/base/repository.yaml
docs/misc/quality-dashboard.md
hack/preview-template.env

https://issues.redhat.com/browse/KONFLUX-3398
new repositories are created:
* https://quay.io/repository/konflux-ci/quality-dashboard-backend?tab=tags
* https://quay.io/repository/konflux-ci/quality-dashboard-frontend?tab=tags
* https://github.com/konflux-ci/quality-dashboard/pull/322
so we're good to go regarding the migration to konflux-ci org
[image refs and links to github resources](https://github.com/redhat-appstudio/infra-deployments/tree/main/components/quality-dashboard/base) will be updated once https://github.com/konflux-ci/quality-dashboard/pull/322 is merged

chore: quality-dashboard -> konflux-ci part 1

---

components/mintmaker/k-components/manager-resources-patch/kustomization.yaml
components/mintmaker/production/kustomization.yaml
components/mintmaker/staging/base/kustomization.yaml
components/mintmaker/staging/base/manager_resources_patch.yaml

The mintmaker controller ran out of memory in the staging environment, which currently handles approximately 500 components.

Increase memory allocation for mintmaker controller

---

hack/secret-creator/create-plnsvc-secrets.sh

Due to this typo, the bootstrap script can't be used to upgrade an already installed instance of Konflux.
example of job logs: https://github.com/redhat-hac-qe/infra-deployments/actions/runs/9639569500/job/26581952807

fix(typo): fix typo in check for postresql-tls

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/staging/base/kustomization.yaml
components/pipeline-service/staging/stone-stage-p01/deploy.yaml
components/pipeline-service/staging/stone-stg-m01/deploy.yaml
components/pipeline-service/staging/stone-stg-rh01/deploy.yaml

While the now third version of the mem leak and cancelled context  fixes held up better in stage by moving log storage off the reconciler thread, the ongoing grpc/http2 performance issues showed enough performance regression from the mem leak fix, coupled with no improvement with cancelled context (log storage still got interrupted) that I am resetting the watcher version to what is currently in prod.
We are actively working the prototypes to either do log retrieval in the api server, or preferrably, move S3 interaction to the watcher.
I was able to successfully test the older version of the watcher with the latest version of the api server, so I am leaving the api server at the more recent version to get its performance tuning improvements.
long term we need …

KFLUXBUGS-863: repin watcher image to mem leak version

---

components/multi-platform-controller/production/host-config.yaml

This PR is to understand the instance allocation issues with AWS c7a.12xlarge

KFLUXINFRA-646: Removed host iops from extra fast amd64

---

argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
components/monitoring/logging/production/kflux-prd-es01/kustomization.yaml

This fixes the same issue from #3680 but for production.

Fix logging operator setup for kflux-prd-es01 cluster

---

components/build-service/README.md
docs/development/deployment.md
hack/build/build-via-appstudio.sh
hack/build/templates/component.yaml
hack/build/templates/secret.yaml

Application CR status is no longer being reconciled by application-service (see https://issues.redhat.com/browse/DEVHAS-651), hence this script needs to be updated accordingly
1. bootstrap cluster
```
./hack/bootstrap-cluster.sh preview
```
2a. (run the script with arguments - git repository URL, repo Dockerfile path):
```
./hack/build/build-via-appstudio.sh https://github.com/<YOUR_GITHUB_ORG>/devfile-sample-python-basic docker/Dockerfile
``` 
2b. (run the script without any arguments - by default 3 components are created on a cluster):
```
./hack/build/build-via-appstudio.sh
```

fix: post-setup verification script update

---

components/integration/production/base/manager_resources_patch.yaml

Enlarge integration service memery resource limit due to OOM in rh01 prod integration service pod

fix: enlarge memery resouce limsit for integration service

---

components/build-service/base/build-pipeline-config/build-pipeline-config.yaml

The pipeline-docker-build includes a fix for the clamav-scan task failing with newer OSP version due to stricter validation.

Use newer version of pipeline-docker-build image

---

components/multi-platform-controller/production-downstream/host-config.yaml

By default, podman will mount secrets declared in
/usr/share/containers/mounts.conf, even if those secrets do not exist on the host system.  This means that it is impossible to mount in entitlements provided by the user, because the subscription management tools will choose the empty entitlement mounted in over the creds mounted in by the user.

feat: allow rootful MPC builds to disable entitlement mounts

---

hack/secret-creator/create-plnsvc-secrets.sh

QE teams are using long living deployments (2+ years) and having short lived certificates breaking their deployments. Re-issuing of those certificates requires redeployment of some components to make use of the new configmaps and secrets. In the common case the use of these secrets is for short lived CI deployments where the lifetime of the certs does not have effect.

Bump Postgres TLS cert lifetime

---

argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml

The ApplicationSet name with the cluster name normalized creates a service URL with the cluster name embedded in it.  By overriding the fullName in the Helm chart, the same name will be used across all deployments.

Fix service name for Opentelemetry Collector

---

components/konflux-ci/base/repository.yaml

E2e tests are already in Konflux. This pull request just remove e2e CR

Remove konflux e2e repository cr

---

components/mintmaker/production/base/kustomization.yaml
components/mintmaker/production/base/manager_patches.yaml
components/mintmaker/staging/base/kustomization.yaml
components/mintmaker/staging/base/manager_patches.yaml

For testing purposes, the staging environment should use the `latest` mintmaker-renovate-image, and production should use a specific digest instead, so we can make sure that the latest changes are well tested before going into production.
ref: [CWFHEALTH-3100](https://issues.redhat.com//browse/CWFHEALTH-3100)

Patch RENOVATE_IMAGE env variable

---

components/multi-platform-controller/staging/host-config.yaml

Adding two types of instances
1. Higher Memory (1:4 ratio for cpu: memory)
2. Higher CPU (1:2 ratio for cpu: memory)
>**Note** Some users may require more memory and less CPU, making Memory Optimized Instances the better choice for them. On the other hand, some users may need more CPU power but less memory, in which case CPU-optimized instances would be a good fit. Therefore, a combination of memory-optimized and CPU-optimized instances is essential to cater to different user needs. In the label naming, **m** refers to memory optimised and **c** refers to compute optimised. 
| Multi-Platform Label | Instance Type | Architecture | CPU | Memory(GB) |
|:--------------------|:-------------|:------------|:-----|:--------|
|linux-mlarge/amd64   | m5a.large     |        AMD64 | 2     | 8 …

KFLUXINFRA-651: Adding Instance Types for Multi-Platform Builds

---

components/multi-platform-controller/OWNERS

Add Bkorren to the multi-platform-controller OWNERS file.

Grant BKorren permissions for MCP

---

components/spi/overlays/production/base/kustomization.yaml
components/spi/overlays/production/stone-prd-m01/kustomization.yaml
components/spi/overlays/production/stone-prd-m01/oauth-service-config-patch.json
components/spi/overlays/production/stone-prd-rh01/kustomization.yaml
components/spi/overlays/production/stone-prd-rh01/oauth-service-config-patch.json
components/spi/overlays/production/stone-prod-p01/kustomization.yaml
components/spi/overlays/production/stone-prod-p01/oauth-service-config-patch.json
components/spi/overlays/production/stone-prod-p02/kustomization.yaml
components/spi/overlays/production/stone-prod-p02/oauth-service-config-patch.json

Update SPI to the version without OAuth being deployed

Update SPI to the next OAuth-less version on production

---

components/mintmaker/base/renovate-config.yaml

Seems like we have to manually disable that because some preset might be taking effect:
https://github.com/renovatebot/renovate/discussions/11330
Let's force this, so that we can disable the dashboard.

Mintmaker: explicitly disable Dependency Dashboard

---

components/workspaces/base/server/config/default/kustomization.yaml
components/workspaces/base/server/config/server/deployment.yaml

This fixes the konflux-workspaces REST API Server's configuration. The ConfigMap that stores the configuration for the REST API Server is not populated correctly.
linked to: #4040 and https://github.com/konflux-workspaces/workspaces/pull/235

workspaces: fix server's configmap

---

argo-cd-apps/base/tenants-config/tenants-config.yaml

Ignore image-controller.appstudio.redhat.com/update-component-image because controller is removing annotation after it is done with it. Without ignoring it, it would be constant loop fight between argoCD syncing and controller removing it

Make ArgoCD ignore annotation on ImageRepository when sycning

---

components/konflux-ci/base/repository.yaml
components/tekton-ci/base/repository.yaml

per explanation from @ralphbean in https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1720725153164939 this facilitates https://github.com/openshift-pipelines/pipeline-service-exporter/pull/70

SRVKP-5825: move pipeline-metric-exporter PAC repository obj from tekton-ci to konflux-ci

---

components/konflux-ci/base/repository.yaml
components/tekton-ci/base/repository.yaml

https://issues.redhat.com/browse/PLNSRVCE-1673 related

SRVKP-5825: move pipeline-service repository obj from tekton-ci to konflux-ci

---

components/mintmaker/base/renovate-config.yaml

This should fix the issue with missing rebase checkbox on updates from [CWFHEALTH-3224](https://issues.redhat.com//browse/CWFHEALTH-3224).
Essentially the issue that we were missing `{{{controls}}}` in `prBodyTemplate` which - from the Renovate source code - is just the checkbox: https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/pr/body/controls.ts

Add controls to prBodyTemplate for Tekton updates

---

components/keycloak/base/configure-keycloak.yaml

There was bug where the user's first and last name were not visible in the UI since they weren't included in the JWT token. Include the "first_name" and "last_name" claims in the JWT token.

KFLUXBUGS-1305: Show the user's first and last name on the UI

---

components/konflux-ci/base/repository.yaml
components/tekton-ci/base/repository.yaml

similar to pipeline-service-exporter and pipeline-service changes https://github.com/redhat-appstudio/infra-deployments/pull/4055 and https://github.com/redhat-appstudio/infra-deployments/pull/4053

SRVKP-5832: move to downstream tekton-results PAC CI to konflux-ci namespace

---

components/ui/base/proxy/nginx.conf

This is causing issues in production, since konflux-workspaces isn't available there yet.  Until workspaces is deployed in production, remove this section of the configuration.
See [here][1] for more context.
[1]: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1721129546697399

ui: remove nginx proxy for konflux workspaces

---

components/pipeline-service/development/kustomization.yaml
components/pipeline-service/production/base/kustomization.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml
components/pipeline-service/staging/base/kustomization.yaml

Until @khrm can either productize his third party tool integration for results log storage, or unless the backup option of accessing S3 from the watcher is done at a tactical solution, the current mem leak version of the watcher still provides slightly better success / performance than the versions that fix the mem leak / cancelled context issues but are more negatively impacted by grpc/http2 scaling issues.
I did run `generate-deploy-config.sh ` @enarha in both the staging and production folders.

SRVKP-5832: maintain pinning of watcher image to mem leak version

---

components/ui/base/proxy/proxy.yaml

1. For 60 seconds, check if no containers in the pod crash loop and only then declare that the pod ready.
2. Add readiness probe. Traffic will be forwarded only to pods that pass the readiness check.
3. Adjust probes to start only after 60 seconds to match the change mention in 1.
4. During upgrade, allow an additional pod to be scheduled for the new replicaset.
5. Don't allow the deployment to have less that 3 pod ready, even during upgrade.

Improve nginx deployment

---

components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml

The plan is to decommission this cluster so disable automatic approval to prevent new users from coming in.
[KFLUXINFRA-648](https://issues.redhat.com//browse/KFLUXINFRA-648)

Disable automatic approval on stone-prod-p01

---

argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml

There is an issue in prod were NS was deleted and we do not want ArgoCD to automatically sync to allow us to restore things.

Disable automated sync for toolchain-member-operator

---

components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml

We are recovering from an outage and want to test m01 before recovering rh01. This change will be reverted after.

Set prd-m01 as default cluster

---

argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml

This reverts commit bba8ee419954122078133b1a3a0cf97c8d3aaba6.

Revert "Disable automated sync for toolchain-member-operator (#4126)"

---

components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml

This reverts commit 37020bed32bb33050e6098cb7640d38fb7e78952. This is preventing new user from signing up to get access to existing workspaces.

Revert "Disable automatic approval on stone-prod-p01 (#4009)"

---

components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml

This was included by mistake in a prior commit.

Remove the SpaceProvisionerConfig for EaaS in public staging

---

components/workspaces/staging/stone-stage-p01/kustomization.yaml
components/workspaces/staging/stone-stg-host/kustomization.yaml
components/workspaces/staging/stone-stg-host/route.yaml

We need to have a route in the external staging environment, which we won't need in the internal.  To rectify this, have our staging config split so that we can deal with each deployment environment separately.

workspaces: split internal & external staging

---

argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml

We had an outage due to a back overlay change. The overlay change resulted in deleting the toolchain member applications thus all resources in toolchain-member-operator namespace. We were lucky that we recovered without data loss.
Since toolchain host and member namespaces contains user registration CRs that are not deployed by ArgoCD, disable the automated pruning to prevent accidental deletion. From now on, if a resource is deleted from those application, someone will need to manually start the sync with prune option after reviewing the resources to delete.

Disable automated pruning for toolchain operators

---

components/mintmaker/base/rbac/mintmaker-team.yaml

DependencyUpdateCheck is a CR used by mintmaker to trigger Renovate jobs.

Allow mintmaker team members to create delete dependencyupdatechecks

---

components/internal-services/kustomization.yaml

The new commit includes the serviceAccount field in the InternalRequest.Spec.

chore(RELEASE-1047): bump internal-services crd commit

---

argo-cd-apps/base/host/workspaces/workspaces.yaml

Argo was looking at the top-level staging/ directory of components/workspaces/, when it should be using the subdirectories based off of the deployment environment.

workspaces: use correct subdir of staging/ to deploy

---

components/workspaces/staging/stone-stg-host/route.yaml

This fixes a out-of-sync loop between what ArgoCD wants (an empty host) and what the route controller wants (a populated .spec.host field).

workspaces: specify host for route

---

argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
argo-cd-apps/base/tenants-config/tenants-config.yaml

Draft PR set up as a start of the tenants-config migration to GitLab. Here I'm making the ArgoCD sync manual before making the GH read-only

Make gh tenants-config argo sync manual

---

components/tekton-ci/production/cleanup-cronjob.yaml

The cleanup-cronjob running in the tekton-ci namespace deletes
Applications used for e2e-tests. Currently, it deletes applications
at least 3 days old.
This doesn't seem to be enough to keep up with the rate of e2e-testing
in build-definitions anymore.
Remove applications after 1 day instead.
Also run the pruner every hour

tekton-ci: prune build-templates-e2e harder

---

components/pipeline-service/production/base/update-tekton-config-performance.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

enable OSP pruner again for resolver memory issues and results prune performance issues seen on prod-rh01 (#4171). The pruner is set to run every 10 minutes, pruning pipelineruns older than 60 minutes. It serves as a backup pruner for the Tekton Results pruner which ideally will be pruning the pipelineruns earlier up to 10 mins after completion.
This is a temporary measure until the Results pruner performance is improved.

enable OSP pruner again

---

components/workspaces/base/server/config/default/kustomization.yaml

Currently, the role bindings we have for server apply to the service account `rest-api-server`, not `workspaces-rest-api-server`.  We need to overwrite the name in the bindings to reflect the processing the names of resources go through as a part of the kustomization process.

workspaces: apply roles to translated service account name

---

components/workspaces/base/server/config/server/kustomization.yaml
components/workspaces/staging/stone-stage-p01/kustomization.yaml
components/workspaces/staging/stone-stg-host/kustomization.yaml

In our top-level kustomize manifest for each staging environment, we were referring to the image name embedded in the deployment manifests directly, not the name that would be replacing it after processing by lower-level kustomize manifests.

workspaces: correctly override image references

---

components/mintmaker/production/base/manager_patches.yaml

Included PRs:
- https://github.com/konflux-ci/mintmaker-renovate-image/pull/33
- https://github.com/konflux-ci/mintmaker-renovate-image/pull/36
- https://github.com/konflux-ci/mintmaker-renovate-image/pull/37
This fixes CWFHEALTH-3280. Tested this image locally, `pip3` shows correctly `rpm-lockfile-prototype    0.5.1`. [Changelog](https://github.com/konflux-ci/rpm-lockfile-prototype/blob/main/CHANGELOG.md).

Update mintmaker-renovate-image digest

---

components/mintmaker/production/base/manager_patches.yaml

For some reason the `c56e548` tag disappeared from quay?

Fix MintMaker tag digest

---

components/cluster-as-a-service/staging/external-secrets.yaml

Labels inside `spec.target.template` are ignored by the API causing the Application to stay out of sync. Labels inside `metadata` should be copied to the resulting Secret.

Fix ExternalSecret labels

---

components/pipeline-service/production/base/bump-results-watcher-mem.yaml
components/pipeline-service/production/stone-prd-m01/deploy.yaml
components/pipeline-service/production/stone-prd-rh01/deploy.yaml
components/pipeline-service/production/stone-prod-p01/deploy.yaml
components/pipeline-service/production/stone-prod-p02/deploy.yaml

related to the recent remote-resolver and re-enablement of OSP pruning

adust watcher mem for increased prod-rh01 load
